/* FinStudio glossary — the lookup layer.
   Every term: a one-line plain-English answer first, then the technical
   definition, then the formula and what it connects to. Terms are
   auto-linked inside lesson prose and open in place, without navigation. */
(function () {
  "use strict";
  var LS = (window.LS = window.LS || {});

  // g(term, plain, def, opts)
  //   plain — one sentence a beginner understands, no jargon
  //   def   — the precise definition
  //   opts  — { fx, also, related, lesson, level, group }
  function g(term, plain, def, opts) {
    opts = opts || {};
    return {
      term: term, plain: plain, def: def,
      fx: opts.fx || null,
      also: opts.also || [],          // alternative names, also auto-linked
      related: opts.related || [],
      lesson: opts.lesson || null,
      level: opts.level || "beginner", // beginner | intermediate | advanced
      group: opts.group || "General"
    };
  }

  LS.glossary = [
    /* ---------------- the five buckets ---------------- */
    g("Asset", "Something the business owns that will bring it money or benefit later.",
      "A resource the business controls as a result of a past event, from which future economic benefit is expected.",
      { related: ["Liability", "Equity", "Current asset"], lesson: "1010-five-buckets", group: "Accounting" }),
    g("Liability", "Money the business owes to someone else.",
      "A present obligation arising from a past event, whose settlement is expected to require an outflow of resources.",
      { related: ["Asset", "Equity", "Trade payables"], lesson: "1010-five-buckets", group: "Accounting" }),
    g("Equity", "What would be left for the owner after selling everything and paying every debt.",
      "The residual interest in the assets of the business after deducting all liabilities. Also called net worth or shareholders' funds.",
      { fx: "Equity = Assets − Liabilities", also: ["Net worth", "Shareholders' funds"],
        related: ["Share capital", "Retained earnings"], lesson: "1020-accounting-equation", group: "Accounting" }),
    g("Accounting equation", "Everything a business owns was paid for by someone — either lenders or the owner.",
      "The identity underlying double-entry bookkeeping: total assets always equal total liabilities plus equity.",
      { fx: "Assets = Liabilities + Equity", related: ["Balance sheet", "Double entry"],
        lesson: "1020-accounting-equation", group: "Accounting" }),
    g("Double entry", "Every transaction changes at least two things, so the books always balance.",
      "A bookkeeping system in which each transaction is recorded with equal and offsetting debit and credit entries.",
      { also: ["Debit", "Credit"], related: ["Accounting equation"], lesson: "1030-two-sides", group: "Accounting" }),

    /* ---------------- balance sheet ---------------- */
    g("Balance sheet", "A photograph of what a business owns and owes on one particular day.",
      "A statement of financial position at a point in time, listing assets on one side and liabilities plus equity on the other.",
      { related: ["Accounting equation", "Income statement", "Cash flow statement"],
        lesson: "1330-balance-sheet", group: "Statements" }),
    g("Current asset", "Something the business expects to turn into cash within a year.",
      "An asset expected to be realised, sold or consumed within twelve months or the normal operating cycle.",
      { related: ["Inventory", "Trade receivables", "Current ratio"], lesson: "1150-cash-deposit", group: "Accounting" }),
    g("PP&E", "The long-lasting physical things a business uses — machines, vehicles, fittings.",
      "Property, plant and equipment: tangible assets held for use in operations over more than one period, carried at cost less accumulated depreciation.",
      { fx: "Net PP&E = Cost − Accumulated depreciation", also: ["Property, plant and equipment", "Fixed assets"],
        related: ["Depreciation", "Capex"], lesson: "1110-ppe", group: "Accounting" }),
    g("Capex", "Money spent on things that will still be useful in future years.",
      "Capital expenditure: cash spent acquiring or improving long-lived assets. It is capitalised on the balance sheet rather than expensed.",
      { also: ["Capital expenditure"], related: ["PP&E", "Depreciation", "Free cash flow"],
        lesson: "1110-ppe", level: "intermediate", group: "Accounting" }),
    g("Depreciation", "Spreading the cost of a long-lasting asset across the years it is used.",
      "The systematic allocation of an asset's cost over its useful life. An expense that consumes no cash, because the cash left when the asset was bought.",
      { fx: "Straight-line = (Cost − Residual value) ÷ Useful life",
        related: ["PP&E", "EBITDA", "Amortisation"], lesson: "1120-depreciation", group: "Accounting" }),
    g("Amortisation", "Depreciation, but for things you cannot touch — software, licences, patents.",
      "The systematic allocation of the cost of an intangible asset over its useful life.",
      { related: ["Depreciation", "EBITDA"], level: "intermediate", group: "Accounting" }),
    g("Inventory", "Goods sitting on the shelf, waiting to be sold.",
      "Assets held for sale in the ordinary course of business, in the process of production, or as materials to be consumed.",
      { fx: "COGS = Opening inventory + Purchases − Closing inventory",
        also: ["Stock"], related: ["COGS", "DIO", "Working capital"], lesson: "1130-inventory", group: "Accounting" }),
    g("Trade receivables", "Money customers owe you for things you have already delivered.",
      "Amounts due from customers for goods or services already supplied. A current asset, because it is a right to near-term cash.",
      { also: ["Accounts receivable", "Debtors"], related: ["DSO", "Revenue", "Working capital"],
        lesson: "1140-receivables", group: "Accounting" }),
    g("Trade payables", "Money you owe suppliers for things they have already delivered.",
      "Amounts owed to suppliers for goods or services already received. A current liability, and effectively interest-free funding.",
      { also: ["Accounts payable", "Creditors"], related: ["DPO", "Working capital"],
        lesson: "1210-payables", group: "Accounting" }),
    g("Accrual", "Recording a cost in the month it belongs to, even if you pay later.",
      "Recognition of income and expenses in the period they are earned or incurred, regardless of when cash moves.",
      { also: ["Accrual accounting", "Accrued expenses"], related: ["Revenue recognition", "Trade payables"],
        lesson: "1210-payables", group: "Accounting" }),
    g("Working capital", "The money tied up in day-to-day trading — stock and unpaid invoices, less what you owe suppliers.",
      "Current assets less current liabilities; in modelling, usually the operating subset: inventory plus receivables less payables.",
      { fx: "Working capital = Inventory + Receivables − Payables",
        related: ["Cash conversion cycle", "Free cash flow"], lesson: "1520-cfo", level: "intermediate", group: "Accounting" }),
    g("Share capital", "The money the owners originally put into the business.",
      "The amount subscribed by shareholders in exchange for shares, recorded at nominal value. It does not change as the business earns.",
      { fx: "Share capital = Shares issued × Face value",
        related: ["Equity", "Retained earnings", "Dilution"], lesson: "1310-share-capital", group: "Accounting" }),
    g("Retained earnings", "All the profit the business has ever made and kept, rather than paid out.",
      "Cumulative profit after tax less cumulative dividends. It is a claim on the business, not a pile of cash.",
      { fx: "Closing RE = Opening RE + Profit after tax − Dividends",
        related: ["Equity", "Profit after tax", "Dividend"], lesson: "1320-retained-earnings", group: "Accounting" }),

    /* ---------------- income statement ---------------- */
    g("Income statement", "A record of what the business earned and spent over a period.",
      "A statement of financial performance for a period: revenue less expenses, ending in profit after tax.",
      { also: ["P&L", "Profit and loss"], related: ["Balance sheet", "Revenue", "Profit after tax"],
        lesson: "1460-pl-capstone", group: "Statements" }),
    g("Revenue", "The value of what you sold — whether or not the customer has paid yet.",
      "Income from ordinary activities, recognised when control of the goods or services transfers to the customer.",
      { also: ["Turnover", "Sales", "Top line"], related: ["Revenue recognition", "Trade receivables", "Gross profit"],
        lesson: "1410-revenue", group: "Statements" }),
    g("Revenue recognition", "You record a sale when you deliver, not when you get paid.",
      "The principle determining when revenue is recorded: on transfer of control, independent of cash timing.",
      { related: ["Revenue", "Accrual", "Deferred revenue"], lesson: "1410-revenue", level: "intermediate", group: "Statements" }),
    g("Deferred revenue", "Money a customer paid you before you delivered — so you owe them, not the reverse.",
      "A liability for consideration received in advance of performance. It becomes revenue as the obligation is satisfied.",
      { also: ["Unearned revenue"], related: ["Revenue recognition", "Liability"], level: "intermediate", group: "Statements" }),
    g("COGS", "What the things you sold actually cost you to make or buy.",
      "Cost of goods sold: the direct cost of inventory consumed in generating the period's revenue.",
      { fx: "Gross profit = Revenue − COGS", also: ["Cost of goods sold", "Cost of sales"],
        related: ["Gross profit", "Inventory"], lesson: "1420-cogs", group: "Statements" }),
    g("Gross profit", "What is left after paying for the product itself, before any overheads.",
      "Revenue less cost of goods sold. Its margin is the cleanest single read on pricing power.",
      { fx: "Gross margin % = Gross profit ÷ Revenue",
        related: ["COGS", "EBITDA", "Margin"], lesson: "1420-cogs", group: "Statements" }),
    g("Operating expenses", "The cost of simply being open — rent, salaries, power, marketing.",
      "Costs of running the business that are not direct product costs. Largely fixed, which is why growth improves margins.",
      { also: ["Opex", "Overheads"], related: ["EBITDA", "Operating leverage"], lesson: "1430-opex-ebitda", group: "Statements" }),
    g("EBITDA", "Profit from running the business, before interest, tax and the cost of assets wearing out.",
      "Earnings before interest, tax, depreciation and amortisation. Useful for comparing operations across different financing and asset structures — but it is not cash flow.",
      { fx: "EBITDA = Gross profit − Operating expenses",
        related: ["EBIT", "EV/EBITDA", "Free cash flow"], lesson: "1430-opex-ebitda", level: "intermediate", group: "Statements" }),
    g("EBIT", "Profit from operations after recognising that assets wear out, but before financing and tax.",
      "Earnings before interest and tax; equivalently EBITDA less depreciation and amortisation. Also called operating profit.",
      { fx: "EBIT = EBITDA − Depreciation & amortisation", also: ["Operating profit"],
        related: ["EBITDA", "ROCE", "Interest coverage"], lesson: "1440-depreciation-pl", level: "intermediate", group: "Statements" }),
    g("Interest expense", "The rent you pay for using someone else's money.",
      "The cost of borrowing for the period. Only interest is an expense — repaying the principal never touches the income statement.",
      { fx: "Interest = Rate × Loan balance", related: ["Interest coverage", "Debt-to-equity"],
        lesson: "1220-borrowings", group: "Statements" }),
    g("Profit before tax", "Profit after paying the bank, before paying tax.",
      "EBIT less interest expense. The base on which the tax charge is computed.",
      { fx: "PBT = EBIT − Interest", also: ["PBT"], related: ["EBIT", "Profit after tax"],
        lesson: "1450-interest-tax", group: "Statements" }),
    g("Profit after tax", "The bottom line — what actually belongs to the owner.",
      "Profit before tax less the tax charge. The only profit figure that belongs to shareholders, and the number that flows into retained earnings.",
      { fx: "PAT = PBT − Tax", also: ["PAT", "Net income", "Net profit", "Bottom line"],
        related: ["Retained earnings", "EPS", "Margin"], lesson: "1460-pl-capstone", group: "Statements" }),
    g("EPS", "Profit divided by the number of shares — each share's slice of the earnings.",
      "Earnings per share: profit after tax attributable to shareholders divided by the weighted average number of shares outstanding.",
      { fx: "EPS = Profit after tax ÷ Shares outstanding", also: ["Earnings per share"],
        related: ["P/E ratio", "Profit after tax"], level: "intermediate", group: "Valuation" }),

    /* ---------------- cash flow ---------------- */
    g("Cash flow statement", "A record of where the money actually went.",
      "A statement reconciling opening to closing cash through operating, investing and financing activities.",
      { related: ["CFO", "Free cash flow", "Balance sheet"], lesson: "1550-cf-capstone", group: "Statements" }),
    g("CFO", "The cash the actual business generated, before buying assets or dealing with lenders.",
      "Cash from operations: profit adjusted for non-cash items and movements in working capital. A business that cannot generate positive CFO is being funded by someone else.",
      { fx: "CFO = PAT + Depreciation ± Working capital changes", also: ["Cash from operations", "Operating cash flow"],
        related: ["Free cash flow", "Working capital"], lesson: "1520-cfo", level: "intermediate", group: "Statements" }),
    g("Free cash flow", "The cash left over after keeping the business running and replacing what wears out.",
      "Cash available to all providers of capital after operating costs, tax and the investment needed to sustain operations.",
      { fx: "FCFF = EBIT × (1 − tax) + Depreciation − Capex − ΔWorking capital",
        also: ["FCF", "FCFF"], related: ["DCF", "Capex", "CFO"], lesson: "2230-fcff", level: "advanced", group: "Valuation" }),
    g("Dividend", "Profit handed to the owners instead of kept in the business.",
      "A distribution of profit to shareholders. It reduces retained earnings and is a financing outflow — it never appears on the income statement.",
      { related: ["Retained earnings", "Equity"], lesson: "1540-cff", group: "Statements" }),

    /* ---------------- ratios ---------------- */
    g("Margin", "How much of every ₹100 of sales you actually keep at a given point.",
      "Any profit line expressed as a percentage of revenue, allowing businesses of different sizes to be compared.",
      { fx: "Margin % = Profit line ÷ Revenue", related: ["Gross profit", "EBITDA", "Operating leverage"],
        lesson: "1610-margins", group: "Ratios" }),
    g("Current ratio", "Whether near-term resources cover near-term bills.",
      "Current assets divided by current liabilities. Below 1 means obligations due within a year exceed the resources available to meet them.",
      { fx: "Current ratio = Current assets ÷ Current liabilities",
        related: ["Quick ratio", "Working capital"], lesson: "1620-liquidity", group: "Ratios" }),
    g("Quick ratio", "The same test as the current ratio, but assuming you cannot sell your stock.",
      "Current assets excluding inventory, divided by current liabilities. The harsher liquidity test, because stock may not convert in a downturn.",
      { fx: "Quick ratio = (Current assets − Inventory) ÷ Current liabilities",
        also: ["Acid test"], related: ["Current ratio", "Inventory"], lesson: "1620-liquidity", level: "intermediate", group: "Ratios" }),
    g("Debt-to-equity", "How many rupees the lenders have put in for every rupee the owner has.",
      "Total borrowings divided by total equity. A stock measure of financial leverage taken from the balance sheet.",
      { fx: "D/E = Borrowings ÷ Equity", also: ["D/E", "Gearing"],
        related: ["Interest coverage", "Leverage"], lesson: "1630-leverage", level: "intermediate", group: "Ratios" }),
    g("Interest coverage", "How many times over your operating profit could pay your interest bill.",
      "EBIT divided by interest expense. A flow measure of debt serviceability, and usually a better early warning of distress than debt-to-equity.",
      { fx: "Interest coverage = EBIT ÷ Interest expense",
        related: ["Debt-to-equity", "EBIT"], lesson: "1630-leverage", level: "intermediate", group: "Ratios" }),
    g("ROE", "The return earned on the owner's own money.",
      "Return on equity: profit after tax divided by shareholders' equity.",
      { fx: "ROE = Profit after tax ÷ Equity", also: ["Return on equity"],
        related: ["ROCE", "DuPont analysis"], lesson: "1640-returns", level: "intermediate", group: "Ratios" }),
    g("ROCE", "The return earned on all the long-term money in the business, whoever provided it.",
      "Return on capital employed: EBIT divided by equity plus debt. It uses EBIT because it measures the assets, not the financing.",
      { fx: "ROCE = EBIT ÷ (Equity + Debt)", also: ["Return on capital employed"],
        related: ["ROE", "WACC"], lesson: "1640-returns", level: "intermediate", group: "Ratios" }),
    g("DuPont analysis", "Splitting return on equity into three levers, to see where it actually comes from.",
      "A decomposition of ROE into net margin, asset turnover and leverage — revealing whether a return is earned on pricing, efficiency or borrowing.",
      { fx: "ROE = Margin × Asset turnover × Leverage",
        related: ["ROE", "Margin", "Leverage"], lesson: "1640-returns", level: "advanced", group: "Ratios" }),
    g("DSO", "How many days customers take to pay you.",
      "Days sales outstanding: receivables expressed as a number of days of revenue.",
      { fx: "DSO = Receivables ÷ Revenue × 365", also: ["Days sales outstanding"],
        related: ["Trade receivables", "Cash conversion cycle"], lesson: "2210-drivers", level: "intermediate", group: "Ratios" }),
    g("DIO", "How many days of stock you are holding.",
      "Days inventory outstanding: inventory expressed as a number of days of cost of goods sold.",
      { fx: "DIO = Inventory ÷ COGS × 365", also: ["Days inventory outstanding"],
        related: ["Inventory", "Cash conversion cycle"], lesson: "2210-drivers", level: "intermediate", group: "Ratios" }),
    g("DPO", "How many days you take to pay your suppliers.",
      "Days payable outstanding: payables expressed as a number of days of cost of goods sold.",
      { fx: "DPO = Payables ÷ COGS × 365", also: ["Days payable outstanding"],
        related: ["Trade payables", "Cash conversion cycle"], lesson: "2210-drivers", level: "intermediate", group: "Ratios" }),
    g("Cash conversion cycle", "How long a rupee is stuck in the business between paying for stock and collecting from customers.",
      "Days inventory outstanding plus days sales outstanding less days payable outstanding. Negative means suppliers fund the working capital.",
      { fx: "CCC = DIO + DSO − DPO", also: ["CCC"],
        related: ["DSO", "DIO", "DPO", "Working capital"], lesson: "2210-drivers", level: "advanced", group: "Ratios" }),
    g("Operating leverage", "Once fixed costs are covered, extra sales drop almost straight to profit.",
      "The sensitivity of operating profit to a change in revenue, arising from the fixed-cost base.",
      { related: ["Operating expenses", "Margin"], level: "intermediate", group: "Ratios" }),
    g("CAGR", "The steady yearly growth rate that would get you from the start value to the end value.",
      "Compound annual growth rate: the constant rate at which a quantity would have grown over a period.",
      { fx: "CAGR = (Ending ÷ Beginning)^(1 ÷ Years) − 1", also: ["Compound annual growth rate"],
        related: ["Compound interest"], level: "intermediate", group: "Ratios" }),

    /* ---------------- valuation & corporate finance ---------------- */
    g("Time value of money", "A rupee today is worth more than a rupee next year, because today's rupee can earn.",
      "The principle that money available now is worth more than the same amount later, given its earning capacity.",
      { fx: "PV = FV ÷ (1 + r)^n", also: ["TVM"],
        related: ["Discount rate", "Present value", "Compound interest"], level: "beginner", group: "Corporate finance" }),
    g("Compound interest", "Interest that itself earns interest, so growth accelerates.",
      "Interest calculated on the initial principal and on the accumulated interest of prior periods.",
      { fx: "FV = PV × (1 + r)^n", related: ["Time value of money", "CAGR"], group: "Corporate finance" }),
    g("Present value", "What a future sum is worth in today's money.",
      "The value today of a future cash flow, discounted at a rate reflecting risk and the time value of money.",
      { fx: "PV = Cash flow ÷ (1 + r)^n", also: ["PV", "Discounting"],
        related: ["NPV", "Discount rate", "DCF"], lesson: "2240-dcf", level: "intermediate", group: "Corporate finance" }),
    g("Discount rate", "The annual return you require to justify tying your money up.",
      "The rate used to convert future cash flows into present value, reflecting the risk of those cash flows.",
      { related: ["WACC", "Present value", "DCF"], lesson: "2240-dcf", level: "intermediate", group: "Corporate finance" }),
    g("NPV", "The value a project creates after allowing for what the money could have earned elsewhere.",
      "Net present value: the sum of a project's discounted cash flows less the initial investment. Positive means the project adds value.",
      { fx: "NPV = Σ CFt ÷ (1 + r)^t − Initial investment",
        also: ["Net present value"], related: ["IRR", "Discount rate", "DCF"], level: "intermediate", group: "Corporate finance" }),
    g("IRR", "The rate of return a project earns on the money invested in it.",
      "Internal rate of return: the discount rate at which a project's net present value equals zero.",
      { also: ["Internal rate of return"], related: ["NPV", "WACC"], level: "advanced", group: "Corporate finance" }),
    g("WACC", "The blended annual return that all your funders — lenders and owners — expect.",
      "Weighted average cost of capital: the cost of equity and debt weighted by their share of total capital, used to discount cash flows available to all funders.",
      { fx: "WACC = E/V × Cost of equity + D/V × Cost of debt × (1 − tax)",
        also: ["Weighted average cost of capital"], related: ["CAPM", "DCF", "Discount rate"],
        lesson: "2240-dcf", level: "advanced", group: "Corporate finance" }),
    g("CAPM", "A way of estimating what return shareholders should demand, given how risky the business is.",
      "Capital asset pricing model: expected return equals the risk-free rate plus beta times the equity risk premium.",
      { fx: "Cost of equity = Rf + β × (Rm − Rf)",
        also: ["Capital asset pricing model"], related: ["Beta", "WACC"], level: "advanced", group: "Corporate finance" }),
    g("Beta", "How much a share tends to move when the whole market moves.",
      "A measure of a security's sensitivity to market movements. Beta above 1 amplifies market moves; below 1 dampens them.",
      { related: ["CAPM", "WACC"], level: "advanced", group: "Corporate finance" }),
    g("DCF", "Valuing a business by adding up its future cash, converted into today's money.",
      "Discounted cash flow: a valuation method that projects free cash flows, discounts them at the cost of capital, and adds a terminal value.",
      { also: ["Discounted cash flow"], related: ["Free cash flow", "WACC", "Terminal value", "Enterprise value"],
        lesson: "2240-dcf", level: "advanced", group: "Valuation" }),
    g("Terminal value", "A single number standing in for every year after your forecast ends.",
      "The value of all cash flows beyond the explicit forecast period, usually estimated by assuming steady perpetual growth.",
      { fx: "TV = Final FCFF × (1 + g) ÷ (WACC − g)",
        related: ["DCF", "WACC"], lesson: "2240-dcf", level: "advanced", group: "Valuation" }),
    g("Enterprise value", "What the whole business is worth, regardless of who funded it.",
      "The value of the operating business to all capital providers: equity value plus net debt.",
      { fx: "Enterprise value = Equity value + Net debt", also: ["EV"],
        related: ["Equity value", "Net debt", "EV/EBITDA"], lesson: "2240-dcf", level: "advanced", group: "Valuation" }),
    g("Equity value", "What the shareholders' stake is worth after the lenders are paid.",
      "Enterprise value less net debt: the portion of business value attributable to shareholders.",
      { fx: "Equity value = Enterprise value − Net debt", also: ["Market capitalisation", "Market cap"],
        related: ["Enterprise value", "Net debt"], lesson: "2250-valuation-capstone", level: "advanced", group: "Valuation" }),
    g("Net debt", "Total borrowings less the cash you already have.",
      "Gross borrowings minus cash and cash equivalents. The bridge between enterprise value and equity value.",
      { fx: "Net debt = Borrowings − Cash", related: ["Enterprise value", "Equity value"],
        level: "intermediate", group: "Valuation" }),
    g("P/E ratio", "How many years of current earnings you are paying for one share.",
      "Price-to-earnings: share price divided by earnings per share. A relative valuation multiple, meaningful only against peers or history.",
      { fx: "P/E = Share price ÷ EPS", also: ["Price to earnings"],
        related: ["EPS", "EV/EBITDA"], level: "intermediate", group: "Valuation" }),
    g("EV/EBITDA", "How many years of operating profit you are paying for the whole business.",
      "Enterprise value divided by EBITDA. Preferred over P/E when comparing companies with different debt levels or tax positions.",
      { fx: "EV/EBITDA = Enterprise value ÷ EBITDA",
        related: ["Enterprise value", "EBITDA", "P/E ratio"], level: "advanced", group: "Valuation" }),
    g("Leverage", "Using borrowed money to make your own money go further — in both directions.",
      "The use of debt to amplify returns. It magnifies gains and losses equally, which is why it raises risk as well as return.",
      { related: ["Debt-to-equity", "Interest coverage", "DuPont analysis"], level: "intermediate", group: "Corporate finance" }),

    /* ---------------- modelling ---------------- */
    g("Three-statement model", "One linked spreadsheet where the income statement, balance sheet and cash flow all agree.",
      "A financial model in which the three statements are connected so that a change in any assumption flows correctly through all of them and the balance sheet still ties.",
      { related: ["Balance sheet", "DCF", "Driver"], lesson: "2120-linked-model", level: "advanced", group: "Modelling" }),
    g("Driver", "An assumption the whole model is built on, kept in its own cell so you can change it.",
      "An input variable — growth, margin, days of working capital — from which the rest of a model is calculated rather than typed.",
      { related: ["Three-statement model", "Sensitivity analysis"], lesson: "2210-drivers", level: "intermediate", group: "Modelling" }),
    g("Sensitivity analysis", "Checking how much the answer changes when your assumptions are wrong.",
      "Re-running a model across a range of input values to see how much the output moves — the honest way to present any valuation.",
      { related: ["DCF", "Driver"], level: "advanced", group: "Modelling" }),

    /* ---------------- startup ---------------- */
    g("ARR", "What your subscription revenue would total over a year, at today's rate.",
      "Annual recurring revenue: monthly recurring revenue multiplied by twelve. A run-rate, not a historical figure, and it should exclude one-off fees.",
      { fx: "ARR = MRR × 12", also: ["Annual recurring revenue", "MRR"],
        related: ["Revenue", "Burn multiple"], level: "intermediate", group: "Startup" }),
    g("Burn rate", "How much cash the business loses each month.",
      "Net burn is cash out less cash in per month; gross burn ignores revenue entirely.",
      { fx: "Net burn = Cash out − Cash in", also: ["Net burn", "Gross burn"],
        related: ["Runway", "CFO"], level: "intermediate", group: "Startup" }),
    g("Runway", "How many months until the bank account hits zero.",
      "Cash in the bank divided by net monthly burn. The countdown that determines when a startup must raise or reach profitability.",
      { fx: "Runway = Cash ÷ Net burn", related: ["Burn rate"], level: "intermediate", group: "Startup" }),
    g("CAC", "What it costs, on average, to win one new customer.",
      "Customer acquisition cost: total sales and marketing spend divided by new customers won in the same period. It must include sales salaries, not just advertising.",
      { fx: "CAC = Sales & marketing spend ÷ New customers", also: ["Customer acquisition cost"],
        related: ["LTV", "Churn"], level: "intermediate", group: "Startup" }),
    g("LTV", "The total profit you expect from one customer before they leave.",
      "Lifetime value: gross profit per customer per period multiplied by expected lifetime. Built from gross profit, never revenue.",
      { fx: "LTV = Monthly gross profit × (1 ÷ Churn)", also: ["Lifetime value", "LTV/CAC"],
        related: ["CAC", "Churn"], level: "advanced", group: "Startup" }),
    g("Churn", "The share of customers who leave each period.",
      "The rate at which customers cancel. Average customer lifetime is one divided by the churn rate, which is why halving churn doubles lifetime value.",
      { fx: "Average lifetime = 1 ÷ Monthly churn", related: ["LTV", "CAC"], level: "intermediate", group: "Startup" }),
    g("Dilution", "Your share of the company shrinks when new shares are issued.",
      "The reduction in existing shareholders' ownership percentage when new shares are created. The number of shares held is unchanged; the denominator grows.",
      { fx: "New % = Old % × (Pre-money ÷ Post-money)",
        also: ["Pre-money", "Post-money", "Cap table"], related: ["Share capital", "Equity"],
        level: "intermediate", group: "Startup" }),
    g("Burn multiple", "How many rupees of cash you burn to add one rupee of recurring revenue.",
      "Net cash burn divided by net new annual recurring revenue. A measure of growth efficiency: under 1x is exceptional, above 3x suggests growth is being bought rather than earned.",
      { fx: "Burn multiple = Net burn ÷ Net new ARR",
        related: ["ARR", "Burn rate", "Rule of 40"], level: "advanced", group: "Startup" }),
    g("Rule of 40", "Growth plus profit margin should clear 40 — be fast, or be profitable.",
      "A software benchmark: revenue growth rate plus profit margin should exceed 40%. It formalises the trade-off between growth and profitability.",
      { fx: "Growth % + Profit margin % ≥ 40", related: ["ARR", "Burn rate"], level: "advanced", group: "Startup" })
  ];

  /* ---------------- index ---------------- */
  var byKey = {};
  LS.glossary.forEach(function (t) {
    byKey[t.term.toLowerCase()] = t;
    t.also.forEach(function (a) { if (!byKey[a.toLowerCase()]) byKey[a.toLowerCase()] = t; });
  });
  LS.glossaryLookup = function (name) { return byKey[String(name).toLowerCase()] || null; };
  LS.glossaryGroups = function () {
    var out = {};
    LS.glossary.forEach(function (t) { (out[t.group] = out[t.group] || []).push(t); });
    return out;
  };
})();
