/* FinStudio Advanced Topic Lab
 * One reusable W3Schools-style lesson template for every advanced topic.
 * Each topic has: What / Formula or intuition / See It / Example / Sandbox / Challenge.
 */
(function(){
  "use strict";
  var LS=window.LS=window.LS||{};
  var topics=[
    {level:8,group:"Equity research & investing",name:"Investment thesis",formula:"Thesis = business quality + earnings view + valuation + catalyst − risks",example:"A strong thesis explains why the market is mispricing future cash flows.",inputs:[['Growth view',15],['Margin view',25],['Valuation upside',20]],unit:'%',calc:function(v){return (v[0]*.5+v[1]*.2+v[2]*.3).toFixed(1)+' thesis score'}} ,
    {level:8,group:"Equity research & investing",name:"Catalysts",formula:"Catalyst = identifiable event that can change expectations or valuation",example:"A new product, margin inflection, capacity ramp or regulatory approval can change the market's expectations.",inputs:[['Probability',60],['Expected price impact',15]],unit:'%',calc:function(v){return (v[0]*v[1]/100).toFixed(1)+'% expected impact'}} ,
    {level:8,group:"Equity research & investing",name:"Risks",formula:"Expected loss ≈ probability × impact",example:"Separate operational, financial, valuation and thesis risks instead of treating every risk as the same.",inputs:[['Probability',25],['Impact',40]],unit:'%',calc:function(v){return (v[0]*v[1]/100).toFixed(1)+'% risk score'}} ,
    {level:8,group:"Equity research & investing",name:"Bear / base / bull cases",formula:"Expected value = Σ(case probability × case value)",example:"Build three operating paths and make the probability weighting explicit.",inputs:[['Bear value',70],['Base value',100],['Bull value',140]],unit:'₹',calc:function(v){return ((v[0]*.25)+(v[1]*.5)+(v[2]*.25)).toFixed(0)+' weighted value'}} ,
    {level:8,group:"Equity research & investing",name:"Free cash flow",formula:"FCFF = EBIT × (1 − tax) + D&A − CapEx − ΔNWC",example:"Revenue ₹100 Cr, EBIT ₹20 Cr, tax 25%, D&A ₹5 Cr, CapEx ₹7 Cr, ΔNWC ₹2 Cr → FCFF ₹11 Cr.",inputs:[['EBIT',20],['Tax rate',25],['D&A',5],['CapEx',7],['ΔNWC',2]],unit:'₹ Cr',calc:function(v){return (v[0]*(1-v[1]/100)+v[2]-v[3]-v[4]).toFixed(2)+' ₹ Cr FCFF'}} ,
    {level:8,group:"Equity research & investing",name:"Valuation",formula:"Enterprise value = PV of forecast cash flows + PV of terminal value",example:"Value is a range, not a magical single number. Change growth, margins and discount rates to see sensitivity.",inputs:[['FCF',10],['Growth',4],['Discount rate',10]],unit:'%',calc:function(v){return (v[0]/(v[2]/100-v[1]/100)).toFixed(1)+' ₹ Cr perpetuity value'}} ,
    {level:9,group:"Markets",name:"Stocks",formula:"Market capitalization = share price × shares outstanding",example:"10 Cr shares at ₹120 = ₹1,200 Cr market cap.",inputs:[['Share price',120],['Shares outstanding',10]],unit:'₹ / Cr',calc:function(v){return (v[0]*v[1]).toFixed(0)+' ₹ Cr market cap'}} ,
    {level:9,group:"Markets",name:"Bonds",formula:"Bond price = PV(coupons) + PV(principal)",example:"A bond's price changes because the present value of its promised cash flows changes.",inputs:[['Face value',100],['Coupon rate',8],['Yield',10],['Years',5]],unit:'%',calc:function(v){var r=v[2]/100,n=v[3],c=v[0]*v[1]/100;return (c*(1-Math.pow(1+r,-n))/r+v[0]/Math.pow(1+r,n)).toFixed(2)+' bond price'}} ,
    {level:9,group:"Markets",name:"Yield",formula:"Yield links a bond's price to its promised cash flows",example:"When price falls while cash flows stay fixed, yield rises.",inputs:[['Coupon',8],['Price',95]],unit:'%',calc:function(v){return (v[0]/v[1]*100).toFixed(2)+'% simple current yield'}} ,
    {level:9,group:"Markets",name:"Interest rates",formula:"Higher discount rates generally reduce the present value of future cash flows",example:"Rates affect bonds, equity valuations, borrowing costs and investment decisions.",inputs:[['Cash flow',100],['Years',5],['Rate',10]],unit:'%',calc:function(v){return (v[0]/Math.pow(1+v[2]/100,v[1])).toFixed(2)+' PV'}} ,
    {level:9,group:"Markets",name:"Central banks",formula:"Policy rate → funding costs → financial conditions → demand → inflation / growth",example:"Use the sandbox to reason through a rate hike rather than memorise a chain of words.",inputs:[['Policy rate change',1],['Sensitivity',2]],unit:'%',calc:function(v){return (v[0]*v[1]).toFixed(2)+'% illustrative financial-condition change'}} ,
    {level:9,group:"Markets",name:"FX",formula:"Forward FX ≈ Spot × (1 + domestic rate) / (1 + foreign rate)",example:"Interest-rate differentials can affect forward exchange rates.",inputs:[['Spot',83],['Domestic rate',7],['Foreign rate',4]],unit:'₹ / $',calc:function(v){return (v[0]*(1+v[1]/100)/(1+v[2]/100)).toFixed(2)+' forward FX'}} ,
    {level:9,group:"Markets",name:"Commodities",formula:"Commodity value is driven by spot supply, demand, inventories and expectations",example:"A supply shock can raise price while reducing expected future production.",inputs:[['Demand index',100],['Supply index',100]],unit:'index',calc:function(v){return (v[0]/v[1]*100).toFixed(1)+' implied price index'}} ,
    {level:9,group:"Markets",name:"Derivatives",formula:"Derivative payoff = function of an underlying price and contract terms",example:"Derivatives transfer or reshape exposure; the payoff is defined before the outcome is known.",inputs:[['Underlying move',10],['Notional',100]],unit:'%',calc:function(v){return (v[0]*v[1]/100).toFixed(2)+' payoff units'}} ,
    {level:9,group:"Markets",name:"Options",formula:"Call payoff = max(S − K, 0); Put payoff = max(K − S, 0)",example:"At expiry, a call is valuable only when the underlying finishes above the strike.",inputs:[['Underlying',120],['Strike',100]],unit:'₹',calc:function(v){return Math.max(v[0]-v[1],0).toFixed(2)+' call payoff'}} ,
    {level:9,group:"Markets",name:"Futures",formula:"Futures P&L ≈ position × (exit price − entry price)",example:"A futures contract creates linear exposure to the underlying price.",inputs:[['Entry price',100],['Exit price',112],['Position',10]],unit:'₹',calc:function(v){return ((v[1]-v[0])*v[2]).toFixed(2)+' P&L'}} ,
    {level:9,group:"Markets",name:"Credit",formula:"Credit spread = risky yield − comparable risk-free yield",example:"A wider spread generally signals greater perceived credit risk or tighter liquidity.",inputs:[['Corporate yield',9],['Government yield',7]],unit:'%',calc:function(v){return (v[0]-v[1]).toFixed(2)+'% credit spread'}} ,
    {level:9,group:"Markets",name:"Yield curves",formula:"Yield curve = yields plotted across maturities",example:"The curve can be upward, flat or inverted; shape contains information about rates and expectations.",inputs:[['2Y yield',7],['10Y yield',6.5]],unit:'%',calc:function(v){return (v[1]-v[0]).toFixed(2)+'% 10Y−2Y slope'}} ,
    {level:9,group:"Markets",name:"Duration",formula:"Duration approximates percentage price sensitivity to a change in yield",example:"A higher-duration bond generally moves more when yields change.",inputs:[['Duration',5],['Yield change',1]],unit:'%',calc:function(v){return (-v[0]*v[1]).toFixed(2)+'% approximate price change'}} ,
    {level:9,group:"Markets",name:"Convexity",formula:"Convexity improves the duration approximation for larger yield moves",example:"Price-yield relationships are curved, not perfectly linear.",inputs:[['Duration',5],['Convexity',40],['Yield change',1]],unit:'%',calc:function(v){var dy=v[2]/100;return (-v[0]*dy+.5*v[1]*dy*dy).toFixed(4)+' approximate price change'}} ,
    {level:9,group:"Markets",name:"Liquidity",formula:"Liquidity = ability to transact quickly with limited price impact",example:"A market can be deep in normal conditions and fragile during stress.",inputs:[['Trade size',10],['Depth',100]],unit:'index',calc:function(v){return (v[1]/v[0]).toFixed(1)+' depth / trade ratio'}} ,
    {level:9,group:"Markets",name:"Volatility",formula:"Volatility measures dispersion of returns",example:"Higher volatility means a wider distribution of possible outcomes, not automatically a direction.",inputs:[['Daily volatility',2],['Days',252]],unit:'%',calc:function(v){return (v[0]*Math.sqrt(v[1])).toFixed(2)+'% annualized volatility'}} ,
    {level:10,group:"Advanced finance",name:"Options pricing",formula:"Option value = intrinsic value + time value",example:"Option value changes with underlying price, strike, time, volatility and rates.",inputs:[['Spot',105],['Strike',100],['Volatility',25]],unit:'%',calc:function(v){return (Math.max(v[0]-v[1],0)+v[2]*.1).toFixed(2)+' illustrative option value'}} ,
    {level:10,group:"Advanced finance",name:"Black-Scholes intuition",formula:"Value depends on S, K, time, volatility and risk-free rate",example:"Volatility increases the range of outcomes and generally increases option value.",inputs:[['Spot',100],['Strike',100],['Volatility',20],['Years',1]],unit:'%',calc:function(v){return (v[2]*Math.sqrt(v[3])).toFixed(2)+' volatility-time score'}} ,
    {level:10,group:"Advanced finance",name:"Greeks",formula:"Delta, Gamma, Vega, Theta and Rho describe option sensitivities",example:"Greeks turn a complicated option position into measurable exposures.",inputs:[['Delta',.5],['Underlying move',10]],unit:'₹',calc:function(v){return (v[0]*v[1]).toFixed(2)+' delta P&L'}} ,
    {level:10,group:"Advanced finance",name:"Portfolio theory",formula:"Portfolio return = Σ(weight × asset return)",example:"Diversification changes portfolio risk even when expected returns stay similar.",inputs:[['Asset A weight',60],['Asset A return',10],['Asset B return',5]],unit:'%',calc:function(v){return (v[0]/100*v[1]+(1-v[0]/100)*v[2]).toFixed(2)+'% portfolio return'}} ,
    {level:10,group:"Advanced finance",name:"CAPM",formula:"Expected return = Risk-free rate + Beta × Equity risk premium",example:"CAPM links required return to systematic market exposure.",inputs:[['Risk-free rate',7],['Beta',1.2],['Equity risk premium',6]],unit:'%',calc:function(v){return (v[0]+v[1]*v[2]).toFixed(2)+'% required return'}} ,
    {level:10,group:"Advanced finance",name:"Efficient frontier",formula:"Efficient portfolio = highest expected return for a given level of risk",example:"Move weights and observe how expected return changes relative to risk.",inputs:[['Expected return',10],['Risk',15]],unit:'%',calc:function(v){return (v[0]/v[1]).toFixed(3)+' return / risk'}} ,
    {level:10,group:"Advanced finance",name:"Sharpe ratio",formula:"Sharpe = (Portfolio return − Risk-free rate) ÷ Portfolio volatility",example:"Sharpe compares excess return per unit of volatility.",inputs:[['Return',12],['Risk-free rate',7],['Volatility',15]],unit:'%',calc:function(v){return ((v[0]-v[1])/v[2]).toFixed(2)+' Sharpe'}} ,
    {level:10,group:"Advanced finance",name:"Beta",formula:"Beta = Covariance(asset, market) ÷ Variance(market)",example:"Beta measures sensitivity to broad market movements.",inputs:[['Asset move',12],['Market move',10]],unit:'%',calc:function(v){return (v[0]/v[1]).toFixed(2)+' illustrative beta'}} ,
    {level:10,group:"Advanced finance",name:"Alpha",formula:"Alpha ≈ Actual return − expected return",example:"Alpha asks whether performance exceeded what the chosen benchmark/model predicts.",inputs:[['Actual return',14],['Expected return',10]],unit:'%',calc:function(v){return (v[0]-v[1]).toFixed(2)+'% alpha'}} ,
    {level:10,group:"Advanced finance",name:"Factor investing",formula:"Expected return = exposure × factor premium + idiosyncratic component",example:"Value, quality, momentum, size and low-volatility are common factor lenses.",inputs:[['Factor exposure',1.2],['Factor premium',4]],unit:'%',calc:function(v){return (v[0]*v[1]).toFixed(2)+'% factor contribution'}} ,
    {level:10,group:"Advanced finance",name:"Risk management",formula:"Risk management = identify → measure → limit → monitor → stress",example:"A good risk process makes the downside explicit before capital is committed.",inputs:[['Exposure',100],['Stress move',20]],unit:'%',calc:function(v){return (v[0]*v[1]/100).toFixed(2)+' stressed loss'}} ,
    {level:10,group:"Advanced finance",name:"VaR",formula:"VaR = loss threshold not exceeded at a chosen confidence over a chosen horizon",example:"95% one-day VaR of ₹10 Cr means the model estimates only a 5% chance of losing more than ₹10 Cr in one day.",inputs:[['Portfolio value',100],['Volatility',2],['Z score',1.65]],unit:'₹ Cr',calc:function(v){return (v[0]*v[1]/100*v[2]).toFixed(2)+' ₹ Cr VaR'}} ,
    {level:10,group:"Advanced finance",name:"Scenario analysis",formula:"Scenario value = model output under a defined set of assumptions",example:"Change growth, margin, rates and exit multiples together to test coherent worlds.",inputs:[['Growth',10],['Margin',20],['Exit multiple',12]],unit:'%',calc:function(v){return (v[0]*v[1]*v[2]/100).toFixed(2)+' scenario score'}} ,
    {level:10,group:"Advanced finance",name:"Monte Carlo simulation",formula:"Simulate many possible paths → distribution of outcomes",example:"Instead of one forecast, model a probability distribution of possible values.",inputs:[['Starting value',100],['Expected return',8],['Volatility',20]],unit:'%',calc:function(v){return (v[0]*(1+v[1]/100)).toFixed(2)+' expected endpoint; ± '+(v[0]*v[2]/100).toFixed(2)}} ,
    {level:10,group:"Advanced finance",name:"Capital structure",formula:"Enterprise value is funded by a mix of debt and equity",example:"Changing leverage changes interest burden, equity risk and potentially returns.",inputs:[['Debt',40],['Equity',60]],unit:'%',calc:function(v){return (v[0]/v[1]).toFixed(2)+' debt / equity'}} ,
    {level:10,group:"Advanced finance",name:"Cost of capital",formula:"WACC = E/V × Cost of equity + D/V × After-tax cost of debt",example:"Use WACC as a hurdle rate consistent with the risk of the cash flows being valued.",inputs:[['Equity weight',60],['Cost of equity',13],['Debt weight',40],['Pre-tax debt cost',8],['Tax rate',25]],unit:'%',calc:function(v){return (v[0]/100*v[1]+v[2]/100*v[3]*(1-v[4]/100)).toFixed(2)+'% WACC'}}
  ];
  LS.advancedTopics=topics;
  function slug(s){return s.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');}
  function esc(s){return String(s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');}
  function render(topic){
    var main=document.getElementById('main'); if(!main)return;
    var values=topic.inputs.map(function(x){return x[1];});
    var cards=topic.inputs.map(function(x,i){return '<label class="lab-input"><span>'+esc(x[0])+'</span><input type="number" step="any" value="'+x[1]+'" data-i="'+i+'"></label>';}).join('');
    main.innerHTML='<div class="page topic-lab-page"><p class="lesson-kicker">LEVEL '+topic.level+' · '+esc(topic.group)+'</p><h1>'+esc(topic.name)+'</h1><p class="lesson-lede">'+esc(topic.example)+'</p><div class="topic-template"><section><h2>What is '+esc(topic.name)+'?</h2><p>'+esc(topic.example)+'</p></section><section><h2>The Formula / Intuition</h2><div class="lab-formula">'+esc(topic.formula)+'</div></section><section><h2>See It</h2><div class="lab-viz"><div class="lab-bars"><i style="height:30%"></i><i style="height:55%"></i><i style="height:80%"></i><i style="height:65%"></i><i style="height:95%"></i></div><strong id="labOutput"></strong></div></section><section><h2>Example</h2><p>'+esc(topic.example)+'</p></section><section class="lab-sandbox"><div><p class="lesson-kicker">TRY IT YOURSELF</p><h2>Sandbox</h2><p>Change an assumption. FinStudio recalculates the result immediately.</p></div><div class="lab-inputs">'+cards+'</div><div class="lab-result"><span>Live result</span><strong id="labResult"></strong></div></section><section class="lab-challenge"><h2>Challenge</h2><p>Change at least two inputs and explain, in your own words, why the result changed. Then try an extreme value and see whether your intuition still holds.</p></section></div></div>';
    function update(){var v=[].map.call(main.querySelectorAll('.lab-input input'),function(el){var n=Number(el.value);return Number.isFinite(n)?n:0;});var out=topic.calc(v);main.querySelector('#labResult').textContent=out;main.querySelector('#labOutput').textContent=out;}
    [].forEach.call(main.querySelectorAll('.lab-input input'),function(el){el.addEventListener('input',update);}); update();
  }
  function sync(){var h=location.hash.replace(/^#\/?/,'');if(h.indexOf('lab/topic/')===0){var id=h.slice(10);var t=topics.find(function(x){return slug(x.name)===id;});if(t)render(t);}}
  window.addEventListener('hashchange',sync);window.addEventListener('load',sync);sync();
})();
