/* Level 4 — Financial Modeling. 25 lessons.
   Learning loop per lesson: intuition → accurate explanation → worked example
   → practice with answers → connection. Depth scales with the concept. */
(function () {
  "use strict";
  var LS = (window.LS = window.LS || {});
  LS.lessons = LS.lessons || {};

  function h2(t) { return { t: "h2", text: t }; }
  function p(h) { return { t: "p", h: h }; }
  function list(i) { return { t: "list", items: i }; }
  function def(term, h) { return { t: "def", term: term, h: h }; }
  function note(i) { return { t: "note", h: "<ul>" + i.map(function (x) { return "<li>" + x + "</li>"; }).join("") + "</ul>" }; }
  function practice(i) { return { t: "practice", items: i }; }
  function sandbox(kind, title, prompt, fields) { return { t: "sandbox", kind: kind, title: title, prompt: prompt, fields: fields }; }
  function formula(title, lines) { return { t: "formula", title: title, lines: lines }; }
  function mcq(q, o, c, w) { return { t: "mcq", q: q, opts: o, correct: c, why: w }; }
  function fig(title, intro, rows, meaning) {
    var h = '<p class="case-title"><strong>' + title + "</strong></p>";
    intro.forEach(function (x) { h += "<p>" + x + "</p>"; });
    h += '<div class="case-figures">';
    rows.forEach(function (r) { h += '<div class="case-row"><span class="case-label">' + r[0] + '</span><span class="case-value">' + r[1] + "</span></div>"; });
    h += "</div><p class=\"case-meaning\"><strong>What it means.</strong></p>";
    meaning.forEach(function (x) { h += "<p>" + x + "</p>"; });
    return { t: "example", h: h };
  }
  function L(id, title, lede, body) {
    LS.lessons[id] = { id: id, title: title, short: title, desc: lede, lede: lede, minutes: 7, body: body };
  }
  var W = "Not quite — re-read the explanation above.";

  /* ============ MODEL ARCHITECTURE ============ */

  L("c-model-architecture", "Model architecture",
    "A model is a chain: assumptions drive schedules, schedules drive statements, statements drive the answer.",
    [
      h2("What is this?"),
      p("A financial model is a spreadsheet that turns a small set of assumptions into a full picture of a company's future. Architecture is how you arrange it so the chain of cause and effect stays visible."),
      p("The standard layout separates three things that beginners usually mix together: <strong>inputs</strong> (numbers you choose), <strong>calculations</strong> (formulas that transform them), and <strong>outputs</strong> (the statements and answers). A number should be typed in exactly one place and referenced everywhere else."),
      h2("Why does it matter?"),
      p("Models are wrong in proportion to how hard they are to check. If growth is typed in twelve places, changing it means finding twelve cells, and you will miss one. If it lives in a single input cell, the whole model updates from one keystroke and anyone can audit it."),
      h2("How does it work?"),
      list([
        "<strong>Inputs sheet.</strong> Every assumption, gathered in one place, formatted so they are obviously inputs.",
        "<strong>Schedules.</strong> Revenue, costs, working capital, capex, depreciation, debt — each built separately.",
        "<strong>Statements.</strong> Income statement, balance sheet and cash flow, pulling from the schedules only.",
        "<strong>Outputs.</strong> Valuation, returns, key ratios and charts.",
      ]),
      p("Information flows one direction: inputs → schedules → statements → outputs. When a formula points backwards, the model becomes hard to follow and easy to break."),
      fig("Real-Life Case Study: one input, one change",
        ["A café model uses a 12% revenue growth assumption. The analyst is asked to test 8%."],
        [["Growth typed into 14 cells", "14 edits, high error risk"], ["Growth in one input cell", "1 edit"], ["Cells referencing that input", "14"], ["Time to re-run scenario", "seconds"]],
        ["The second model answers the question in one keystroke and the first probably answers it wrongly.",
         "This is the entire argument for architecture: it is not neatness, it is the difference between a model you can trust and one you cannot."]),
      h2("Key terms"),
      def("Input", "A number the modeller chooses. Typed once, never calculated."),
      def("Schedule", "A supporting calculation block — debt, capex, working capital — feeding the statements."),
      def("Hardcode", "A number typed directly inside a formula. The main source of untraceable errors."),
      h2("Practice"),
      practice([
        { q: "A model has =B5*1.12 in the revenue row. What is wrong with it and how would you fix it?", a: "The 1.12 growth rate is hardcoded inside the formula, so it is invisible and must be edited cell by cell. Fix: put 12% in an input cell and write =B5*(1+$B$2), referencing it." },
        { q: "Why should the balance sheet never feed back into the revenue assumption?", a: "It breaks the one-directional flow. Revenue is a driver; the balance sheet is a result. Pointing a driver at a result creates circular logic and makes the chain of cause and effect impossible to follow." },
      ]),
      h2("Connection"),
      p("Everything else in this level sits inside this structure. The schedules you build next all live between the inputs and the statements."),
      mcq("In a well-built model, an assumption should be typed:",
        ["In every formula that uses it", "Once, in an input cell, and referenced everywhere else", "Nowhere — models calculate assumptions", "In the balance sheet"], 1,
        [W, "Correct. One source per number makes the model auditable and lets a scenario change in one keystroke.", W, W]),
    ]);

  L("c-assumptions", "Assumptions",
    "Every model output is just your assumptions, rearranged.",
    [
      h2("What is this?"),
      p("Assumptions are the numbers you choose rather than calculate: growth rates, margins, collection days, capex, interest rates, tax rates. Everything else in the model is arithmetic performed on them."),
      p("That is worth sitting with. A valuation is not a discovery about a company — it is a restatement of what you assumed, expressed in rupees."),
      h2("Why does it matter?"),
      p("Because the output looks precise, people trust it. A model saying ₹487.32 per share feels like a measurement. It is not: change growth from 10% to 8% and it might say ₹402. The decimals are false confidence."),
      p("Good practice is to state assumptions explicitly, justify each one, and show how sensitive the answer is to the two or three that matter most."),
      h2("How does it work?"),
      list([
        "<strong>Ground them in history.</strong> If margins have been 12-14% for five years, 22% needs a specific reason.",
        "<strong>Keep them few.</strong> Twenty assumptions do not make a model more accurate, only harder to check.",
        "<strong>Label the driver assumptions.</strong> Usually growth, margin and capital intensity carry most of the answer.",
        "<strong>Write down the reason</strong> beside each one, so a reviewer can argue with the logic, not just the number.",
      ]),
      fig("Real-Life Case Study: the same model, two views",
        ["An analyst values a business at ₹500 crore using 12% growth and a 20% EBITDA margin."],
        [["Growth 12%, margin 20%", "₹500 crore"], ["Growth 9%, margin 20%", "₹430 crore"], ["Growth 12%, margin 17%", "₹425 crore"], ["Growth 9%, margin 17%", "₹365 crore"]],
        ["Small, entirely reasonable changes to two assumptions move the answer by 27%.",
         "The honest output is not ₹500 crore; it is 'roughly ₹365-500 crore depending on growth and margin, and here is why I lean towards the middle.'"]),
      h2("Key terms"),
      def("Driver assumption", "An input the answer is highly sensitive to — usually growth, margin or capital intensity."),
      def("Base case", "The set of assumptions you consider most likely."),
      def("False precision", "Reporting an answer to more decimal places than the inputs justify."),
      h2("Practice"),
      practice([
        { q: "A company's revenue grew 6%, 7% and 5% over three years. Your model assumes 18%. What must you be able to explain?", a: "A specific reason for the break from history: a new product, a capacity expansion completing, a large contract won, or a market shift. Without one, 18% is a wish, and every number downstream inherits it." },
        { q: "Why is it more useful to report a valuation range than a single figure?", a: "The single figure implies a precision the inputs do not support. A range makes the uncertainty visible and forces the discussion onto the assumptions driving it — which is where the real disagreement always lies." },
      ]),
      h2("Connection"),
      p("Scenario and sensitivity analysis, later in this level, exist precisely to test the assumptions you set here."),
      mcq("A model's output is best described as:",
        ["An objective measurement of value", "Your assumptions restated in rupees", "A guarantee of future performance", "An accounting fact"], 1,
        [W, "Correct. The arithmetic is reliable; the answer is only as good as the inputs you chose.", W, W]),
    ]);

  L("c-historical-periods", "Historical periods",
    "Three years of actuals is where every credible forecast starts.",
    [
      h2("What is this?"),
      p("Historical periods are the actual reported results — usually three to five years — laid out in the model before any forecast. They are not decoration. They are the evidence base for every assumption you are about to make."),
      h2("Why does it matter?"),
      p("Forecasting without history is guessing. Once the actuals are in, you can compute what growth, margins and working capital days have actually been, and any forecast that departs from them needs a reason you can say out loud."),
      p("Laying out history also surfaces problems: a one-off gain, a change in accounting policy, an acquisition mid-year. Each distorts the ratios you are about to extrapolate."),
      h2("How does it work?"),
      list([
        "Enter reported figures exactly as published — no adjustments in the input rows.",
        "Compute the derived metrics beneath: growth, margins, days, capex as a percentage of revenue.",
        "Look for trend, not level. Three years of falling margin matters more than this year's number.",
        "Flag one-offs separately so they do not silently become part of the forecast base.",
      ]),
      fig("Real-Life Case Study: reading the actuals",
        ["Three years of a components maker, with derived metrics computed underneath."],
        [["Revenue FY23 / FY24 / FY25", "₹420 / ₹468 / ₹510 crore"], ["Growth", "— / 11.4% / 9.0%"], ["EBITDA margin", "18.1% / 17.4% / 16.2%"], ["Days receivable", "58 / 64 / 71"], ["Capex ÷ revenue", "6.2% / 6.0% / 5.9%"]],
        ["Growth is decelerating, margins are falling about a point a year, and collections are slipping 6-7 days a year.",
         "A forecast of 12% growth with stable margins would contradict all three trends. The history has already told you what to defend."]),
      h2("Key terms"),
      def("Actuals", "Reported historical figures, entered unchanged."),
      def("Derived metric", "A ratio computed from actuals — growth, margin, days — used to set assumptions."),
      def("Normalisation", "Adjusting history to remove one-off items so the base is representative."),
      h2("Practice"),
      practice([
        { q: "FY25 net profit includes a ₹30 crore gain from selling land. Why must this be flagged before forecasting?", a: "Net margin and profit growth computed from FY25 would be inflated by a one-off. Extrapolating that base builds a permanent gain into every forecast year from a transaction that happened once." },
        { q: "Days receivable moved 58 → 64 → 71 over three years. What should your forecast assume, and what should you investigate?", a: "Do not assume a snap back to 58 without a reason; 71 or a little worse is the defensible base. Investigate why: weaker customers, longer terms offered to win sales, or slipping collection discipline. Each has different implications for cash and bad debts." },
      ]),
      h2("Connection"),
      p("Every schedule in the next module — revenue, cost, working capital, capex — takes its starting assumption from these derived metrics."),
      mcq("The main purpose of laying out historical periods is:",
        ["To fill space in the model", "To provide the evidence base and trends that justify forecast assumptions", "To calculate the share price", "To satisfy auditors"], 1,
        [W, "Correct. History tells you what the business actually does, so any forecast departing from it needs an explicit reason.", W, W]),
    ]);

  L("c-model-formatting", "Model formatting",
    "Formatting is not decoration — it is how a reader knows which numbers they may change.",
    [
      h2("What is this?"),
      p("Modelling convention uses colour and formatting to encode meaning. The near-universal standard: <strong>blue for inputs</strong> typed by hand, <strong>black for formulas</strong>, <strong>green for links to other sheets</strong>."),
      p("Anyone opening the file can then tell at a glance what is an assumption and what is a calculation, without clicking a single cell."),
      h2("Why does it matter?"),
      p("Models are read by other people — a manager, a lender, a colleague picking it up a year later. Consistent formatting is the difference between a file someone can use and one they have to rebuild."),
      p("It also protects you from yourself. A black number where you expected blue means someone hardcoded over a formula, which is the most common way models silently break."),
      h2("How does it work?"),
      list([
        "Blue for hardcoded inputs; black for calculations; green for cross-sheet links.",
        "One sign convention throughout: either costs are negative and you add, or positive and you subtract. Never mix.",
        "Units labelled in row headers — ₹ crore, %, days — so nobody misreads a scale.",
        "Consistent decimals: money to zero or one decimal, ratios to one, percentages to one.",
        "No hidden rows or columns in a model others will use.",
      ]),
      fig("Real-Life Case Study: spotting the break",
        ["A reviewer opens a forecast and scans the EBITDA row."],
        [["FY26 EBITDA", "black (formula)"], ["FY27 EBITDA", "black (formula)"], ["FY28 EBITDA", "blue (typed)"], ["FY29 EBITDA", "black (formula)"]],
        ["FY28 is blue in a row that should be entirely calculated: someone typed over the formula, probably to force a number.",
         "The reviewer found it in two seconds without opening a single cell. Without the convention, that error ships."]),
      h2("Key terms"),
      def("Sign convention", "The consistent choice to enter costs as negatives or positives throughout a model."),
      def("Hardcode", "Typing a value over a formula. Legitimate in an input cell, dangerous anywhere else."),
      h2("Practice"),
      practice([
        { q: "You inherit a model where some costs are negative and others positive in the same column. What breaks, and what do you do?", a: "Any SUM over the column double-counts or cancels, so every subtotal is suspect. Pick one convention — usually costs negative, then SUM — and rebuild the column, checking each subtotal against the reported statement." },
        { q: "Why is a blue cell in the middle of a calculated row a warning sign?", a: "It means a formula was overwritten with a typed number. The model will no longer respond to assumption changes in that period, and a scenario run will silently produce wrong answers." },
      ]),
      h2("Connection"),
      p("The model checks lesson relies on these conventions: many of the checks are visual before they are arithmetic."),
      mcq("By convention, a blue number in a financial model means:",
        ["An error", "A hardcoded input the user may change", "A formula", "A link to another file"], 1,
        [W, "Correct. Blue marks a typed assumption; black marks a calculation. The distinction lets a reader audit at a glance.", W, W]),
    ]);

  L("c-model-best-practices", "Model best practices",
    "The habits that separate a model people trust from one they quietly rebuild.",
    [
      h2("What is this?"),
      p("A short list of disciplines that experienced modellers apply without thinking. None are difficult; all of them are skipped under time pressure, which is exactly when errors get made."),
      h2("Why does it matter?"),
      p("Studies of spreadsheets in professional use consistently find errors in a large majority of them. Models drive real decisions — lending, investing, hiring — so the cost of a wrong cell is not academic."),
      h2("How does it work?"),
      list([
        "<strong>One row, one formula.</strong> A formula copied across a row should be identical in every period. Breaks in the pattern are where errors hide.",
        "<strong>No hardcodes outside inputs.</strong> If you must override, colour it and note why.",
        "<strong>Build checks as you go</strong>, not at the end. Balance sheet balances, cash ties, sources equal uses.",
        "<strong>Keep it as simple as the question allows.</strong> Extra detail adds error surface, not accuracy.",
        "<strong>Label everything.</strong> Units, periods, currency, actual versus forecast.",
        "<strong>Never break the flow:</strong> inputs → schedules → statements → outputs.",
      ]),
      fig("Real-Life Case Study: the cost of one broken row",
        ["A model forecasts five years. In FY28 someone edited a single formula to force a target."],
        [["Years with the standard formula", "FY26, FY27, FY29, FY30"], ["Year overridden", "FY28"], ["Effect on FY28 EBITDA", "+₹22 crore"], ["Effect on the valuation", "+₹190 crore"], ["Time to notice", "after the deal was priced"]],
        ["One cell moved the valuation by nearly a fifth, and nothing on screen looked wrong.",
         "The one-row-one-formula rule exists precisely because this error is invisible unless the pattern is unbroken."]),
      h2("Key terms"),
      def("Check row", "A formula that verifies an identity — for example closing cash on the balance sheet equalling closing cash on the cash flow."),
      def("Error surface", "The number of places a model can be wrong. Complexity increases it."),
      h2("Practice"),
      practice([
        { q: "Your model must hit a specific EBITDA the CEO has promised. What is the right way to reflect that?", a: "Change the assumptions that would produce it — growth, price, cost — and see whether they are defensible. Never type over the EBITDA formula. If no credible assumption set reaches the target, that is the finding, and it is more valuable than a model that agrees." },
        { q: "Why does adding more detail not necessarily make a model more accurate?", a: "Each extra line is another assumption and another place to be wrong. Forecasting fifty cost lines individually adds error surface without adding information, when the aggregate cost ratio was more stable and easier to defend." },
      ]),
      h2("Connection"),
      p("These habits make the integrated model — where an error in any schedule propagates into all three statements — safe to build."),
      mcq("A model must reach a target the assumptions do not support. The correct response is:",
        ["Type the target over the formula", "Report that no defensible assumption set reaches it", "Hide the row", "Change the tax rate until it works"], 1,
        [W, "Correct. The model's job is to tell you what the assumptions imply. Forcing the output destroys the only value it has.", W, W]),
    ]);

  /* ============ OPERATING SCHEDULES ============ */

  L("c-revenue-build", "Revenue build",
    "Forecast revenue by building it from what actually drives it, not by picking a growth rate.",
    [
      h2("What is this?"),
      p("A revenue build breaks the top line into the physical drivers underneath it — units and price, stores and sales per store, customers and spend per customer — and forecasts each separately."),
      p("The alternative, applying a single growth percentage, hides every assumption inside one number nobody can argue with."),
      h2("Why does it matter?"),
      p("'Revenue grows 15%' cannot be debated. 'We open 8 stores and same-store sales rise 4%' can: someone can ask whether 8 stores is fundable, whether the sites exist, whether 4% is consistent with history. A build makes the forecast falsifiable, which is what makes it useful."),
      h2("How does it work?"),
      list([
        "<strong>Pick the drivers the business actually runs on.</strong> Retail: stores × sales per store. SaaS: customers × ARPU. Manufacturing: volume × price.",
        "<strong>Forecast each driver separately</strong>, each grounded in its own history.",
        "<strong>Multiply, don't add.</strong> Price and volume growth compound.",
        "<strong>Sanity-check the implied total growth</strong> against history and market size.",
      ]),
      formula("Revenue build", [
        "<b>Revenue = Volume × Price</b>",
        "<b>Growth = (1 + volume growth) × (1 + price growth) − 1</b>",
        "Volume and price are forecast separately, then combined",
      ]),
      fig("Real-Life Case Study: a café chain",
        ["FY25 actuals, then the FY26 build."],
        [["Stores FY25", "40"], ["Revenue per store FY25", "₹1.2 crore"], ["Revenue FY25", "₹48 crore"],
         ["New stores FY26", "+6"], ["Same-store growth", "+5%"], ["Revenue FY26", "₹57.96 crore"], ["Implied total growth", "20.8%"]],
        ["46 stores × ₹1.26 crore = ₹57.96 crore. The 20.8% growth was not assumed — it fell out of two assumptions that can each be challenged.",
         "Now the discussion is useful: can they fund six fit-outs, and is 5% same-store growth consistent with last year's 3%?"]),
      h2("Key terms"),
      def("Driver", "The physical quantity revenue depends on — units, customers, stores."),
      def("Same-store growth", "Growth from existing locations only, excluding new openings. Isolates underlying demand."),
      def("ARPU", "Average revenue per user — the price side of a subscription build."),
      h2("Practice"),
      practice([
        { q: "A SaaS business has 4,000 customers paying ₹18,000 a year. It expects 25% customer growth and a 6% price rise. Compute FY26 revenue.", a: "Customers = 4,000 × 1.25 = 5,000. Price = 18,000 × 1.06 = ₹19,080. Revenue = 5,000 × 19,080 = ₹9.54 crore, against ₹7.2 crore — 32.5% growth, because 25% and 6% multiply." },
        { q: "Why does a build make a forecast easier to challenge than a single growth rate?", a: "Each driver is separately visible and separately testable against history, capacity and market size. A single percentage bundles every assumption into one number with no visible reasoning to attack." },
      ]),
      h2("Connection"),
      p("This is the top line of the integrated model. Every schedule that follows — costs, working capital, capex — is usually driven off it."),
      sandbox("revenue-growth", "Revenue build sandbox",
        "Set price and volume growth separately and check why the combined growth exceeds their sum.", [
        { key: "price", label: "Price per unit", value: 1200000, unit: "₹" },
        { key: "volume", label: "Units (stores)", value: 40 },
        { key: "priceGrowth", label: "Price / same-store growth", value: 5, unit: "%" },
        { key: "volumeGrowth", label: "Volume growth", value: 15, unit: "%" },
      ]),
      mcq("Volume grows 25% and price grows 6%. Revenue grows:",
        ["31%", "32.5%", "25%", "19%"], 1,
        [W, "Correct. 1.25 × 1.06 = 1.325. The two effects multiply, so the answer exceeds their sum.", W, W]),
    ]);

  L("c-cost-build", "Cost build",
    "Forecast costs by how they behave, not by growing them all at the same rate.",
    [
      h2("What is this?"),
      p("A cost build separates costs by behaviour before forecasting them: variable costs are modelled as a percentage of revenue or per unit; fixed costs are modelled as an amount that grows with inflation or with specific decisions."),
      h2("Why does it matter?"),
      p("Growing every cost line at the revenue growth rate assumes the business has no operating leverage at all — which is almost never true, and quietly removes the most important dynamic in the forecast."),
      p("Modelled correctly, a 20% revenue rise produces a much larger profit rise, because rent and salaried staff do not scale with it. That gap is where most of the value in a growth forecast comes from."),
      h2("How does it work?"),
      list([
        "<strong>Variable costs:</strong> forecast as a % of revenue, or as cost per unit × volume.",
        "<strong>Fixed costs:</strong> forecast as an amount, grown by inflation, plus any step changes you know about.",
        "<strong>Step costs:</strong> flat until capacity is hit, then jumping — a second shift, another warehouse.",
        "<strong>Check the implied margin</strong> against history. If your build produces a margin the business has never achieved, something is wrong.",
      ]),
      fig("Real-Life Case Study: leverage in the build",
        ["Revenue rises 20%. COGS is variable at 60% of revenue; overheads are fixed and rise 6% with inflation."],
        [["Revenue FY25 → FY26", "₹100 → ₹120 crore"], ["COGS (60% of revenue)", "₹60 → ₹72 crore"], ["Overheads (fixed +6%)", "₹25 → ₹26.5 crore"], ["Operating profit", "₹15 → ₹21.5 crore"], ["Revenue growth", "+20%"], ["Profit growth", "+43%"]],
        ["Profit grew more than twice as fast as revenue, entirely because overheads did not scale.",
         "Had you grown overheads by 20% too, profit would have been ₹18 crore and you would have understated the business by ₹3.5 crore — and missed the whole point of the growth."]),
      h2("Key terms"),
      def("Variable cost", "A cost that moves with volume — materials, freight, transaction fees."),
      def("Step cost", "A fixed cost that jumps at a capacity threshold."),
      def("Cost ratio", "A cost expressed as a percentage of revenue, used to forecast variable lines."),
      h2("Practice"),
      practice([
        { q: "Revenue ₹200 crore rising 15%. COGS is 55% of revenue; fixed overheads are ₹40 crore rising 5%. Compute next year's operating profit and its growth.", a: "Revenue ₹230 crore. COGS = 55% × 230 = ₹126.5 crore. Overheads = ₹42 crore. Operating profit = 230 − 126.5 − 42 = ₹61.5 crore, against 200 − 110 − 40 = ₹50 crore. Growth 23% on 15% revenue growth." },
        { q: "Your build produces a 32% EBITDA margin for a business that has never exceeded 21%. What should you do?", a: "Find the error before defending the number. Usually a fixed cost has been left flat when it should step up, a cost line has been omitted, or a variable ratio was taken from an unusual year. A margin with no precedent needs a specific, nameable cause." },
      ]),
      h2("Connection"),
      p("This build produces the gross profit and EBITDA lines of the model, and it is where operating leverage — from Level 3 — enters the forecast."),
      sandbox("operating-leverage", "Cost behaviour sandbox",
        "Change volume by +20% and −20% and watch profit move by far more, because fixed costs stay put.", [
        { key: "price", label: "Price per unit", value: 1000, unit: "₹" },
        { key: "variableCost", label: "Variable cost per unit", value: 600, unit: "₹" },
        { key: "units", label: "Units sold", value: 1000000 },
        { key: "fixedCosts", label: "Fixed costs", value: 250000000, unit: "₹" },
        { key: "volumeChange", label: "Volume change", value: 20, unit: "%" },
      ]),
      mcq("Growing every cost line at the revenue growth rate assumes:",
        ["Costs are all fixed", "The business has no operating leverage", "Margins will expand", "Inflation is zero"], 1,
        [W, "Correct. If all costs scale with revenue, the margin never changes — which removes the main effect a growth forecast is supposed to capture.", W, W]),
    ]);

  L("c-headcount-model", "Headcount model",
    "For most service businesses, people are the cost base — so forecast people, not a salary line.",
    [
      h2("What is this?"),
      p("A headcount model forecasts staff numbers by role, multiplies by cost per head, and produces the employee cost line. It replaces the lazy approach of growing 'salaries' by a percentage."),
      h2("Why does it matter?"),
      p("In consultancies, software firms, hospitals and banks, people are 50-70% of costs. Getting that line right matters more than everything else combined, and it can only be right if you model hires and salary inflation separately."),
      p("It also makes capacity explicit. If each engineer supports ₹40 lakh of revenue, then ₹40 crore of revenue needs 100 engineers — and if the plan hires 60, the revenue forecast is not deliverable."),
      h2("How does it work?"),
      list([
        "Split headcount by role: delivery, sales, support, management.",
        "Forecast hires from the revenue plan, using a productivity ratio (revenue per head, or clients per manager).",
        "Apply cost per head, grown by salary inflation, plus benefits and payroll taxes.",
        "Time the hires. Someone joining in month 9 costs a quarter of their annual salary this year.",
      ]),
      fig("Real-Life Case Study: an IT services firm",
        ["Revenue per delivery engineer has been stable at ₹32 lakh."],
        [["FY26 revenue target", "₹96 crore"], ["Engineers required", "300"], ["Engineers today", "255"], ["Hires needed", "45"], ["Average cost per engineer", "₹11 lakh"], ["Full-year cost of new hires", "₹4.95 crore"], ["Cost if hired evenly through the year", "≈₹2.5 crore"]],
        ["The revenue target requires 45 hires; the cost depends heavily on when they arrive.",
         "Modelling them as joining on day one overstates cost by ₹2.45 crore. Modelling them as joining on the last day understates the revenue they were hired to deliver. Timing is not a detail here."]),
      h2("Key terms"),
      def("Revenue per head", "A productivity ratio linking headcount to the revenue it can support."),
      def("Fully loaded cost", "Salary plus benefits, payroll taxes and other per-employee costs."),
      def("Ramp", "The period before a new hire reaches full productivity."),
      h2("Practice"),
      practice([
        { q: "A firm needs 40 hires at a fully loaded ₹9 lakh each, joining evenly through the year. Estimate this year's cost and next year's.", a: "Evenly through the year averages about half a year each: 40 × 9 × 0.5 = ₹1.8 crore this year. Next year they are all present for the full year: 40 × 9 = ₹3.6 crore, before any salary inflation." },
        { q: "Revenue per head is ₹32 lakh and the plan targets 40% revenue growth with 10% headcount growth. What is being assumed?", a: "That revenue per head rises from ₹32 lakh to about ₹41 lakh — a 28% productivity jump. That may be possible with automation or price rises, but it is a large claim that the model is making silently, and it should be stated and defended." },
      ]),
      h2("Connection"),
      p("Headcount cost feeds the cost build and therefore EBITDA; the productivity ratio ties it back to the revenue build."),
      mcq("A hire joining nine months into the year costs approximately:",
        ["A full year's salary", "One quarter of the annual salary", "Nothing this year", "Double, because of recruitment"], 1,
        [W, "Correct. Three months of a twelve-month salary is a quarter of the annual cost — which is why hire timing must be modelled, not averaged.", W, W]),
    ]);

  L("c-working-capital-model", "Working capital model",
    "Forecast working capital in days, then convert to rupees — never guess the balance directly.",
    [
      h2("What is this?"),
      p("A working capital schedule forecasts inventory, receivables and payables by assuming a number of days for each, then converting those days into balances using forecast revenue and cost of goods sold."),
      h2("Why does it matter?"),
      p("Days are stable and comparable; balances are not. A ₹120 crore receivable balance means nothing on its own, but 60 days of sales means something you can compare with last year and with competitors — and it scales automatically as revenue grows."),
      p("This schedule is also where the growth-consumes-cash effect enters the model. Get it wrong and a forecast will show profit turning into cash that the business would never actually see."),
      h2("How does it work?"),
      formula("Days to balances", [
        "<b>Receivables = DSO ÷ 365 × Revenue</b>",
        "<b>Inventory = DIO ÷ 365 × COGS</b>",
        "<b>Payables = DPO ÷ 365 × COGS</b>",
        "<b>Cash effect = −(closing working capital − opening working capital)</b>",
      ]),
      fig("Real-Life Case Study: growth eating the profit",
        ["Revenue grows from ₹400 crore to ₹520 crore. Days are held at historical levels; COGS is 60% of revenue."],
        [["DSO 65 days — receivables", "₹71.2 → ₹92.6 crore"], ["DIO 90 days — inventory", "₹59.2 → ₹76.9 crore"], ["DPO 55 days — payables", "₹36.2 → ₹47.0 crore"], ["Working capital", "₹94.2 → ₹122.5 crore"], ["Increase (cash consumed)", "₹28.3 crore"], ["Forecast net profit", "₹31 crore"]],
        ["Days did not deteriorate at all — the company simply grew, and growth locked up ₹28.3 crore.",
         "Almost the entire forecast profit is consumed before a rupee reaches the bank. A model without this schedule would have shown ₹31 crore of cash that does not exist."]),
      h2("Key terms"),
      def("DSO / DIO / DPO", "Days sales outstanding, days inventory outstanding, days payable outstanding."),
      def("Working capital investment", "The cash consumed by the increase in working capital as a business grows."),
      h2("Practice"),
      practice([
        { q: "Revenue ₹730 crore, DSO 50 days. Compute receivables. Then compute the balance if DSO slips to 62.", a: "Receivables = 50 ÷ 365 × 730 = ₹100 crore. At 62 days: 62 ÷ 365 × 730 = ₹124 crore — a further ₹24 crore of cash consumed with no change in sales." },
        { q: "Your model holds days flat while revenue grows 30%. Does working capital consume cash, and why?", a: "Yes. Holding days flat means balances grow in proportion to revenue, so working capital rises about 30% and the increase is a cash outflow. Flat days is not a neutral assumption — it is an assumption that growth consumes cash proportionally." },
      ]),
      h2("Connection"),
      p("This schedule produces the working capital line of the cash flow statement, and the receivables, inventory and payables lines of the balance sheet."),
      sandbox("receivables-cash", "Collection days sandbox",
        "Move DSO and read the cash consumed or released — the same arithmetic the schedule performs each period.", [
        { key: "revenue", label: "Forecast revenue", value: 5200000000, unit: "₹" },
        { key: "dsoNow", label: "Current DSO", value: 65, unit: "days" },
        { key: "dsoNew", label: "Forecast DSO", value: 65, unit: "days" },
      ]),
      mcq("Forecasting working capital in days rather than rupees is better because days:",
        ["Are easier to type", "Are comparable over time and scale automatically with revenue", "Never change", "Avoid the need for a cash flow statement"], 1,
        [W, "Correct. Days are a stable, benchmarkable behaviour; balances are just their consequence at a given revenue level.", W, W]),
    ]);

  L("c-capex-model", "Capex model",
    "Split capital spending into keeping the lights on and building something new.",
    [
      h2("What is this?"),
      p("A capex schedule forecasts cash spent on long-lived assets, usually split into <strong>maintenance capex</strong> — what is needed to keep current capacity running — and <strong>growth capex</strong>, which adds new capacity."),
      h2("Why does it matter?"),
      p("The two behave completely differently. Maintenance capex is roughly permanent and roughly equal to depreciation; growth capex is a choice, tied to specific expansion plans, and can be stopped."),
      p("It also matters for valuation: free cash flow is operating cash flow minus capex, so a model that gets capex wrong gets the answer wrong regardless of how good the profit forecast is."),
      h2("How does it work?"),
      list([
        "Forecast maintenance capex as a percentage of revenue, or anchored to depreciation.",
        "Forecast growth capex from the actual expansion plan — six stores, one new line — not as a percentage.",
        "Feed capex into the fixed asset roll-forward, which then drives depreciation.",
        "Check the implied capacity: if revenue grows 40% with no growth capex, ask where the output comes from.",
      ]),
      formula("Fixed asset roll-forward", [
        "<b>Closing PP&amp;E = Opening PP&amp;E + Capex − Depreciation</b>",
        "<b>Free cash flow = Operating cash flow − Capex</b>",
      ]),
      fig("Real-Life Case Study: two capex plans",
        ["A manufacturer with ₹300 crore of PP&E and ₹36 crore of annual depreciation."],
        [["Plan A — maintenance only", "₹36 crore"], ["Plan A — closing PP&E", "₹300 crore"], ["Plan A — free cash flow", "₹64 crore"],
         ["Plan B — maintenance + new line", "₹96 crore"], ["Plan B — closing PP&E", "₹360 crore"], ["Plan B — free cash flow", "₹4 crore"]],
        ["Plan A holds capacity steady and produces cash. Plan B consumes almost all the cash to build capacity that produces nothing this year.",
         "Neither is right or wrong on its own. Plan B is right only if the new line's future returns beat the cost of the capital used — which is a ROIC question, not a capex question."]),
      h2("Key terms"),
      def("Maintenance capex", "Spending needed to sustain existing capacity. Roughly tracks depreciation."),
      def("Growth capex", "Spending that adds capacity. Discretionary and tied to a specific plan."),
      def("Roll-forward", "Opening balance + additions − reductions = closing balance."),
      h2("Practice"),
      practice([
        { q: "Opening PP&E ₹500 crore, capex ₹80 crore, depreciation ₹95 crore. Compute closing PP&E and say what it implies.", a: "Closing = 500 + 80 − 95 = ₹485 crore. Spending is below depreciation, so the asset base is shrinking — the company is consuming capacity. Fine briefly, damaging if it continues." },
        { q: "A model forecasts 45% revenue growth with capex held at maintenance level. What is wrong?", a: "The capacity to produce 45% more output has to come from somewhere. Either growth capex is missing, or the business genuinely has spare capacity — which should be stated and evidenced, since it materially affects free cash flow and the valuation." },
      ]),
      h2("Connection"),
      p("Capex feeds the depreciation schedule below it and the free cash flow used in valuation at Level 5."),
      sandbox("ppe-rollforward", "Capex sandbox",
        "Set capex below depreciation and watch the asset base shrink; raise it and see the capacity being built.", [
        { key: "opening", label: "Opening PP&E", value: 3000000000, unit: "₹" },
        { key: "capex", label: "Capital expenditure", value: 360000000, unit: "₹" },
        { key: "depreciationCharge", label: "Depreciation", value: 360000000, unit: "₹" },
      ]),
      mcq("Maintenance capex is best anchored to:",
        ["The CEO's target", "Depreciation, or a stable percentage of revenue", "Interest costs", "Dividend policy"], 1,
        [W, "Correct. Depreciation approximates the rate at which existing assets are consumed, so replacement spending tends to track it.", W, W]),
    ]);

  L("c-depreciation-schedule", "Depreciation schedule",
    "The block that turns capital spending into an expense, one year at a time.",
    [
      h2("What is this?"),
      p("A depreciation schedule tracks the fixed asset base and computes the annual charge: opening PP&E plus capex less depreciation gives closing PP&E, and the charge itself is derived from asset cost and useful life."),
      p("In a forecast, each year's new capex starts its own depreciation stream, so the total charge is the sum of depreciation on existing assets plus depreciation on everything bought since."),
      h2("Why does it matter?"),
      p("Depreciation sits in three places at once: it reduces profit on the income statement, it reduces the asset on the balance sheet, and it is added back on the cash flow statement because no cash moved. Getting it wrong breaks all three."),
      h2("How does it work?"),
      list([
        "Start with existing PP&E and its remaining depreciation.",
        "Add each year's capex as a new layer, depreciated over its own useful life.",
        "Sum the layers for the total annual charge.",
        "Roll the balance forward: opening + capex − depreciation = closing.",
      ]),
      fig("Real-Life Case Study: layering new capex",
        ["Existing assets carry ₹40 crore of annual depreciation. New capex is depreciated straight-line over 10 years."],
        [["FY26 capex", "₹60 crore"], ["FY26 depreciation on new capex", "₹6 crore"], ["FY26 total charge", "₹46 crore"],
         ["FY27 capex", "₹70 crore"], ["FY27 depreciation on new capex", "₹7 crore"], ["FY27 total charge", "₹53 crore"]],
        ["Each year's spending adds a permanent layer, so the total charge climbs steadily as the company invests.",
         "A model that holds depreciation flat while capex grows will overstate profit every year, and the error compounds."]),
      h2("Key terms"),
      def("Useful life", "The number of years over which an asset's cost is spread."),
      def("Layering", "Adding each year's capex as a separate depreciation stream."),
      def("Net book value", "Original cost less accumulated depreciation."),
      h2("Practice"),
      practice([
        { q: "Existing depreciation is ₹25 crore. FY26 capex of ₹40 crore has a 8-year life. Compute the FY26 charge and closing PP&E if opening was ₹200 crore.", a: "New layer = 40 ÷ 8 = ₹5 crore. Total charge = ₹30 crore. Closing PP&E = 200 + 40 − 30 = ₹210 crore." },
        { q: "Why does holding depreciation flat while capex grows overstate profit?", a: "Every rupee of capex creates a future expense. Freezing the charge omits the cost of the assets being bought, so profit is overstated by the missing depreciation — and the error grows each year as more capex is added." },
      ]),
      h2("Connection"),
      p("This schedule links the capex model to EBIT on the income statement and to the add-back on the cash flow statement."),
      sandbox("depreciation", "Depreciation sandbox",
        "Change the useful life and watch the annual charge — and therefore forecast profit — move.", [
        { key: "cost", label: "Asset cost", value: 600000000, unit: "₹" },
        { key: "residual", label: "Residual value", value: 0, unit: "₹" },
        { key: "usefulLife", label: "Useful life (years)", value: 10 },
        { key: "yearsElapsed", label: "Years elapsed", value: 3 },
      ]),
      mcq("Depreciation appears on the cash flow statement as an add-back because:",
        ["It is an error", "It reduced profit but no cash left the business", "It is a form of revenue", "Tax rules require it"], 1,
        [W, "Correct. The cash left when the asset was bought; the depreciation charge is an allocation, so it is added back to get from profit to cash.", W, W]),
    ]);

  L("c-debt-schedule", "Debt schedule",
    "Track every borrowing: what is owed, what is repaid, and what interest it generates.",
    [
      h2("What is this?"),
      p("A debt schedule rolls each borrowing forward — opening balance, plus drawdowns, less repayments, equals closing balance — and calculates the interest that balance generates."),
      h2("Why does it matter?"),
      p("Debt touches all three statements: interest hits the income statement, the balance is a liability, and drawdowns and repayments are financing cash flows. Without a schedule, the three will not agree."),
      p("It is also how a model answers the questions that decide whether a plan is viable: can the company meet its repayments, will it breach a covenant, does it need to raise more?"),
      h2("How does it work?"),
      formula("Debt roll-forward", [
        "<b>Closing debt = Opening debt + Drawdowns − Repayments</b>",
        "<b>Interest = Average balance × Interest rate</b>",
        "Average balance = (opening + closing) ÷ 2",
      ]),
      p("Interest is normally computed on the average balance, because the debt was not at its closing level all year. Using the opening or closing balance alone is a common and material simplification."),
      fig("Real-Life Case Study: a term loan",
        ["A ₹200 crore loan at 10%, repaid in ₹40 crore annual instalments."],
        [["FY26 opening", "₹200 crore"], ["FY26 repayment", "₹40 crore"], ["FY26 closing", "₹160 crore"], ["Average balance", "₹180 crore"], ["FY26 interest at 10%", "₹18 crore"], ["FY27 interest", "₹14 crore"]],
        ["Interest falls each year as the balance amortises — ₹18 crore, then ₹14 crore, and so on.",
         "Using the opening balance would have charged ₹20 crore in FY26, overstating interest by ₹2 crore and understating profit. Small per year, material over five."]),
      h2("Key terms"),
      def("Drawdown", "Cash received from a new or existing facility."),
      def("Amortising loan", "One repaid in instalments over its life, rather than at maturity."),
      def("Revolver", "A facility drawn and repaid flexibly, often used to plug cash shortfalls in a model."),
      h2("Practice"),
      practice([
        { q: "Opening debt ₹300 crore, ₹50 crore drawn, ₹80 crore repaid, rate 9%. Compute closing debt and interest on the average balance.", a: "Closing = 300 + 50 − 80 = ₹270 crore. Average = (300 + 270) ÷ 2 = ₹285 crore. Interest = 285 × 9% = ₹25.65 crore." },
        { q: "Why is principal repayment absent from the income statement but present in the debt schedule?", a: "Repayment settles a liability rather than consuming a resource, so it is not an expense. It reduces the debt balance and appears as a financing cash outflow — which is exactly why the schedule is needed to keep the three statements consistent." },
      ]),
      h2("Connection"),
      p("The debt schedule feeds the interest schedule next, the liability on the balance sheet, and the financing section of the cash flow statement."),
      sandbox("leverage-returns", "Debt sandbox",
        "Reduce the debt balance and watch the interest burden and owner return change together.", [
        { key: "operatingProfit", label: "Operating profit", value: 600000000, unit: "₹" },
        { key: "debt", label: "Average debt balance", value: 1800000000, unit: "₹" },
        { key: "interestRate", label: "Interest rate", value: 10, unit: "%" },
        { key: "equity", label: "Equity", value: 2000000000, unit: "₹" },
      ]),
      mcq("Interest in a debt schedule is normally computed on:",
        ["The opening balance", "The average of opening and closing balances", "The closing balance only", "The original loan amount forever"], 1,
        [W, "Correct. The balance changed during the year, so the average approximates the amount actually outstanding across the period.", W, W]),
    ]);

  L("c-interest-schedule", "Interest schedule",
    "Interest paid on debt, interest earned on cash — and the loop this creates.",
    [
      h2("What is this?"),
      p("The interest schedule computes interest expense from the debt balances and interest income from cash balances, producing the net finance cost that appears on the income statement."),
      h2("Why does it matter?"),
      p("It is small in rupees and large in consequence, because it creates the model's most famous structural problem: interest depends on debt, debt depends on the cash shortfall, the shortfall depends on profit, and profit depends on interest. The model refers back to itself."),
      h2("How does it work?"),
      list([
        "Interest expense = average debt balance × the rate on that facility.",
        "Interest income = average cash balance × the deposit rate.",
        "Net finance cost = expense − income, taken to the income statement.",
        "Where several facilities exist at different rates, compute each separately and total them.",
      ]),
      fig("Real-Life Case Study: net finance cost",
        ["A company carries term debt and holds surplus cash."],
        [["Average term debt", "₹400 crore"], ["Rate", "9.5%"], ["Interest expense", "₹38 crore"],
         ["Average cash", "₹90 crore"], ["Deposit rate", "5%"], ["Interest income", "₹4.5 crore"], ["Net finance cost", "₹33.5 crore"]],
        ["The income statement shows ₹33.5 crore, not ₹38 crore — netting the two matters.",
         "It also shows why holding cash while carrying debt is expensive: the company pays 9.5% and earns 5%, losing 4.5 points on every rupee held both ways."]),
      h2("Key terms"),
      def("Net finance cost", "Interest expense less interest income."),
      def("Circularity", "The loop created when interest affects profit, which affects cash, which affects debt, which affects interest."),
      h2("Practice"),
      practice([
        { q: "Average debt ₹250 crore at 11%; average cash ₹60 crore at 4%. Compute net finance cost.", a: "Expense = 250 × 11% = ₹27.5 crore. Income = 60 × 4% = ₹2.4 crore. Net = ₹25.1 crore." },
        { q: "A company holds ₹100 crore of cash while carrying ₹100 crore of debt at 10%, earning 4% on the cash. What does this cost annually, and why might it still be sensible?", a: "It costs 6 points on ₹100 crore = ₹6 crore a year. It can still be sensible: the cash may be needed for a known payment, a seasonal working capital swing, or as insurance against losing access to credit. Liquidity has a price, and sometimes it is worth paying." },
      ]),
      h2("Connection"),
      p("This schedule is the direct cause of circularity, which the next lessons in this module address."),
      mcq("Net finance cost is:",
        ["Interest expense only", "Interest expense less interest income", "Debt divided by EBITDA", "Principal plus interest"], 1,
        [W, "Correct. The income statement shows the net of what the company pays on borrowings and earns on cash.", W, W]),
    ]);

  L("c-tax-schedule", "Tax schedule",
    "Compute tax from taxable profit, not by applying a rate to accounting profit.",
    [
      h2("What is this?"),
      p("A tax schedule works from profit before tax to the tax charge, applying the effective rate and, where relevant, the brought-forward losses that shelter profit from tax."),
      h2("Why does it matter?"),
      p("Tax is often the second-largest cost after direct costs, and applying the statutory rate to accounting profit is usually wrong. Companies with past losses may pay almost nothing for years and then jump to the full rate, and a model that misses this overstates near-term profit or understates the later fall."),
      h2("How does it work?"),
      list([
        "Start from forecast profit before tax.",
        "Apply available brought-forward losses, within whatever limits the law allows, to reduce taxable profit.",
        "Apply the effective rate to what remains.",
        "Track the remaining loss balance forward — it is an asset that gets consumed.",
      ]),
      p("Tax rules are set by legislation and change; treat any specific rate or loss-carry rule as current fact to be verified, not a permanent feature of the model."),
      fig("Real-Life Case Study: losses running out",
        ["A company with ₹60 crore of brought-forward losses and a 25% rate."],
        [["FY26 profit before tax", "₹40 crore"], ["Losses used", "₹40 crore"], ["FY26 tax", "₹0"], ["Losses remaining", "₹20 crore"],
         ["FY27 profit before tax", "₹50 crore"], ["Losses used", "₹20 crore"], ["FY27 tax on ₹30 crore", "₹7.5 crore"], ["FY28 tax on ₹55 crore", "₹13.75 crore"]],
        ["Tax goes from zero to ₹7.5 crore to ₹13.75 crore while the business simply grows normally.",
         "Net profit in FY28 is far lower relative to pre-tax profit than in FY26. A model applying a flat 25% throughout would have misstated all three years."]),
      h2("Key terms"),
      def("Effective tax rate", "Tax expense ÷ profit before tax — what is actually borne."),
      def("Carried-forward loss", "A past loss set against future taxable profit, within statutory limits."),
      h2("Practice"),
      practice([
        { q: "Profit before tax ₹80 crore, brought-forward losses ₹30 crore, rate 25%. Compute tax and the effective rate.", a: "Taxable profit = 80 − 30 = ₹50 crore. Tax = ₹12.5 crore. Effective rate = 12.5 ÷ 80 = 15.6%." },
        { q: "Why might net profit fall next year even though pre-tax profit rises?", a: "If brought-forward losses are exhausted, the effective rate jumps towards the statutory rate. A larger pre-tax profit taxed at a much higher effective rate can produce a smaller net profit — with no operating change at all." },
      ]),
      h2("Connection"),
      p("The tax charge completes the income statement and feeds net profit into retained earnings on the balance sheet."),
      mcq("A company has large brought-forward losses. In the near term its effective tax rate will be:",
        ["Higher than statutory", "Lower than statutory, until the losses are used", "Exactly statutory", "Zero forever"], 1,
        [W, "Correct. The losses shelter taxable profit, so the rate is low until they run out — after which it rises sharply.", W, W]),
    ]);

  L("c-retained-earnings-schedule", "Retained earnings",
    "The joint that carries profit from the income statement onto the balance sheet.",
    [
      h2("What is this?"),
      p("The retained earnings schedule rolls the balance forward: opening retained earnings, plus net profit for the period, less dividends, equals closing retained earnings."),
      h2("Why does it matter?"),
      p("This is the single link that makes an integrated model balance. Net profit is calculated on the income statement and must land inside equity, or assets will no longer equal liabilities plus equity."),
      p("If your balance sheet does not balance, this schedule is the first place to look — usually the profit being carried across is the wrong figure, or dividends have been double-counted."),
      h2("How does it work?"),
      formula("Retained earnings roll-forward", [
        "<b>Closing = Opening + Net profit − Dividends</b>",
        "Net profit comes from the income statement",
        "Dividends are a distribution, not an expense",
      ]),
      fig("Real-Life Case Study: three forecast years",
        ["Opening retained earnings of ₹240 crore, with a 30% payout policy."],
        [["FY26 net profit", "₹60 crore"], ["FY26 dividends", "₹18 crore"], ["FY26 closing", "₹282 crore"],
         ["FY27 net profit", "₹72 crore"], ["FY27 dividends", "₹21.6 crore"], ["FY27 closing", "₹332.4 crore"]],
        ["Equity grows by the profit the company keeps — ₹42 crore, then ₹50.4 crore.",
         "That retained cash is what funds the capex and working capital in the other schedules. Raise the payout to 80% and the model will need far more debt to fund the same plan."]),
      h2("Key terms"),
      def("Payout ratio", "Dividends as a percentage of net profit."),
      def("Roll-forward", "Opening + additions − reductions = closing, the structure of every schedule."),
      h2("Practice"),
      practice([
        { q: "Opening retained earnings ₹150 crore, net profit ₹40 crore, payout 35%. Compute dividends and closing retained earnings.", a: "Dividends = 40 × 35% = ₹14 crore. Closing = 150 + 40 − 14 = ₹176 crore." },
        { q: "Your balance sheet is out by exactly the dividend amount. What is the likely error?", a: "Dividends have probably been deducted twice — once in the retained earnings roll-forward and again as a cash outflow that was also netted from profit — or they were deducted in the schedule but not reflected in financing cash flow. Check that each appears exactly once." },
      ]),
      h2("Connection"),
      p("This schedule is the reason the three-statement model closes. It is also where dividend policy from Level 2 changes how much external funding the plan needs."),
      sandbox("retained", "Retention sandbox",
        "Raise the dividend above the year's profit and watch the balance fall — retained earnings is a running total, not a cash pile.", [
        { key: "opening", label: "Opening retained earnings", value: 2400000000, unit: "₹" },
        { key: "netProfit", label: "Net profit", value: 600000000, unit: "₹" },
        { key: "dividends", label: "Dividends", value: 180000000, unit: "₹" },
      ]),
      mcq("If a forecast balance sheet does not balance, the first schedule to check is:",
        ["The capex schedule", "Retained earnings — the link carrying profit into equity", "The revenue build", "The headcount model"], 1,
        [W, "Correct. Net profit must land in equity for the balance sheet identity to hold, so an error here breaks the balance directly.", W, W]),
    ]);

  /* ============ INTEGRATED MODELING ============ */

  L("c-scenario-analysis", "Scenario analysis",
    "Build three coherent versions of the future instead of one confident guess.",
    [
      h2("What is this?"),
      p("Scenario analysis runs the model under several internally consistent sets of assumptions — typically base, upside and downside — and compares the outcomes."),
      p("The key word is <strong>consistent</strong>. A recession scenario does not just cut revenue: it also compresses margins, stretches collections and probably raises the interest rate. Scenarios describe whole worlds, not single-variable tweaks."),
      h2("Why does it matter?"),
      p("A single forecast is almost certainly wrong. Three scenarios tell you the range of outcomes and, more usefully, whether the company survives the bad one — which is the question that actually matters for a lender or an investor."),
      h2("How does it work?"),
      list([
        "Define each scenario as a full set of assumptions, not one changed cell.",
        "Store them in the inputs area with a switch that selects which set is live.",
        "Run the model on each and record the outputs that matter: profit, cash, leverage, covenant headroom.",
        "Ask the survival question on the downside, not just the profit question.",
      ]),
      fig("Real-Life Case Study: three coherent worlds",
        ["A manufacturer with a covenant capping net debt / EBITDA at 3.5x."],
        [["Base — revenue growth", "8%"], ["Base — EBITDA margin", "17%"], ["Base — leverage", "2.4x"],
         ["Downside — revenue growth", "−6%"], ["Downside — EBITDA margin", "13%"], ["Downside — leverage", "4.1x"],
         ["Covenant limit", "3.5x"]],
        ["The base case is comfortable. The downside breaches the covenant, which can make the debt immediately repayable.",
         "That finding — the company does not survive its own downside case without renegotiating — is worth more than any point estimate the base case produces."]),
      h2("Key terms"),
      def("Base case", "The most likely set of assumptions."),
      def("Downside case", "A coherent adverse world used to test survival, not just profitability."),
      def("Scenario switch", "A single input cell selecting which assumption set the model uses."),
      h2("Practice"),
      practice([
        { q: "A colleague builds a downside case by cutting revenue 10% and changing nothing else. What is missing?", a: "Coherence. In a genuine downturn margins usually compress too, customers pay later, inventory builds, and credit may cost more. Changing revenue alone understates the damage, often by a wide margin, because the effects compound." },
        { q: "Why is the downside case usually more decision-relevant than the upside?", a: "The upside affects how much you make; the downside affects whether you survive. Covenant breaches, funding gaps and insolvency all live in the downside, and those outcomes are not symmetric with the gains." },
      ]),
      h2("Connection"),
      p("Scenarios test the assumptions set earlier in this level, and feed the valuation range built in Level 5."),
      mcq("A well-built downside scenario changes:",
        ["Revenue only", "A coherent set of assumptions that would move together in reality", "The tax rate only", "Nothing — it uses base assumptions"], 1,
        [W, "Correct. Revenue, margin, working capital and financing costs deteriorate together in a real downturn, and the compounding is the point.", W, W]),
    ]);

  L("c-sensitivity-analysis", "Sensitivity analysis",
    "Find which one or two assumptions actually decide the answer.",
    [
      h2("What is this?"),
      p("Sensitivity analysis varies one or two assumptions at a time across a range and tabulates the effect on an output — usually value per share, IRR or leverage. The classic form is a two-way table with growth down one axis and margin or discount rate across the other."),
      h2("Why does it matter?"),
      p("Models have dozens of assumptions, but usually two or three carry almost all of the answer. Sensitivity finds them, so you can spend your research time on the things that matter and stop arguing about the ones that do not."),
      p("It also reframes the output honestly. Instead of 'the value is ₹82', you get 'the value is ₹59 to ₹104 depending on the multiple, and the multiple is the assumption to defend'."),
      h2("How does it work?"),
      list([
        "Pick the output that drives the decision.",
        "Pick two assumptions you suspect matter most.",
        "Vary each across a plausible range — not a wild one — and tabulate.",
        "Read the spread: a wide spread means the assumption is critical, a narrow one means it is not worth arguing about.",
      ]),
      fig("Real-Life Case Study: value per share sensitivity",
        ["EBITDA multiple across the top, EBITDA margin down the side."],
        [["Margin 15%, multiple 7x", "₹48"], ["Margin 15%, multiple 9x", "₹66"], ["Margin 17%, multiple 7x", "₹59"],
         ["Margin 17%, multiple 9x", "₹82"], ["Margin 19%, multiple 9x", "₹98"], ["Market price", "₹75"]],
        ["The value ranges from ₹48 to ₹98 — the market price of ₹75 sits comfortably inside it.",
         "The honest conclusion is that this valuation cannot distinguish cheap from expensive without settling the multiple and the margin first. That is a far more useful finding than a single confident number."]),
      h2("Key terms"),
      def("Two-way table", "A grid varying two assumptions simultaneously against one output."),
      def("Swing factor", "The assumption producing the largest change in the output."),
      h2("Practice"),
      practice([
        { q: "Varying the discount rate by ±1 point moves the value ±22%; varying the tax rate by ±2 points moves it ±3%. Where should your research go?", a: "Into the discount rate. It is the swing factor by a wide margin, so time spent refining the tax assumption cannot change the conclusion, while a small error in the discount rate can reverse it." },
        { q: "How is sensitivity analysis different from scenario analysis?", a: "Sensitivity varies one or two assumptions mechanically across a range to find what the answer depends on. Scenario analysis changes a coherent set of assumptions together to describe a plausible world. One is diagnostic; the other is narrative." },
      ]),
      h2("Connection"),
      p("Every DCF in Level 5 should be presented with a sensitivity table, because its answer depends heavily on two assumptions you cannot observe."),
      mcq("A sensitivity table shows value ranging from ₹48 to ₹98 around a ₹75 market price. The right conclusion is:",
        ["The stock is clearly cheap", "The analysis cannot distinguish cheap from expensive until the key assumptions are settled", "The model is broken", "The stock is clearly expensive"], 1,
        [W, "Correct. The market price sits inside the range, so the decision rests entirely on which assumptions you can defend.", W, W]),
    ]);

  L("c-circularity", "Circularity",
    "The model's built-in loop: interest depends on debt, and debt depends on interest.",
    [
      h2("What is this?"),
      p("Circularity is a genuine logical loop in an integrated model. Interest expense reduces net profit; net profit affects cash; the cash shortfall determines how much must be borrowed; the borrowing determines interest. The model needs its own answer to compute its answer."),
      h2("Why does it matter?"),
      p("It is not an error — it reflects reality. But spreadsheets cannot resolve a loop directly, so it must be handled deliberately. Handled badly, the model either refuses to calculate or silently produces a stale number that no longer reflects the inputs."),
      h2("How does it work?"),
      p("Three standard approaches, in order of how most practitioners rank them:"),
      list([
        "<strong>Break the loop.</strong> Compute interest on the <em>opening</em> debt balance rather than the average. Slightly less precise, completely stable, and by far the safest choice in a model others will use.",
        "<strong>Iterative calculation.</strong> Let the spreadsheet loop until the numbers settle. Accurate, but the file can hold stale values and errors propagate invisibly.",
        "<strong>Circuit breaker.</strong> A switch that forces interest to zero, letting you clear a stuck model. Standard practice wherever iteration is enabled.",
      ]),
      fig("Real-Life Case Study: the loop in numbers",
        ["A model needs to borrow to cover a cash shortfall, and the borrowing itself adds interest."],
        [["Cash shortfall before interest", "₹100 crore"], ["Borrowing required", "₹100 crore"], ["Interest at 10%", "₹10 crore"],
         ["Revised shortfall", "₹110 crore"], ["Revised interest", "₹11 crore"], ["Settles at borrowing of", "≈₹111 crore"]],
        ["Each pass changes the answer by less than the last, and the sequence converges — which is what iteration does automatically.",
         "Computing interest on the opening balance instead sidesteps the loop entirely: you would borrow ₹100 crore and charge interest on the opening debt, accepting a small understatement in exchange for a model that always calculates."]),
      h2("Key terms"),
      def("Circular reference", "A formula that depends, directly or indirectly, on its own result."),
      def("Circuit breaker", "A switch that zeroes the circular term so a stuck model can be reset."),
      def("Iterative calculation", "A spreadsheet setting that resolves loops by repeated recalculation."),
      h2("Practice"),
      practice([
        { q: "Explain the loop in one sentence, then give the simplest fix.", a: "Interest reduces profit, which reduces cash, which increases the borrowing needed, which increases interest. Simplest fix: calculate interest on the opening debt balance, which removes the dependency on this period's own result." },
        { q: "Why do many practitioners prefer breaking the loop to enabling iteration?", a: "Iteration can leave stale values in cells and hides errors — a broken formula may still show a plausible number. Opening-balance interest is marginally less precise but always recalculates cleanly, which matters more in a model other people will rely on." },
      ]),
      h2("Connection"),
      p("Circularity arises from the interest schedule and is the last structural problem to solve before the three statements will tie."),
      mcq("Circularity in a financial model arises because:",
        ["Of a formula typing error", "Interest depends on debt, which depends on the cash shortfall, which depends on interest", "Spreadsheets cannot multiply", "Depreciation is non-cash"], 1,
        [W, "Correct. It is a real logical loop, not a mistake — which is why it must be handled deliberately rather than 'fixed'.", W, W]),
    ]);

  /* ============ BUILD A REAL MODEL ============ */

  L("c-revenue-forecast", "Revenue",
    "The first line of the forecast, and the one every other line depends on.",
    [
      h2("What is this?"),
      p("In the built model, revenue is the output of the revenue build: drivers forecast separately, multiplied together, laid across the forecast years."),
      h2("Why does it matter?"),
      p("Almost every other line is derived from it. Variable costs are a percentage of revenue; receivables are days of revenue; often capex is too. An error here does not stay contained — it propagates through every statement and into the valuation."),
      h2("How does it work?"),
      list([
        "Take the driver forecast — volume and price, or customers and ARPU.",
        "Compute revenue for each forecast year.",
        "Show the implied growth rate underneath, and compare it with history.",
        "Sanity-check against market size: a forecast implying 40% market share needs justification.",
      ]),
      fig("Real-Life Case Study: five forecast years",
        ["A café chain, built from stores and revenue per store."],
        [["FY25 actual", "₹48.0 crore"], ["FY26", "₹58.0 crore (+20.8%)"], ["FY27", "₹68.3 crore (+17.8%)"],
         ["FY28", "₹78.4 crore (+14.8%)"], ["FY29", "₹87.4 crore (+11.5%)"], ["FY30", "₹95.0 crore (+8.7%)"]],
        ["Growth decelerates because new stores become a smaller proportion of a larger base — the arithmetic does this on its own.",
         "A forecast holding 20% growth for five years would imply the chain more than doubles its store count every three years, which is a funding and execution claim, not a revenue assumption."]),
      h2("Practice"),
      practice([
        { q: "40 stores today, 6 new stores a year, ₹1.2 crore per store growing 5% a year. Compute FY27 revenue.", a: "FY26: 46 stores × ₹1.26 crore = ₹57.96 crore. FY27: 52 stores × ₹1.323 crore = ₹68.8 crore." },
        { q: "Why does growth naturally decelerate in a store-count model even with constant openings?", a: "Six new stores on a base of 40 is 15%; on a base of 70 it is 8.6%. The absolute addition is constant but the base grows, so the percentage falls automatically — which is usually more realistic than assuming a flat growth rate." },
      ]),
      h2("Connection"),
      p("Revenue drives the cost build, the working capital schedule and, ultimately, the free cash flow that Level 5 discounts."),
      mcq("In an integrated model, revenue matters most because:",
        ["It is the largest number", "Most other lines are derived from it, so errors propagate everywhere", "It determines the tax rate", "It has no effect on cash"], 1,
        [W, "Correct. Costs, working capital and often capex are all expressed relative to revenue, so a revenue error flows into all three statements.", W, W]),
    ]);

  L("c-gross-profit-model", "Gross Profit",
    "Revenue less direct costs, forecast by holding or trending the gross margin.",
    [
      h2("What is this?"),
      p("In the model, gross profit is revenue minus cost of goods sold, where COGS is normally forecast as a percentage of revenue taken from history and adjusted for anything you know is changing."),
      h2("Why does it matter?"),
      p("The gross margin assumption is one of the highest-leverage numbers in the whole model. A single point of margin on ₹500 crore of revenue is ₹5 crore of profit, which flows all the way to value."),
      h2("How does it work?"),
      list([
        "Compute historical gross margin for each actual year.",
        "Decide whether it holds, improves or erodes — and state why.",
        "Apply the ratio to forecast revenue to get COGS.",
        "Check the resulting gross profit against the trend before moving on.",
      ]),
      fig("Real-Life Case Study: margin assumptions compared",
        ["Historical gross margin: 41.2%, 40.5%, 39.8%. Forecast revenue FY26 is ₹58 crore."],
        [["Hold at 39.8%", "₹23.1 crore"], ["Assume recovery to 41%", "₹23.8 crore"], ["Continue the trend to 39.1%", "₹22.7 crore"], ["Spread across five years", "₹1.1 crore difference by FY30"]],
        ["The three assumptions differ by under a rupee crore in year one, and by materially more by year five.",
         "Given three years of steady erosion, 'holds flat' is already the optimistic case. Assuming recovery needs a specific reason — a price rise, a cheaper input contract, a mix shift."]),
      h2("Practice"),
      practice([
        { q: "Forecast revenue ₹120 crore at a 37% gross margin. Compute gross profit and COGS.", a: "Gross profit = 120 × 37% = ₹44.4 crore. COGS = ₹75.6 crore." },
        { q: "Gross margin has fallen 0.7 points a year for three years. What is the most defensible forecast, and what would change it?", a: "Continuing the erosion, or holding flat as a mildly optimistic case. Assuming recovery requires a specific, nameable cause — a contracted input price, a completed automation project, or a deliberate shift towards higher-margin products with evidence it is happening." },
      ]),
      h2("Connection"),
      p("Gross profit feeds EBITDA once operating costs are subtracted, and the margin assumption reappears in every sensitivity table you build."),
      mcq("COGS in a forecast is most commonly modelled as:",
        ["A fixed rupee amount", "A percentage of revenue based on history", "Equal to depreciation", "Whatever balances the model"], 1,
        [W, "Correct. Direct costs move with volume, so a ratio to revenue is the natural forecasting basis.", W, W]),
    ]);

  L("c-ebitda-model", "EBITDA",
    "Gross profit less operating costs — where the cost build's fixed and variable split pays off.",
    [
      h2("What is this?"),
      p("EBITDA in the model is gross profit minus operating expenses, with the operating costs coming from the cost build: variable lines as a ratio of revenue, fixed lines as amounts grown by inflation."),
      h2("Why does it matter?"),
      p("This is where operating leverage shows up in the forecast. If you have modelled fixed costs as fixed, EBITDA will grow faster than revenue and the margin will expand — which is usually the single most valuable feature of a growth forecast."),
      h2("How does it work?"),
      list([
        "Pull gross profit from the line above.",
        "Subtract each operating cost line, forecast according to its behaviour.",
        "Compute the EBITDA margin and compare it with history.",
        "If the margin expands, be able to say exactly which fixed cost is producing the leverage.",
      ]),
      fig("Real-Life Case Study: leverage in the forecast",
        ["Revenue grows 20.8%; overheads are fixed and rise 6% with inflation."],
        [["FY25 gross profit", "₹19.1 crore"], ["FY25 overheads", "₹13.4 crore"], ["FY25 EBITDA", "₹5.7 crore (11.9% margin)"],
         ["FY26 gross profit", "₹23.1 crore"], ["FY26 overheads", "₹14.2 crore"], ["FY26 EBITDA", "₹8.9 crore (15.3% margin)"]],
        ["EBITDA grew 56% on 20.8% revenue growth, and the margin widened 3.4 points.",
         "All of it came from overheads growing 6% instead of 20.8%. If that assumption is wrong — if the chain needs more area managers as it grows — most of the forecast profit improvement disappears."]),
      h2("Practice"),
      practice([
        { q: "Gross profit ₹40 crore, fixed overheads ₹25 crore. Revenue and gross profit both grow 15%; overheads grow 5%. Compute EBITDA growth.", a: "Now: 40 − 25 = ₹15 crore. Next: 46 − 26.25 = ₹19.75 crore. Growth = 31.7%, against 15% revenue growth." },
        { q: "Your forecast shows the EBITDA margin expanding every year for five years. What must you check?", a: "Whether the fixed costs really stay fixed at that scale. Most businesses hit step costs — more supervisors, a bigger warehouse, another system — so indefinite margin expansion usually means a step cost has been omitted." },
      ]),
      h2("Connection"),
      p("EBITDA is the base for the valuation multiple in Level 5 and for the leverage covenant tested in scenario analysis."),
      sandbox("profit-bridge", "EBITDA sandbox",
        "Hold operating costs steady and raise revenue — the margin widening is operating leverage inside the forecast.", [
        { key: "revenue", label: "Revenue", value: 580000000, unit: "₹" },
        { key: "cogs", label: "Cost of goods sold", value: 349000000, unit: "₹" },
        { key: "opex", label: "Operating costs", value: 142000000, unit: "₹" },
        { key: "interest", label: "Interest", value: 12000000, unit: "₹" },
        { key: "taxRate", label: "Tax rate", value: 25, unit: "%" },
      ]),
      mcq("A forecast EBITDA margin that expands every year for five years usually means:",
        ["Excellent management", "A step cost has probably been omitted", "Revenue is understated", "Tax is too low"], 1,
        [W, "Correct. Real businesses add supervisors, space and systems as they scale, so unbroken margin expansion is a red flag in the cost build.", W, W]),
    ]);

  L("c-ebit-model", "EBIT",
    "EBITDA less depreciation — the point where the capex you forecast starts costing you.",
    [
      h2("What is this?"),
      p("EBIT in the model is EBITDA minus the depreciation and amortisation coming from the depreciation schedule. It is the first line where the capital spending forecast affects reported profit."),
      h2("Why does it matter?"),
      p("A model can forecast aggressive expansion and show wonderful EBITDA, because EBITDA ignores the cost of the assets being bought. EBIT is where that cost lands, and it is the line that feeds interest coverage and ROIC."),
      h2("How does it work?"),
      list([
        "Take EBITDA from the line above.",
        "Subtract the total depreciation charge from the depreciation schedule — existing assets plus every capex layer.",
        "The result is EBIT, and dividing it by revenue gives the operating margin to compare with history.",
      ]),
      fig("Real-Life Case Study: capex catching up",
        ["A company invests heavily; EBITDA grows steadily but depreciation follows."],
        [["FY26 EBITDA", "₹8.9 crore"], ["FY26 depreciation", "₹2.1 crore"], ["FY26 EBIT", "₹6.8 crore"],
         ["FY29 EBITDA", "₹14.2 crore"], ["FY29 depreciation", "₹5.4 crore"], ["FY29 EBIT", "₹8.8 crore"]],
        ["EBITDA grew 60% over the period; EBIT grew only 29%, because each year's capex added a permanent depreciation layer.",
         "Judging this expansion on EBITDA alone would have overstated its success by a wide margin. EBIT tells you what the growth cost."]),
      h2("Practice"),
      practice([
        { q: "EBITDA ₹22 crore, existing depreciation ₹6 crore, new capex ₹30 crore with a 10-year life. Compute EBIT.", a: "New layer = ₹3 crore. Total depreciation = ₹9 crore. EBIT = 22 − 9 = ₹13 crore." },
        { q: "Why can a model show strong EBITDA growth and weak EBIT growth?", a: "Because capex is accumulating. Every year's investment adds a depreciation layer that reduces EBIT but not EBITDA, so a capital-hungry expansion looks far better on EBITDA than it actually is." },
      ]),
      h2("Connection"),
      p("EBIT feeds interest coverage, ROIC from Level 3, and the after-tax operating profit used in a DCF."),
      mcq("The difference between forecast EBITDA and forecast EBIT is:",
        ["Interest", "Depreciation and amortisation from the capex you modelled", "Tax", "Dividends"], 1,
        [W, "Correct. EBIT charges for the assets being consumed, which is exactly the cost EBITDA ignores.", W, W]),
    ]);

  L("c-net-income-model", "Net Income",
    "The bottom line of the forecast — after the debt schedule and the tax schedule have taken their share.",
    [
      h2("What is this?"),
      p("Net income completes the forecast income statement: EBIT less net finance cost gives profit before tax, and applying the tax schedule gives net profit."),
      h2("Why does it matter?"),
      p("Net income is the figure that flows into retained earnings and makes the balance sheet balance. It is also where financing and tax decisions — which the operating forecast ignored entirely — finally change the answer."),
      h2("How does it work?"),
      list([
        "EBIT from the line above.",
        "Less net finance cost from the interest schedule.",
        "Equals profit before tax.",
        "Less the tax charge from the tax schedule.",
        "Equals net profit, which goes to the retained earnings schedule.",
      ]),
      fig("Real-Life Case Study: completing the statement",
        ["FY26 for the café chain, with debt taken to fund the new stores."],
        [["EBIT", "₹6.8 crore"], ["Net finance cost", "₹1.2 crore"], ["Profit before tax", "₹5.6 crore"],
         ["Tax at 25%", "₹1.4 crore"], ["Net profit", "₹4.2 crore"], ["Dividends at 30%", "₹1.26 crore"], ["To retained earnings", "₹2.94 crore"]],
        ["₹6.8 crore of operating profit becomes ₹4.2 crore for the owners, and ₹2.94 crore actually stays in the business.",
         "That ₹2.94 crore is what funds next year's expansion without more borrowing — which is precisely how the income statement and the funding plan connect."]),
      h2("Practice"),
      practice([
        { q: "EBIT ₹40 crore, interest expense ₹9 crore, interest income ₹1 crore, tax rate 25%. Compute net profit.", a: "Net finance cost = ₹8 crore. Profit before tax = ₹32 crore. Tax = ₹8 crore. Net profit = ₹24 crore." },
        { q: "Two companies have identical EBIT forecasts but very different net profit forecasts. Name the two causes.", a: "Different financing — one carries more debt, so interest is larger — and different tax positions, such as brought-forward losses or different effective rates. Neither reflects any difference in operating performance." },
      ]),
      h2("Connection"),
      p("Net profit is the number the retained earnings schedule carries onto the balance sheet, closing the loop between the statements."),
      mcq("Net profit in the model flows directly into:",
        ["Revenue", "Retained earnings within equity", "Capex", "Inventory"], 1,
        [W, "Correct. That link is what allows the forecast balance sheet to balance.", W, W]),
    ]);

  L("c-cash-flow", "Cash Flow",
    "Rebuild cash from profit: add back the non-cash, subtract what the balance sheet absorbed.",
    [
      h2("What is this?"),
      p("The forecast cash flow statement converts net profit into cash. It adds back non-cash charges, adjusts for the working capital movement, subtracts capex, and adds or subtracts financing flows."),
      h2("Why does it matter?"),
      p("This is where a forecast becomes honest. The income statement can show a healthy profit while the cash flow statement shows the company running out of money, because growth consumed working capital and capex took the rest."),
      p("It also produces the closing cash balance that the balance sheet needs — so if the two disagree, the model has an error."),
      h2("How does it work?"),
      formula("From profit to cash", [
        "<b>CFO = Net profit + Depreciation − Increase in working capital</b>",
        "<b>CFI = −Capex</b>",
        "<b>CFF = Drawdowns − Repayments − Dividends + Equity raised</b>",
        "<b>Closing cash = Opening cash + CFO + CFI + CFF</b>",
      ]),
      fig("Real-Life Case Study: the honest year",
        ["The café chain's FY26, funding six new stores."],
        [["Net profit", "₹4.2 crore"], ["Add depreciation", "₹2.1 crore"], ["Less working capital increase", "−₹0.9 crore"],
         ["Cash from operations", "₹5.4 crore"], ["Less capex (6 stores)", "−₹7.2 crore"], ["Free cash flow", "−₹1.8 crore"],
         ["Debt drawn", "₹4.0 crore"], ["Dividends paid", "−₹1.26 crore"], ["Net change in cash", "₹0.94 crore"]],
        ["The business is profitable and still consumed ₹1.8 crore before financing — the expansion cost more than operations produced.",
         "It works only because ₹4 crore was borrowed. That is a perfectly normal growth plan, but the model has now made the dependence on funding explicit rather than hiding it inside a profit number."]),
      h2("Practice"),
      practice([
        { q: "Net profit ₹30 crore, depreciation ₹12 crore, working capital up ₹18 crore, capex ₹20 crore. Compute CFO and free cash flow.", a: "CFO = 30 + 12 − 18 = ₹24 crore. Free cash flow = 24 − 20 = ₹4 crore. Reported profit of ₹30 crore produced ₹4 crore of genuinely free cash." },
        { q: "Your forecast shows rising profit and falling cash every year. Is the model wrong?", a: "Not necessarily. Rapid growth consumes working capital and capex ahead of collection, so profit can rise while cash falls. It is only an error if the working capital or capex schedules are wrong — otherwise it is a real finding about how the plan must be funded." },
      ]),
      h2("Connection"),
      p("The free cash flow this statement produces is exactly what a DCF discounts in Level 5."),
      sandbox("profit-to-cash", "Profit-to-cash sandbox",
        "Raise the working capital increase and watch cash separate from profit — the core dynamic of the forecast.", [
        { key: "profit", label: "Net profit", value: 42000000, unit: "₹" },
        { key: "receivablesIncrease", label: "Increase in receivables", value: 6000000, unit: "₹" },
        { key: "inventoryIncrease", label: "Increase in inventory", value: 4000000, unit: "₹" },
        { key: "payablesIncrease", label: "Increase in payables", value: 1000000, unit: "₹" },
      ]),
      mcq("Depreciation is added back in the cash flow statement because:",
        ["It is an error", "It reduced profit but no cash left in that period", "It increases revenue", "It is a financing flow"], 1,
        [W, "Correct. The cash left when the asset was purchased; the charge is an allocation, so it must be reversed to get to cash.", W, W]),
    ]);

  L("c-balance-sheet", "Balance Sheet",
    "The forecast balance sheet is where every schedule meets — and where errors announce themselves.",
    [
      h2("What is this?"),
      p("The forecast balance sheet assembles the closing balances from every schedule: cash from the cash flow statement, working capital from its schedule, PP&E from the capex roll-forward, debt from the debt schedule, and equity from retained earnings."),
      h2("Why does it matter?"),
      p("It is the model's built-in error detector. Assets must equal liabilities plus equity, and that identity only holds if every schedule is internally correct and correctly connected. If it balances, the model is probably right. If it does not, something specific is wrong."),
      h2("How does it work?"),
      list([
        "Pull each closing balance from its own schedule — never type one in.",
        "Compute total assets, and total liabilities plus equity.",
        "Add a check row: the difference must be zero in every forecast year.",
        "When it is not, work through the usual suspects: retained earnings, the cash tie, capex versus depreciation, dividends counted twice.",
      ]),
      fig("Real-Life Case Study: the check row",
        ["FY26 for the café chain, assembled from the schedules."],
        [["Cash (from cash flow)", "₹1.9 crore"], ["Working capital assets", "₹4.6 crore"], ["PP&E (roll-forward)", "₹19.1 crore"],
         ["Total assets", "₹25.6 crore"], ["Payables", "₹2.1 crore"], ["Debt (debt schedule)", "₹8.5 crore"],
         ["Equity (retained earnings)", "₹15.0 crore"], ["Check (assets − liabilities − equity)", "₹0.0"]],
        ["The zero is the whole point. It means the profit landed in equity, the cash tied to the cash flow statement, and the asset roll-forward was consistent with depreciation.",
         "A model that balances in every forecast year is not guaranteed correct, but a model that does not balance is guaranteed wrong."]),
      h2("Practice"),
      practice([
        { q: "Your forecast balance sheet is out by exactly the FY26 depreciation charge. Where would you look first?", a: "The PP&E roll-forward or the cash flow add-back. Either depreciation was subtracted from PP&E but not added back in the cash flow statement, or it was added back but not deducted from the asset — both produce a gap of exactly that amount." },
        { q: "Why is a check row better than eyeballing the two totals?", a: "A formula computes the difference in every year automatically and shows a non-zero the instant it appears. Eyeballing large numbers hides small differences, and small differences usually indicate real structural errors." },
      ]),
      h2("Connection"),
      p("A balancing forecast balance sheet is the precondition for everything in Level 5: you cannot value cash flows produced by a model that does not tie."),
      sandbox("balance", "Balance check sandbox",
        "Change assets or liabilities and watch equity absorb the difference — the identity that must hold in every forecast year.", [
        { key: "assets", label: "Total assets", value: 256000000, unit: "₹" },
        { key: "liabilities", label: "Total liabilities", value: 106000000, unit: "₹" },
      ]),
      mcq("A forecast balance sheet that does not balance means:",
        ["The company is insolvent", "There is a structural error in the model", "Revenue was too high", "Tax was miscalculated"], 1,
        [W, "Correct. The identity holds by construction, so a non-zero check row is always a modelling error — most often in retained earnings or the cash tie.", W, W]),
    ]);
})();
