/* Level 9 — Markets. 17 lessons.
   Same schema and loop as Levels 4-8. Instruments and mechanics, taught with
   arithmetic a beginner can follow. Educational only: nothing here recommends
   any security or strategy. */
(function () {
  "use strict";
  var LS = (window.LS = window.LS || {});
  LS.lessons = LS.lessons || {};

  function h2(t) { return { t: "h2", text: t }; }
  function p(h) { return { t: "p", h: h }; }
  function list(i) { return { t: "list", items: i }; }
  function def(term, h) { return { t: "def", term: term, h: h }; }
  function note(i) { return { t: "note", h: "<ul>" + i.map(function (x) { return "<li>" + x + "</li>"; }).join("") + "</ul>" }; }
  function practice(i) { return { t: "practice", items: i }; }
  function sandbox(kind, title, prompt, fields) { return { t: "sandbox", kind: kind, title: title, prompt: prompt, fields: fields }; }
  function formula(title, lines) { return { t: "formula", title: title, lines: lines }; }
  function mcq(q, o, c, w) { return { t: "mcq", q: q, opts: o, correct: c, why: w }; }
  function fig(title, intro, rows, meaning) {
    var h = '<p class="case-title"><strong>' + title + "</strong></p>";
    intro.forEach(function (x) { h += "<p>" + x + "</p>"; });
    h += '<div class="case-figures">';
    rows.forEach(function (r) { h += '<div class="case-row"><span class="case-label">' + r[0] + '</span><span class="case-value">' + r[1] + "</span></div>"; });
    h += '</div><p class="case-meaning"><strong>What it means.</strong></p>';
    meaning.forEach(function (x) { h += "<p>" + x + "</p>"; });
    return { t: "example", h: h };
  }
  function L(id, title, lede, body) {
    LS.lessons[id] = { id: id, title: title, short: title, desc: lede, lede: lede, minutes: 7, body: body };
  }
  var W = "Not quite — re-read the explanation above.";

  /* ============ EQUITIES ============ */

  L("c-stocks", "Stocks",
    "A share is a slice of ownership in a real business — not a ticker that moves.",
    [
      h2("What is this?"),
      p("A stock, or share, is a unit of ownership in a company. Owning one share of a company with 10 crore shares makes you the owner of one ten-crore-th of everything it owns and earns, after its debts."),
      p("That ownership carries two rights: a claim on residual profits, usually paid as dividends, and a vote on certain decisions."),
      h2("Why does it matter?"),
      p("Almost every mistake beginners make in equities comes from forgetting this. A share price that halves is not a number falling — it is the market changing its opinion about a business, which may or may not be correct."),
      p("It also explains why equity is risky. Shareholders rank behind every lender and supplier, so they get everything that remains and, sometimes, nothing."),
      h2("How does it work?"),
      list([
        "<strong>Issued by the company</strong> in a primary offering; after that, shares change hands between investors.",
        "<strong>Price is set by trading</strong>, not by the company — buyers and sellers meeting.",
        "<strong>Returns come from two sources:</strong> dividends received and price appreciation.",
        "<strong>Ownership is proportional:</strong> your claim is your shares divided by shares outstanding.",
      ]),
      fig("Real-Life Case Study: what one share buys",
        ["A company with 8 crore shares outstanding, trading at ₹180."],
        [["Market capitalisation", "₹1,440 crore"], ["Your holding", "100 shares"],
         ["Your ownership", "0.000125%"], ["Company net profit", "₹80 crore"],
         ["Your share of annual profit", "₹1,000"], ["Dividend at a 30% payout", "₹300"]],
        ["Your ₹18,000 buys a claim on ₹1,000 of annual profit, of which ₹300 is paid out and ₹700 is reinvested on your behalf.",
         "That reinvested ₹700 is the point of equity ownership. If the company deploys it above its cost of capital, your claim grows without you contributing anything further."]),
      h2("Key terms"),
      def("Share", "A unit of ownership representing a proportional claim on a company's assets and profits."),
      def("Dividend", "The portion of profit distributed to shareholders."),
      def("Residual claim", "The shareholder's position — paid after all other claimants."),
      h2("Practice"),
      practice([
        { q: "A company earns ₹120 crore with 15 crore shares. You own 500. Compute your share of profit and of a 40% payout.", a: "EPS = 120 ÷ 15 = ₹8 per share. Your profit claim = 500 × 8 = ₹4,000. Dividend = 40% = ₹1,600." },
        { q: "Why is a share price fall not necessarily a loss of business value?", a: "Price reflects the market's current opinion, which changes with sentiment, interest rates and flows as well as with the business. The company's earnings and assets may be unchanged — the price says what someone will pay today, not what it is worth." },
      ]),
      h2("Connection"),
      p("This is the instrument everything in Level 8 was analysing, and the asset the portfolio theory in Level 10 combines."),
      mcq("Owning a share entitles you to:",
        ["A guaranteed dividend", "A proportional claim on profits and assets after all other claimants", "Repayment of your investment", "Priority over lenders"], 1,
        [W, "Correct. Equity is a residual claim — everything left after debts, which can be a great deal or nothing.", W, W]),
    ]);

  L("c-market-capitalization-equities", "Market capitalization",
    "The market's price for the whole equity — and what it does not include.",
    [
      h2("What is this?"),
      p("Market capitalisation is share price times shares outstanding: the market's current valuation of all the equity in a company. It is also how companies are sorted into large, mid and small cap."),
      h2("Why does it matter?"),
      p("Size affects behaviour. Larger companies are more heavily researched, more liquid and generally less volatile; smaller ones are less efficiently priced and harder to trade in size."),
      p("The persistent trap: market cap values the equity only. A company with a small market cap and large debt may be a large business — enterprise value, not market cap, measures that."),
      h2("How does it work?"),
      formula("Market capitalisation", [
        "<b>Market cap = Share price × Shares outstanding</b>",
        "<b>Enterprise value = Market cap + Net debt</b>",
        "Free float = the portion of shares actually available to trade",
      ]),
      p("<strong>Free float</strong> matters separately. If promoters hold 70%, only 30% trades, so index weights and liquidity are based on far less than the headline market cap."),
      fig("Real-Life Case Study: same market cap, different businesses",
        ["Two companies each capitalised at ₹1,440 crore."],
        [["Company A — market cap", "₹1,440 crore"], ["Company A — net debt", "₹60 crore"], ["Company A — EV", "₹1,500 crore"],
         ["Company B — market cap", "₹1,440 crore"], ["Company B — net debt", "₹2,100 crore"], ["Company B — EV", "₹3,540 crore"]],
        ["Company B controls a business more than twice the size, funded largely by lenders rather than owners.",
         "Screening on market cap alone would treat these as equivalent mid-caps. On enterprise value one is more than double the other, with very different risk."]),
      h2("Key terms"),
      def("Free float", "Shares genuinely available for trading, excluding locked or promoter holdings."),
      def("Large / mid / small cap", "Size bands by market capitalisation, affecting liquidity and coverage."),
      h2("Practice"),
      practice([
        { q: "Price ₹250, 12 crore shares, net debt ₹800 crore. Compute market cap and EV.", a: "Market cap = ₹3,000 crore. EV = 3,000 + 800 = ₹3,800 crore." },
        { q: "Two companies have identical market caps but one carries far more debt. Which controls the larger business, and which is riskier for shareholders?", a: "The indebted one controls the larger business, since EV is higher. It is also riskier for shareholders: the same operating decline hits a thinner equity cushion, so the share price moves far more." },
      ]),
      h2("Connection"),
      p("This is the same figure from Level 5, applied here to classifying and comparing listed companies."),
      mcq("A company with a small market cap and large debt is:",
        ["A small business", "Potentially a large business mostly funded by lenders", "Debt free", "Always cheap"], 1,
        [W, "Correct. Market cap sizes the equity slice; enterprise value sizes the business.", W, W]),
    ]);

  /* ============ FIXED INCOME ============ */

  L("c-bonds", "Bonds",
    "A bond is a loan you can trade — fixed payments, a fixed date, and a price that moves.",
    [
      h2("What is this?"),
      p("A bond is a tradable loan. The issuer borrows a face amount, pays a fixed <strong>coupon</strong> periodically, and repays the face value at <strong>maturity</strong>. You can hold it to maturity or sell it to someone else."),
      h2("Why does it matter?"),
      p("Bonds are how governments and large companies borrow, and they are far larger than equity markets. Their yields set the risk-free rate that anchors every valuation — the discount rate in a DCF starts with a government bond."),
      p("They are also where beginners meet an important counter-intuition: a bond's payments are fixed, but its price is not."),
      h2("How does it work?"),
      list([
        "<strong>Face value</strong> — the amount repaid at maturity, typically ₹100 or ₹1,000.",
        "<strong>Coupon</strong> — the fixed annual payment, quoted as a percentage of face value.",
        "<strong>Maturity</strong> — when the face value is repaid.",
        "<strong>Price</strong> — what the bond trades at, which moves inversely with market interest rates.",
      ]),
      p("The inverse relationship is the whole of bond mathematics. If a bond pays 7% and new bonds are issued at 9%, nobody will pay full price for the 7% bond — its price falls until its total return matches 9%."),
      fig("Real-Life Case Study: why the price moves",
        ["A ₹1,000 face value bond paying a 7% coupon, five years to maturity."],
        [["Annual coupon", "₹70"], ["Market rate when issued", "7.0%"], ["Price at issue", "₹1,000"],
         ["Market rates rise to", "9.0%"], ["Price falls to approximately", "₹922"],
         ["Market rates fall to", "5.0%"], ["Price rises to approximately", "₹1,087"]],
        ["The ₹70 coupon never changes. The price adjusts so that a buyer at today's price earns the going market rate.",
         "That is the mechanism behind every bond loss and gain: not default, but rates moving. A holder to maturity still receives ₹70 a year and ₹1,000 back — the price move only matters if you sell."]),
      h2("Key terms"),
      def("Face value", "The amount repaid at maturity, also called par."),
      def("Coupon", "The fixed periodic payment, as a percentage of face value."),
      def("Maturity", "The date the face value is repaid."),
      h2("Practice"),
      practice([
        { q: "A ₹1,000 bond pays an 8% coupon for 6 years. Compute total coupons received and total cash if held to maturity.", a: "Annual coupon = ₹80. Over 6 years = ₹480. Plus ₹1,000 face value at maturity = ₹1,480 total." },
        { q: "Market rates rise after you buy a bond. What happens to your position if you hold to maturity versus sell today?", a: "Held to maturity, nothing changes: you receive the same coupons and face value. Sold today, you realise a loss, because the price fell so a new buyer earns the higher market rate. The loss is real only if you sell." },
      ]),
      h2("Connection"),
      p("Government bond yields are the risk-free rate from Level 5 — the base of every discount rate."),
      sandbox("present-value", "Bond price sandbox",
        "Discount a ₹1,000 repayment at different market rates and see why a higher rate means a lower price today.", [
        { key: "amount", label: "Face value repaid", value: 1000, unit: "₹" },
        { key: "rate", label: "Market interest rate", value: 9, unit: "%" },
        { key: "years", label: "Years to maturity", value: 5 },
      ]),
      mcq("When market interest rates rise, existing bond prices:",
        ["Rise", "Fall, so their return matches the new market rate", "Stay fixed", "Become zero"], 1,
        [W, "Correct. The coupon is fixed, so only the price can adjust to bring the return into line with new issues.", W, W]),
    ]);

  L("c-yield", "Yield",
    "The return you actually earn on a bond at today's price — not the coupon.",
    [
      h2("What is this?"),
      p("Yield is the return a bond delivers at its current price. The <strong>current yield</strong> is simply coupon divided by price. The more complete measure, <strong>yield to maturity</strong>, is the annual return earned if you buy today and hold to maturity, including the gain or loss to face value."),
      h2("Why does it matter?"),
      p("The coupon tells you what the bond pays; the yield tells you what you earn. Buying a 7% bond at ₹922 earns considerably more than 7%, because you also collect ₹78 of price appreciation by maturity."),
      p("Yield is also the common language of fixed income — bonds are quoted and compared by yield, not by price."),
      h2("How does it work?"),
      formula("Yield measures", [
        "<b>Current yield = Annual coupon ÷ Price</b>",
        "<b>Yield to maturity</b> = the discount rate making the present value of all payments equal the price",
        "Price below face → YTM above coupon. Price above face → YTM below coupon",
      ]),
      fig("Real-Life Case Study: three prices, one bond",
        ["A ₹1,000 bond with a 7% coupon and 5 years remaining."],
        [["Price ₹1,000 — current yield", "7.00%"], ["Price ₹1,000 — YTM", "7.00%"],
         ["Price ₹922 — current yield", "7.59%"], ["Price ₹922 — YTM", "≈9.0%"],
         ["Price ₹1,087 — current yield", "6.44%"], ["Price ₹1,087 — YTM", "≈5.0%"]],
        ["At ₹922, current yield says 7.59% and yield to maturity says 9.0%. The difference is the ₹78 gain to par, spread over five years.",
         "Current yield is a shortcut that ignores that gain. Yield to maturity is the number to compare across bonds, because it captures everything you actually receive."]),
      h2("Key terms"),
      def("Current yield", "Annual coupon divided by current price — ignores the gain or loss to maturity."),
      def("Yield to maturity", "The total annual return if held to maturity, including price convergence to par."),
      def("Par", "A price equal to face value, where YTM equals the coupon."),
      h2("Practice"),
      practice([
        { q: "A ₹1,000 bond with an 8% coupon trades at ₹950. Compute the current yield and say whether YTM is higher or lower.", a: "Current yield = 80 ÷ 950 = 8.42%. YTM is higher still, because the buyer also gains ₹50 as the price converges to ₹1,000 at maturity." },
        { q: "Why do bonds trading above face value have a YTM below their coupon?", a: "The holder receives the coupon but loses the premium as the price falls to face value at maturity. That capital loss offsets part of the coupon income, so the total return is below the coupon rate." },
      ]),
      h2("Connection"),
      p("Yield to maturity is a discount rate — the same present value arithmetic from Level 5, solved for the rate instead of the value."),
      mcq("A bond bought below face value has a yield to maturity:",
        ["Below its coupon rate", "Above its coupon rate", "Equal to its coupon rate", "Of zero"], 1,
        [W, "Correct. The buyer collects the coupon and a capital gain as the price rises to par, so the total return exceeds the coupon.", W, W]),
    ]);

  L("c-yield-curves", "Yield curves",
    "Yields plotted against maturity — and what the shape says about the economy.",
    [
      h2("What is this?"),
      p("A yield curve plots the yields of government bonds against their maturities: 1 year, 2, 5, 10, 30. It shows the price of borrowing at each horizon on a single chart."),
      h2("Why does it matter?"),
      p("Every long-term valuation uses a point on this curve as its risk-free rate. Its shape also carries information: it aggregates what the entire bond market expects about growth, inflation and central bank policy."),
      h2("How does it work?"),
      list([
        "<strong>Upward-sloping (normal):</strong> longer maturities yield more, compensating for time and inflation uncertainty. The usual shape.",
        "<strong>Flat:</strong> little difference across maturities — often a transition.",
        "<strong>Inverted:</strong> short rates above long rates. Historically associated with expectations of slowing growth and rate cuts ahead.",
      ]),
      p("Read the curve as expectations, not prophecy. An inverted curve says the market expects lower rates later, which usually accompanies a weaker economy — a correlation, not a mechanism."),
      fig("Real-Life Case Study: two curves",
        ["The same market, eighteen months apart."],
        [["Normal — 1 year", "6.4%"], ["Normal — 5 year", "7.1%"], ["Normal — 10 year", "7.4%"],
         ["Inverted — 1 year", "8.1%"], ["Inverted — 5 year", "7.6%"], ["Inverted — 10 year", "7.3%"]],
        ["In the normal curve, lending for ten years pays a full point more than for one. In the inverted curve, it pays less.",
         "That inversion means the market expects rates to fall — usually because growth is expected to weaken. For a valuation, the 10-year yield fell only 0.1 points, but the short rate rose 1.7, which changes borrowing costs for every company with floating-rate debt."]),
      h2("Key terms"),
      def("Yield curve", "Government bond yields plotted against maturity."),
      def("Inversion", "Short-term yields exceeding long-term yields."),
      def("Term premium", "The extra yield demanded for lending over a longer horizon."),
      h2("Practice"),
      practice([
        { q: "1-year yields 8.1% and 10-year yields 7.3%. Describe the curve and what it implies.", a: "Inverted by 0.8 points. The market expects short rates to fall over the coming years, typically because it expects weaker growth or lower inflation — investors accept less to lock in the long rate now." },
        { q: "Which point on the curve should you use as the risk-free rate for a DCF of a long-lived business?", a: "A long maturity, usually the 10-year, because it matches the horizon of the cash flows being discounted. Using a 1-year yield would price a decade of cash flows off a rate that resets in twelve months." },
      ]),
      h2("Connection"),
      p("The curve supplies the risk-free rate for CAPM and WACC from Level 5, and its shape moves every valuation at once."),
      mcq("An inverted yield curve means:",
        ["Bonds have defaulted", "Short-term yields exceed long-term yields, implying expected rate cuts", "Inflation is zero", "Equity markets will rise"], 1,
        [W, "Correct. Investors accept lower long-term yields when they expect rates to fall — historically associated with slowing growth.", W, W]),
    ]);

  L("c-duration", "Duration",
    "How much a bond's price moves when interest rates change.",
    [
      h2("What is this?"),
      p("Duration measures a bond's price sensitivity to interest rates. A duration of 6 means that if yields rise 1 percentage point, the price falls roughly 6%."),
      p("It is expressed in years because it is also the weighted average time until the bond's cash flows arrive — but its practical use is as a sensitivity measure."),
      h2("Why does it matter?"),
      p("It is the single most useful number in fixed income. It converts a vague worry — 'rates might rise' — into a specific figure: a 30-year bond loses roughly three times as much as a 10-year one for the same rate move."),
      p("It also explains why long bonds are volatile despite having no default risk. A government bond can lose 20% of its value without anything going wrong at all."),
      h2("How does it work?"),
      formula("Duration and price change", [
        "<b>Price change ≈ −Duration × Change in yield</b>",
        "<b>Modified duration = Macaulay duration ÷ (1 + yield)</b>",
        "Longer maturity and lower coupon both increase duration",
      ]),
      list([
        "<strong>Longer maturity → higher duration.</strong> More of the value sits further away.",
        "<strong>Lower coupon → higher duration.</strong> Less cash arrives early, so the average payment date is later.",
        "<strong>Zero-coupon bonds</strong> have duration equal to maturity — all the cash comes at the end.",
      ]),
      fig("Real-Life Case Study: the same rate move, three bonds",
        ["Yields rise 1 percentage point across the curve."],
        [["2-year bond — duration 1.9", "price −1.9%"], ["10-year bond — duration 7.4", "price −7.4%"],
         ["30-year bond — duration 15.8", "price −15.8%"], ["30-year zero-coupon — duration 30", "price −30%"],
         ["Default risk in all cases", "none"]],
        ["A one-point move destroys nearly a sixth of a 30-year bond's value and 1.9% of a 2-year bond's.",
         "None of these bonds is more likely to default than the others. Duration alone explains the entire difference, which is why matching duration to your horizon matters more than credit quality for government bonds."]),
      h2("Key terms"),
      def("Duration", "Price sensitivity to a 1 percentage point change in yield, expressed in years."),
      def("Modified duration", "The version used directly for price-change estimates."),
      def("Interest rate risk", "The risk that rate changes move a bond's price — what duration measures."),
      h2("Practice"),
      practice([
        { q: "A bond has a modified duration of 6.5 and yields rise 0.75 points. Estimate the price change.", a: "−6.5 × 0.75 = −4.875%. A ₹1,000 bond falls to about ₹951." },
        { q: "Why does a lower coupon increase duration for bonds of the same maturity?", a: "A lower coupon means less cash arrives in early years, so proportionally more of the bond's value sits in the final repayment. The weighted average arrival time of cash is later, making the price more sensitive to the discount rate." },
      ]),
      h2("Connection"),
      p("Duration is the bond market's version of the discount-factor arithmetic from Level 5 — distant cash flows are the most rate-sensitive."),
      sandbox("present-value", "Rate sensitivity sandbox",
        "Hold the amount fixed and raise the rate. The further away the cash flow, the more its value collapses — that is duration.", [
        { key: "amount", label: "Cash flow at maturity", value: 1000, unit: "₹" },
        { key: "rate", label: "Yield", value: 7, unit: "%" },
        { key: "years", label: "Years to maturity", value: 10 },
      ]),
      mcq("A bond with a modified duration of 8 will fall roughly how much if yields rise 0.5 points?",
        ["0.5%", "4%", "8%", "16%"], 1,
        [W, "Correct. Price change ≈ −8 × 0.5 = −4%.", W, W]),
    ]);

  L("c-convexity", "Convexity",
    "The correction to duration — and why it works in the bondholder's favour.",
    [
      h2("What is this?"),
      p("Duration assumes the price-yield relationship is a straight line. It is not: it curves. Convexity measures that curvature, and it is the correction that makes duration estimates accurate for larger rate moves."),
      h2("Why does it matter?"),
      p("The curvature is asymmetric in the holder's favour. For a given size of rate move, prices rise slightly more when yields fall than they fall when yields rise. Duration alone overstates losses and understates gains."),
      p("For small moves the correction is negligible. For large ones — two or three points — it is material, which is precisely when it matters most."),
      h2("How does it work?"),
      formula("Price change with convexity", [
        "<b>Price change ≈ −Duration × Δy + ½ × Convexity × (Δy)²</b>",
        "The convexity term is always positive for a standard bond",
        "Δy = change in yield, in decimal form",
      ]),
      p("Because the convexity term is squared, it grows quickly with the size of the move — and because it is positive, it always improves the outcome relative to the duration-only estimate."),
      fig("Real-Life Case Study: duration alone versus the correction",
        ["A bond with duration 12 and convexity 150, for a 2-point yield move."],
        [["Duration estimate, +2% yields", "−24.0%"], ["Convexity adjustment", "+3.0%"], ["Actual price change", "−21.0%"],
         ["Duration estimate, −2% yields", "+24.0%"], ["Convexity adjustment", "+3.0%"], ["Actual price change", "+27.0%"]],
        ["The bond loses 21% when rates rise 2 points and gains 27% when they fall 2 points — the same move, an asymmetric result.",
         "That asymmetry is convexity, and it is why long-duration bonds are valuable in volatile rate environments beyond what duration alone suggests."]),
      h2("Key terms"),
      def("Convexity", "The curvature of the price-yield relationship, correcting duration estimates."),
      def("Positive convexity", "The property that gains exceed losses for equal-sized yield moves in each direction."),
      h2("Practice"),
      practice([
        { q: "Duration 10, convexity 120, yields fall 1.5 points. Estimate the price change.", a: "Duration term = +15%. Convexity = ½ × 120 × 0.015² = 0.0135 = +1.35%. Total ≈ +16.35%." },
        { q: "Why does duration alone become unreliable for large rate moves?", a: "It is a straight-line approximation to a curved relationship. The error grows with the square of the move, so it is negligible for 0.1 points and material for 2 points — exactly the scenarios where accuracy matters." },
      ]),
      h2("Connection"),
      p("Convexity refines duration; both describe how the discounting arithmetic from Level 5 behaves as rates change."),
      mcq("Positive convexity means that for equal yield moves:",
        ["Losses exceed gains", "Gains exceed losses", "Price does not move", "Duration is zero"], 1,
        [W, "Correct. The curvature works in the bondholder's favour, so duration overstates losses and understates gains.", W, W]),
    ]);

  L("c-credit", "Credit",
    "The risk the borrower does not pay — and the extra yield demanded for it.",
    [
      h2("What is this?"),
      p("Credit risk is the possibility a borrower fails to make its payments. Investors demand a <strong>credit spread</strong> — extra yield above a government bond of the same maturity — as compensation."),
      h2("Why does it matter?"),
      p("The spread is the market's continuously updated opinion of a borrower's health. When a company's spread widens sharply, bond investors are saying something that equity investors sometimes notice later."),
      p("Spreads also drive corporate borrowing costs directly, which flows into WACC and therefore into every valuation."),
      h2("How does it work?"),
      formula("Credit spread", [
        "<b>Corporate yield = Government yield + Credit spread</b>",
        "<b>Expected loss ≈ Probability of default × (1 − Recovery rate)</b>",
        "Spread compensates for expected loss plus uncertainty and illiquidity",
      ]),
      list([
        "<strong>Ratings</strong> summarise credit quality — investment grade down to high yield — but they lag the market.",
        "<strong>Seniority</strong> matters: senior secured debt recovers more in default than subordinated debt.",
        "<strong>Recovery rate</strong> is what lenders get back after default, often 40-60% for senior claims.",
      ]),
      fig("Real-Life Case Study: pricing default risk",
        ["Three borrowers, ten-year debt, against a 7.3% government yield."],
        [["Government bond", "7.30%"], ["Strong corporate — spread", "+0.9% → 8.20%"],
         ["Mid-grade corporate — spread", "+2.4% → 9.70%"], ["High yield — spread", "+6.1% → 13.40%"],
         ["Implied annual default probability (high yield, 45% recovery)", "≈11%"]],
        ["The 6.1-point spread on the high-yield borrower implies roughly an 11% annual chance of default, given typical recovery.",
         "That is the discipline: convert a spread into an implied default probability and ask whether you believe it. If you think the true risk is 5%, you are being overpaid; if 20%, underpaid."]),
      h2("Key terms"),
      def("Credit spread", "The yield premium over a government bond of the same maturity."),
      def("Recovery rate", "The proportion of face value recovered after a default."),
      def("Investment grade", "Ratings indicating relatively low default risk; below it is high yield."),
      h2("Practice"),
      practice([
        { q: "Government yield 7.3%, corporate spread 2.4 points. Compute the corporate yield and the annual cost on ₹500 crore of debt.", a: "Yield = 9.7%. Annual interest = 500 × 9.7% = ₹48.5 crore, of which ₹12 crore is the spread over borrowing at the government rate." },
        { q: "A company's credit spread widens from 2.0 to 4.5 points in three months with no news. What might it indicate?", a: "That bond investors have re-assessed its default risk — perhaps due to sector conditions, refinancing concerns or leverage. Spreads often move before equity prices, so a widening spread is a signal worth investigating rather than dismissing." },
      ]),
      h2("Connection"),
      p("The credit spread determines the cost of debt in WACC from Level 5, and covenant risk from Level 3."),
      mcq("A credit spread compensates investors for:",
        ["Inflation only", "The risk the borrower defaults, plus uncertainty and illiquidity", "Currency movements", "Tax"], 1,
        [W, "Correct. It is the extra yield above a default-free government bond of the same maturity.", W, W]),
    ]);

  /* ============ MACRO & CURRENCIES ============ */

  L("c-interest-rates", "Interest rates",
    "The price of money — and the single variable that moves every asset at once.",
    [
      h2("What is this?"),
      p("An interest rate is the price of borrowing money for a period. Market rates are set by supply and demand for capital, heavily influenced by the central bank's policy rate at the short end."),
      h2("Why does it matter?"),
      p("Rates appear in the denominator of every valuation. When the risk-free rate rises one point, every discount rate rises, so every future cash flow in every asset is worth less — simultaneously, and without any business changing."),
      p("They also change behaviour: borrowing becomes dearer, saving more attractive, and marginal projects stop clearing their hurdle rate."),
      h2("How does it work?"),
      list([
        "<strong>Nominal rate ≈ real rate + expected inflation.</strong> Lenders need compensation for both.",
        "<strong>Short rates</strong> follow central bank policy closely; <strong>long rates</strong> reflect expectations about growth and inflation over years.",
        "<strong>Higher rates</strong> reduce asset values, slow borrowing and typically cool inflation, with a lag.",
        "The effect is largest on assets whose value sits furthest in the future — long bonds and growth equities.",
      ]),
      fig("Real-Life Case Study: one point, several assets",
        ["Rates rise 1 percentage point across the curve."],
        [["2-year bond (duration 1.9)", "−1.9%"], ["10-year bond (duration 7.4)", "−7.4%"],
         ["Mature equity (WACC 11% → 12%)", "≈−9%"], ["Growth equity (long-dated cash flows)", "≈−18%"],
         ["Floating-rate borrower's interest cost", "+1 point immediately"]],
        ["Nothing about any of these businesses changed. One macro variable moved and every valuation reset.",
         "Note the pattern: the further into the future an asset's cash flows sit, the more it falls. That is duration, and it applies to equities as much as to bonds."]),
      h2("Key terms"),
      def("Policy rate", "The central bank's benchmark rate, anchoring short-term borrowing costs."),
      def("Real rate", "The nominal rate less expected inflation — the true cost of borrowing."),
      h2("Practice"),
      practice([
        { q: "Nominal rate 8.5%, expected inflation 5.5%. Compute the approximate and precise real rates.", a: "Approximate: 8.5 − 5.5 = 3.0%. Precise: (1.085 ÷ 1.055) − 1 = 2.84%." },
        { q: "Why do long-duration growth companies fall more than mature companies when rates rise?", a: "More of their value sits in distant cash flows, which are discounted by (1+r) raised to a higher power. A rate rise therefore shrinks their present value proportionally more — the same mechanism that makes long bonds more rate-sensitive than short ones." },
      ]),
      h2("Connection"),
      p("Rates set the risk-free rate feeding CAPM and WACC, and drive the discount factors from Level 5."),
      sandbox("inflation-real", "Real rate sandbox",
        "Set the nominal rate below inflation and watch purchasing power fall even as the balance grows.", [
        { key: "amount", label: "Amount", value: 100000, unit: "₹" },
        { key: "nominalRate", label: "Nominal interest rate", value: 8.5, unit: "%" },
        { key: "inflation", label: "Inflation", value: 5.5, unit: "%" },
        { key: "years", label: "Years", value: 5 },
      ]),
      mcq("When interest rates rise, long-duration assets fall more because:",
        ["They are riskier businesses", "More of their value lies in distant cash flows, which discount more heavily", "They pay no dividends", "They have more debt"], 1,
        [W, "Correct. The discount factor compounds over time, so distant cash flows lose the most value when the rate rises.", W, W]),
    ]);

  L("c-central-banks", "Central banks",
    "The institution that sets the short-term price of money, and why markets watch it.",
    [
      h2("What is this?"),
      p("A central bank — the Reserve Bank of India, the US Federal Reserve — manages a country's monetary policy. Its main tool is the policy rate at which it lends to commercial banks, which propagates through the whole economy."),
      h2("Why does it matter?"),
      p("Because it anchors the short end of the yield curve, and expectations about it drive the long end. Every asset priced by discounting is therefore affected by what the central bank does and, more importantly, what it is expected to do."),
      p("Markets move on expectations, not events. A rate rise that was fully expected changes little; a hold when a cut was expected can move markets sharply."),
      h2("How does it work?"),
      list([
        "<strong>Mandate:</strong> typically price stability, sometimes alongside growth or employment objectives.",
        "<strong>Raising rates</strong> makes borrowing dearer, cooling demand and, with a lag, inflation.",
        "<strong>Cutting rates</strong> does the reverse.",
        "<strong>Communication</strong> matters as much as action — guidance about future policy moves markets immediately.",
        "Effects arrive with a lag of several quarters, which is why policy is often criticised as late.",
      ]),
      p("Central bank policy is a live political and economic debate. This lesson describes the mechanism; whether any particular decision was correct is contested and outside its scope."),
      fig("Real-Life Case Study: expectations versus outcome",
        ["Two policy meetings, same 0.25-point rise."],
        [["Meeting 1 — market expected", "+0.25%"], ["Meeting 1 — delivered", "+0.25%"],
         ["Meeting 1 — 10-year yield move", "≈0"], ["Meeting 2 — market expected", "no change"],
         ["Meeting 2 — delivered", "+0.25%"], ["Meeting 2 — 10-year yield move", "+0.18%"]],
        ["The identical action moved yields in one case and not the other, entirely because of what was already priced in.",
         "This is why 'the central bank raised rates so markets will fall' is unreliable reasoning. What matters is the surprise relative to expectations, not the action itself."]),
      h2("Key terms"),
      def("Policy rate", "The benchmark rate the central bank sets, such as the repo rate in India."),
      def("Forward guidance", "Communication about likely future policy, which markets price immediately."),
      def("Monetary transmission", "The lagged process by which policy changes reach the real economy."),
      h2("Practice"),
      practice([
        { q: "A central bank raises rates exactly as expected and bond yields barely move. Why?", a: "The rise was already priced into bond prices before the meeting. Markets discount expected events in advance, so only the surprise component moves prices." },
        { q: "Why do policy changes affect inflation with a lag?", a: "Higher rates work through borrowing decisions, investment plans and hiring, which take quarters to change. The rate moves immediately; the behaviour it targets responds slowly." },
      ]),
      h2("Connection"),
      p("Policy rates anchor the yield curve, which supplies the risk-free rate for every valuation in Level 5."),
      mcq("Markets typically move most when a central bank:",
        ["Does exactly what was expected", "Surprises relative to expectations", "Publishes minutes", "Changes its governor"], 1,
        [W, "Correct. Expected actions are already reflected in prices; only the surprise carries new information.", W, W]),
    ]);

  L("c-fx", "FX",
    "Exchange rates — the price of one currency in another, and why it matters to a business.",
    [
      h2("What is this?"),
      p("A foreign exchange rate is the price of one currency in terms of another. If the rupee-dollar rate is ₹83, one US dollar costs 83 rupees."),
      h2("Why does it matter?"),
      p("Any company earning or spending in another currency has its results changed by rates it does not control. An exporter earning dollars gains when the rupee weakens; an importer paying in dollars loses."),
      p("For investors, currency also changes returns: a foreign investment can rise 10% in local terms and deliver less, or more, once converted home."),
      h2("How does it work?"),
      list([
        "<strong>Rates float</strong> based on trade flows, interest rate differentials, capital flows and expectations.",
        "<strong>Depreciation</strong> of the home currency helps exporters and hurts importers.",
        "<strong>Translation exposure</strong> affects reported results of foreign subsidiaries.",
        "<strong>Hedging</strong> with forwards or options can fix a rate, at a cost.",
      ]),
      fig("Real-Life Case Study: an exporter and an importer",
        ["The rupee weakens from ₹80 to ₹86 per dollar."],
        [["Exporter — revenue $20 million", "₹160 cr → ₹172 cr"], ["Exporter — gain", "+₹12 crore"],
         ["Importer — purchases $15 million", "₹120 cr → ₹129 cr"], ["Importer — cost increase", "+₹9 crore"],
         ["Exporter with 60% imported inputs", "net gain much smaller"]],
        ["The same 7.5% currency move helps one company and hurts another by comparable amounts.",
         "The third line is the one analysts miss: an exporter buying imported raw materials has a natural partial hedge, so its net exposure is far smaller than its revenue suggests."]),
      h2("Key terms"),
      def("Depreciation", "A fall in the value of one currency against another."),
      def("Natural hedge", "Offsetting exposures — earning and spending in the same foreign currency."),
      def("Forward contract", "An agreement to exchange currency at a fixed future rate."),
      h2("Practice"),
      practice([
        { q: "An exporter earns $25 million. The rupee moves from ₹82 to ₹85. Compute the revenue change in rupees.", a: "Before: ₹205 crore. After: ₹212.5 crore. Gain = ₹7.5 crore, purely from the currency." },
        { q: "Why might an exporter with large imported inputs be less exposed to currency moves than its revenue suggests?", a: "Its costs move with the same currency as its revenue, so gains on sales are partly offset by higher input costs. The net exposure is revenue minus foreign-currency costs, not revenue alone." },
      ]),
      h2("Connection"),
      p("Currency exposure is an operational risk to identify in the Level 8 risk register, and it changes forecast revenue and margins."),
      mcq("A weakening home currency generally:",
        ["Helps importers", "Helps exporters and hurts importers", "Has no effect on companies", "Reduces inflation"], 1,
        [W, "Correct. Foreign earnings convert into more home currency, while foreign purchases cost more.", W, W]),
    ]);

  L("c-commodities", "Commodities",
    "Standardised physical goods whose prices are set globally and outside any company's control.",
    [
      h2("What is this?"),
      p("Commodities are interchangeable raw materials — crude oil, steel, copper, wheat, gold — traded on global markets where one unit is equivalent to another."),
      h2("Why does it matter?"),
      p("For most businesses, commodities are an input cost set by a global market. A packaging company cannot negotiate the world price of paper; it can only pass it on, absorb it, or hedge it."),
      p("That makes commodity exposure a major driver of margin volatility, and the ability to pass costs through is a direct test of pricing power."),
      h2("How does it work?"),
      list([
        "<strong>Price is set by global supply and demand</strong>, not by any individual buyer or seller.",
        "<strong>Producers</strong> are price takers — their revenue swings with the commodity.",
        "<strong>Consumers</strong> face input cost volatility, mitigated by pass-through pricing or hedging.",
        "<strong>Hedging with futures</strong> fixes a price for a period, converting uncertainty into a known cost.",
      ]),
      fig("Real-Life Case Study: pass-through decides the damage",
        ["A key input rises 30%; it is 40% of cost of goods sold."],
        [["Revenue", "₹1,000 crore"], ["COGS before", "₹600 crore"], ["Input cost increase", "+₹72 crore"],
         ["With full pass-through — gross margin", "unchanged"], ["With no pass-through — gross margin", "40% → 32.8%"],
         ["With no pass-through — EBITDA effect", "−₹72 crore"]],
        ["The identical commodity move is either a non-event or a 7-point margin collapse, depending entirely on pricing power.",
         "That is why commodity exposure must be analysed alongside competitive position. A branded product with loyal customers passes it on; an undifferentiated one absorbs it."]),
      h2("Key terms"),
      def("Price taker", "A participant with no influence over the market price."),
      def("Pass-through", "The ability to raise selling prices when input costs rise."),
      def("Hedging", "Fixing a future price with a contract to remove uncertainty."),
      h2("Practice"),
      practice([
        { q: "A commodity is 40% of a ₹600 crore COGS and rises 30%. Compute the cost increase and the margin effect on ₹1,000 crore of revenue with no pass-through.", a: "Increase = 600 × 40% × 30% = ₹72 crore. Gross margin falls from 40% to (1,000 − 672) ÷ 1,000 = 32.8%." },
        { q: "How does a company's competitive position change its commodity risk?", a: "Pricing power determines pass-through. A differentiated product can raise prices without losing volume, so the cost increase reaches the customer. A commodity-like product cannot, so the producer absorbs it in margin." },
      ]),
      h2("Connection"),
      p("Commodity exposure feeds the cost build in Level 4 and the risk register in Level 8; pass-through is competitive advantage in practice."),
      mcq("A company's exposure to a commodity input depends most on:",
        ["The size of its treasury team", "Its ability to pass the cost through to customers", "Its share price", "Its tax rate"], 1,
        [W, "Correct. Pricing power determines whether a cost increase reaches the customer or the margin.", W, W]),
    ]);

  /* ============ DERIVATIVES ============ */

  L("c-derivatives", "Derivatives",
    "Contracts whose value comes from something else — used to transfer risk, or to take it.",
    [
      h2("What is this?"),
      p("A derivative is a contract whose value derives from an underlying asset: a share, an index, a currency, a commodity, an interest rate. You are not trading the asset, but an agreement about it."),
      h2("Why does it matter?"),
      p("Derivatives exist to transfer risk. A farmer fixes a price for the harvest; an airline fixes fuel costs; an importer fixes an exchange rate. Each transfers uncertainty to someone willing to hold it."),
      p("The same instruments allow large positions for small outlays, which is why they are also how institutions occasionally destroy themselves. The instrument is neutral; the leverage is the danger."),
      h2("How does it work?"),
      list([
        "<strong>Forwards and futures:</strong> an agreement to transact at a fixed price on a future date. Both sides are obliged.",
        "<strong>Options:</strong> the right, not the obligation, to transact at a set price.",
        "<strong>Swaps:</strong> exchanging one set of cash flows for another, such as floating interest for fixed.",
        "<strong>Hedging</strong> reduces existing exposure; <strong>speculation</strong> creates new exposure. The same contract does either.",
      ]),
      fig("Real-Life Case Study: the same contract, two purposes",
        ["A jet fuel futures contract fixing the price at ₹95,000 per kilolitre."],
        [["Airline — physical fuel need", "yes"], ["Airline — effect of contract", "cost fixed, risk removed"],
         ["Trader — physical fuel need", "none"], ["Trader — effect of contract", "new exposure created"],
         ["If fuel rises to ₹115,000", "airline protected; trader gains"],
         ["If fuel falls to ₹75,000", "airline forgoes saving; trader loses"]],
        ["Identical contract, opposite economic function. The airline reduced uncertainty it already had; the trader manufactured uncertainty it did not.",
         "That distinction — hedging against an existing exposure versus speculating without one — is what separates prudent use from gambling, and it is invisible in the contract itself."]),
      h2("Key terms"),
      def("Underlying", "The asset whose price determines the derivative's value."),
      def("Hedging", "Using a derivative to offset an exposure you already have."),
      def("Notional", "The face amount a derivative references, usually far larger than the cash outlay."),
      h2("Practice"),
      practice([
        { q: "An airline fixes fuel at ₹95,000 per kilolitre; the market price rises to ₹115,000. What was the effect?", a: "It pays ₹95,000, saving ₹20,000 per kilolitre against the market. The hedge worked — though had prices fallen to ₹75,000 it would have paid ₹20,000 above market. Hedging removes both outcomes." },
        { q: "Why is the same futures contract prudent for one party and speculative for another?", a: "The airline has an existing fuel exposure the contract offsets, reducing total risk. A trader with no fuel exposure creates a new one, increasing total risk. The contract is identical; the position it sits alongside is not." },
      ]),
      h2("Connection"),
      p("Derivatives are how the currency, commodity and rate exposures in this level are managed — or amplified."),
      mcq("The difference between hedging and speculating with the same contract is:",
        ["The contract terms", "Whether it offsets an existing exposure or creates a new one", "The exchange used", "The maturity"], 1,
        [W, "Correct. Hedging reduces risk you already carry; speculation adds risk you did not have.", W, W]),
    ]);

  L("c-options", "Options",
    "The right, but not the obligation — which is what makes the payoff asymmetric.",
    [
      h2("What is this?"),
      p("An option gives its buyer the right to buy (a <strong>call</strong>) or sell (a <strong>put</strong>) an asset at a fixed <strong>strike price</strong> before expiry. The buyer pays a <strong>premium</strong> for that right and can simply walk away."),
      h2("Why does it matter?"),
      p("That asymmetry is the whole point. The buyer's loss is capped at the premium paid, while the gain can be large. The seller has the mirror image: a capped gain and a potentially very large loss."),
      p("It also appears throughout finance beyond trading — employee stock options, convertible bonds, and the equity of a heavily indebted company all behave like options."),
      h2("How does it work?"),
      formula("Option payoffs at expiry", [
        "<b>Call payoff = max(Spot − Strike, 0) − Premium</b>",
        "<b>Put payoff = max(Strike − Spot, 0) − Premium</b>",
        "Buyer's maximum loss = the premium. Seller's maximum gain = the premium",
      ]),
      fig("Real-Life Case Study: a call option's asymmetry",
        ["A call with a ₹200 strike, premium ₹12, on a share trading at ₹190."],
        [["Share at expiry ₹180", "option worthless; loss ₹12"], ["Share at expiry ₹200", "worthless; loss ₹12"],
         ["Share at expiry ₹212", "breakeven"], ["Share at expiry ₹250", "profit ₹38"],
         ["Share at expiry ₹320", "profit ₹108"], ["Maximum loss", "₹12"]],
        ["Below ₹212 the buyer loses, but never more than ₹12. Above it, gains rise without limit.",
         "The seller of that option collected ₹12 and now carries the mirror: ₹12 of maximum gain and an unbounded loss if the share runs. Selling options collects small premiums reliably and loses large amounts rarely — a payoff profile that misleads people about the risk being taken."]),
      h2("Key terms"),
      def("Call", "The right to buy at the strike price."),
      def("Put", "The right to sell at the strike price."),
      def("Strike", "The fixed price at which the option can be exercised."),
      def("Premium", "The price paid for the option — the buyer's maximum loss."),
      h2("Practice"),
      practice([
        { q: "A call with a ₹150 strike costs ₹9. Compute the payoff if the share ends at ₹140, ₹159 and ₹185.", a: "At ₹140: worthless, loss ₹9. At ₹159: intrinsic value ₹9, so breakeven. At ₹185: intrinsic ₹35 less ₹9 premium = ₹26 profit." },
        { q: "Why does selling options look profitable most of the time and still carry serious risk?", a: "The seller collects the premium whenever the option expires worthless, which is most of the time. The rare occasion when it does not can produce a loss many times the premiums collected — frequent small gains against infrequent large losses." },
      ]),
      h2("Connection"),
      p("Level 10 covers how options are priced and what drives their value before expiry."),
      mcq("The maximum loss for an option buyer is:",
        ["Unlimited", "The premium paid", "The strike price", "The share price"], 1,
        [W, "Correct. The buyer holds a right, not an obligation, so they simply let it expire — losing only what they paid.", W, W]),
    ]);

  L("c-futures", "Futures",
    "A binding agreement to transact later at a price fixed today.",
    [
      h2("What is this?"),
      p("A futures contract obliges both parties to exchange an asset at a set price on a set date. Unlike an option, neither side can walk away — the obligation is symmetric."),
      h2("Why does it matter?"),
      p("Futures are the standard tool for locking in prices: a producer fixes what it will receive, a consumer fixes what it will pay. They are standardised and exchange-traded, so counterparty risk is managed by a clearing house rather than by trusting the other side."),
      p("They also embed leverage. A small margin deposit controls a large notional position, which magnifies both outcomes and creates margin calls."),
      h2("How does it work?"),
      list([
        "<strong>Standardised</strong> in size, quality and delivery date, so contracts are interchangeable.",
        "<strong>Margin</strong> — a deposit, often 5-15% of notional — is posted rather than the full value.",
        "<strong>Marked to market daily:</strong> gains and losses settle each day, and losses trigger margin calls.",
        "<strong>Most are closed before delivery</strong> rather than settled physically.",
      ]),
      fig("Real-Life Case Study: leverage and margin calls",
        ["A ₹50 lakh notional futures position with 10% margin."],
        [["Notional value", "₹50,00,000"], ["Margin posted", "₹5,00,000"],
         ["Price moves +4%", "gain ₹2,00,000 (+40% on margin)"],
         ["Price moves −4%", "loss ₹2,00,000 (−40% on margin)"],
         ["Price moves −10%", "loss ₹5,00,000 — margin wiped out"]],
        ["A 4% move in the underlying produces a 40% swing on the capital committed, in either direction.",
         "At a 10% adverse move the entire deposit is gone and more is demanded the same day. That combination — daily settlement and leverage — is why futures positions can be forced to close at exactly the worst moment."]),
      h2("Key terms"),
      def("Margin", "The deposit required to hold a futures position, far below its notional value."),
      def("Mark to market", "Daily settlement of gains and losses on the position."),
      def("Margin call", "A demand for additional deposit when losses erode the margin."),
      h2("Practice"),
      practice([
        { q: "A ₹40 lakh notional position with 12% margin moves 5% in your favour. Compute the gain and the return on margin.", a: "Margin = ₹4.8 lakh. Gain = 40 × 5% = ₹2 lakh. Return on margin = 2 ÷ 4.8 = 41.7%." },
        { q: "Why can a futures position be closed out at the worst possible moment?", a: "Daily marking to market means losses must be funded immediately. A sharp adverse move triggers a margin call, and a holder unable to post more is closed out at that price — even if the position would have recovered." },
      ]),
      h2("Connection"),
      p("Futures are how the commodity and currency exposures earlier in this level are hedged, and they are the leverage mechanism behind many blow-ups."),
      mcq("Compared with an option buyer, a futures holder:",
        ["Has a capped loss", "Is obliged to transact, with losses that can exceed the deposit", "Pays a premium", "Has no counterparty"], 1,
        [W, "Correct. Futures obligations are symmetric — there is no right to walk away, and daily settlement can demand more capital.", W, W]),
    ]);

  /* ============ MARKET MECHANICS ============ */

  L("c-liquidity", "Liquidity",
    "How easily you can trade without moving the price against yourself.",
    [
      h2("What is this?"),
      p("Liquidity is the ability to buy or sell an asset quickly, in size, near the prevailing price. Cash is perfectly liquid; a small-cap share or a property is not."),
      h2("Why does it matter?"),
      p("An asset's quoted price applies to the size normally traded. A holding worth ₹50 crore on paper in a stock that trades ₹2 crore a day cannot be sold at that price — the act of selling would move it."),
      p("Liquidity also vanishes exactly when it is needed. In stressed markets spreads widen and depth disappears, so the assumption that you can exit fails at the worst time."),
      h2("How does it work?"),
      list([
        "<strong>Bid-ask spread</strong> — the gap between the best buy and sell prices, a direct round-trip cost.",
        "<strong>Depth</strong> — how much can trade at those prices before the price moves.",
        "<strong>Average daily volume</strong> — a rough measure of how long a position takes to exit.",
        "<strong>Market impact</strong> — how much your own trading moves the price against you.",
      ]),
      fig("Real-Life Case Study: exiting a position",
        ["A ₹50 crore holding in a stock trading ₹2 crore a day, assuming you take 20% of daily volume."],
        [["Position value", "₹50 crore"], ["Average daily volume", "₹2 crore"], ["Tradeable per day at 20%", "₹40 lakh"],
         ["Days to exit", "125 trading days"], ["Bid-ask spread", "1.2%"],
         ["Estimated total exit cost", "3-6% of value"]],
        ["Selling this position takes six months and costs several percent — a cost that never appears in any return calculation.",
         "This is why institutions cap position sizes relative to daily volume. A brilliant analysis of an illiquid stock can be undone entirely by the cost of getting in and out."]),
      h2("Key terms"),
      def("Bid-ask spread", "The gap between the highest bid and lowest ask — the cost of immediacy."),
      def("Market impact", "The adverse price move caused by your own trading."),
      def("Depth", "The volume available near the current price."),
      h2("Practice"),
      practice([
        { q: "A ₹30 crore position trades ₹1.5 crore a day. At 20% of volume, how long to exit?", a: "₹30 lakh a day, so 100 trading days — roughly five months, during which the price and your thesis may both change." },
        { q: "Why does liquidity disappear when it is most needed?", a: "In stress, everyone wants to sell simultaneously and market makers widen spreads to protect themselves from adverse selection. Depth falls precisely when volume demand rises, so exit costs spike exactly when exits are wanted." },
      ]),
      h2("Connection"),
      p("Liquidity is a practical constraint on the position sizing that the Level 8 investment case concluded with."),
      mcq("A large position in a thinly traded stock means:",
        ["Higher returns", "The quoted price may not be achievable when selling", "Lower volatility", "No transaction costs"], 1,
        [W, "Correct. The quoted price applies to normal trade sizes; exiting a large holding moves the price against you.", W, W]),
    ]);

  L("c-volatility", "Volatility",
    "How much prices move — a measure of variability, not of direction.",
    [
      h2("What is this?"),
      p("Volatility measures how much a price fluctuates, usually as the annualised standard deviation of returns. An annual volatility of 25% means returns typically fall within about 25 points either side of the average in a given year."),
      h2("Why does it matter?"),
      p("It is finance's standard proxy for risk, and it drives option prices, position sizing and portfolio construction throughout Level 10."),
      p("It is also frequently misunderstood. Volatility measures variability, not loss. A share that rises steeply is volatile; a share that falls slowly and permanently may not be. Confusing the two leads people to treat price fluctuation as the risk rather than permanent capital loss."),
      h2("How does it work?"),
      formula("Volatility", [
        "<b>Volatility = standard deviation of returns</b>",
        "<b>Annualised volatility ≈ daily volatility × √252</b>",
        "<b>Historical</b> volatility looks back; <b>implied</b> volatility is derived from option prices",
      ]),
      p("Volatility clusters: calm periods follow calm periods and turbulent ones follow turbulence. That is why a low-volatility past does not guarantee a low-volatility future."),
      fig("Real-Life Case Study: two paths, same endpoint",
        ["Two shares, both ending the year up 12%."],
        [["Share A — annual volatility", "14%"], ["Share A — worst drawdown", "−9%"],
         ["Share B — annual volatility", "42%"], ["Share B — worst drawdown", "−38%"],
         ["Both — return over the year", "+12%"]],
        ["Identical returns, entirely different experiences. Share B fell 38% along the way.",
         "For a long-term holder who never sells, that difference may not matter. For anyone who might need the money, or who would panic and sell at −38%, it matters enormously — which is why volatility is a real risk even when it is not permanent loss."]),
      h2("Key terms"),
      def("Volatility", "The standard deviation of returns, measuring variability."),
      def("Implied volatility", "The volatility the market's option prices imply for the future."),
      def("Drawdown", "The fall from a peak to a trough — what an investor actually experiences."),
      h2("Practice"),
      practice([
        { q: "Daily volatility is 1.5%. Estimate the annualised figure.", a: "1.5% × √252 = 1.5 × 15.87 = 23.8% annualised." },
        { q: "Why is volatility an imperfect measure of risk?", a: "It treats upside and downside variation identically and says nothing about permanent loss. A stock that rises sharply scores as risky; one that declines steadily to zero may show low volatility throughout. Permanent capital loss is the risk that matters most." },
      ]),
      h2("Connection"),
      p("Volatility is the input to option pricing, the Sharpe ratio and portfolio construction in Level 10."),
      mcq("Volatility measures:",
        ["The probability of loss", "How much returns vary, in both directions", "Expected return", "Credit risk"], 1,
        [W, "Correct. It is a measure of variability. Upside movement counts as volatility just as downside does.", W, W]),
    ]);
})();
