/* Level 5 — Valuation. 27 lessons.
   Same schema and loop as Level 4: intuition → explanation → worked example →
   practice with answers → explained check → connection. One company (Bharat
   Kitchen Appliances, from the capstone) runs through the DCF module so the
   numbers accumulate rather than reset each lesson. */
(function () {
  "use strict";
  var LS = (window.LS = window.LS || {});
  LS.lessons = LS.lessons || {};

  function h2(t) { return { t: "h2", text: t }; }
  function p(h) { return { t: "p", h: h }; }
  function list(i) { return { t: "list", items: i }; }
  function def(term, h) { return { t: "def", term: term, h: h }; }
  function note(i) { return { t: "note", h: "<ul>" + i.map(function (x) { return "<li>" + x + "</li>"; }).join("") + "</ul>" }; }
  function practice(i) { return { t: "practice", items: i }; }
  function sandbox(kind, title, prompt, fields) { return { t: "sandbox", kind: kind, title: title, prompt: prompt, fields: fields }; }
  function formula(title, lines) { return { t: "formula", title: title, lines: lines }; }
  function mcq(q, o, c, w) { return { t: "mcq", q: q, opts: o, correct: c, why: w }; }
  function fig(title, intro, rows, meaning) {
    var h = '<p class="case-title"><strong>' + title + "</strong></p>";
    intro.forEach(function (x) { h += "<p>" + x + "</p>"; });
    h += '<div class="case-figures">';
    rows.forEach(function (r) { h += '<div class="case-row"><span class="case-label">' + r[0] + '</span><span class="case-value">' + r[1] + "</span></div>"; });
    h += '</div><p class="case-meaning"><strong>What it means.</strong></p>';
    meaning.forEach(function (x) { h += "<p>" + x + "</p>"; });
    return { t: "example", h: h };
  }
  function L(id, title, lede, body) {
    LS.lessons[id] = { id: id, title: title, short: title, desc: lede, lede: lede, minutes: 7, body: body };
  }
  var W = "Not quite — re-read the explanation above.";

  /* ============ VALUATION BUILDING BLOCKS ============ */

  L("c-enterprise-value", "Enterprise value",
    "What the operating business is worth, before asking who financed it.",
    [
      h2("What is this?"),
      p("Enterprise value is the value of the business itself — its factories, brands, customers and cash flows — regardless of whether it was funded with debt or equity."),
      p("Think of buying a flat worth ₹1 crore with a ₹60 lakh loan outstanding. The flat is worth ₹1 crore whoever holds the mortgage; your equity in it is ₹40 lakh. Enterprise value is the flat. Equity value is your slice."),
      h2("Why does it matter?"),
      p("Two companies with identical operations but different debt have the same enterprise value and very different market capitalisations. Comparing them on market cap alone would say one is cheaper when nothing about the businesses differs."),
      p("EV is also what an acquirer effectively pays: buy the shares and you inherit the debt, so the real cost is equity plus debt less the cash you get with it."),
      h2("How does it work?"),
      formula("Enterprise value", [
        "<b>EV = Market capitalisation + Debt − Cash</b>",
        "<b>EV = Market capitalisation + Net debt</b>",
        "Equivalently: EV = Equity value + Net debt",
      ]),
      p("Cash is subtracted because it is not part of the operating business — an acquirer gets it back immediately and can use it to repay part of the purchase."),
      fig("Real-Life Case Study: same business, two balance sheets",
        ["Two appliance makers each generate ₹136 crore of EBITDA."],
        [["Firm A — market cap", "₹900 crore"], ["Firm A — debt / cash", "₹280 / ₹40 crore"], ["Firm A — enterprise value", "₹1,140 crore"],
         ["Firm B — market cap", "₹1,100 crore"], ["Firm B — debt / cash", "₹80 / ₹40 crore"], ["Firm B — enterprise value", "₹1,140 crore"]],
        ["Firm B's market cap is 22% higher, yet the two businesses are worth exactly the same.",
         "The entire difference is financing: Firm A's owners hold a smaller slice of the same asset because lenders hold the rest. Judged on market cap, A looks cheap. Judged on EV, they are identical."]),
      h2("Key terms"),
      def("Enterprise value", "The value of the operating business: market cap plus debt less cash."),
      def("Net debt", "Debt less cash — the borrowing burden after offsetting available cash."),
      h2("Practice"),
      practice([
        { q: "Market cap ₹900 crore, debt ₹280 crore, cash ₹40 crore. Compute enterprise value.", a: "EV = 900 + 280 − 40 = ₹1,140 crore." },
        { q: "A company issues ₹100 crore of new debt and holds the proceeds as cash. What happens to enterprise value?", a: "Nothing. Debt rises ₹100 crore and cash rises ₹100 crore, so net debt is unchanged and EV is unchanged. The operating business did not change, which is exactly the property EV is designed to have." },
      ]),
      h2("Connection"),
      p("Every EV-based multiple in this module — EV/Revenue, EV/EBITDA — uses this number, and a DCF calculates it directly from cash flows."),
      mcq("Cash is subtracted when computing enterprise value because:",
        ["It is not real money", "An acquirer receives it and can use it to offset the purchase price", "Cash earns interest", "Accounting rules require it"], 1,
        [W, "Correct. Cash is not part of the operating business; buying the company hands it straight back to you.", W, W]),
    ]);

  L("c-equity-value", "Equity value",
    "The shareholders' slice: what remains of the business after the lenders' claim.",
    [
      h2("What is this?"),
      p("Equity value is what the shareholders' portion of a company is worth. Start with the value of the whole operating business and subtract net debt — because lenders are paid before owners."),
      p("For a listed company, equity value and market capitalisation are the same thing measured two ways: market cap is what the market says it is; equity value is what your analysis says it should be."),
      h2("Why does it matter?"),
      p("This is the number you actually compare with a share price. A valuation that stops at enterprise value has not yet answered whether the shares are worth buying."),
      p("It is also where debt hurts owners. Two companies with identical enterprise values but different net debt deliver very different equity values — the more indebted one leaves less for shareholders."),
      h2("How does it work?"),
      formula("Equity value", [
        "<b>Equity value = Enterprise value − Net debt</b>",
        "<b>Value per share = Equity value ÷ Shares outstanding</b>",
        "Net debt = debt − cash",
      ]),
      fig("Real-Life Case Study: from EV to a share price",
        ["Bharat Kitchen Appliances: EBITDA ₹136 crore, valued at 9× by comparable companies."],
        [["Enterprise value", "₹1,224 crore"], ["Debt", "₹280 crore"], ["Cash", "₹40 crore"], ["Net debt", "₹240 crore"],
         ["Equity value", "₹984 crore"], ["Shares outstanding", "12 crore"], ["Value per share", "₹82"]],
        ["The business is worth ₹1,224 crore; the shareholders' claim on it is ₹984 crore.",
         "If the company repaid ₹100 crore of debt from operating cash, EV would be unchanged but equity value would rise towards ₹1,084 crore — the same business, a larger owner's slice."]),
      h2("Key terms"),
      def("Equity value", "Enterprise value less net debt — the shareholders' claim."),
      def("Value per share", "Equity value divided by shares outstanding, comparable directly with the market price."),
      h2("Practice"),
      practice([
        { q: "EV ₹1,500 crore, debt ₹400 crore, cash ₹60 crore, 20 crore shares. Compute equity value and value per share.", a: "Net debt = ₹340 crore. Equity value = 1,500 − 340 = ₹1,160 crore. Per share = 1,160 ÷ 20 = ₹58." },
        { q: "Two firms both have an EV of ₹1,000 crore. One has ₹500 crore of net debt, the other has none. Which has the higher equity value, and does that make it the better business?", a: "The debt-free one: ₹1,000 crore versus ₹500 crore. It is not a better business — the operations are valued identically. It simply has fewer prior claims, so more of the same value belongs to shareholders." },
      ]),
      h2("Connection"),
      p("Every DCF ends here: discount the cash flows to get EV, subtract net debt, divide by shares, and compare with the market price."),
      mcq("Equity value equals:",
        ["Enterprise value + net debt", "Enterprise value − net debt", "EBITDA × multiple", "Total assets"], 1,
        [W, "Correct. Lenders rank ahead of owners, so their claim comes out of the business's value first.", W, W]),
    ]);

  L("c-market-capitalization", "Market capitalization",
    "The market's price tag on the equity — not on the business.",
    [
      h2("What is this?"),
      p("Market capitalisation is share price multiplied by the number of shares outstanding. It is what the stock market currently says the equity is worth."),
      h2("Why does it matter?"),
      p("It is the most quoted number in investing and the most misused. Market cap values the shareholders' slice only; it says nothing about the debt sitting alongside it. A ₹900 crore market cap on a company with ₹280 crore of debt means the business is being valued near ₹1,140 crore."),
      p("It is also a price, not a value. Market cap tells you what people are paying today; whether that is sensible is what the rest of this level is for."),
      h2("How does it work?"),
      formula("Market capitalisation", [
        "<b>Market cap = Share price × Shares outstanding</b>",
        "<b>EV = Market cap + Net debt</b>",
      ]),
      p("Use shares actually outstanding. Options and convertible instruments can increase the count if exercised — the diluted share count — which lowers value per share."),
      fig("Real-Life Case Study: price is not value",
        ["Two companies quoted on the same exchange."],
        [["Firm X — share price", "₹2,400"], ["Firm X — shares", "2 crore"], ["Firm X — market cap", "₹4,800 crore"],
         ["Firm Y — share price", "₹75"], ["Firm Y — shares", "12 crore"], ["Firm Y — market cap", "₹900 crore"]],
        ["Firm X's share price is 32 times Firm Y's, and its market cap is only about 5 times larger.",
         "Share price alone says nothing about size or value — it depends entirely on how many shares the company chose to issue. Market cap is the comparable figure; enterprise value is the complete one."]),
      h2("Key terms"),
      def("Market capitalisation", "Share price times shares outstanding — the market's valuation of the equity."),
      def("Diluted shares", "Shares outstanding plus those that would exist if options and convertibles were exercised."),
      h2("Practice"),
      practice([
        { q: "Share price ₹75, 12 crore shares, debt ₹280 crore, cash ₹40 crore. Compute market cap and enterprise value.", a: "Market cap = 75 × 12 = ₹900 crore. EV = 900 + 280 − 40 = ₹1,140 crore." },
        { q: "Why is a ₹2,400 share price not evidence that a company is larger or more expensive than one at ₹75?", a: "The price depends on how many shares exist. A company can halve its share price by doubling the share count without changing its value at all. Only market cap, and better still enterprise value, allows a comparison." },
      ]),
      h2("Connection"),
      p("Market cap is the starting point for enterprise value and the denominator input for P/E."),
      mcq("A company's share price doubles after a share split halves the count. Market cap:",
        ["Doubles", "Is unchanged", "Halves", "Becomes zero"], 1,
        [W, "Correct. Price times count is unchanged — which is why the share price alone carries no information about size or value.", W, W]),
    ]);

  L("c-net-debt", "Net debt",
    "Borrowings less the cash that could repay them.",
    [
      h2("What is this?"),
      p("Net debt is total borrowings minus cash and equivalents. A company owing ₹280 crore while holding ₹40 crore of cash carries ₹240 crore of net debt."),
      h2("Why does it matter?"),
      p("It is the bridge between enterprise value and equity value, so every valuation passes through it. It is also the honest measure of indebtedness: gross debt overstates the burden of a company sitting on a large cash pile."),
      h2("How does it work?"),
      formula("Net debt", [
        "<b>Net debt = Total debt − Cash and equivalents</b>",
        "Total debt includes short-term borrowings, long-term debt and lease liabilities",
        "<b>Equity value = EV − Net debt</b>",
      ]),
      p("Include all debt-like obligations: the current portion of long-term debt, overdrafts and lease liabilities. Excluding them understates the claim ranking ahead of shareholders."),
      fig("Real-Life Case Study: what counts",
        ["An analyst assembles net debt from the balance sheet."],
        [["Long-term borrowings", "₹210 crore"], ["Current portion of long-term debt", "₹40 crore"], ["Short-term working capital loan", "₹30 crore"],
         ["Lease liabilities", "₹35 crore"], ["Total debt", "₹315 crore"], ["Less cash", "−₹40 crore"], ["Net debt", "₹275 crore"]],
        ["Taking only the ₹210 crore of long-term borrowings would have understated net debt by ₹65 crore.",
         "At 12 crore shares, that error alone moves value per share by more than ₹5 — on a stock trading at ₹75, a 7% mistake from one omitted line."]),
      h2("Key terms"),
      def("Net debt", "Total debt less cash — the borrowing burden after offsetting available cash."),
      def("Debt-like items", "Obligations that behave as debt, including leases and the current portion of long-term borrowings."),
      h2("Practice"),
      practice([
        { q: "Long-term debt ₹180 crore, current portion ₹35 crore, leases ₹25 crore, cash ₹55 crore. Compute net debt.", a: "Total debt = 180 + 35 + 25 = ₹240 crore. Net debt = 240 − 55 = ₹185 crore." },
        { q: "A company holds cash equal to its debt. What is its net debt, and does that make it risk-free?", a: "Net debt is zero. It is not risk-free: the cash may be needed for operations or committed elsewhere, and the interest on the debt is still payable while the cash earns less. Zero net debt is a strong position, not an absence of obligation." },
      ]),
      h2("Connection"),
      p("Net debt converts every enterprise value in this module into an equity value, and it drives the leverage ratio from Level 3."),
      mcq("Which should be included in net debt?",
        ["Trade payables", "Lease liabilities and the current portion of long-term debt", "Accrued salaries", "Deferred revenue"], 1,
        [W, "Correct. Debt-like obligations that must be serviced and repaid belong in net debt; ordinary operating liabilities do not.", W, W]),
    ]);

  L("c-ev-revenue", "EV/Revenue",
    "The multiple you use when a company has no profit yet.",
    [
      h2("What is this?"),
      p("EV/Revenue divides enterprise value by annual revenue. It says how many rupees of business value the market assigns per rupee of sales."),
      h2("Why does it matter?"),
      p("Some companies have no earnings to divide by — early-stage software, biotech, a business in a loss-making expansion phase. Revenue is the only reliable denominator available, so this multiple is what remains."),
      p("Its weakness is severe: it ignores profitability entirely. A business earning 40% margins and one losing money on every sale can show the same EV/Revenue, and one of them is worth far more."),
      h2("How does it work?"),
      formula("EV/Revenue", [
        "<b>EV/Revenue = Enterprise value ÷ Revenue</b>",
        "Only comparable between companies with similar margins and growth",
      ]),
      p("The multiple is only meaningful alongside a margin assumption. A firm at 2× revenue with 30% EBITDA margins is cheaper than one at 2× revenue with 8% margins — the first converts far more of each sale into value."),
      fig("Real-Life Case Study: margin decides",
        ["Two software businesses, each with ₹200 crore of revenue and an EV of ₹800 crore."],
        [["Both — EV/Revenue", "4.0x"], ["Firm P — EBITDA margin", "35%"], ["Firm P — implied EV/EBITDA", "11.4x"],
         ["Firm Q — EBITDA margin", "12%"], ["Firm Q — implied EV/EBITDA", "33.3x"]],
        ["On revenue they are identically priced. On earnings, Firm Q is nearly three times as expensive.",
         "EV/Revenue hid the entire difference. Use it when there is no alternative, and always state the margin assumption that makes it meaningful."]),
      h2("Key terms"),
      def("EV/Revenue", "Enterprise value divided by revenue — a multiple usable when earnings are negative."),
      def("Implied multiple", "Converting one multiple to another using the margin, to check comparability."),
      h2("Practice"),
      practice([
        { q: "EV ₹1,140 crore, revenue ₹800 crore. Compute EV/Revenue, and the implied EV/EBITDA at a 17% margin.", a: "EV/Revenue = 1,140 ÷ 800 = 1.43x. EBITDA = 17% × 800 = ₹136 crore, so EV/EBITDA = 1,140 ÷ 136 = 8.4x." },
        { q: "Why can EV/Revenue mislead when comparing a distributor with a software firm?", a: "Their margins are structurally different — a distributor may convert 3% of revenue into EBITDA and the software firm 35%. The same revenue multiple therefore represents completely different earnings multiples, so the comparison is meaningless without adjusting for margin." },
      ]),
      h2("Connection"),
      p("This is the crudest of the multiples; EV/EBITDA next adds profitability, and a DCF later removes the reliance on comparables altogether."),
      mcq("EV/Revenue is most defensible when:",
        ["Comparing companies with very different margins", "A company has negative earnings and no usable earnings multiple", "You want the most precise valuation", "Debt is zero"], 1,
        [W, "Correct. It is a fallback when earnings cannot serve as a denominator — never a first choice.", W, W]),
    ]);

  L("c-ev-ebitda", "EV/EBITDA",
    "The workhorse multiple: business value against operating earnings.",
    [
      h2("What is this?"),
      p("EV/EBITDA divides enterprise value by EBITDA. Both terms exclude financing, so the multiple compares operating businesses without their debt structures getting in the way."),
      p("A 9× multiple means the market values the business at nine years of current operating earnings, ignoring interest, tax and depreciation."),
      h2("Why does it matter?"),
      p("It is the most widely used multiple in transactions and credit analysis precisely because of that consistency: EV includes the debt, EBITDA is measured before interest, so numerator and denominator agree about capital structure."),
      p("Its blind spot is capital intensity. EBITDA ignores the cost of replacing machinery, so a capital-heavy business at 9× is materially more expensive than an asset-light one at the same multiple."),
      h2("How does it work?"),
      formula("EV/EBITDA", [
        "<b>EV/EBITDA = Enterprise value ÷ EBITDA</b>",
        "<b>Implied EV = EBITDA × Multiple</b>",
        "<b>Equity value = Implied EV − Net debt</b>",
      ]),
      list([
        "Pick the multiple from genuinely comparable companies — same industry, similar growth and margins.",
        "Multiply by the company's EBITDA to get implied enterprise value.",
        "Subtract net debt for equity value, then divide by shares.",
      ]),
      fig("Real-Life Case Study: valuing on comparables",
        ["Bharat Kitchen Appliances: EBITDA ₹136 crore, net debt ₹240 crore, 12 crore shares. Peers trade at 8-10×."],
        [["At 8× — EV", "₹1,088 crore"], ["At 8× — value per share", "₹71"], ["At 9× — EV", "₹1,224 crore"],
         ["At 9× — value per share", "₹82"], ["At 10× — value per share", "₹93"], ["Market price", "₹75"]],
        ["A two-turn range in the multiple moves value per share from ₹71 to ₹93 — the market price sits inside it.",
         "That is the honest output: the shares are neither clearly cheap nor clearly expensive until you can defend a specific multiple, which is why the comparable set matters more than the arithmetic."]),
      h2("Key terms"),
      def("EV/EBITDA", "Enterprise value divided by EBITDA — the standard multiple for comparing operating businesses."),
      def("Comparable set", "The peer companies whose multiples justify the one you apply."),
      def("Turn", "One unit of a multiple. Moving from 8× to 9× is 'one turn'."),
      h2("Practice"),
      practice([
        { q: "EBITDA ₹90 crore, multiple 7.5×, net debt ₹150 crore, 15 crore shares. Compute value per share.", a: "EV = 90 × 7.5 = ₹675 crore. Equity value = 675 − 150 = ₹525 crore. Per share = 525 ÷ 15 = ₹35." },
        { q: "Why is a capital-intensive business at 9× EV/EBITDA more expensive than an asset-light one at 9×?", a: "EBITDA adds back depreciation, but the capital-heavy business must actually spend that money replacing assets. Its free cash flow is far lower for the same EBITDA, so the same multiple buys much less real cash." },
      ]),
      h2("Connection"),
      p("This multiple reappears as the exit multiple in terminal value, and as the cross-check on any DCF answer."),
      sandbox("profit-bridge", "EBITDA base sandbox",
        "Adjust revenue and costs to see the EBITDA a multiple would be applied to — the valuation rests entirely on this figure.", [
        { key: "revenue", label: "Revenue", value: 8000000000, unit: "₹" },
        { key: "cogs", label: "Cost of goods sold", value: 4800000000, unit: "₹" },
        { key: "opex", label: "Operating costs excl. D&A", value: 1840000000, unit: "₹" },
        { key: "interest", label: "Interest", value: 280000000, unit: "₹" },
        { key: "taxRate", label: "Tax rate", value: 25, unit: "%" },
      ]),
      mcq("EV/EBITDA is consistent because:",
        ["Both terms are audited", "Both are measured before the effects of financing", "EBITDA equals cash flow", "It ignores revenue"], 1,
        [W, "Correct. EV includes debt and EBITDA sits above interest, so numerator and denominator treat capital structure the same way.", W, W]),
    ]);

  L("c-p-e", "P/E",
    "Price against earnings — the most quoted multiple, and the easiest to misread.",
    [
      h2("What is this?"),
      p("The price-to-earnings ratio divides the share price by earnings per share, or equivalently market capitalisation by net profit. A P/E of 15 means investors pay ₹15 for every ₹1 of annual earnings."),
      h2("Why does it matter?"),
      p("It is the fastest read on how much optimism is priced in. But unlike EV multiples, P/E is an equity measure — net profit is after interest — so it is distorted by leverage. A company that borrows heavily shows lower earnings and a different P/E for reasons unrelated to the business."),
      p("It is also distorted by tax positions and one-off items, both of which move net profit without changing operations."),
      h2("How does it work?"),
      formula("Price-to-earnings", [
        "<b>P/E = Share price ÷ Earnings per share</b>",
        "<b>P/E = Market capitalisation ÷ Net profit</b>",
        "<b>Earnings yield = 1 ÷ P/E</b>",
      ]),
      p("A high P/E is not the same as expensive. It means the market expects earnings to grow; whether that expectation is reasonable is the actual question."),
      fig("Real-Life Case Study: high P/E, cheap stock",
        ["Two companies, both priced at ₹100 a share."],
        [["Firm R — EPS today", "₹10"], ["Firm R — P/E", "10x"], ["Firm R — EPS in 3 years", "₹11"],
         ["Firm S — EPS today", "₹4"], ["Firm S — P/E", "25x"], ["Firm S — EPS in 3 years", "₹14"], ["Firm S — P/E on year-3 earnings", "7.1x"]],
        ["Firm S looks 2.5 times more expensive today and is cheaper on the earnings it will actually produce.",
         "This is why 'low P/E means cheap' fails. The ratio compares today's price with today's earnings; the value of a business depends on all its future earnings."]),
      h2("Key terms"),
      def("P/E", "Share price divided by earnings per share."),
      def("Earnings yield", "The inverse of P/E — earnings as a percentage of price."),
      def("Forward P/E", "Price divided by expected future earnings rather than reported ones."),
      h2("Practice"),
      practice([
        { q: "Share price ₹75, net profit ₹54 crore, 12 crore shares. Compute EPS and P/E.", a: "EPS = 54 ÷ 12 = ₹4.50. P/E = 75 ÷ 4.50 = 16.7x." },
        { q: "Why can a company with a 25× P/E be cheaper than one at 10×?", a: "If the 25× company's earnings grow rapidly, its P/E on future earnings falls quickly, while a company with flat earnings stays at 10× forever. Price reflects all future earnings, so today's ratio only makes sense alongside a growth expectation." },
      ]),
      h2("Connection"),
      p("PEG next adjusts P/E for growth, and the DCF module replaces the comparison with an explicit forecast of the earnings a P/E is silently assuming."),
      mcq("A high P/E indicates:",
        ["The stock is definitely expensive", "The market expects earnings growth — whether it is right is a separate question", "The company has no debt", "Earnings are negative"], 1,
        [W, "Correct. P/E prices expectations. Judging it requires forming your own view of the growth those expectations assume.", W, W]),
    ]);

  L("c-peg", "PEG",
    "P/E divided by growth — a rough correction for the ratio's biggest flaw.",
    [
      h2("What is this?"),
      p("The PEG ratio divides the P/E by the expected earnings growth rate in percentage points. A company on a 24× P/E growing 24% a year has a PEG of 1.0."),
      p("The rule of thumb is that a PEG around 1 is fair, below 1 is potentially cheap, and well above 1 means you are paying a lot for the growth. Treat it as a screening heuristic, not a valuation."),
      h2("Why does it matter?"),
      p("It addresses the exact problem in the previous lesson: P/E punishes fast-growing companies for having small current earnings. PEG makes a 30× grower and a 10× stagnant business roughly comparable."),
      h2("How does it work?"),
      formula("PEG ratio", [
        "<b>PEG = P/E ÷ Expected earnings growth rate (%)</b>",
        "A 20x P/E with 20% growth gives a PEG of 1.0",
      ]),
      p("Two cautions. The growth rate is a forecast, so PEG inherits all the uncertainty of that forecast. And it ignores risk entirely — two companies growing 20% are not equivalent if one's growth is contracted and the other's is speculative."),
      fig("Real-Life Case Study: PEG in use",
        ["Three companies screened on P/E alone would rank in one order, and on PEG in another."],
        [["Firm T — P/E 12x, growth 6%", "PEG 2.0"], ["Firm U — P/E 22x, growth 25%", "PEG 0.88"], ["Firm V — P/E 30x, growth 12%", "PEG 2.5"]],
        ["On P/E, Firm T looks cheapest. On PEG, it is the second most expensive — its low price reflects almost no growth.",
         "Firm U's higher P/E buys far more growth per rupee. That said, all three PEGs rest on forecast growth rates, and Firm U's 25% is the least certain of the three."]),
      h2("Key terms"),
      def("PEG ratio", "P/E divided by the expected percentage earnings growth rate."),
      def("Growth at a reasonable price", "The investing style PEG is associated with — paying up for growth, but not unlimited amounts."),
      h2("Practice"),
      practice([
        { q: "P/E 28x, expected growth 20%. Compute PEG and interpret it.", a: "PEG = 28 ÷ 20 = 1.4. Above 1, so you are paying somewhat more than one unit of price per unit of growth — reasonable if the growth is durable and low-risk, expensive if it is speculative." },
        { q: "Name the two things PEG ignores that could make a low-PEG stock a poor investment.", a: "Risk — the growth may be far less certain than a competitor's — and durability, since PEG uses a single growth number and says nothing about whether it lasts three years or ten. A low PEG on fragile growth is not a bargain." },
      ]),
      h2("Connection"),
      p("PEG is a shortcut for what a DCF does properly: valuing growth explicitly, year by year, with a discount rate that reflects its risk."),
      mcq("A PEG ratio of 0.7 suggests:",
        ["The company is unprofitable", "The price is low relative to expected growth — worth investigating", "Growth is negative", "The stock is definitely a bargain"], 1,
        [W, "Correct. It is a screening signal that the growth may be underpriced, subject to whether the forecast growth is credible and its risk acceptable.", W, W]),
    ]);

  /* ============ DCF ============ */

  L("c-risk-free-rate", "Risk-free rate",
    "The return you can earn without taking credit risk — the floor under every other return.",
    [
      h2("What is this?"),
      p("The risk-free rate is the return available on an asset with essentially no default risk, normally a long-dated government bond in the currency of the cash flows being valued."),
      h2("Why does it matter?"),
      p("It is the base of every required return. If a government bond pays 7%, no rational investor accepts less than 7% for a risky business — so every discount rate starts here and adds premiums for the risks taken on top."),
      p("It also explains why valuations move when interest rates do. A rise in the risk-free rate lifts every required return, which lowers the present value of every future cash flow — with no change in any company's operations."),
      h2("How does it work?"),
      list([
        "Match the currency: value rupee cash flows against a rupee government bond.",
        "Match the horizon: a long-lived business is usually valued against a 10-year government bond.",
        "Use the current yield, not a historical average — it is the return available today.",
      ]),
      p("Government bonds are described as risk-free of <em>default</em>, not free of all risk: their prices still move with interest rates, and inflation still erodes their real return."),
      fig("Real-Life Case Study: rates move valuations",
        ["The same company valued at two different points in the rate cycle."],
        [["Risk-free rate", "7.0% → 8.5%"], ["Equity risk premium", "5.5% (unchanged)"], ["Cost of equity", "12.5% → 14.0%"],
         ["WACC", "11.0% → 12.2%"], ["Enterprise value", "₹1,224 → ₹1,050 crore"], ["Change", "−14%"]],
        ["Nothing about the business changed. A 1.5-point rise in the risk-free rate removed 14% of its value.",
         "This is the mechanism behind market-wide falls when central banks raise rates: every discount rate rises together, so every valuation falls together."]),
      h2("Key terms"),
      def("Risk-free rate", "The yield on a default-free government bond in the relevant currency and horizon."),
      def("Yield", "The annual return an investor earns holding a bond to maturity at the current price."),
      h2("Practice"),
      practice([
        { q: "You are valuing an Indian company's rupee cash flows over 10 years. Which risk-free rate should you use and why?", a: "The current yield on a 10-year Indian government bond. It matches the currency of the cash flows and their horizon — using a US Treasury yield would mix currencies and embed a different inflation expectation." },
        { q: "The risk-free rate rises 1 point with no change to the business. What happens to its valuation, and why?", a: "It falls. Every required return rises by roughly that point, so future cash flows are discounted more heavily and their present value drops. Operations are unchanged; the price of waiting has gone up." },
      ]),
      h2("Connection"),
      p("This is the first term in CAPM and therefore in the cost of equity, WACC and the DCF that follows."),
      mcq("Government bonds are called risk-free because:",
        ["Their prices never change", "Default risk is negligible, though rate and inflation risk remain", "They beat inflation", "They are insured"], 1,
        [W, "Correct. 'Risk-free' means free of default risk specifically — the price still moves with interest rates.", W, W]),
    ]);

  L("c-equity-risk-premium", "Equity risk premium",
    "The extra return investors demand for owning shares instead of government bonds.",
    [
      h2("What is this?"),
      p("The equity risk premium is the additional expected return over the risk-free rate that investors require to hold equities. If bonds yield 7% and investors need 12.5% from a diversified basket of shares, the premium is 5.5 points."),
      h2("Why does it matter?"),
      p("It quantifies the price of equity risk for a whole market and is one of only two inputs to CAPM. Move it a point and every valuation in the market moves several percent."),
      p("It is also unobservable. Nobody publishes the premium investors require; it is estimated from long-run historical returns or implied from current market prices, and reasonable analysts disagree by a point or more."),
      h2("How does it work?"),
      formula("Equity risk premium", [
        "<b>ERP = Expected market return − Risk-free rate</b>",
        "<b>Cost of equity = Risk-free rate + Beta × ERP</b>",
      ]),
      list([
        "<strong>Historical approach:</strong> average the excess of equity returns over bonds across many decades.",
        "<strong>Implied approach:</strong> solve for the return that current market prices and expected cash flows imply.",
        "Emerging markets typically carry a higher premium than developed ones, reflecting greater volatility and country risk.",
      ]),
      fig("Real-Life Case Study: a one-point disagreement",
        ["Two analysts value the same company, differing only on the premium."],
        [["Risk-free rate", "7.0%"], ["Analyst A — ERP", "5.0%"], ["Analyst A — cost of equity (beta 1.1)", "12.5%"],
         ["Analyst B — ERP", "6.5%"], ["Analyst B — cost of equity (beta 1.1)", "14.2%"], ["Difference in value", "≈18%"]],
        ["A disagreement about a number neither can observe moves the valuation by nearly a fifth.",
         "This is why serious valuations present a range and disclose the premium used, rather than a single figure implying precision the input cannot support."]),
      h2("Key terms"),
      def("Equity risk premium", "The extra expected return required for holding equities over government bonds."),
      def("Implied premium", "The premium backed out of current market prices rather than history."),
      h2("Practice"),
      practice([
        { q: "Risk-free rate 7%, expected market return 13%. Compute the equity risk premium and the cost of equity for a beta of 0.9.", a: "ERP = 13 − 7 = 6%. Cost of equity = 7 + 0.9 × 6 = 12.4%." },
        { q: "Why do two competent analysts arrive at different equity risk premiums?", a: "It cannot be observed. One may average historical excess returns over a long period, another may imply it from today's prices, and the choice of period, index and method each shift the answer. Both are estimates of an expectation nobody publishes." },
      ]),
      h2("Connection"),
      p("The premium is the second input to CAPM, which produces the cost of equity used in WACC."),
      mcq("The equity risk premium is:",
        ["Published daily by the exchange", "An estimate of the extra return investors require for equity risk", "Always exactly 5%", "The dividend yield"], 1,
        [W, "Correct. It is estimated from history or implied from prices — never directly observed, which is why valuations should show a range.", W, W]),
    ]);

  L("c-beta", "Beta",
    "How much a share moves when the whole market moves.",
    [
      h2("What is this?"),
      p("Beta measures a share's sensitivity to market movements. A beta of 1.0 means the share has historically moved roughly in line with the market; 1.5 means it tends to move half again as much in both directions; 0.6 means it moves less."),
      h2("Why does it matter?"),
      p("In CAPM, beta scales the equity risk premium for the specific company. A cyclical steel producer with a beta of 1.4 demands more return than a utility at 0.6, because its returns swing more with the economy."),
      p("Note carefully what beta measures: sensitivity to market-wide moves, not total risk. A company facing a large company-specific risk — a single customer, a pending lawsuit — can still show a low beta, because that risk is not correlated with the market."),
      h2("How does it work?"),
      formula("Beta in CAPM", [
        "<b>Cost of equity = Risk-free rate + Beta × Equity risk premium</b>",
        "Beta = 1.0 moves with the market; > 1.0 amplifies; < 1.0 dampens",
      ]),
      list([
        "Beta is estimated by regressing the share's returns against the market index over several years.",
        "It reflects both business risk and financial leverage — more debt raises beta mechanically.",
        "For unlisted companies, analysts take peer betas, strip out their leverage, and re-apply the target's own.",
      ]),
      fig("Real-Life Case Study: beta and required return",
        ["Risk-free rate 7%, equity risk premium 5.5%."],
        [["Utility — beta 0.6", "Cost of equity 10.3%"], ["Appliance maker — beta 1.1", "Cost of equity 13.1%"],
         ["Cyclical commodity — beta 1.6", "Cost of equity 15.8%"], ["Value of ₹100 in 10 years at each rate", "₹37 / ₹29 / ₹23"]],
        ["The same ₹100 arriving in ten years is worth ₹37 to the utility's investors and ₹23 to the commodity producer's.",
         "Beta is not an abstraction: it decides how heavily distant cash flows are discounted, and therefore how much a growth-heavy business is worth."]),
      h2("Key terms"),
      def("Beta", "Sensitivity of a share's returns to market returns."),
      def("Systematic risk", "Market-wide risk that diversification cannot remove — the risk beta measures."),
      def("Unlevered beta", "Beta with the effect of debt removed, so business risk can be compared across companies."),
      h2("Practice"),
      practice([
        { q: "Risk-free 7%, ERP 5.5%, beta 1.3. Compute the cost of equity.", a: "7 + 1.3 × 5.5 = 7 + 7.15 = 14.15%." },
        { q: "A company's only customer might not renew its contract, yet its beta is 0.7. Is it low risk?", a: "Not in total. Beta only captures co-movement with the market, and customer concentration is company-specific risk, which is diversifiable in a portfolio and therefore not priced by CAPM. For a concentrated holder it is a very real risk that beta will not show." },
      ]),
      h2("Connection"),
      p("Beta is the company-specific term in CAPM, which produces the cost of equity feeding WACC."),
      mcq("A beta of 1.4 means the share has historically:",
        ["Returned 40% a year", "Moved about 40% more than the market in both directions", "No risk", "Paid a higher dividend"], 1,
        [W, "Correct. Beta scales market movements — amplified upside and amplified downside alike.", W, W]),
    ]);

  L("c-capm", "CAPM",
    "One line that turns risk into a required return.",
    [
      h2("What is this?"),
      p("The Capital Asset Pricing Model states that the return investors require from a share equals the risk-free rate plus beta times the equity risk premium."),
      p("The logic is simple. Start with what you could earn risk-free. Add compensation for equity risk in general. Scale that compensation by how much this particular share amplifies market movements."),
      h2("Why does it matter?"),
      p("It is the standard way to get a cost of equity, which is the largest component of WACC and therefore of every DCF. Its assumptions are contested, but it remains the common language: when someone says a company's cost of equity is 13%, this is almost always where the number came from."),
      h2("How does it work?"),
      formula("Capital Asset Pricing Model", [
        "<b>Cost of equity = Rf + β × (Rm − Rf)</b>",
        "Rf = risk-free rate",
        "β = beta, sensitivity to market movements",
        "(Rm − Rf) = equity risk premium",
      ]),
      p("CAPM prices only systematic risk, on the assumption that investors hold diversified portfolios and can eliminate company-specific risk for free. That assumption is why a concentrated owner should not treat CAPM's answer as their own required return."),
      fig("Real-Life Case Study: building the cost of equity",
        ["Bharat Kitchen Appliances, an appliance maker with moderate cyclicality."],
        [["Risk-free rate (10-year G-sec)", "7.0%"], ["Equity risk premium", "5.5%"], ["Beta", "1.1"],
         ["Beta × ERP", "6.05%"], ["Cost of equity", "13.05%"], ["Sanity check vs market", "reasonable for the sector"]],
        ["Shareholders require about 13% a year. Anything the company earns above that on their money creates value; anything below destroys it.",
         "Notice how few inputs there are — three — and how much rests on two of them being estimates. The precision of '13.05%' is not real; 'around 13%' is the honest statement."]),
      h2("Key terms"),
      def("CAPM", "A model giving required return as risk-free rate plus beta times the equity risk premium."),
      def("Cost of equity", "The return shareholders require for holding the company's shares."),
      def("Diversifiable risk", "Company-specific risk that CAPM assumes investors eliminate and therefore does not price."),
      h2("Practice"),
      practice([
        { q: "Risk-free 6.8%, ERP 6.0%, beta 0.85. Compute the cost of equity.", a: "6.8 + 0.85 × 6.0 = 6.8 + 5.1 = 11.9%." },
        { q: "A founder holds 90% of their wealth in one company's shares. Why is CAPM's cost of equity too low for them?", a: "CAPM assumes the holder is diversified and so prices only market risk. The founder bears the full company-specific risk too — a failed product ruins them, not just a portfolio line — so their genuine required return is higher than the model's." },
      ]),
      h2("Connection"),
      p("CAPM's output is the cost of equity, which combines with the cost of debt in WACC to produce the DCF discount rate."),
      mcq("CAPM prices:",
        ["All risk a company faces", "Only systematic, market-related risk", "Only company-specific risk", "Accounting risk"], 1,
        [W, "Correct. It assumes company-specific risk is diversified away, so only co-movement with the market earns a premium.", W, W]),
    ]);

  L("c-cost-of-equity", "Cost of equity",
    "The return shareholders require — the most expensive money a company uses.",
    [
      h2("What is this?"),
      p("The cost of equity is the annual return shareholders expect for putting money into the business and bearing its risk. Nobody sends an invoice for it, which is exactly why it gets ignored."),
      h2("Why does it matter?"),
      p("Equity feels free because there is no interest and no repayment date. It is not: shareholders could have invested elsewhere at similar risk, and if the company earns less than that, they lose by holding it even while the company reports a profit."),
      p("It is also the largest input to WACC in most companies, because equity is usually the biggest share of the capital and the most expensive part of it."),
      h2("How does it work?"),
      formula("Cost of equity", [
        "<b>Cost of equity = Rf + β × ERP</b> (CAPM)",
        "Cross-check: <b>Earnings yield = 1 ÷ P/E</b>, and dividend yield + growth",
      ]),
      p("Equity costs more than debt for a structural reason: lenders are paid first and their return is fixed, so they bear less risk. Shareholders are paid last, receive whatever remains, and demand more for that position."),
      fig("Real-Life Case Study: the invisible cost",
        ["A company earns ₹54 crore on ₹300 crore of shareholders' equity."],
        [["Return on equity", "18.0%"], ["Cost of equity (CAPM)", "13.1%"], ["Spread", "+4.9 points"],
         ["Value created on ₹300 crore", "≈₹14.7 crore/year"], ["If ROE were 11%", "−₹6.3 crore/year"]],
        ["At 18% the company creates roughly ₹14.7 crore of value a year above what shareholders required.",
         "At 11% it would report a healthy-looking ₹33 crore profit while destroying ₹6.3 crore of value annually. Profit alone cannot tell you which case you are in — only comparison with the cost of equity can."]),
      h2("Key terms"),
      def("Cost of equity", "The return shareholders require, given the risk of the business."),
      def("Opportunity cost of capital", "What investors could earn elsewhere at comparable risk — the source of the requirement."),
      h2("Practice"),
      practice([
        { q: "Cost of equity 13%, equity ₹500 crore, net profit ₹52 crore. Is value being created?", a: "ROE = 52 ÷ 500 = 10.4%, against a 13% requirement. The company is destroying about 2.6% × 500 = ₹13 crore of value a year despite reporting a profit." },
        { q: "Why is equity more expensive than debt for the same company?", a: "Lenders rank ahead and receive a contractual return, so they take less risk. Shareholders are paid last and only from what remains, so they require a higher expected return to accept that position." },
      ]),
      h2("Connection"),
      p("This is the equity leg of WACC, and the hurdle that ROE from Level 3 has to clear."),
      sandbox("leverage-returns", "Return versus requirement sandbox",
        "Compare the owner return produced by the business with the ~13% shareholders require. Below it, profit is still value destruction.", [
        { key: "operatingProfit", label: "Operating profit", value: 1000000000, unit: "₹" },
        { key: "debt", label: "Debt", value: 2800000000, unit: "₹" },
        { key: "interestRate", label: "Interest rate", value: 10, unit: "%" },
        { key: "equity", label: "Equity", value: 3000000000, unit: "₹" },
      ]),
      mcq("Equity has no interest payments, so its cost is:",
        ["Zero", "Real but implicit — the return shareholders require", "Equal to the tax rate", "Lower than debt"], 1,
        [W, "Correct. The cost is an opportunity cost. It never appears on the income statement, which is why value destruction can hide behind reported profit.", W, W]),
    ]);

  L("c-cost-of-debt", "Cost of debt",
    "What borrowing actually costs after the tax deduction.",
    [
      h2("What is this?"),
      p("The cost of debt is the interest rate a company pays on its borrowings. What matters in valuation is the <strong>after-tax</strong> cost, because interest is deductible against taxable profit."),
      h2("Why does it matter?"),
      p("The deduction makes debt materially cheaper than its headline rate. At 10% interest and a 25% tax rate, the company effectively pays 7.5% — the government absorbs a quarter of the cost."),
      p("This tax shield is a genuine advantage of debt and one reason companies borrow at all. It is not unlimited: it only helps while there are profits to shield, and more debt raises the risk of financial distress."),
      h2("How does it work?"),
      formula("After-tax cost of debt", [
        "<b>After-tax cost of debt = Interest rate × (1 − Tax rate)</b>",
        "Interest rate = the marginal rate on new borrowing, not the historical average",
      ]),
      p("Use the rate the company would pay to borrow today, not the average rate on old loans. Valuation is forward-looking, and an old cheap loan does not tell you what new capital costs."),
      fig("Real-Life Case Study: the tax shield",
        ["A company borrows ₹280 crore at 10%, with a 25% tax rate."],
        [["Interest expense", "₹28 crore"], ["Tax saved on that interest", "₹7 crore"], ["Net cost of borrowing", "₹21 crore"],
         ["Headline rate", "10.0%"], ["After-tax rate", "7.5%"], ["Cost of equity, for comparison", "13.1%"]],
        ["The borrowing costs 7.5% after tax, against 13.1% for equity — debt is much the cheaper source.",
         "That is not a reason to maximise it. The interest is owed regardless of results, so cheap capital that must be serviced in a bad year is how solvent companies fail."]),
      h2("Key terms"),
      def("After-tax cost of debt", "Interest rate multiplied by one minus the tax rate."),
      def("Tax shield", "The tax saved because interest is deductible."),
      def("Marginal borrowing rate", "The rate the company would pay on new debt today."),
      h2("Practice"),
      practice([
        { q: "A company borrows at 11% with a 25% tax rate. Compute the after-tax cost of debt.", a: "11% × (1 − 0.25) = 8.25%." },
        { q: "A loss-making company borrows at 11%. What is its effective after-tax cost, and why?", a: "Close to the full 11%. With no taxable profit there is nothing to shield, so the deduction has no immediate value. The tax advantage of debt only exists when there are profits to deduct against." },
      ]),
      h2("Connection"),
      p("This is the debt leg of WACC; the tax shield is why WACC falls as modest leverage is added."),
      mcq("The after-tax cost of debt is lower than the interest rate because:",
        ["Lenders offer discounts", "Interest is deductible, so tax savings offset part of the cost", "Debt is repaid slowly", "Inflation reduces it"], 1,
        [W, "Correct. The deduction transfers part of the interest cost to the tax authority, but only while the company has profits to shield.", W, W]),
    ]);

  L("c-wacc", "WACC",
    "The blended cost of all the money a business uses — and the hurdle every project must clear.",
    [
      h2("What is this?"),
      p("The weighted average cost of capital is the blended rate a company pays for its funding: the cost of equity and the after-tax cost of debt, each weighted by their share of total capital."),
      p("If a business is 70% equity at 13.1% and 30% debt at 7.5% after tax, its WACC is 0.7 × 13.1 + 0.3 × 7.5 = 11.4%. That is the return the business must earn just to satisfy everyone who funded it."),
      h2("Why does it matter?"),
      p("WACC is the discount rate in a DCF, so it determines the value of every future cash flow. It is also the hurdle rate for investment decisions: a project earning above WACC creates value, one earning below it destroys value however profitable it looks."),
      p("Because it sits in the denominator of every discounted year, small errors compound. A one-point WACC error can move a valuation more than a two-point revenue growth error."),
      h2("How does it work?"),
      formula("Weighted average cost of capital", [
        "<b>WACC = (E ÷ V) × Re + (D ÷ V) × Rd × (1 − t)</b>",
        "E = market value of equity, D = market value of debt, V = E + D",
        "Re = cost of equity (from CAPM), Rd = pre-tax cost of debt, t = tax rate",
      ]),
      list([
        "Weight by <strong>market</strong> values, not book values — you are pricing capital as it stands today.",
        "Use the marginal cost of each source, not historical averages.",
        "Modest leverage lowers WACC because debt is cheaper after tax; heavy leverage raises it again as distress risk lifts both costs.",
      ]),
      fig("Real-Life Case Study: computing and using WACC",
        ["Bharat Kitchen Appliances: market cap ₹900 crore, debt ₹280 crore, cost of equity 13.05%, cost of debt 10%, tax 25%."],
        [["Total capital (V)", "₹1,180 crore"], ["Equity weight", "76.3%"], ["Debt weight", "23.7%"],
         ["After-tax cost of debt", "7.5%"], ["Equity contribution", "9.96%"], ["Debt contribution", "1.78%"], ["WACC", "11.7%"]],
        ["The business must earn 11.7% on its capital just to break even against what its funders require.",
         "Its ROIC was 13.9%, so it clears the hurdle by about 2 points. That thin spread is the whole investment case — and a one-point rise in WACC would nearly eliminate it."]),
      h2("Key terms"),
      def("WACC", "The blended, weighted cost of a company's debt and equity funding."),
      def("Hurdle rate", "The minimum return a project must earn to be worth doing — usually WACC or higher."),
      def("Market value weights", "Weighting each capital source by its current market value rather than book value."),
      h2("Practice"),
      practice([
        { q: "Equity ₹600 crore at 14%, debt ₹400 crore at 9% pre-tax, tax 25%. Compute WACC.", a: "V = ₹1,000 crore. Equity weight 60%, debt weight 40%. After-tax debt = 9 × 0.75 = 6.75%. WACC = 0.6 × 14 + 0.4 × 6.75 = 8.4 + 2.7 = 11.1%." },
        { q: "A project is forecast to return 10.5%. The company's WACC is 11.7%. Should it proceed, and why?", a: "No. The project earns less than the capital funding it costs, so each rupee invested destroys about 1.2 paise of value a year. It will still increase reported profit, which is precisely why the WACC comparison — not the profit figure — is the correct test." },
      ]),
      h2("Connection"),
      p("WACC is the discount rate used in the DCF that follows, and the hurdle ROIC from Level 3 must beat."),
      sandbox("leverage-returns", "Capital mix sandbox",
        "Shift the debt and equity balance and watch the blended return change — the same weighting logic WACC performs.", [
        { key: "operatingProfit", label: "Operating profit", value: 1000000000, unit: "₹" },
        { key: "debt", label: "Debt", value: 2800000000, unit: "₹" },
        { key: "interestRate", label: "Pre-tax cost of debt", value: 10, unit: "%" },
        { key: "equity", label: "Equity (market value)", value: 9000000000, unit: "₹" },
      ]),
      mcq("Why does adding a modest amount of debt usually reduce WACC?",
        ["Debt has no cost", "Debt is cheaper than equity after the tax deduction", "It removes shareholders", "Interest rates fall"], 1,
        [W, "Correct. Substituting cheaper after-tax debt for costlier equity lowers the blend — until leverage rises far enough that distress risk pushes both costs up again.", W, W]),
    ]);

  L("c-discount-factors", "Discount factors",
    "The multiplier that converts a future rupee into a today rupee.",
    [
      h2("What is this?"),
      p("A discount factor is the number you multiply a future cash flow by to express it in today's money. At a 12% discount rate, the factor for year 3 is 1 ÷ 1.12³ = 0.712, so ₹100 arriving in year 3 is worth ₹71.20 today."),
      h2("Why does it matter?"),
      p("It is the mechanical heart of a DCF. Every valuation is the sum of future cash flows multiplied by their discount factors, so understanding the factor is understanding why distant cash flows contribute so little."),
      p("It also shows why the discount rate matters so much: the factor falls exponentially, so a higher rate punishes later years far more than earlier ones."),
      h2("How does it work?"),
      formula("Discount factor", [
        "<b>Discount factor = 1 ÷ (1 + r)^t</b>",
        "<b>Present value = Cash flow × Discount factor</b>",
        "r = discount rate (WACC), t = years from today",
      ]),
      fig("Real-Life Case Study: the shape of discounting",
        ["Factors at an 11.7% discount rate."],
        [["Year 1", "0.895"], ["Year 2", "0.801"], ["Year 3", "0.717"], ["Year 5", "0.575"],
         ["Year 10", "0.330"], ["Year 20", "0.109"]],
        ["₹100 in year 10 is worth ₹33 today; in year 20 it is worth ₹11.",
         "This is why forecasting fifteen years in detail adds little — the far years barely move the answer. It is also why terminal value, which captures everything beyond the forecast, has to be handled carefully rather than ignored."]),
      h2("Key terms"),
      def("Discount factor", "1 ÷ (1+r)^t — the multiplier converting a future amount to present value."),
      def("Present value", "A future cash flow expressed in today's money."),
      h2("Practice"),
      practice([
        { q: "At a 12% discount rate, compute the year-4 discount factor and the present value of ₹250 crore arriving then.", a: "Factor = 1 ÷ 1.12⁴ = 1 ÷ 1.5735 = 0.6355. PV = 250 × 0.6355 = ₹158.9 crore." },
        { q: "Why does raising the discount rate reduce the value of year 10 far more than year 1?", a: "The factor is 1 ÷ (1+r)^t, so the rate compounds over t years. One extra point barely changes a single year's division but is applied ten times over for year 10, shrinking that factor much more sharply." },
      ]),
      h2("Connection"),
      p("These factors are applied to the free cash flows and to terminal value in the DCF that follows."),
      sandbox("present-value", "Discount factor sandbox",
        "Change the years and the rate to see how quickly a future amount loses value in today's terms.", [
        { key: "amount", label: "Future cash flow", value: 25000000000, unit: "₹" },
        { key: "rate", label: "Discount rate (WACC)", value: 11.7, unit: "%" },
        { key: "years", label: "Years away", value: 4 },
      ]),
      mcq("At a 12% rate, ₹100 received in 10 years is worth roughly:",
        ["₹100", "₹32", "₹88", "₹310"], 1,
        [W, "Correct. The factor is 1 ÷ 1.12¹⁰ ≈ 0.322, so about ₹32 — distant cash flows contribute far less than their face value suggests.", W, W]),
    ]);

  L("c-terminal-value", "Terminal value",
    "Everything after the forecast period — usually most of the valuation.",
    [
      h2("What is this?"),
      p("Terminal value is the value of all cash flows beyond the explicit forecast. You cannot forecast year by year forever, so after five or ten years you capture the rest in a single figure and discount it back."),
      h2("Why does it matter?"),
      p("It typically accounts for 60-80% of a DCF's total value. That is uncomfortable but unavoidable: a business does not stop at year five. It does mean the assumption behind terminal value deserves more scrutiny than any single forecast year."),
      h2("How does it work?"),
      p("Two accepted methods, which should be cross-checked against each other:"),
      formula("Terminal value", [
        "<b>Perpetuity growth: TV = FCF(final year) × (1 + g) ÷ (WACC − g)</b>",
        "<b>Exit multiple: TV = Final-year EBITDA × Multiple</b>",
        "<b>PV of TV = TV × Discount factor for the final year</b>",
      ]),
      p("Both produce a value <em>as at the final forecast year</em>, so both must then be discounted back to today with that year's factor."),
      fig("Real-Life Case Study: how much sits in the tail",
        ["A five-year DCF at an 11.7% WACC, final-year free cash flow ₹42 crore, terminal growth 4%."],
        [["PV of years 1-5 cash flows", "₹128 crore"], ["Terminal value at year 5", "₹567 crore"],
         ["Year-5 discount factor", "0.575"], ["PV of terminal value", "₹326 crore"],
         ["Enterprise value", "₹454 crore"], ["Terminal value share", "72%"]],
        ["Nearly three-quarters of the valuation comes from a single number representing years six to infinity.",
         "That is normal, not an error. It does mean the terminal growth rate and the multiple deserve the same scrutiny as the entire five-year forecast combined."]),
      h2("Key terms"),
      def("Terminal value", "The value of all cash flows beyond the explicit forecast period."),
      def("Explicit forecast period", "The years modelled individually, usually five to ten."),
      h2("Practice"),
      practice([
        { q: "Final-year FCF ₹50 crore, WACC 12%, terminal growth 4%. Compute terminal value at the final year.", a: "TV = 50 × 1.04 ÷ (0.12 − 0.04) = 52 ÷ 0.08 = ₹650 crore." },
        { q: "Terminal value is 78% of your DCF. Should you abandon the DCF?", a: "No — that proportion is typical for a long-lived business. It should change how you present the answer: show the valuation across a range of terminal growth rates and exit multiples, since the tail assumption is carrying most of the weight." },
      ]),
      h2("Connection"),
      p("The next two lessons cover the two methods in detail; both feed the enterprise value the DCF produces."),
      mcq("Terminal value typically represents what share of a DCF's total value?",
        ["Under 10%", "Roughly 60-80%", "Exactly 50%", "None — it is optional"], 1,
        [W, "Correct. Most of a long-lived business's value lies beyond any explicit forecast, which is why the terminal assumption deserves the most scrutiny.", W, W]),
    ]);

  L("c-perpetuity-growth", "Perpetuity growth",
    "Assume the business grows slowly forever — and keep that growth honest.",
    [
      h2("What is this?"),
      p("The perpetuity growth method computes terminal value by assuming free cash flow grows at a constant rate forever after the forecast period, and capitalising it at the discount rate less that growth."),
      h2("Why does it matter?"),
      p("It is the theoretically cleaner of the two terminal value methods, because it values the business on its own cash flows rather than on what someone else's shares happen to trade at."),
      p("It is also dangerously sensitive. The denominator is WACC minus growth, so as growth approaches WACC the denominator shrinks towards zero and the value explodes. Small changes in g produce large changes in value."),
      h2("How does it work?"),
      formula("Perpetuity growth (Gordon growth)", [
        "<b>TV = FCF(final) × (1 + g) ÷ (WACC − g)</b>",
        "g = perpetual growth rate, which must be below WACC",
        "Sensible ceiling: long-run nominal GDP growth of the economy",
      ]),
      p("The discipline is this: no company can grow faster than the economy forever, because it would eventually become the entire economy. A terminal growth rate above long-run nominal GDP growth is an arithmetic impossibility, not an optimistic assumption."),
      fig("Real-Life Case Study: sensitivity to g",
        ["Final-year free cash flow ₹42 crore, WACC 11.7%."],
        [["g = 3%", "TV ₹497 crore"], ["g = 4%", "TV ₹567 crore"], ["g = 5%", "TV ₹658 crore"],
         ["g = 6%", "TV ₹782 crore"], ["g = 9%", "TV ₹1,696 crore"], ["Change from 3% to 6%", "+57%"]],
        ["Three percentage points of assumed perpetual growth changed terminal value by 57%.",
         "At g = 9%, approaching the 11.7% WACC, the value nearly quadruples — the formula is breaking down, not revealing hidden worth. Keep g well below WACC and at or under long-run GDP growth."]),
      h2("Key terms"),
      def("Perpetuity growth rate", "The constant rate at which cash flows are assumed to grow forever."),
      def("Gordon growth model", "The formula capitalising a growing perpetuity: CF × (1+g) ÷ (r − g)."),
      h2("Practice"),
      practice([
        { q: "Final-year FCF ₹60 crore, WACC 12%, g 4%. Compute TV. Then recompute at g = 6%.", a: "At 4%: 60 × 1.04 ÷ 0.08 = ₹780 crore. At 6%: 60 × 1.06 ÷ 0.06 = ₹1,060 crore — a 36% increase from two points of assumed perpetual growth." },
        { q: "Why must the perpetual growth rate stay below long-run nominal GDP growth?", a: "A business growing faster than the economy forever would eventually exceed the size of the economy, which is impossible. Exceeding GDP growth in perpetuity is not aggressive — it is arithmetically incoherent." },
      ]),
      h2("Connection"),
      p("This is one of the two terminal value methods; the exit multiple next is the market-based cross-check on it."),
      mcq("A perpetuity growth rate of 9% against a WACC of 11.7% is:",
        ["Reasonable for a growth company", "Almost certainly too high — it approaches WACC and exceeds long-run GDP growth", "Too low", "Required by the formula"], 1,
        [W, "Correct. As g approaches WACC the denominator collapses and the value explodes, and no business outgrows the economy forever.", W, W]),
    ]);

  L("c-exit-multiple", "Exit multiple",
    "Value the tail by assuming you sell the business at a market multiple.",
    [
      h2("What is this?"),
      p("The exit multiple method computes terminal value by applying an EV/EBITDA multiple to the final forecast year's EBITDA — as if the business were sold at that point at a normal market price."),
      h2("Why does it matter?"),
      p("It grounds the terminal value in observable transaction and trading multiples rather than an assumed perpetual growth rate. Practitioners often find it easier to defend '8× EBITDA, which is where this sector trades' than 'growing at 4% forever'."),
      p("The weakness is circular reasoning: you are valuing a company using the market's current pricing of similar companies. If the whole sector is overvalued, your DCF inherits that error while appearing to be independent of it."),
      h2("How does it work?"),
      formula("Exit multiple terminal value", [
        "<b>TV = Final-year EBITDA × Exit multiple</b>",
        "<b>PV of TV = TV × Final-year discount factor</b>",
        "Cross-check: what perpetual growth rate does this multiple imply?",
      ]),
      p("Good practice is to compute both methods and check they agree. If an 8× exit multiple implies 7% perpetual growth, one of the two assumptions is wrong."),
      fig("Real-Life Case Study: cross-checking the methods",
        ["Final-year EBITDA ₹196 crore, final-year FCF ₹42 crore, WACC 11.7%."],
        [["Exit multiple 6x — TV", "₹1,176 crore"], ["Implied perpetual growth", "≈8.0%"],
         ["Exit multiple 4x — TV", "₹784 crore"], ["Implied perpetual growth", "≈6.1%"],
         ["Perpetuity method at g = 4%", "₹567 crore"], ["Implied exit multiple", "≈2.9x"]],
        ["The two methods disagree substantially, and that disagreement is the useful information.",
         "A 6× exit multiple implies 8% perpetual growth, which is above sustainable long-run growth. Either the multiple is too generous or the forecast final-year EBITDA is too low — and you should resolve that before quoting a value."]),
      h2("Key terms"),
      def("Exit multiple", "The EV/EBITDA multiple assumed at the end of the forecast period."),
      def("Implied growth", "The perpetual growth rate that would produce the same terminal value as a given exit multiple."),
      h2("Practice"),
      practice([
        { q: "Final-year EBITDA ₹150 crore, exit multiple 7×, year-5 discount factor 0.57. Compute TV and its present value.", a: "TV = 150 × 7 = ₹1,050 crore. PV = 1,050 × 0.57 = ₹598.5 crore." },
        { q: "Your exit multiple implies 9% perpetual growth. What should you do?", a: "Reduce the multiple or revisit the forecast. Nine percent forever exceeds sustainable long-run growth, so the terminal value is overstated. The cross-check exists precisely to catch this, and ignoring it means quoting a number you cannot defend." },
      ]),
      h2("Connection"),
      p("Use this alongside perpetuity growth; the two together bracket the terminal value used in the DCF."),
      mcq("The main weakness of the exit multiple method is:",
        ["It is hard to calculate", "It imports the market's current pricing, so a mispriced sector contaminates the DCF", "It ignores EBITDA", "It cannot be discounted"], 1,
        [W, "Correct. The method borrows the market's opinion, which undermines the DCF's claim to be an independent estimate of value.", W, W]),
    ]);

  L("c-sensitivity-analysis-dcf", "Sensitivity analysis",
    "Show the range a DCF actually supports, not the single number it prints.",
    [
      h2("What is this?"),
      p("Sensitivity analysis in a DCF varies the two assumptions that drive the answer — almost always WACC and terminal growth — across a plausible range, and tabulates the resulting value per share."),
      h2("Why does it matter?"),
      p("A DCF produces a precise-looking figure from inputs that are estimates. Presenting ₹82.14 implies a confidence the model cannot support. A table showing ₹64 to ₹106 across reasonable assumptions is both more honest and more useful, because it shows what the decision actually depends on."),
      h2("How does it work?"),
      list([
        "Put WACC across the top, terminal growth down the side — these two carry most of the answer.",
        "Vary each by ±1 to 1.5 points around your base case, in steps.",
        "Fill the grid with value per share and mark the market price inside it.",
        "Read the conclusion: does the stock look cheap across most of the grid, or only in one corner?",
      ]),
      fig("Real-Life Case Study: value per share grid",
        ["WACC across, terminal growth down. Market price ₹75."],
        [["WACC 10.7%, g 3%", "₹88"], ["WACC 10.7%, g 4%", "₹99"], ["WACC 11.7%, g 3%", "₹74"],
         ["WACC 11.7%, g 4%", "₹82"], ["WACC 12.7%, g 3%", "₹64"], ["WACC 12.7%, g 4%", "₹70"]],
        ["The value ranges from ₹64 to ₹99 across assumptions that are all defensible, with the ₹75 market price sitting in the middle.",
         "The honest conclusion is that this DCF cannot call the stock cheap or expensive. It can say the market price implies roughly an 11.7% WACC and 3-4% perpetual growth — and then you decide whether you believe those."]),
      h2("Key terms"),
      def("Sensitivity grid", "A two-way table showing value across ranges of two key assumptions."),
      def("Implied assumption", "Working backwards from the market price to the growth or WACC it embeds."),
      h2("Practice"),
      practice([
        { q: "Your grid spans ₹64 to ₹99 and the market price is ₹75. What can you legitimately conclude?", a: "That the market price is consistent with reasonable assumptions, so the DCF does not identify a mispricing. You can state which assumptions the price implies and whether you find them conservative or optimistic — but not that the stock is cheap." },
        { q: "Why are WACC and terminal growth the standard axes rather than revenue growth?", a: "Both affect every discounted year and the terminal value, which is most of the valuation, so the answer is far more sensitive to them. Near-term revenue growth mainly affects a few early years that discount to relatively little." },
      ]),
      h2("Connection"),
      p("Every DCF output in the Live DCF module should be presented with this grid rather than as a single figure."),
      mcq("A DCF sensitivity grid spanning ₹64-₹99 around a ₹75 price means:",
        ["The stock is cheap", "The analysis cannot distinguish cheap from expensive at current assumptions", "The model is broken", "The stock is expensive"], 1,
        [W, "Correct. The price sits inside the defensible range, so the decision rests on which assumptions you can justify.", W, W]),
    ]);

  /* ============ LIVE DCF ============ */

  L("c-revenue-growth", "Revenue growth",
    "The first DCF input: how fast the top line expands over the forecast.",
    [
      h2("What is this?"),
      p("In a DCF, revenue growth is the assumption driving the forecast top line for each explicit year. Every cash flow the model discounts starts from it."),
      h2("Why does it matter?"),
      p("It sets the scale of everything downstream — costs, working capital and capex are usually expressed relative to revenue. But its effect on value is smaller than beginners expect, because near-term years are discounted only lightly while the terminal assumption carries most of the weight."),
      h2("How does it work?"),
      list([
        "Anchor year one to the actual trend and any known contracts or capacity.",
        "Fade growth towards a sustainable long-run rate by the final forecast year — companies rarely sustain high growth for a decade.",
        "Ensure the final year's growth is close to the terminal growth rate, or the transition creates an artificial jump in value.",
      ]),
      fig("Real-Life Case Study: fading growth",
        ["A five-year forecast that converges towards the 4% terminal rate."],
        [["Year 1", "12%"], ["Year 2", "10%"], ["Year 3", "8%"], ["Year 4", "6%"], ["Year 5", "5%"], ["Terminal", "4%"]],
        ["Growth declines smoothly into the perpetuity assumption, so nothing discontinuous happens at the handover.",
         "Holding 12% through year five and then dropping to 4% forever would create a cliff — and would also imply the company sustains double-digit growth far longer than most businesses manage."]),
      h2("Practice"),
      practice([
        { q: "Revenue ₹800 crore growing 12%, 10%, 8%, 6%, 5%. Compute year-5 revenue.", a: "800 × 1.12 × 1.10 × 1.08 × 1.06 × 1.05 = ₹1,185 crore." },
        { q: "Why should forecast growth fade towards the terminal rate?", a: "Because the terminal value assumes the company grows at that rate forever from year six. If year five is still growing 12%, the model implies an abrupt permanent collapse to 4% — an unexplained discontinuity that distorts the valuation." },
      ]),
      h2("Connection"),
      p("This input feeds the margin assumption next, and together they produce the cash flows the DCF discounts."),
      sandbox("revenue-growth", "Growth input sandbox",
        "Change growth and see the revenue base the whole DCF is built on.", [
        { key: "price", label: "Revenue base", value: 8000000000, unit: "₹" },
        { key: "volume", label: "Multiplier", value: 1 },
        { key: "priceGrowth", label: "Growth rate", value: 12, unit: "%" },
        { key: "volumeGrowth", label: "Additional growth", value: 0, unit: "%" },
      ]),
      mcq("Forecast growth should fade towards the terminal rate because:",
        ["Spreadsheets require it", "Otherwise the model implies an abrupt, unexplained permanent drop after the forecast", "Growth is always negative", "It reduces the tax charge"], 1,
        [W, "Correct. A smooth transition into perpetuity avoids a discontinuity the business has no reason to experience.", W, W]),
    ]);

  L("c-margin", "Margin",
    "The second DCF input: how much of each rupee of revenue survives as cash.",
    [
      h2("What is this?"),
      p("The margin assumption converts forecast revenue into operating profit, and then — after tax, working capital and capex — into the free cash flow the DCF discounts."),
      h2("Why does it matter?"),
      p("Margin is usually the assumption with the largest effect on value after WACC and terminal growth, because it applies to every forecast year and to the terminal value base."),
      p("It is also where optimism hides most easily. Assuming a company steadily improves margins for five years costs nothing to type and can add a quarter to the valuation."),
      h2("How does it work?"),
      list([
        "Start from the historical margin, not from a target.",
        "Justify any expansion specifically: operating leverage on fixed costs, a completed automation project, a mix shift with evidence.",
        "Check the endpoint. A forecast reaching a margin the company has never achieved needs a named cause.",
        "Apply the margin to forecast revenue to get EBIT, then tax it to reach the cash flow base.",
      ]),
      fig("Real-Life Case Study: margin's leverage on value",
        ["Bharat Kitchen Appliances, forecast five years at an 11.7% WACC and 4% terminal growth."],
        [["EBITDA margin held at 17%", "EV ₹1,224 crore"], ["Margin rising to 19%", "EV ₹1,368 crore"],
         ["Margin falling to 15%", "EV ₹1,080 crore"], ["Range from ±2 points", "±12%"]],
        ["Two points of margin either way moves enterprise value by roughly 12%.",
         "That is a large swing from an assumption that takes one keystroke, which is why the margin path should be defended line by line rather than trended optimistically."]),
      h2("Practice"),
      practice([
        { q: "Year-5 revenue ₹1,185 crore at a 17% EBITDA margin, with D&A of ₹52 crore and a 25% tax rate. Compute year-5 EBIT and after-tax EBIT.", a: "EBITDA = 1,185 × 17% = ₹201 crore. EBIT = 201 − 52 = ₹149 crore. After tax = 149 × 0.75 = ₹112 crore." },
        { q: "A DCF assumes margins expand 0.5 points a year for five years. What should you require?", a: "A named, specific cause for each point — fixed costs being spread over more revenue, a contracted input price, an automation programme with a timetable. Without one, the 2.5-point expansion is an assumption dressed as a forecast, and it may be carrying a tenth of the valuation." },
      ]),
      h2("Connection"),
      p("Margin and growth together produce the operating cash flow; WACC then determines what it is worth today."),
      sandbox("profit-bridge", "Margin input sandbox",
        "Change costs to move the margin and see the profit base the DCF will discount.", [
        { key: "revenue", label: "Forecast revenue", value: 11850000000, unit: "₹" },
        { key: "cogs", label: "Cost of goods sold", value: 7110000000, unit: "₹" },
        { key: "opex", label: "Operating costs incl. D&A", value: 3250000000, unit: "₹" },
        { key: "interest", label: "Interest", value: 280000000, unit: "₹" },
        { key: "taxRate", label: "Tax rate", value: 25, unit: "%" },
      ]),
      mcq("Assuming steady margin expansion across a forecast:",
        ["Is standard practice requiring no justification", "Can add materially to value and needs a specific named cause", "Has no effect on valuation", "Only affects the terminal year"], 1,
        [W, "Correct. It applies to every year and to the terminal base, so unexplained expansion is one of the commonest ways a DCF is quietly inflated.", W, W]),
    ]);

  L("c-wacc-dcf-input", "WACC",
    "The DCF input that moves the answer most.",
    [
      h2("What is this?"),
      p("As a DCF input, WACC is the discount rate applied to every forecast cash flow and to the terminal value. It is the same number built in the earlier WACC lesson, now doing its job."),
      h2("Why does it matter?"),
      p("It is the single most powerful input in the model. It appears in the discount factor for every year and in the terminal value denominator, so its effect compounds through the entire valuation."),
      p("A one-point change in WACC typically moves value more than a two-point change in revenue growth, because growth affects near-term years that are discounted lightly, while WACC affects everything including the terminal value."),
      h2("How does it work?"),
      formula("WACC in the DCF", [
        "<b>PV of each year = FCF ÷ (1 + WACC)^t</b>",
        "<b>TV = FCF(final) × (1 + g) ÷ (WACC − g)</b>",
        "WACC appears in every discount factor and in the terminal denominator",
      ]),
      fig("Real-Life Case Study: WACC sensitivity",
        ["Same cash flows, same 4% terminal growth, three discount rates."],
        [["WACC 10.7%", "EV ₹1,410 crore"], ["WACC 11.7%", "EV ₹1,224 crore"], ["WACC 12.7%", "EV ₹1,078 crore"],
         ["Value per share at each", "₹98 / ₹82 / ₹70"], ["Swing from ±1 point", "±14%"]],
        ["One point either way moves value per share by about ₹14 — nearly a fifth of the ₹75 market price.",
         "Since WACC is built from an estimated equity risk premium and an estimated beta, that precision simply is not available. Always present the DCF across a WACC range."]),
      h2("Practice"),
      practice([
        { q: "Free cash flow ₹42 crore in year 3. Compute its present value at a WACC of 11% and at 13%.", a: "At 11%: 42 ÷ 1.11³ = 42 ÷ 1.368 = ₹30.7 crore. At 13%: 42 ÷ 1.13³ = 42 ÷ 1.443 = ₹29.1 crore. A single year moves little; applied to every year and the terminal value, the effect becomes large." },
        { q: "Why does WACC affect value more than near-term revenue growth?", a: "Growth mainly changes the early years, which are discounted lightly and represent a small share of value. WACC changes every discount factor and the terminal value denominator, where most of the value sits." },
      ]),
      h2("Connection"),
      p("WACC connects the cost of equity, cost of debt and capital structure lessons directly to the enterprise value output next."),
      sandbox("present-value", "Discount rate sandbox",
        "Move the rate and watch the present value of a single future cash flow — then imagine the effect applied to every year.", [
        { key: "amount", label: "Future free cash flow", value: 420000000, unit: "₹" },
        { key: "rate", label: "WACC", value: 11.7, unit: "%" },
        { key: "years", label: "Years away", value: 5 },
      ]),
      mcq("WACC affects a DCF more than near-term growth because:",
        ["It is larger", "It applies to every discount factor and to the terminal value", "It is easier to estimate", "It is tax deductible"], 1,
        [W, "Correct. Its effect compounds across the whole forecast and the terminal value, where most of the valuation sits.", W, W]),
    ]);

  L("c-terminal-growth", "Terminal growth",
    "The rate the business grows forever — small number, large consequences.",
    [
      h2("What is this?"),
      p("Terminal growth is the constant rate at which free cash flow is assumed to grow after the forecast period, used in the perpetuity terminal value formula."),
      h2("Why does it matter?"),
      p("Because terminal value is most of a DCF, and this rate sits in its denominator as WACC minus g, small changes produce large swings. Moving g from 3% to 5% can add a fifth to the valuation."),
      h2("How does it work?"),
      list([
        "Cap it at long-run nominal GDP growth for the economy — the mathematical ceiling.",
        "Consider whether the business will even keep pace with the economy in perpetuity; many mature industries will not.",
        "Ensure the final forecast year's growth has faded close to it.",
        "Cross-check the implied exit multiple: if g implies 15× EBITDA in a sector trading at 8×, g is too high.",
      ]),
      fig("Real-Life Case Study: the cross-check",
        ["Final-year FCF ₹42 crore, EBITDA ₹196 crore, WACC 11.7%."],
        [["g = 3% — TV", "₹497 crore"], ["Implied exit multiple", "2.5x"], ["g = 4% — TV", "₹567 crore"],
         ["Implied exit multiple", "2.9x"], ["g = 6% — TV", "₹782 crore"], ["Implied exit multiple", "4.0x"], ["Sector trades at", "8-10x"]],
        ["Every perpetuity assumption here implies an exit multiple far below where the sector trades.",
         "That is a useful signal in the other direction: either the final-year free cash flow is depressed by heavy capex, or the market is pricing growth this DCF does not assume. Either way, investigate before publishing a number."]),
      h2("Practice"),
      practice([
        { q: "FCF ₹42 crore, WACC 11.7%, g 4%. Compute terminal value, then recompute at g 5%.", a: "At 4%: 42 × 1.04 ÷ 0.077 = ₹567 crore. At 5%: 42 × 1.05 ÷ 0.067 = ₹658 crore — 16% higher from one point." },
        { q: "Why cross-check terminal growth against an implied exit multiple?", a: "The two methods should describe the same business. If your growth assumption implies a multiple far from where comparable companies trade, one of the assumptions is wrong, and the gap tells you which direction to investigate." },
      ]),
      h2("Connection"),
      p("Terminal growth pairs with WACC as the two axes of the sensitivity grid, and with the exit multiple as its cross-check."),
      mcq("The ceiling on a sensible terminal growth rate is:",
        ["The company's historical growth", "Long-run nominal GDP growth of the economy", "The WACC", "There is no ceiling"], 1,
        [W, "Correct. Growing faster than the economy forever would make the company larger than the economy — arithmetically impossible.", W, W]),
    ]);

  L("c-enterprise-value-dcf-output", "Enterprise Value",
    "The DCF's first output: the sum of discounted cash flows plus discounted terminal value.",
    [
      h2("What is this?"),
      p("Enterprise value from a DCF is the present value of the explicit forecast free cash flows plus the present value of the terminal value. It is the model's estimate of what the operating business is worth today."),
      h2("Why does it matter?"),
      p("Unlike a multiple, this number is built from the company's own forecast cash flows rather than from what other companies' shares happen to trade at. That independence is the whole reason to build a DCF."),
      h2("How does it work?"),
      formula("Enterprise value from a DCF", [
        "<b>EV = Σ [FCF(t) ÷ (1 + WACC)^t] + [TV ÷ (1 + WACC)^n]</b>",
        "t = each forecast year, n = final forecast year",
        "TV must be discounted from year n, not treated as a present value",
      ]),
      fig("Real-Life Case Study: assembling the value",
        ["Five forecast years at an 11.7% WACC, terminal growth 4%."],
        [["PV of year 1-5 free cash flows", "₹128 crore"], ["Terminal value at year 5", "₹567 crore"],
         ["Year-5 discount factor", "0.575"], ["PV of terminal value", "₹326 crore"],
         ["Enterprise value", "₹454 crore"], ["EV implied by 9x EBITDA", "₹1,224 crore"]],
        ["The DCF and the multiple disagree by a wide margin, and that gap is the finding worth chasing.",
         "The likely cause here is that free cash flow is depressed by heavy growth capex, so the DCF's near-term cash flows understate the mature earning power while the multiple assumes it. Reconciling the two is the actual analytical work."]),
      h2("Practice"),
      practice([
        { q: "PV of forecast cash flows ₹150 crore, terminal value ₹700 crore at year 5, year-5 factor 0.575. Compute enterprise value.", a: "PV of TV = 700 × 0.575 = ₹402.5 crore. EV = 150 + 402.5 = ₹552.5 crore." },
        { q: "A common beginner error is adding terminal value without discounting it. How large is that error at a 0.575 factor?", a: "It overstates the terminal contribution by about 74% — ₹700 crore instead of ₹402.5 crore. Since terminal value is most of the valuation, the total EV would be overstated by well over half." },
      ]),
      h2("Connection"),
      p("Subtract net debt from this figure to reach equity value, then divide by shares for the price comparison."),
      mcq("Terminal value must be:",
        ["Added to enterprise value as it stands", "Discounted from the final forecast year back to today", "Ignored if it is large", "Added to net debt"], 1,
        [W, "Correct. It is a value as at year n, so it needs that year's discount factor before it can be added to today's value.", W, W]),
    ]);

  L("c-equity-value-dcf-output", "Equity Value",
    "Subtract what the lenders are owed, and what remains belongs to shareholders.",
    [
      h2("What is this?"),
      p("Equity value in a DCF is enterprise value less net debt. It converts the value of the operating business into the value of the shareholders' claim on it."),
      h2("Why does it matter?"),
      p("This is the bridge from a business valuation to an investment decision. A DCF that stops at enterprise value has not yet said anything about whether the shares are worth their price."),
      p("It is also where two identical businesses diverge: the one carrying more debt delivers less to shareholders from the same operating value."),
      h2("How does it work?"),
      formula("From EV to equity value", [
        "<b>Equity value = Enterprise value − Net debt</b>",
        "Net debt = total debt (including leases) − cash",
        "Add the value of any non-operating assets excluded from the cash flows",
      ]),
      p("If the company holds material non-operating assets — surplus land, a stake in another business — their value must be added, because the forecast cash flows did not include them."),
      fig("Real-Life Case Study: the bridge",
        ["Bharat Kitchen Appliances, valued on the 9× multiple for comparability."],
        [["Enterprise value", "₹1,224 crore"], ["Less: total debt", "−₹280 crore"], ["Add: cash", "+₹40 crore"],
         ["Equity value", "₹984 crore"], ["Add: surplus land held for sale", "+₹25 crore"], ["Adjusted equity value", "₹1,009 crore"]],
        ["The ₹25 crore of surplus land generates no operating cash flow, so the DCF never captured it — but it is real value belonging to shareholders.",
         "Omitting non-operating assets is a common and quietly material error, especially in older manufacturing companies holding legacy property."]),
      h2("Practice"),
      practice([
        { q: "EV ₹552 crore, debt ₹180 crore, cash ₹35 crore, surplus investments ₹20 crore. Compute equity value.", a: "Net debt = 180 − 35 = ₹145 crore. Equity value = 552 − 145 + 20 = ₹427 crore." },
        { q: "Why must non-operating assets be added separately rather than left in the cash flows?", a: "The forecast models operating cash flows only, so an idle plot of land or a passive shareholding contributes nothing to them. Their value is real but invisible to the DCF, so it must be added after the bridge from enterprise to equity value." },
      ]),
      h2("Connection"),
      p("Divide this by the share count to reach the value per share that the final lesson compares with the market price."),
      mcq("A non-operating asset such as surplus land should be:",
        ["Ignored", "Added to equity value, because the operating cash flows never included it", "Subtracted from EV", "Treated as debt"], 1,
        [W, "Correct. It belongs to shareholders but produces no operating cash flow, so the DCF cannot have captured it.", W, W]),
    ]);

  L("c-share-price", "Share Price",
    "The last step: compare your value per share with the price, and decide.",
    [
      h2("What is this?"),
      p("Value per share is equity value divided by the diluted share count. Comparing it with the market price is the point of the whole exercise."),
      h2("Why does it matter?"),
      p("This is where valuation becomes a decision. Everything before it — the forecast, WACC, terminal value — exists to produce a number you can hold against a price."),
      p("It is also where humility belongs. Your value is an estimate built from estimates; the price is a fact set by many participants. A small gap between them is not a signal, and a large gap deserves the question: what does the market know or assume that I do not?"),
      h2("How does it work?"),
      formula("Value per share and margin of safety", [
        "<b>Value per share = Equity value ÷ Diluted shares outstanding</b>",
        "<b>Upside = (Value per share ÷ Market price) − 1</b>",
        "<b>Margin of safety = the discount you require before acting</b>",
      ]),
      p("Use diluted shares. Outstanding options and convertibles will increase the count if exercised, and ignoring them overstates value per share."),
      fig("Real-Life Case Study: the decision",
        ["Bharat Kitchen Appliances, sensitivity grid from the earlier lesson."],
        [["Value per share — base case", "₹82"], ["Range across the grid", "₹64 - ₹99"],
         ["Market price", "₹75"], ["Base-case upside", "+9%"], ["Diluted share count effect", "−₹2"], ["Adjusted base case", "₹80"]],
        ["A 9% base-case upside sits well inside the range the assumptions support, so this is not a mispricing you can rely on.",
         "The defensible conclusion: the price implies roughly an 11.7% WACC and 3-4% perpetual growth, which are reasonable. Without a margin of safety wide enough to absorb the error in your own estimate, the right answer may be to wait rather than to act."]),
      h2("Key terms"),
      def("Margin of safety", "The discount to estimated value an investor requires before buying, to absorb estimation error."),
      def("Diluted share count", "Shares outstanding plus those from options and convertibles that would be issued on exercise."),
      h2("Practice"),
      practice([
        { q: "Equity value ₹1,009 crore, 12.3 crore diluted shares, market price ₹75. Compute value per share and the upside.", a: "Value per share = 1,009 ÷ 12.3 = ₹82. Upside = 82 ÷ 75 − 1 = 9.3%." },
        { q: "Your DCF says ₹82 and the market says ₹75. Give the two questions you should ask before buying.", a: "First, is 9% wider than the error in my own estimate? The sensitivity grid spanned ₹64-₹99, so it is not. Second, what does the market assume that I do not — a slower growth path, a working capital problem, a competitive threat? A gap this small is more likely to be my estimation noise than the market's mistake." },
      ]),
      h2("Connection"),
      p("This closes the valuation chain that began with enterprise value, and it is the same decision the capstone asks you to make with the full picture."),
      mcq("Your DCF gives ₹82 against a ₹75 market price, with a sensitivity range of ₹64-₹99. The sound conclusion is:",
        ["Buy immediately — 9% upside", "The gap is within the model's own error range, so it is not a reliable signal", "Sell short", "The market is wrong"], 1,
        [W, "Correct. When the upside is smaller than the spread your own assumptions produce, it is noise rather than a mispricing.", W, W]),
    ]);
})();
