/* Level 3 concept lessons — Financial Analysis.
   Same standard as Levels 0-2: plain-English concept, why it matters,
   step-by-step mechanics, a worked case study with figures, key terms,
   practice with solutions, an interactive sandbox and a quiz. */
(function () {
  "use strict";
  var LS = (window.LS = window.LS || {});
  LS.lessons = LS.lessons || {};

  function h2(t) { return { t: "h2", text: t }; }
  function h3(t) { return { t: "h3", text: t }; }
  function p(h) { return { t: "p", h: h }; }
  function list(items) { return { t: "list", items: items }; }
  function def(term, h) { return { t: "def", term: term, h: h }; }
  function note(items) {
    return { t: "note", h: "<ul>" + items.map(function (i) { return "<li>" + i + "</li>"; }).join("") + "</ul>" };
  }
  function practice(items) { return { t: "practice", items: items }; }
  function sandbox(kind, title, prompt, fields) {
    return { t: "sandbox", kind: kind, title: title, prompt: prompt, fields: fields };
  }
  function formula(title, lines) { return { t: "formula", title: title, lines: lines }; }
  function mcq(q, opts, correct, why) { return { t: "mcq", q: q, opts: opts, correct: correct, why: why }; }
  function caseStudy(title, intro, rows, meaning) {
    var html = '<p class="case-title"><strong>' + title + "</strong></p>";
    intro.forEach(function (x) { html += "<p>" + x + "</p>"; });
    if (rows.length) {
      html += '<div class="case-figures">';
      rows.forEach(function (r) {
        html += '<div class="case-row"><span class="case-label">' + r[0] +
          '</span><span class="case-value">' + r[1] + "</span></div>";
      });
      html += "</div>";
    }
    html += '<p class="case-meaning"><strong>What it means.</strong></p>';
    meaning.forEach(function (x) { html += "<p>" + x + "</p>"; });
    return { t: "example", h: html };
  }
  function lesson(id, title, lede, body) {
    LS.lessons[id] = { id: id, title: title, short: title, desc: lede, lede: lede, minutes: 8, body: body };
  }
  var W = "Not this one — re-read the section above.";

  /* ================= PROFITABILITY & RETURNS ================= */

  lesson("c-ebitda-margin", "EBITDA margin",
    "What share of every rupee of sales survives as operating cash-like profit.",
    [
      h2("What is this?"),
      p("EBITDA margin is EBITDA divided by revenue, expressed as a percentage. It answers: of every ₹100 of sales, how much is left after the costs of actually running the business, but before interest, tax and depreciation?"),
      p("Because it excludes financing and depreciation, it isolates the operating engine — useful when comparing a company that owns its assets with one that leases them."),
      h2("Why does it matter?"),
      p("Margins are how businesses of different sizes are compared. A ₹5 crore EBITDA means nothing until you know whether it came from ₹20 crore of sales (25% — excellent) or ₹200 crore (2.5% — fragile)."),
      p("The margin also shows scalability. If revenue grows 30% and EBITDA margin rises, fixed costs are being spread over more sales. If margin falls while revenue grows, the company is buying growth with discounts or rising costs."),
      h2("How does it work?"),
      h3("Step 1: Compute EBITDA"),
      p("Operating profit plus depreciation and amortisation."),
      h3("Step 2: Divide by revenue"),
      p("EBITDA ÷ revenue. Use the same period for both, and be consistent about what is included."),
      h3("Step 3: Compare across time, not across industries"),
      p("A 12% margin is strong in retail and weak in software. The meaningful comparison is a company against its own history and its direct competitors."),
      h3("Step 4: Ask what moved it"),
      p("Price, input cost, mix or operating cost discipline. A margin figure without an explanation is trivia."),
      formula("EBITDA margin", [
        "<b>EBITDA margin = EBITDA ÷ Revenue</b>",
        "EBITDA = operating profit + depreciation + amortisation",
        "Revenue = sales for the same period",
      ]),
      caseStudy("Real-Life Case Study: a hotel chain over two years",
        ["Occupancy improved while the cost base stayed largely fixed."],
        [["Year 1 revenue", "₹400 crore"], ["Year 1 EBITDA", "₹60 crore"], ["Year 1 EBITDA margin", "15.0%"],
         ["Year 2 revenue", "₹480 crore"], ["Year 2 EBITDA", "₹96 crore"], ["Year 2 EBITDA margin", "20.0%"]],
        ["Revenue rose 20% but EBITDA rose 60%, because most hotel costs — property, core staff — do not increase with occupancy.",
         "That 5-point margin gain is operating leverage working in the company's favour. The same mechanism runs in reverse when occupancy falls, which is why hotel earnings swing so violently in a downturn."]),
      h2("Key terms"),
      def("EBITDA margin", "EBITDA as a percentage of revenue — operating profitability before financing, tax and depreciation."),
      def("Margin expansion", "A rise in margin over time, usually from scale, pricing power or cost control."),
      def("Operating leverage", "The tendency of profit to move by a larger percentage than revenue, caused by fixed costs."),
      def("Comparable set", "The specific competitors a margin should be measured against, since margins are industry-specific."),
      h2("Practice"),
      practice([
        { q: "Revenue ₹250 crore, operating profit ₹28 crore, depreciation ₹17 crore. Compute EBITDA and the EBITDA margin.", a: "EBITDA = 28 + 17 = ₹45 crore. Margin = 45 ÷ 250 = 18%." },
        { q: "Revenue grows 25% while EBITDA margin falls from 22% to 18%. Compute both years' EBITDA on a ₹100 crore base and say what likely happened.", a: "Year 1: ₹22 crore. Year 2: 125 × 18% = ₹22.5 crore. Revenue grew a quarter and EBITDA barely moved — growth was bought with discounting or higher costs, so the extra sales added almost nothing." },
        { q: "Why can an asset-heavy firm show a much higher EBITDA margin than an asset-light competitor with identical economics?", a: "The asset-heavy firm's depreciation is added back and is large; the asset-light firm rents instead, and rent is an operating cost that is not added back. EBITDA margin flatters ownership over leasing even when the cash economics are similar." },
      ]),
      h2("Sandbox"),
      sandbox("profit-bridge", "Margin sandbox",
        "Raise revenue while holding operating costs fixed and watch every margin widen — that is operating leverage.", [
        { key: "revenue", label: "Revenue", value: 4000000000, unit: "₹" },
        { key: "cogs", label: "Direct costs", value: 2400000000, unit: "₹" },
        { key: "opex", label: "Operating costs", value: 1000000000, unit: "₹" },
        { key: "interest", label: "Interest", value: 120000000, unit: "₹" },
        { key: "taxRate", label: "Tax rate", value: 25, unit: "%" },
      ]),
      h2("What to remember"),
      note([
        "EBITDA margin = EBITDA ÷ revenue.",
        "Compare a company with itself over time and with close competitors — never across industries.",
        "Rising margin on rising revenue signals operating leverage; falling margin signals bought growth.",
        "It flatters asset owners relative to lessees, because depreciation is added back and rent is not.",
      ]),
      h2("Common mistakes"),
      list([
        "<strong>Comparing margins across industries</strong> and concluding one business is better run.",
        "<strong>Treating EBITDA margin as a cash margin.</strong> Capex and working capital are not in it.",
        "<strong>Celebrating margin gains from one-off items</strong> rather than from operations.",
        "<strong>Ignoring the revenue trend.</strong> A rising margin on collapsing revenue is not good news.",
      ]),
      mcq("Revenue ₹500 crore and EBITDA ₹90 crore. The EBITDA margin is:",
        ["5.6%", "18%", "55%", "90%"], 1,
        [W, "Correct. 90 ÷ 500 = 18%.", W, W]),
      mcq("Revenue rises 20% and EBITDA rises 45%. This most likely indicates:",
        ["Falling prices", "Operating leverage — fixed costs spread over more sales", "Higher tax", "More borrowing"], 1,
        [W, "Correct. Profit growing faster than revenue is the signature of fixed costs being spread across a larger base.", W, W]),
      mcq("Why is EBITDA margin a poor way to compare a company that owns its factories with one that leases them?",
        ["Leases are illegal", "Owners' depreciation is added back while lessees' rent is not, flattering the owner", "Both have identical margins", "Rent is tax-free"], 1,
        [W, "Correct. The add-back applies to depreciation only, so ownership looks more profitable on this measure even when the underlying economics match.", W, W]),
    ]);

  lesson("c-ebit-margin", "EBIT margin",
    "Operating margin: profitability after the cost of assets wearing out, before financing and tax.",
    [
      h2("What is this?"),
      p("EBIT margin — also called operating margin — is operating profit divided by revenue. It is EBITDA margin's stricter sibling: it charges for depreciation and amortisation instead of adding them back."),
      p("For most analysts it is the better measure of operating profitability, because assets genuinely do wear out and pretending otherwise overstates what a business earns."),
      h2("Why does it matter?"),
      p("EBIT margin is the cleanest comparison of how efficiently two companies convert sales into operating profit, independent of how they are financed. It also feeds ROIC, the return measure most closely linked to value creation."),
      p("The gap between EBITDA margin and EBIT margin is itself informative: a wide gap means a capital-intensive business whose reported EBITDA needs treating with caution."),
      h2("How does it work?"),
      h3("Step 1: Compute EBIT"),
      p("Revenue − COGS − operating expenses − depreciation and amortisation."),
      h3("Step 2: Divide by revenue"),
      p("EBIT ÷ revenue, same period both sides."),
      h3("Step 3: Compare with the EBITDA margin"),
      p("The difference is depreciation as a share of revenue — a quick read on capital intensity."),
      h3("Step 4: Track the trend"),
      p("A margin drifting down over several years usually means competition is eroding pricing power, whatever the explanation offered."),
      formula("EBIT margin", [
        "<b>EBIT margin = Operating profit ÷ Revenue</b>",
        "Operating profit = revenue − COGS − operating expenses − D&amp;A",
      ]),
      caseStudy("Real-Life Case Study: capital intensity revealed",
        ["Two firms both report a 20% EBITDA margin on ₹300 crore of revenue."],
        [["Both — revenue", "₹300 crore"], ["Both — EBITDA", "₹60 crore"], ["Firm A — depreciation", "₹9 crore"], ["Firm A — EBIT margin", "17.0%"], ["Firm B — depreciation", "₹42 crore"], ["Firm B — EBIT margin", "6.0%"]],
        ["On EBITDA the two look identical. On EBIT, Firm A earns nearly three times the margin.",
         "Firm B's assets consume ₹42 crore a year of value, and it must keep spending to replace them. The EBITDA comparison hid the entire difference — which is why operating margin is the fairer first look."]),
      h2("Key terms"),
      def("EBIT margin", "Operating profit as a percentage of revenue. Also called operating margin."),
      def("Capital intensity", "How much fixed asset investment a business needs per rupee of revenue."),
      def("Pricing power", "The ability to raise prices without losing volume — usually visible as a stable or rising margin."),
      def("ROIC", "Return on invested capital, built from after-tax EBIT divided by the capital employed."),
      h2("Practice"),
      practice([
        { q: "Revenue ₹180 crore, COGS ₹104 crore, operating expenses ₹38 crore, depreciation ₹14 crore. Compute the EBIT margin.", a: "EBIT = 180 − 104 − 38 − 14 = ₹24 crore. Margin = 24 ÷ 180 = 13.3%." },
        { q: "A company's EBITDA margin is 30% and its EBIT margin is 11%. What does the gap tell you?", a: "Depreciation is 19% of revenue — very capital intensive. Almost two-thirds of the EBITDA is consumed by assets wearing out, so EBITDA badly overstates the economics here and capex should be checked against depreciation." },
        { q: "EBIT margin has fallen from 16% to 12% over four years while revenue doubled. Is this good or bad?", a: "It depends on why. If the company entered a lower-margin but large segment deliberately, absolute EBIT still rose substantially and the trade may be sound. If it reflects price competition in the core business, it is erosion of pricing power and will likely continue. Segment-level margins settle the question." },
      ]),
      h2("Sandbox"),
      sandbox("profit-bridge", "Operating margin sandbox",
        "Increase operating costs a little at a time and watch operating profit fall much faster in percentage terms.", [
        { key: "revenue", label: "Revenue", value: 1800000000, unit: "₹" },
        { key: "cogs", label: "Direct costs", value: 1040000000, unit: "₹" },
        { key: "opex", label: "Operating costs incl. depreciation", value: 520000000, unit: "₹" },
        { key: "interest", label: "Interest", value: 60000000, unit: "₹" },
        { key: "taxRate", label: "Tax rate", value: 25, unit: "%" },
      ]),
      h2("What to remember"),
      note([
        "EBIT margin = operating profit ÷ revenue, after depreciation.",
        "It is the fairer operating comparison because it charges for assets wearing out.",
        "The EBITDA-to-EBIT margin gap measures capital intensity.",
        "A steadily falling margin usually means eroding pricing power.",
      ]),
      h2("Common mistakes"),
      list([
        "<strong>Using EBITDA margin when comparing capital-heavy businesses.</strong> It hides the largest cost.",
        "<strong>Reading one year's margin in isolation.</strong> The trend carries the information.",
        "<strong>Confusing operating margin with net margin.</strong> Interest and tax still come after this.",
        "<strong>Assuming a lower margin means a worse business.</strong> Volume and capital turnover matter just as much.",
      ]),
      mcq("EBIT ₹36 crore on revenue of ₹240 crore. The EBIT margin is:",
        ["6.7%", "15%", "24%", "36%"], 1,
        [W, "Correct. 36 ÷ 240 = 15%.", W, W]),
      mcq("A wide gap between EBITDA margin and EBIT margin indicates:",
        ["High interest costs", "High depreciation — a capital-intensive business", "A large tax bill", "Fast revenue growth"], 1,
        [W, "Correct. The only difference between the two is depreciation and amortisation, so a wide gap means heavy fixed assets.", W, W]),
      mcq("Which margin is most useful for comparing operating efficiency between a debt-funded and an equity-funded competitor?",
        ["Net margin", "EBIT margin", "Gross margin only", "Dividend yield"], 1,
        [W, "Correct. EBIT sits above interest, so financing differences do not distort it, while it still charges for depreciation.", W, W]),
    ]);

  lesson("c-net-margin", "Net margin",
    "The share of every rupee of sales that finally belongs to the owners.",
    [
      h2("What is this?"),
      p("Net margin is net profit divided by revenue. It is the bottom line expressed as a percentage — what survives after direct costs, operating costs, depreciation, interest and tax."),
      p("Because it includes everything, it is the most complete margin and the least useful for isolating any single cause. A change in net margin could come from operations, financing, tax, or a one-off gain."),
      h2("Why does it matter?"),
      p("It is what actually accrues to shareholders, and it drives earnings per share and most valuation multiples. A business with a 2% net margin has almost no room for error; a 25% net margin absorbs shocks comfortably."),
      p("Read alongside EBIT margin it also decomposes cleanly: if operating margin is stable and net margin is falling, the cause is below the operating line — usually interest or tax, not the business."),
      h2("How does it work?"),
      h3("Step 1: Take net profit"),
      p("After interest, tax and any non-operating items."),
      h3("Step 2: Divide by revenue"),
      p("Net profit ÷ revenue."),
      h3("Step 3: Compare with the operating margin"),
      p("The gap is everything below EBIT. Widening gap means financing or tax is taking more."),
      h3("Step 4: Strip out one-offs before judging"),
      p("An asset sale can lift net margin for a year and tell you nothing about the business."),
      formula("Net margin", [
        "<b>Net margin = Net profit ÷ Revenue</b>",
        "<b>EPS = Net profit ÷ Shares outstanding</b>",
      ]),
      caseStudy("Real-Life Case Study: where the margin went",
        ["A company's net margin fell from 9.0% to 5.5% while operating margin barely moved."],
        [["Revenue", "₹600 crore"], ["Operating margin, both years", "≈14%"], ["Year 1 interest", "₹18 crore"], ["Year 2 interest", "₹39 crore"], ["Year 1 net margin", "9.0%"], ["Year 2 net margin", "5.5%"]],
        ["Operations were unchanged: the same ₹84 crore of operating profit on the same sales.",
         "The entire decline came from interest more than doubling after a debt-funded acquisition. Judging the operating business by net margin would have wrongly concluded it was deteriorating."]),
      h2("Key terms"),
      def("Net margin", "Net profit as a percentage of revenue — the complete bottom-line profitability."),
      def("One-off item", "A non-recurring gain or loss that distorts a single period's margin."),
      def("Effective tax rate", "Tax expense ÷ profit before tax; a driver of net margin independent of operations."),
      def("Margin bridge", "Explaining the move from operating margin to net margin line by line."),
      h2("Practice"),
      practice([
        { q: "Revenue ₹320 crore, net profit ₹22.4 crore. Compute the net margin.", a: "22.4 ÷ 320 = 7.0%." },
        { q: "Operating margin is flat at 15% but net margin fell from 10% to 6%. Name the two most likely causes and how to distinguish them.", a: "Higher interest (check the debt balance and interest expense) or a higher effective tax rate (compute tax ÷ profit before tax for both years). Both sit below EBIT, which is why operating margin did not move." },
        { q: "Why is net margin the least useful margin for comparing two companies' operating skill?", a: "It bundles operating performance with financing structure, tax position and one-off items. Two identically-run businesses can show very different net margins purely because one borrowed and the other did not." },
      ]),
      h2("Sandbox"),
      sandbox("profit-bridge", "Net margin sandbox",
        "Hold revenue and costs fixed, then raise interest and the tax rate — operating profit will not move while net profit falls.", [
        { key: "revenue", label: "Revenue", value: 6000000000, unit: "₹" },
        { key: "cogs", label: "Direct costs", value: 3600000000, unit: "₹" },
        { key: "opex", label: "Operating costs", value: 1560000000, unit: "₹" },
        { key: "interest", label: "Interest", value: 180000000, unit: "₹" },
        { key: "taxRate", label: "Tax rate", value: 25, unit: "%" },
      ]),
      h2("What to remember"),
      note([
        "Net margin = net profit ÷ revenue — the most complete and least diagnostic margin.",
        "Compare it with operating margin to see whether a change came from operations or from below the line.",
        "Thin net margins leave no room for shocks.",
        "One-off items distort it badly; strip them before drawing conclusions.",
      ]),
      h2("Common mistakes"),
      list([
        "<strong>Judging operating quality by net margin.</strong> Financing and tax are in it.",
        "<strong>Comparing net margins across industries.</strong> Grocery retail and software are not comparable.",
        "<strong>Missing a one-off gain</strong> that inflated the margin for a single year.",
        "<strong>Assuming a higher net margin means a better investment.</strong> Price paid decides that.",
      ]),
      mcq("Net profit ₹45 crore on revenue ₹500 crore. Net margin is:",
        ["4.5%", "9%", "11%", "45%"], 1,
        [W, "Correct. 45 ÷ 500 = 9%.", W, W]),
      mcq("Operating margin is unchanged but net margin dropped sharply. The cause is most likely:",
        ["Falling prices", "Higher interest or tax — both sit below operating profit", "Rising COGS", "Lower revenue"], 1,
        [W, "Correct. Anything above EBIT would have moved the operating margin too, so the cause lies below it.", W, W]),
      mcq("A company reports a 20% net margin, boosted by selling a building. For forecasting next year you should:",
        ["Use 20%", "Exclude the gain and use the underlying margin", "Double it", "Ignore margins entirely"], 1,
        [W, "Correct. The gain will not repeat, so the underlying margin is the basis for any forecast.", W, W]),
    ]);

  lesson("c-roa", "ROA",
    "Return on assets: how much profit the company squeezes out of everything it owns.",
    [
      h2("What is this?"),
      p("Return on assets is net profit divided by total assets. It measures how productively a business uses its entire asset base — factories, stock, receivables, cash — regardless of who funded them."),
      p("It answers a simple question: for every ₹100 of assets on the balance sheet, how many rupees of profit does this business produce a year?"),
      h2("Why does it matter?"),
      p("ROA exposes businesses that generate profit only by piling on assets. Two firms may both earn ₹50 crore, but if one needs ₹200 crore of assets and the other ₹1,000 crore, the first is five times as efficient and needs far less capital to grow."),
      p("It also travels well across companies of different sizes, and it is the base of the DuPont decomposition: ROA = net margin × asset turnover, which separates <em>selling profitably</em> from <em>using assets intensively</em>."),
      h2("How does it work?"),
      h3("Step 1: Take net profit for the period"),
      p("From the income statement."),
      h3("Step 2: Take total assets"),
      p("Ideally the average of opening and closing balances, since profit is earned across the year while the balance sheet is a snapshot."),
      h3("Step 3: Divide"),
      p("Net profit ÷ average total assets."),
      h3("Step 4: Decompose it"),
      p("ROA = (net profit ÷ revenue) × (revenue ÷ assets). The first term is margin; the second is turnover. Most businesses win on one and lose on the other."),
      formula("Return on assets and its decomposition", [
        "<b>ROA = Net profit ÷ Average total assets</b>",
        "<b>ROA = Net margin × Asset turnover</b>",
        "Net margin = net profit ÷ revenue",
        "Asset turnover = revenue ÷ average total assets",
      ]),
      caseStudy("Real-Life Case Study: two routes to the same ROA",
        ["A jeweller and a supermarket both earn a 6% return on assets, by opposite means."],
        [["Jeweller — net margin", "12.0%"], ["Jeweller — asset turnover", "0.5x"], ["Jeweller — ROA", "6.0%"],
         ["Supermarket — net margin", "1.5%"], ["Supermarket — asset turnover", "4.0x"], ["Supermarket — ROA", "6.0%"]],
        ["The jeweller sells slowly at a fat margin; the supermarket sells fast at a thin one. Both convert assets into profit at the same rate.",
         "This is why margin alone never settles which business is better. It also predicts their risks: the supermarket is destroyed by a small margin squeeze, the jeweller by stock that stops selling."]),
      h2("Key terms"),
      def("ROA", "Return on assets — net profit divided by average total assets."),
      def("Asset turnover", "Revenue divided by assets. How many rupees of sales each rupee of assets generates."),
      def("DuPont decomposition", "Splitting a return measure into margin, turnover and leverage to see what drives it."),
      def("Average balance", "The mean of opening and closing balance sheet figures, used because profit accrues over the whole period."),
      h2("Practice"),
      practice([
        { q: "Net profit ₹36 crore, opening assets ₹420 crore, closing assets ₹480 crore. Compute ROA.", a: "Average assets = (420 + 480) ÷ 2 = ₹450 crore. ROA = 36 ÷ 450 = 8.0%." },
        { q: "A company has a 3% net margin and asset turnover of 2.5x. Compute ROA, and say what would have to change to reach 10%.", a: "ROA = 3% × 2.5 = 7.5%. To reach 10% it needs either margin up to 4% at the same turnover, or turnover up to 3.33x at the same margin — or a combination. Which is achievable depends on the industry's structure." },
        { q: "Why does ROA usually fall immediately after a large acquisition, even a sensible one?", a: "The acquired assets and goodwill land on the balance sheet at once, while the profit contribution and any synergies arrive gradually. The denominator jumps before the numerator does, so ROA dips before recovering — if the deal works." },
      ]),
      h2("Sandbox"),
      sandbox("leverage-returns", "Return sandbox",
        "Compare the all-equity return — profit over total capital, the ROA idea — with the levered owner return as you add debt.", [
        { key: "operatingProfit", label: "Profit before interest", value: 360000000, unit: "₹" },
        { key: "debt", label: "Debt", value: 1800000000, unit: "₹" },
        { key: "interestRate", label: "Interest rate", value: 10, unit: "%" },
        { key: "equity", label: "Equity", value: 2700000000, unit: "₹" },
      ]),
      h2("What to remember"),
      note([
        "ROA = net profit ÷ average total assets.",
        "ROA = net margin × asset turnover — always decompose before judging.",
        "High margin and low turnover can equal low margin and high turnover.",
        "Use average assets, not the closing snapshot, when the balance sheet moved a lot.",
      ]),
      h2("Common mistakes"),
      list([
        "<strong>Comparing ROA across industries.</strong> Asset needs differ enormously by sector.",
        "<strong>Using closing assets after a big acquisition,</strong> which understates ROA sharply.",
        "<strong>Ignoring the decomposition</strong> and treating margin as the whole story.",
        "<strong>Confusing ROA with ROE.</strong> ROA ignores how assets were funded; ROE does not.",
      ]),
      mcq("Net profit ₹20 crore, average total assets ₹250 crore. ROA is:",
        ["4%", "8%", "12.5%", "20%"], 1,
        [W, "Correct. 20 ÷ 250 = 8%.", W, W]),
      mcq("A supermarket has a 1.5% net margin and 4.0x asset turnover. Its ROA is:",
        ["1.5%", "6.0%", "4.0%", "2.7%"], 1,
        [W, "Correct. ROA = margin × turnover = 1.5% × 4.0 = 6.0%. Thin margins with fast turnover produce a respectable return.", W, W]),
      mcq("ROA differs from ROE because ROA:",
        ["Uses revenue instead of profit", "Ignores how the assets were financed", "Excludes tax", "Is always higher"], 1,
        [W, "Correct. ROA measures the whole asset base regardless of funding; ROE measures the return on the owners' slice only.", W, W]),
    ]);

  lesson("c-roic", "ROIC",
    "The return the business earns on the money actually invested in it — the number that decides whether growth creates value.",
    [
      h2("What is this?"),
      p("Return on invested capital is after-tax operating profit divided by the capital invested in operations — debt plus equity, less surplus cash. It measures what the business earns on the money put into it, before deciding how that money was split between lenders and owners."),
      p("It differs from ROE, which is inflated by borrowing, and from ROA, which counts every asset including idle cash."),
      h2("Why does it matter?"),
      p("ROIC compared with the cost of capital is the single clearest test of whether a company creates value. If it earns 18% on capital costing 12%, every rupee reinvested adds value. If it earns 8% on capital costing 12%, growth actively destroys value — the company would serve shareholders better by shrinking."),
      p("This is why two companies growing at the same rate can be worth wildly different amounts. Growth is only valuable when ROIC exceeds the cost of capital."),
      h2("How does it work?"),
      h3("Step 1: Compute NOPAT"),
      p("Net operating profit after tax = EBIT × (1 − tax rate). Using EBIT keeps financing out of the numerator."),
      h3("Step 2: Compute invested capital"),
      p("Total debt + equity − surplus cash. Equivalently, the operating assets the business actually uses."),
      h3("Step 3: Divide"),
      p("NOPAT ÷ invested capital."),
      h3("Step 4: Compare with the cost of capital"),
      p("The spread between ROIC and the weighted cost of capital, multiplied by the capital invested, is roughly the value created each year."),
      formula("ROIC and value creation", [
        "<b>ROIC = EBIT × (1 − tax rate) ÷ Invested capital</b>",
        "<b>Invested capital = Debt + Equity − Surplus cash</b>",
        "<b>Value created ≈ (ROIC − Cost of capital) × Invested capital</b>",
      ]),
      caseStudy("Real-Life Case Study: growth that destroys value",
        ["Two firms each reinvest ₹100 crore a year and grow revenue 15%. Their cost of capital is 12%."],
        [["Firm A — ROIC", "19%"], ["Firm A — spread over cost of capital", "+7 points"], ["Firm A — value created on ₹100 cr", "₹7 crore/yr"],
         ["Firm B — ROIC", "8%"], ["Firm B — spread", "−4 points"], ["Firm B — value created on ₹100 cr", "−₹4 crore/yr"]],
        ["Identical growth rates, opposite outcomes. Firm A's expansion makes shareholders richer each year; Firm B's makes them poorer while reporting rising profits.",
         "Firm B is not badly managed in an obvious way — revenue and profit both grow. The damage is invisible unless you compare the return on the capital consumed with what that capital costs."]),
      h2("Key terms"),
      def("NOPAT", "Net operating profit after tax — EBIT adjusted for tax, excluding financing effects."),
      def("Invested capital", "Debt plus equity less surplus cash; the money actually funding operations."),
      def("Cost of capital", "The blended return lenders and shareholders require — the hurdle ROIC must clear."),
      def("Spread", "ROIC minus cost of capital. Positive creates value; negative destroys it."),
      h2("Practice"),
      practice([
        { q: "EBIT ₹90 crore, tax rate 25%, invested capital ₹500 crore. Compute ROIC.", a: "NOPAT = 90 × 0.75 = ₹67.5 crore. ROIC = 67.5 ÷ 500 = 13.5%." },
        { q: "With a 12% cost of capital, how much value does the company above create on its ₹500 crore?", a: "Spread = 13.5% − 12% = 1.5 points. Value created ≈ 1.5% × 500 = ₹7.5 crore a year. Positive but thin — a small deterioration in ROIC would wipe it out." },
        { q: "A company earning 7% ROIC against a 12% cost of capital announces a large expansion. What should shareholders expect?", a: "Reported revenue and probably profit will rise, so headlines will look positive. But each rupee invested earns 7 and costs 12, so the expansion destroys about 5 paise of value per rupee per year. Shareholders would be better served by the company returning that capital instead." },
      ]),
      h2("Sandbox"),
      sandbox("leverage-returns", "Capital return sandbox",
        "The all-equity return is the ROIC idea: profit over total capital. Add debt and see the owner return diverge while the underlying business return does not.", [
        { key: "operatingProfit", label: "Operating profit (EBIT)", value: 900000000, unit: "₹" },
        { key: "debt", label: "Debt", value: 2000000000, unit: "₹" },
        { key: "interestRate", label: "Interest rate", value: 11, unit: "%" },
        { key: "equity", label: "Equity", value: 3000000000, unit: "₹" },
      ]),
      h2("What to remember"),
      note([
        "ROIC = after-tax operating profit ÷ invested capital.",
        "Growth creates value only when ROIC exceeds the cost of capital.",
        "It excludes financing effects, so it is not inflated by leverage the way ROE is.",
        "A company with a persistently negative spread should shrink, not grow.",
      ]),
      h2("Common mistakes"),
      list([
        "<strong>Assuming growth is always good.</strong> Below the cost of capital it destroys value.",
        "<strong>Using net profit in the numerator.</strong> That reintroduces the financing effects ROIC is designed to exclude.",
        "<strong>Forgetting to remove surplus cash</strong> from invested capital, which understates the return.",
        "<strong>Comparing ROIC with the interest rate alone.</strong> The hurdle is the blended cost of debt and equity.",
      ]),
      mcq("EBIT ₹120 crore, tax 25%, invested capital ₹600 crore. ROIC is:",
        ["20%", "15%", "12%", "25%"], 1,
        [W, "Correct. NOPAT = 120 × 0.75 = ₹90 crore; 90 ÷ 600 = 15%.", W, W]),
      mcq("A firm earns 9% ROIC with a 13% cost of capital. Growing faster will:",
        ["Create value quickly", "Destroy value — each rupee invested earns less than it costs", "Have no effect on value", "Reduce risk"], 1,
        [W, "Correct. A negative spread means growth consumes capital at a loss, however healthy the profit line looks.", W, W]),
      mcq("Why is ROIC preferred to ROE when judging business quality?",
        ["It is easier to calculate", "It is not inflated by borrowing, so it measures the business rather than the financing", "It ignores tax", "It always gives a higher number"], 1,
        [W, "Correct. ROE rises with leverage even when operations are unchanged; ROIC isolates the return the operations themselves produce.", W, W]),
    ]);

  lesson("c-asset-turnover", "Asset turnover",
    "How many rupees of sales each rupee of assets produces — the volume half of returns.",
    [
      h2("What is this?"),
      p("Asset turnover is revenue divided by average total assets. If a company has ₹200 crore of assets and generates ₹400 crore of sales, its asset turnover is 2.0x — every rupee of assets produces two rupees of revenue a year."),
      p("It measures intensity of use, not profitability. A business can turn assets rapidly and still lose money if its margins are negative."),
      h2("Why does it matter?"),
      p("Turnover is the other half of return on assets. Margin tells you how much profit each sale carries; turnover tells you how many sales the asset base can support. Weak margins with high turnover is a perfectly viable model — it is how supermarkets and distributors operate."),
      p("It also flags trouble early. Falling turnover means assets are growing faster than sales — usually inventory piling up, receivables stretching, or a new plant not yet producing."),
      h2("How does it work?"),
      h3("Step 1: Take revenue for the period"),
      p("The full year's sales."),
      h3("Step 2: Take average total assets"),
      p("Average opening and closing, since revenue accrues over the year."),
      h3("Step 3: Divide"),
      p("Revenue ÷ average total assets, expressed as a multiple."),
      h3("Step 4: Look at which assets moved"),
      p("If turnover is falling, find out whether it is inventory, receivables or fixed assets. Each implies a different problem."),
      formula("Asset turnover", [
        "<b>Asset turnover = Revenue ÷ Average total assets</b>",
        "<b>ROA = Net margin × Asset turnover</b>",
      ]),
      caseStudy("Real-Life Case Study: a new plant's drag",
        ["A manufacturer commissions a large plant in year 2 that will not run at full capacity until year 4."],
        [["Year 1 revenue", "₹500 crore"], ["Year 1 average assets", "₹400 crore"], ["Year 1 asset turnover", "1.25x"],
         ["Year 2 revenue", "₹540 crore"], ["Year 2 average assets", "₹620 crore"], ["Year 2 asset turnover", "0.87x"]],
        ["Revenue grew 8%, but the asset base grew 55%, so turnover fell by nearly a third and ROA fell with it.",
         "This is expected and temporary if the plant fills up. It becomes a real problem if revenue never catches up with the capacity built — which is exactly the risk of large expansions financed on optimism."]),
      h2("Key terms"),
      def("Asset turnover", "Revenue divided by average total assets — sales generated per rupee of assets."),
      def("Fixed asset turnover", "Revenue divided by net fixed assets only, isolating plant productivity."),
      def("Capacity utilisation", "How much of the available productive capacity is actually being used."),
      def("Asset-light model", "A business structured to generate revenue with minimal owned assets, producing high turnover."),
      h2("Practice"),
      practice([
        { q: "Revenue ₹720 crore, opening assets ₹560 crore, closing assets ₹640 crore. Compute asset turnover.", a: "Average assets = (560 + 640) ÷ 2 = ₹600 crore. Turnover = 720 ÷ 600 = 1.2x." },
        { q: "Asset turnover fell from 1.8x to 1.3x while revenue was flat. What happened and what would you check?", a: "Assets grew roughly 38% with no revenue gain. Check whether it was inventory building up (demand weakening), receivables stretching (collection or channel-stuffing problems), or a new fixed asset not yet productive. Each has a different remedy and a different severity." },
        { q: "Why do distributors typically have far higher asset turnover than manufacturers, and what must they accept in return?", a: "Distributors own little productive plant — mainly stock and receivables — so revenue per rupee of assets is high. In exchange they earn thin margins, because they add less transformation to the product. High turnover and low margin is the structural trade." },
      ]),
      h2("What to remember"),
      note([
        "Asset turnover = revenue ÷ average total assets.",
        "It is the volume half of ROA; margin is the other half.",
        "Low margin with high turnover is a legitimate and common model.",
        "Falling turnover means assets are outgrowing sales — always find out which assets.",
      ]),
      h2("Common mistakes"),
      list([
        "<strong>Treating high turnover as good in itself.</strong> It says nothing about profitability.",
        "<strong>Comparing turnover across industries.</strong> Structural asset needs differ enormously.",
        "<strong>Using closing assets in a year with heavy capex,</strong> which understates turnover.",
        "<strong>Panicking at a dip caused by new capacity</strong> that has not yet ramped up.",
      ]),
      mcq("Revenue ₹900 crore, average total assets ₹450 crore. Asset turnover is:",
        ["0.5x", "2.0x", "4.5x", "20%"], 1,
        [W, "Correct. 900 ÷ 450 = 2.0x — every rupee of assets generates two rupees of sales.", W, W]),
      mcq("Net margin 2% and asset turnover 3.5x. ROA is:",
        ["2%", "7%", "3.5%", "17.5%"], 1,
        [W, "Correct. ROA = 2% × 3.5 = 7%. Thin margins can still deliver a solid return when assets turn quickly.", W, W]),
      mcq("Asset turnover falls sharply while revenue is unchanged. The most likely cause is:",
        ["Prices rose", "The asset base grew — new capacity, more stock or higher receivables", "Interest costs rose", "Tax rates changed"], 1,
        [W, "Correct. With revenue flat, only a larger denominator can reduce the ratio, so something on the asset side has grown.", W, W]),
    ]);

  /* ================= LIQUIDITY & LEVERAGE ================= */

  lesson("c-quick-ratio", "Quick ratio",
    "Can the company pay its short-term bills without having to sell any stock first?",
    [
      h2("What is this?"),
      p("The quick ratio — sometimes called the acid-test — compares the assets that can become cash quickly with the liabilities due within a year. It is the current ratio with inventory removed."),
      p("The reason for removing inventory is simple: unsold stock is the least certain current asset. In a crisis it sells slowly and at a discount, exactly when cash is needed most."),
      h2("Why does it matter?"),
      p("It is a stricter and more honest liquidity test than the current ratio for any business carrying significant stock. A retailer can show a comfortable current ratio of 2.0 and a quick ratio of 0.4, meaning it cannot meet near-term obligations unless the stock actually sells."),
      p("Liquidity failures are what kill companies, not unprofitability, so a measure that assumes stock is as good as cash is dangerous."),
      h2("How does it work?"),
      h3("Step 1: Take current assets"),
      p("Cash, short-term investments, receivables, inventory, prepayments."),
      h3("Step 2: Remove inventory and prepayments"),
      p("What is left — cash, marketable securities and receivables — are the 'quick' assets."),
      h3("Step 3: Divide by current liabilities"),
      p("Payables, short-term borrowings, accrued expenses, the current portion of long-term debt."),
      h3("Step 4: Interpret in context"),
      p("Around 1.0 means quick assets just cover near-term obligations. Below that is not automatically fatal — a supermarket collects cash instantly and can run far below 1 safely — but it demands an explanation."),
      formula("Quick ratio", [
        "<b>Quick ratio = (Cash + Marketable securities + Receivables) ÷ Current liabilities</b>",
        "<b>Current ratio = Current assets ÷ Current liabilities</b>",
        "The difference between them is inventory and prepayments",
      ]),
      caseStudy("Real-Life Case Study: a fashion retailer",
        ["Seasonal stock dominates the balance sheet."],
        [["Cash", "₹8 crore"], ["Receivables", "₹12 crore"], ["Inventory", "₹70 crore"], ["Current assets", "₹90 crore"], ["Current liabilities", "₹50 crore"], ["Current ratio", "1.80"], ["Quick ratio", "0.40"]],
        ["The current ratio of 1.8 looks reassuring. The quick ratio of 0.4 says something quite different: without selling stock, the company can cover only 40% of what falls due within the year.",
         "If the season goes badly and the stock must be discounted 50%, the apparent cushion largely evaporates. For inventory-heavy businesses the quick ratio is the number that matters."]),
      h2("Key terms"),
      def("Quick assets", "Cash, marketable securities and receivables — current assets convertible to cash quickly and at predictable value."),
      def("Current liabilities", "Obligations due within one year."),
      def("Acid-test", "Another name for the quick ratio."),
      def("Liquidity", "The ability to meet obligations as they fall due — a matter of timing, not profitability."),
      h2("Practice"),
      practice([
        { q: "Cash ₹15 crore, receivables ₹35 crore, inventory ₹60 crore, current liabilities ₹70 crore. Compute both the current and quick ratios.", a: "Current ratio = (15 + 35 + 60) ÷ 70 = 1.57. Quick ratio = (15 + 35) ÷ 70 = 0.71. The gap of 0.86 is entirely inventory." },
        { q: "A software firm has a quick ratio of 0.6 and a supermarket has 0.3. Which is more concerning, and why?", a: "The software firm. Supermarkets collect cash at the till and pay suppliers later, so they operate on negative working capital by design and a low quick ratio is structural. A software firm with slow receivables and a 0.6 has genuinely less cover for its near-term obligations." },
        { q: "Why can a company with a quick ratio above 1.0 still fail to pay a bill next week?", a: "The ratio treats all current items as equivalent within a year. If receivables are due in 80 days and the payment is due in 7, the timing does not line up. Ratios are annual snapshots; solvency is a question of specific dates." },
      ]),
      h2("Sandbox"),
      sandbox("working-capital", "Liquidity sandbox",
        "Push inventory up and receivables down and watch working capital hold steady — even though the quick position has quietly worsened.", [
        { key: "inventory", label: "Inventory", value: 700000000, unit: "₹" },
        { key: "receivables", label: "Receivables", value: 120000000, unit: "₹" },
        { key: "payables", label: "Payables", value: 500000000, unit: "₹" },
      ]),
      h2("What to remember"),
      note([
        "Quick ratio = (cash + securities + receivables) ÷ current liabilities.",
        "It removes inventory because stock is the least reliable current asset.",
        "For inventory-heavy businesses it is far more informative than the current ratio.",
        "Interpret it against the business model — some models run safely below 1.0.",
      ]),
      h2("Common mistakes"),
      list([
        "<strong>Applying a universal benchmark.</strong> The right level depends on how fast the business collects and pays.",
        "<strong>Trusting the current ratio alone</strong> in a business whose current assets are mostly stock.",
        "<strong>Treating receivables as certain.</strong> A large overdue or concentrated receivable is not quick.",
        "<strong>Reading a ratio as a payment schedule.</strong> Timing within the year is invisible to it.",
      ]),
      mcq("Cash ₹20 crore, receivables ₹30 crore, inventory ₹50 crore, current liabilities ₹40 crore. The quick ratio is:",
        ["2.5", "1.25", "1.0", "0.8"], 1,
        [W, "Correct. (20 + 30) ÷ 40 = 1.25. Inventory is excluded.", W, W]),
      mcq("The quick ratio excludes inventory because:",
        ["Inventory is not an asset", "Stock may sell slowly and at a discount exactly when cash is needed", "Inventory is always overstated", "Accounting rules require it"], 1,
        [W, "Correct. Its convertibility to cash is the least certain of all current assets, so a strict liquidity test leaves it out.", W, W]),
      mcq("A retailer shows a current ratio of 2.0 and a quick ratio of 0.35. This means:",
        ["It has plenty of cash", "Almost all of its current assets are inventory", "It has no liabilities", "Its receivables are very large"], 1,
        [W, "Correct. The large gap between the two ratios is inventory, so near-term obligations depend on that stock actually selling.", W, W]),
    ]);

  lesson("c-net-debt-ebitda", "Net debt/EBITDA",
    "Roughly how many years of operating earnings it would take to repay the borrowings.",
    [
      h2("What is this?"),
      p("Net debt to EBITDA compares borrowings, less cash on hand, with annual operating earnings. A ratio of 3.0x means the company owes about three years of EBITDA."),
      p("Cash is netted off because a company holding ₹100 crore against ₹300 crore of debt is genuinely less indebted than one with no cash at all."),
      h2("Why does it matter?"),
      p("It is the standard measure of leverage in lending and credit analysis, and most loan covenants are written against it. Breaching the agreed level can make long-term debt immediately repayable, which is how a manageable situation becomes a crisis."),
      p("It is also the most intuitive leverage measure: it converts a large, abstract debt number into a number of years, which is far easier to reason about than an absolute rupee figure."),
      h2("How does it work?"),
      h3("Step 1: Compute net debt"),
      p("Total borrowings − cash and cash equivalents. Include short-term debt and lease liabilities."),
      h3("Step 2: Take EBITDA for the last twelve months"),
      p("Trailing figures, not forecasts, for a credit view."),
      h3("Step 3: Divide"),
      p("Net debt ÷ EBITDA, expressed as a multiple."),
      h3("Step 4: Judge it against the business's stability"),
      p("A regulated utility with predictable cash flows can carry 5x safely. A cyclical commodity producer at 5x is in danger, because EBITDA can halve in a downturn and the ratio doubles without any new borrowing."),
      formula("Net debt / EBITDA", [
        "<b>Net debt = Total debt − Cash and equivalents</b>",
        "<b>Leverage = Net debt ÷ EBITDA</b>",
      ]),
      caseStudy("Real-Life Case Study: a cyclical downturn",
        ["A commodity producer borrows at what looks like a comfortable level, then demand falls."],
        [["Total debt", "₹900 crore"], ["Cash", "₹100 crore"], ["Net debt", "₹800 crore"], ["EBITDA — good year", "₹320 crore"], ["Leverage — good year", "2.5x"], ["EBITDA — downturn", "₹160 crore"], ["Leverage — downturn", "5.0x"]],
        ["Not one rupee of new debt was borrowed. EBITDA halved, and leverage doubled.",
         "If the loan covenant caps leverage at 4.0x, the company is now in breach and the lenders can demand repayment — in the worst possible year. This is why cyclical businesses must borrow far less than their good-year earnings appear to support."]),
      h2("Key terms"),
      def("Net debt", "Total borrowings less cash and equivalents."),
      def("Leverage ratio", "Net debt divided by EBITDA — a measure of indebtedness in years of earnings."),
      def("Covenant", "A contractual limit, often on leverage, that a borrower must keep meeting."),
      def("Headroom", "The gap between the current ratio and the covenant limit — the cushion before breach."),
      h2("Practice"),
      practice([
        { q: "Total debt ₹450 crore, cash ₹90 crore, EBITDA ₹120 crore. Compute net debt and leverage.", a: "Net debt = 450 − 90 = ₹360 crore. Leverage = 360 ÷ 120 = 3.0x." },
        { q: "The covenant caps leverage at 3.5x. How far can EBITDA fall before breach?", a: "Breach occurs when 360 ÷ EBITDA = 3.5, so EBITDA = ₹102.9 crore. That is a fall of about 14% from ₹120 crore — thin headroom for any business with volatile earnings." },
        { q: "Why is a 5.0x leverage acceptable for a regulated water utility but alarming for a steel producer?", a: "The utility's cash flows are contracted and stable, so EBITDA barely moves and the ratio stays put. Steel EBITDA can halve in a cyclical trough, doubling the ratio without new borrowing and triggering covenants precisely when refinancing is hardest." },
      ]),
      h2("Sandbox"),
      sandbox("leverage-returns", "Leverage sandbox",
        "Halve operating profit, as a downturn would, and watch the owners' return collapse while the interest bill does not move.", [
        { key: "operatingProfit", label: "Operating profit", value: 3200000000, unit: "₹" },
        { key: "debt", label: "Net debt", value: 8000000000, unit: "₹" },
        { key: "interestRate", label: "Interest rate", value: 10, unit: "%" },
        { key: "equity", label: "Equity", value: 6000000000, unit: "₹" },
      ]),
      h2("What to remember"),
      note([
        "Net debt / EBITDA ≈ how many years of operating earnings the debt represents.",
        "Cash is netted off because it could repay debt tomorrow.",
        "The safe level depends entirely on how stable the earnings are.",
        "In a downturn the ratio worsens through the denominator, with no new borrowing at all.",
      ]),
      h2("Common mistakes"),
      list([
        "<strong>Applying one benchmark to every industry.</strong> Stability of EBITDA is what sets the safe level.",
        "<strong>Sizing debt against peak-cycle earnings.</strong> The ratio is measured in the trough too.",
        "<strong>Ignoring covenant headroom.</strong> A breach can accelerate repayment of everything.",
        "<strong>Forgetting lease liabilities</strong>, which are debt-like obligations under current standards.",
      ]),
      mcq("Total debt ₹600 crore, cash ₹150 crore, EBITDA ₹150 crore. Net debt / EBITDA is:",
        ["4.0x", "3.0x", "5.0x", "1.5x"], 1,
        [W, "Correct. Net debt = 600 − 150 = ₹450 crore; 450 ÷ 150 = 3.0x.", W, W]),
      mcq("A company's EBITDA halves while its debt is unchanged. Leverage will:",
        ["Halve", "Double", "Stay the same", "Fall slightly"], 1,
        [W, "Correct. The denominator halved, so the ratio doubles — leverage worsens sharply without borrowing a rupee.", W, W]),
      mcq("Why is cash subtracted when measuring leverage?",
        ["To make the ratio look better", "Because cash on hand could repay debt immediately, so it offsets the obligation", "Because cash earns interest", "Regulators require it"], 1,
        [W, "Correct. A borrower holding large cash balances is genuinely less indebted than one with none, so net debt is the meaningful figure.", W, W]),
    ]);

  lesson("c-interest-coverage", "Interest coverage",
    "How many times over the operating profit covers the interest bill — the first test of whether debt is safe.",
    [
      h2("What is this?"),
      p("Interest coverage is EBIT divided by interest expense. A coverage of 4.0x means operating profit is four times the annual interest bill, so profit could fall 75% before interest became exactly unaffordable."),
      p("It is a margin-of-safety measure rather than a profitability measure: it asks how much can go wrong before a fixed obligation cannot be met."),
      h2("Why does it matter?"),
      p("Interest is contractual. It falls due whether the year was excellent or catastrophic, which is exactly what makes debt dangerous. Coverage translates a debt load into the terms that matter: how much cushion exists."),
      p("It complements net debt/EBITDA. That ratio measures the size of the debt; coverage measures the affordability of carrying it. A company can look moderately geared and still have thin coverage if its borrowing is expensive."),
      h2("How does it work?"),
      h3("Step 1: Take EBIT"),
      p("Operating profit, after depreciation — the profit genuinely available before financing."),
      h3("Step 2: Take interest expense"),
      p("The gross interest cost for the period, not net of interest income."),
      h3("Step 3: Divide"),
      p("EBIT ÷ interest expense, expressed as a multiple."),
      h3("Step 4: Stress it"),
      p("Ask what coverage would be if EBIT fell 30% or 50%. That answer, not the current figure, is the risk assessment."),
      formula("Interest coverage", [
        "<b>Interest coverage = EBIT ÷ Interest expense</b>",
        "<b>Cash coverage = (EBIT + Depreciation) ÷ Interest expense</b>",
      ]),
      caseStudy("Real-Life Case Study: stress-testing two borrowers",
        ["Both companies pay ₹20 crore of interest a year."],
        [["Firm A — EBIT", "₹120 crore"], ["Firm A — coverage", "6.0x"], ["Firm A — coverage if EBIT falls 40%", "3.6x"],
         ["Firm B — EBIT", "₹36 crore"], ["Firm B — coverage", "1.8x"], ["Firm B — coverage if EBIT falls 40%", "1.1x"]],
        ["In a good year both pay their interest without difficulty. The difference only appears under stress.",
         "After a 40% earnings fall, Firm A still covers interest 3.6 times; Firm B is at 1.1x, with essentially nothing left for tax, capex or owners. Firm B is one bad quarter from distress, and its current 1.8x barely hints at it."]),
      h2("Key terms"),
      def("Interest coverage", "EBIT divided by interest expense — how many times operating profit covers the interest bill."),
      def("Cash coverage", "A variant adding depreciation back, since it is a non-cash charge."),
      def("Fixed charge", "An obligation that does not vary with performance — interest is the classic example."),
      def("Stress test", "Recomputing a ratio under a deliberately adverse assumption to find the breaking point."),
      h2("Practice"),
      practice([
        { q: "EBIT ₹84 crore, interest expense ₹21 crore. Compute interest coverage and the fall in EBIT that would take it to 1.0x.", a: "Coverage = 84 ÷ 21 = 4.0x. Coverage reaches 1.0x when EBIT equals ₹21 crore — a fall of 75%." },
        { q: "Two firms both have net debt/EBITDA of 3.0x, but one has 5x interest coverage and the other 1.9x. How is that possible, and which is riskier?", a: "The second borrows at a much higher interest rate, or has higher depreciation reducing EBIT relative to EBITDA. It is riskier: the debt is the same size relative to earnings, but affording it consumes far more of the operating profit." },
        { q: "Why might cash coverage be the more relevant test for a capital-intensive company in a bad year?", a: "Depreciation is a non-cash charge, so cash available to pay interest exceeds EBIT. In a short downturn a company can service interest from cash flow while deferring capex. It is only a temporary reprieve — the assets still need replacing eventually." },
      ]),
      h2("Sandbox"),
      sandbox("profit-bridge", "Coverage sandbox",
        "Reduce revenue step by step until profit before tax turns negative — the point at which operating profit no longer covers interest.", [
        { key: "revenue", label: "Revenue", value: 3600000000, unit: "₹" },
        { key: "cogs", label: "Direct costs", value: 2160000000, unit: "₹" },
        { key: "opex", label: "Operating costs incl. depreciation", value: 1080000000, unit: "₹" },
        { key: "interest", label: "Interest", value: 200000000, unit: "₹" },
        { key: "taxRate", label: "Tax rate", value: 25, unit: "%" },
      ]),
      h2("What to remember"),
      note([
        "Interest coverage = EBIT ÷ interest expense.",
        "It measures cushion, not profitability.",
        "Read it with net debt/EBITDA: one sizes the debt, the other tests affordability.",
        "The useful number is coverage under stress, not coverage today.",
      ]),
      h2("Common mistakes"),
      list([
        "<strong>Judging safety by today's coverage</strong> without asking what a downturn does to it.",
        "<strong>Netting interest income against interest expense,</strong> which flatters the ratio.",
        "<strong>Ignoring principal repayments.</strong> Coverage tests interest only; maturities can still sink the company.",
        "<strong>Assuming high coverage means low risk.</strong> A concentrated customer base can remove EBIT quickly.",
      ]),
      mcq("EBIT ₹60 crore, interest expense ₹15 crore. Interest coverage is:",
        ["0.25x", "4.0x", "45x", "75x"], 1,
        [W, "Correct. 60 ÷ 15 = 4.0x — operating profit covers interest four times over.", W, W]),
      mcq("Interest coverage of 1.2x means:",
        ["The company is very safe", "Operating profit only just covers interest, leaving almost nothing for tax, capex or owners", "There is no debt", "Interest has been paid in advance"], 1,
        [W, "Correct. A small earnings decline would leave interest uncovered — a precarious position.", W, W]),
      mcq("Interest coverage tests the affordability of interest but ignores:",
        ["Revenue", "Principal repayments falling due", "Depreciation", "Tax rates"], 1,
        [W, "Correct. A company can cover interest comfortably and still default on a large maturing principal repayment.", W, W]),
    ]);

  /* ================= CASH & OPERATING ANALYSIS ================= */

  lesson("c-working-capital-analysis", "Working capital analysis",
    "Diagnosing where a company's cash is trapped, and whether the trap is getting bigger.",
    [
      h2("What is this?"),
      p("Working capital analysis breaks the working capital figure into its three drivers — inventory, receivables and payables — and converts each into days, so changes can be diagnosed rather than merely observed."),
      p("The totals tell you cash moved. The day metrics tell you why, and whose behaviour changed: customers, suppliers, or the company's own stock management."),
      h2("Why does it matter?"),
      p("Working capital is usually the largest swing factor between profit and cash, and it is the part management can most directly control. Reducing collection time by ten days can release more cash than a year of margin improvement."),
      p("It is also an early warning system. Deteriorating receivable days often mean the company is selling to weaker customers or extending terms to hit sales targets — visible months before it appears in bad debts."),
      h2("How does it work?"),
      h3("Step 1: Convert each component to days"),
      p("Days inventory = inventory ÷ COGS × 365. Days receivable = receivables ÷ revenue × 365. Days payable = payables ÷ COGS × 365."),
      h3("Step 2: Compare with last year and with competitors"),
      p("The direction of travel matters more than the level."),
      h3("Step 3: Quantify the cash effect"),
      p("One extra day of receivables costs roughly revenue ÷ 365 in cash. Multiply by the number of days it moved."),
      h3("Step 4: Attribute the change"),
      p("Stock building up, customers paying slower and suppliers being paid faster all consume cash — but they mean very different things."),
      formula("Working capital days", [
        "<b>Days inventory = Inventory ÷ COGS × 365</b>",
        "<b>Days receivable = Receivables ÷ Revenue × 365</b>",
        "<b>Days payable = Payables ÷ COGS × 365</b>",
        "<b>Cash per extra receivable day ≈ Revenue ÷ 365</b>",
      ]),
      caseStudy("Real-Life Case Study: diagnosing a cash squeeze",
        ["Revenue and margins were flat, yet the company consumed ₹18 crore of cash."],
        [["Revenue", "₹365 crore"], ["Days receivable — last year", "55 days"], ["Days receivable — this year", "73 days"], ["Cash per receivable day", "₹1 crore"], ["Cash consumed by slower collection", "₹18 crore"], ["Days inventory — change", "unchanged"]],
        ["Inventory and payables did not move; the entire ₹18 crore went into customers taking 18 more days to pay.",
         "That is a collections or customer-quality problem, not an operational one. The remedy — tightening credit terms, chasing overdue accounts — is quite different from what a stock build-up would require, which is why the decomposition matters."]),
      h2("Key terms"),
      def("Days inventory outstanding", "How long stock sits before being sold, in days of cost of goods sold."),
      def("Days sales outstanding", "How long customers take to pay, in days of revenue."),
      def("Days payable outstanding", "How long the company takes to pay suppliers, in days of cost of goods sold."),
      def("Cash release", "Cash freed by reducing working capital — a one-off benefit, not recurring income."),
      h2("Practice"),
      practice([
        { q: "Revenue ₹730 crore, receivables ₹120 crore. Compute days sales outstanding and the cash cost of one extra day.", a: "DSO = 120 ÷ 730 × 365 = 60 days. One extra day costs 730 ÷ 365 = ₹2 crore of cash." },
        { q: "COGS ₹500 crore, inventory ₹110 crore, payables ₹75 crore. Compute days inventory and days payable.", a: "Days inventory = 110 ÷ 500 × 365 = 80 days. Days payable = 75 ÷ 500 × 365 = 55 days. Stock sits 25 days longer than the supplier credit funding it, so the gap must be financed." },
        { q: "A company boasts of releasing ₹40 crore from working capital. What should you check before treating this as good news?", a: "Which component moved. Faster collection and leaner stock are genuine improvements. Simply paying suppliers later shifts financing onto suppliers and can damage relationships or signal cash stress. And in every case, the release is one-off — it cannot repeat next year." },
      ]),
      h2("Sandbox"),
      sandbox("receivables-cash", "Collection sandbox",
        "Move collection days up and down and read the cash released or consumed — that is the size of the prize from better collections.", [
        { key: "revenue", label: "Annual revenue", value: 3650000000, unit: "₹" },
        { key: "dsoNow", label: "Current DSO", value: 55, unit: "days" },
        { key: "dsoNew", label: "New DSO", value: 73, unit: "days" },
      ]),
      h2("What to remember"),
      note([
        "Convert inventory, receivables and payables into days before drawing conclusions.",
        "One extra receivable day costs roughly revenue ÷ 365 in cash.",
        "Rising receivable days is an early warning about customer quality or sales pressure.",
        "Working capital releases are one-off; they do not repeat.",
      ]),
      h2("Common mistakes"),
      list([
        "<strong>Looking at the net figure only</strong> and missing which component actually moved.",
        "<strong>Treating a payables-driven release as an improvement.</strong> It is financing shifted onto suppliers.",
        "<strong>Comparing days across industries.</strong> Normal terms differ by sector.",
        "<strong>Projecting a one-off release into future years.</strong>",
      ]),
      mcq("Revenue ₹1,095 crore and receivables ₹180 crore. Days sales outstanding is:",
        ["30 days", "60 days", "90 days", "120 days"], 1,
        [W, "Correct. 180 ÷ 1,095 × 365 = 60 days.", W, W]),
      mcq("Revenue is flat, margins are flat, but cash fell sharply. The first thing to check is:",
        ["The tax rate", "Whether working capital days deteriorated", "The share price", "Dividend policy"], 1,
        [W, "Correct. With profit unchanged, working capital is the usual explanation — and the day metrics show which component caused it.", W, W]),
      mcq("A company reduces its days payable from 60 to 40. The cash effect is:",
        ["Cash is released", "Cash is consumed — suppliers are being paid faster", "No effect", "Profit rises"], 1,
        [W, "Correct. Paying sooner means less supplier funding, so cash leaves the business earlier.", W, W]),
    ]);

  lesson("c-cash-conversion-cycle", "Cash conversion cycle",
    "How many days pass between paying for stock and collecting from the customer.",
    [
      h2("What is this?"),
      p("The cash conversion cycle measures how long a company's cash is tied up in operations: days inventory plus days receivable minus days payable."),
      p("It answers a very physical question. You pay a supplier today; the goods sit in a warehouse; a customer buys them on credit; eventually the money arrives. How many days is your cash out of your hands during that journey?"),
      h2("Why does it matter?"),
      p("The cycle determines how much funding growth requires. A company with a 90-day cycle must finance three months of operations before cash returns; doubling revenue roughly doubles that need."),
      p("A <strong>negative</strong> cycle is a genuinely powerful position: the customer pays before the supplier is paid, so growth generates cash instead of consuming it. Supermarkets and many online marketplaces operate this way, effectively funded by their suppliers."),
      h2("How does it work?"),
      h3("Step 1: Days inventory outstanding"),
      p("How long stock sits before it sells."),
      h3("Step 2: Days sales outstanding"),
      p("How long customers take to pay after the sale."),
      h3("Step 3: Days payable outstanding"),
      p("How long the company takes to pay its own suppliers — this funds part of the cycle."),
      h3("Step 4: Combine"),
      p("Cycle = DIO + DSO − DPO. Multiply by daily cost to estimate the cash the cycle absorbs."),
      formula("Cash conversion cycle", [
        "<b>CCC = Days inventory + Days receivable − Days payable</b>",
        "A negative cycle means suppliers fund the business",
      ]),
      caseStudy("Real-Life Case Study: two business models",
        ["A machinery distributor against a supermarket chain."],
        [["Distributor — days inventory", "85"], ["Distributor — days receivable", "62"], ["Distributor — days payable", "45"], ["Distributor — cash cycle", "102 days"],
         ["Supermarket — days inventory", "22"], ["Supermarket — days receivable", "2"], ["Supermarket — days payable", "48"], ["Supermarket — cash cycle", "−24 days"]],
        ["The distributor funds 102 days of operations itself. Every rupee of growth demands more cash up front, so expansion needs external funding.",
         "The supermarket collects 24 days before it pays. Growth generates cash — it is effectively financed by its suppliers, interest-free. The same growth rate has opposite cash consequences in the two models."]),
      h2("Key terms"),
      def("Cash conversion cycle", "Days inventory + days receivable − days payable; the period cash is tied up in operations."),
      def("Negative cycle", "Collecting from customers before paying suppliers, so operations generate rather than consume cash."),
      def("Operating cycle", "Days inventory + days receivable, before allowing for supplier credit."),
      def("Supplier financing", "The interest-free funding provided by the gap between receiving goods and paying for them."),
      h2("Practice"),
      practice([
        { q: "Days inventory 70, days receivable 50, days payable 40. Compute the cash conversion cycle.", a: "CCC = 70 + 50 − 40 = 80 days. Cash is tied up in operations for roughly 80 days on each cycle." },
        { q: "The company above has COGS of ₹365 crore. Estimate the cash absorbed by the cycle, and the effect of cutting inventory days to 55.", a: "Daily cost ≈ ₹1 crore, so about ₹80 crore is absorbed. Cutting inventory by 15 days shortens the cycle to 65 days and releases roughly ₹15 crore of cash — once." },
        { q: "Why does a negative cash conversion cycle make rapid growth easier to fund?", a: "Cash arrives from customers before suppliers are paid, so each additional sale generates cash immediately rather than consuming it. Growth funds itself, removing the working capital constraint that limits most expanding businesses." },
      ]),
      h2("Sandbox"),
      sandbox("working-capital", "Cycle sandbox",
        "Cut inventory and raise payables — both shorten the cycle and release the cash trapped in it.", [
        { key: "inventory", label: "Inventory", value: 700000000, unit: "₹" },
        { key: "receivables", label: "Receivables", value: 500000000, unit: "₹" },
        { key: "payables", label: "Payables", value: 400000000, unit: "₹" },
      ]),
      h2("What to remember"),
      note([
        "CCC = days inventory + days receivable − days payable.",
        "It measures how long your cash is out of your hands.",
        "A longer cycle means growth needs more funding.",
        "A negative cycle means growth generates cash — a structural advantage.",
      ]),
      h2("Common mistakes"),
      list([
        "<strong>Lengthening payables to flatter the cycle</strong> while damaging supplier relationships.",
        "<strong>Comparing cycles across industries</strong> with structurally different terms.",
        "<strong>Ignoring seasonality.</strong> A year-end snapshot can miss the peak funding need entirely.",
        "<strong>Treating cycle improvements as recurring.</strong> Each improvement releases cash only once.",
      ]),
      mcq("Days inventory 60, days receivable 45, days payable 30. The cash conversion cycle is:",
        ["135 days", "75 days", "45 days", "15 days"], 1,
        [W, "Correct. 60 + 45 − 30 = 75 days.", W, W]),
      mcq("A negative cash conversion cycle means:",
        ["The company is losing money", "Customers pay before suppliers are paid, so operations generate cash", "Inventory is negative", "The company has no customers"], 1,
        [W, "Correct. It is a strong position: suppliers effectively finance the business, and growth releases cash rather than consuming it.", W, W]),
      mcq("Which change would shorten the cycle without harming supplier relationships?",
        ["Paying suppliers much later than agreed", "Reducing the time stock sits before selling", "Extending customer credit terms", "Buying more inventory"], 1,
        [W, "Correct. Faster stock turnover shortens the cycle through the company's own efficiency, rather than by pushing the burden onto suppliers or customers.", W, W]),
    ]);

  lesson("c-operating-leverage", "Operating leverage",
    "Why fixed costs make profit swing far harder than sales in both directions.",
    [
      h2("What is this?"),
      p("Operating leverage is the tendency of profit to change by a larger percentage than revenue, caused by fixed costs that do not move with volume."),
      p("A business with high fixed costs and low variable costs — a cinema, an airline, a software company — has high operating leverage. Each extra sale adds almost pure profit, and each lost sale removes almost pure profit."),
      h2("Why does it matter?"),
      p("It explains why some companies' earnings are far more volatile than their revenue, and why the same 10% sales decline is trivial for one business and fatal for another."),
      p("It also shapes strategy. High operating leverage makes growth extremely rewarding and downturns extremely dangerous, which is why such businesses should generally carry less debt — stacking financial leverage on top of operating leverage compounds both risks."),
      h2("How does it work?"),
      h3("Step 1: Split costs into fixed and variable"),
      p("Would this cost change if we sold one unit fewer? If not, it is fixed."),
      h3("Step 2: Compute contribution"),
      p("Price − variable cost per unit. This is what each sale contributes towards fixed costs."),
      h3("Step 3: Find the break-even volume"),
      p("Fixed costs ÷ contribution per unit. Below it the business loses money; above it, each unit adds full contribution to profit."),
      h3("Step 4: Measure the degree of operating leverage"),
      p("Contribution ÷ operating profit. A value of 4 means a 10% revenue change produces roughly a 40% profit change."),
      formula("Operating leverage", [
        "<b>Contribution = Price − Variable cost per unit</b>",
        "<b>Break-even units = Fixed costs ÷ Contribution per unit</b>",
        "<b>Degree of operating leverage = Total contribution ÷ Operating profit</b>",
      ]),
      caseStudy("Real-Life Case Study: a cinema",
        ["Tickets sell at ₹250. The variable cost per admission is ₹20. Fixed costs — rent, staff, projection — are ₹1,84,00,000 a year."],
        [["Contribution per ticket", "₹230"], ["Break-even admissions", "80,000"], ["Admissions at 1,00,000 — profit", "₹46,00,000"], ["Admissions at 1,20,000 — profit", "₹92,00,000"], ["Admissions change", "+20%"], ["Profit change", "+100%"]],
        ["A 20% rise in admissions doubled profit, because the extra 20,000 tickets carried ₹230 each straight to the bottom line.",
         "The same mechanism runs backwards: 80,000 admissions produce exactly zero profit, and 70,000 produce a ₹23,00,000 loss. Nothing about the cost structure changed — only volume."]),
      h2("Key terms"),
      def("Fixed cost", "A cost that does not vary with sales volume in the short run."),
      def("Contribution", "Selling price less variable cost per unit — what each sale contributes to fixed costs and profit."),
      def("Break-even point", "The volume at which total contribution exactly equals fixed costs."),
      def("Degree of operating leverage", "Contribution divided by operating profit; the multiplier between revenue and profit changes."),
      h2("Practice"),
      practice([
        { q: "Price ₹800, variable cost ₹300, fixed costs ₹1,00,00,000. Compute contribution per unit and break-even volume.", a: "Contribution = 800 − 300 = ₹500. Break-even = 1,00,00,000 ÷ 500 = 20,000 units." },
        { q: "At 26,000 units, compute profit and the degree of operating leverage.", a: "Contribution = 26,000 × 500 = ₹1,30,00,000. Profit = 1,30,00,000 − 1,00,00,000 = ₹30,00,000. DOL = 130 ÷ 30 = 4.33, so a 10% volume change moves profit about 43%." },
        { q: "Why should a business with very high operating leverage generally borrow less than one with low operating leverage?", a: "Interest is another fixed cost. Stacking it on an already volatile profit stream means a modest revenue decline can take profit below the interest bill. The two leverages multiply rather than add, so businesses with volatile operating profit need more conservative balance sheets." },
      ]),
      h2("Sandbox"),
      sandbox("operating-leverage", "Operating leverage sandbox",
        "Try +20% volume, then −20%. The asymmetry you feel is exactly what fixed costs do to a business.", [
        { key: "price", label: "Price per unit", value: 250, unit: "₹" },
        { key: "variableCost", label: "Variable cost per unit", value: 20, unit: "₹" },
        { key: "units", label: "Units sold", value: 100000 },
        { key: "fixedCosts", label: "Fixed costs", value: 18400000, unit: "₹" },
        { key: "volumeChange", label: "Volume change", value: 20, unit: "%" },
      ]),
      h2("What to remember"),
      note([
        "Fixed costs make profit move by a larger percentage than revenue.",
        "Break-even = fixed costs ÷ contribution per unit.",
        "Degree of operating leverage = contribution ÷ operating profit.",
        "High operating leverage argues for lower financial leverage.",
      ]),
      h2("Common mistakes"),
      list([
        "<strong>Assuming costs fall proportionally with sales.</strong> Fixed costs do not move in the short run.",
        "<strong>Forgetting leverage cuts both ways.</strong> The same multiplier applies to declines.",
        "<strong>Treating all costs as fixed or all as variable.</strong> Most businesses have both, plus step costs.",
        "<strong>Combining high operating and high financial leverage</strong> without recognising the compounding risk.",
      ]),
      mcq("Contribution per unit ₹400, fixed costs ₹80,00,000. Break-even volume is:",
        ["8,000 units", "20,000 units", "32,000 units", "2,00,000 units"], 1,
        [W, "Correct. 80,00,000 ÷ 400 = 20,000 units.", W, W]),
      mcq("Total contribution ₹150 crore, operating profit ₹50 crore. A 10% fall in revenue would reduce profit by roughly:",
        ["10%", "30%", "3%", "50%"], 1,
        [W, "Correct. DOL = 150 ÷ 50 = 3.0, so a 10% revenue fall cuts profit about 30%.", W, W]),
      mcq("Which business has the highest operating leverage?",
        ["A trading firm whose costs are almost all purchases", "A cinema with high rent and staff costs and low cost per admission", "A consultancy paying contractors per project", "A reseller with no fixed premises"], 1,
        [W, "Correct. Large fixed costs and a very low variable cost per unit is the defining combination — each extra admission is almost pure profit, and each lost one almost pure loss.", W, W]),
    ]);

  lesson("c-financial-leverage", "Financial leverage",
    "Borrowing multiplies the owners' returns — upward and downward, with no say in the matter.",
    [
      h2("What is this?"),
      p("Financial leverage is the use of debt to fund part of a business. Because lenders receive a fixed return, whatever the business earns above that cost belongs to the owners — and whatever it falls short by is taken from them."),
      p("The result is that a given change in operating profit produces a larger change in the return to shareholders. That amplification is the whole point, and the whole danger."),
      h2("Why does it matter?"),
      p("Leverage is why two companies with identical operations can deliver very different shareholder returns, and why some fail in a downturn while others merely have a poor year."),
      p("It is also the clearest illustration of the risk-return trade-off in corporate finance: nothing about the business improved when debt was added, yet expected returns rose. What changed is who bears the downside."),
      h2("How does it work?"),
      h3("Step 1: Compare the return on assets with the cost of debt"),
      p("If the business earns more on its capital than the interest rate, leverage adds to owner returns."),
      h3("Step 2: Apply the fixed charge"),
      p("Interest is paid regardless of results, so it does not shrink in a bad year."),
      h3("Step 3: Measure what reaches the owners"),
      p("Owner return = (operating profit − interest) ÷ equity. As equity shrinks relative to total capital, this figure becomes more volatile."),
      h3("Step 4: Stress it"),
      p("Halve the operating profit and recompute. If the owner return turns sharply negative, the leverage is too high for that business's volatility."),
      formula("Leverage effect", [
        "<b>Owner return = (Operating profit − Interest) ÷ Equity</b>",
        "<b>Unlevered return = Operating profit ÷ (Debt + Equity)</b>",
        "Leverage helps when unlevered return exceeds the interest rate",
      ]),
      caseStudy("Real-Life Case Study: the same business, three outcomes",
        ["₹100 crore of capital: ₹50 crore equity and ₹50 crore debt at 10%. Interest is ₹5 crore a year regardless."],
        [["Good year — operating profit", "₹16 crore"], ["Good year — owner return", "22.0%"], ["Normal year — operating profit", "₹10 crore"], ["Normal year — owner return", "10.0%"], ["Bad year — operating profit", "₹4 crore"], ["Bad year — owner return", "−2.0%"]],
        ["Unlevered, these three years would produce 16%, 10% and 4% — all positive, all moderate.",
         "With half the capital borrowed, the same business produces 22%, 10% and −2%. The ₹5 crore of interest never moved; only the profit available to absorb it did. Leverage did not change the business, only the distribution of its outcomes."]),
      h2("Key terms"),
      def("Financial leverage", "Using debt to fund assets, amplifying returns to equity in both directions."),
      def("Equity multiplier", "Total assets divided by equity — a direct measure of how leveraged the balance sheet is."),
      def("Fixed charge", "An obligation such as interest that does not vary with performance."),
      def("Downside amplification", "The tendency of leverage to magnify losses at least as much as it magnifies gains."),
      h2("Practice"),
      practice([
        { q: "Capital of ₹200 crore: ₹120 crore equity, ₹80 crore debt at 9%. Operating profit is ₹24 crore. Compute the owner return and the all-equity return.", a: "Interest = 80 × 9% = ₹7.2 crore. Owner return = (24 − 7.2) ÷ 120 = 14.0%. All-equity return = 24 ÷ 200 = 12.0%. Leverage added 2 points because the business earned 12% on capital costing 9%." },
        { q: "Operating profit falls to ₹12 crore. Recompute both returns.", a: "Owner return = (12 − 7.2) ÷ 120 = 4.0%. All-equity = 12 ÷ 200 = 6.0%. Operating profit halved, but the owner return fell by 71% while the unlevered return fell 50%. Leverage amplified the decline." },
        { q: "A company earns 8% on its capital and borrows at 11%. What does leverage do to shareholder returns, and why might management still do it?", a: "It reduces them — each borrowed rupee earns 8 and costs 11. Management might still borrow to fund growth they expect will raise returns later, to avoid diluting existing shareholders, or because they are over-optimistic about the project. None of those changes the arithmetic while the spread is negative." },
      ]),
      h2("Sandbox"),
      sandbox("leverage-returns", "Financial leverage sandbox",
        "Move operating profit up and down 60% and compare how gently the all-equity return moves against the levered one.", [
        { key: "operatingProfit", label: "Operating profit", value: 100000000, unit: "₹" },
        { key: "debt", label: "Debt", value: 500000000, unit: "₹" },
        { key: "interestRate", label: "Interest rate", value: 10, unit: "%" },
        { key: "equity", label: "Equity", value: 500000000, unit: "₹" },
      ]),
      h2("What to remember"),
      note([
        "Leverage amplifies owner returns in both directions.",
        "It helps only when the return on capital exceeds the borrowing cost.",
        "Interest is fixed; profit is not — that mismatch is the risk.",
        "Always stress-test leverage against a halved operating profit.",
      ]),
      h2("Common mistakes"),
      list([
        "<strong>Judging leverage by good-year returns.</strong> The bad year is what decides survival.",
        "<strong>Combining high financial and high operating leverage</strong> without recognising the compounding.",
        "<strong>Assuming a positive spread persists.</strong> Returns on capital fall in downturns while interest does not.",
        "<strong>Confusing higher returns with better performance.</strong> Leverage raises returns without improving the business.",
      ]),
      mcq("Capital ₹100 crore (₹50 debt at 10%, ₹50 equity), operating profit ₹15 crore. The owner return is:",
        ["15%", "20%", "10%", "30%"], 1,
        [W, "Correct. Interest = ₹5 crore; (15 − 5) ÷ 50 = 20%, against 15% if the business were all-equity.", W, W]),
      mcq("Leverage increases shareholder returns only when:",
        ["Interest rates are high", "The return on capital exceeds the cost of debt", "The company is small", "Revenue is growing"], 1,
        [W, "Correct. The owners keep the spread between what the capital earns and what it costs; a negative spread transfers value away from them.", W, W]),
      mcq("A business with highly volatile operating profit should generally:",
        ["Borrow as much as possible", "Carry less debt, because operating and financial leverage compound", "Ignore leverage entirely", "Borrow only at floating rates"], 1,
        [W, "Correct. Volatile profit against a fixed interest bill risks the profit falling below the obligation, so volatile businesses need more conservative balance sheets.", W, W]),
    ]);
})();
