/* Level 2 concept lessons — Financial Statements.
   Authored to the same standard as Levels 0 and 1: plain-English concept,
   why it matters, step-by-step mechanics, a worked case study with figures,
   key terms, practice with solutions, an interactive sandbox and a quiz.
   Sandbox kinds come from LS.sandbox (see curriculum-map.js). */
(function () {
  "use strict";
  var LS = (window.LS = window.LS || {});
  LS.lessons = LS.lessons || {};

  /* ---- small builders, so the block shapes stay identical to Levels 0-1 ---- */
  function h2(t) { return { t: "h2", text: t }; }
  function h3(t) { return { t: "h3", text: t }; }
  function p(h) { return { t: "p", h: h }; }
  function list(items) { return { t: "list", items: items }; }
  function def(term, h) { return { t: "def", term: term, h: h }; }
  function note(items) {
    return { t: "note", h: "<ul>" + items.map(function (i) { return "<li>" + i + "</li>"; }).join("") + "</ul>" };
  }
  function practice(items) { return { t: "practice", items: items }; }
  function sandbox(kind, title, prompt, fields) {
    return { t: "sandbox", kind: kind, title: title, prompt: prompt, fields: fields };
  }
  function mcq(q, opts, correct, why) { return { t: "mcq", q: q, opts: opts, correct: correct, why: why }; }
  /* Case study: intro paragraphs, aligned label/value rows, then the meaning. */
  function caseStudy(title, intro, rows, meaning) {
    var html = '<p class="case-title"><strong>' + title + "</strong></p>";
    intro.forEach(function (x) { html += "<p>" + x + "</p>"; });
    if (rows.length) {
      html += '<div class="case-figures">';
      rows.forEach(function (r) {
        html += '<div class="case-row"><span class="case-label">' + r[0] +
          '</span><span class="case-value">' + r[1] + "</span></div>";
      });
      html += "</div>";
    }
    html += '<p class="case-meaning"><strong>What it means.</strong></p>';
    meaning.forEach(function (x) { html += "<p>" + x + "</p>"; });
    return { t: "example", h: html };
  }
  function lesson(id, title, lede, body) {
    LS.lessons[id] = { id: id, title: title, short: title, desc: lede, lede: lede, minutes: 8, body: body };
  }

  var WRONG = "Not this one — re-read the section above.";

  /* ====================== INCOME STATEMENT ====================== */

  lesson("c-gross-profit", "Gross profit",
    "Gross profit is what survives after the cost of making the thing you sold.",
    [
      h2("What is this?"),
      p("Gross profit is revenue minus the direct cost of producing what you sold. It is the first subtotal on the income statement, and the first honest test of whether a product makes money at all."),
      p("The word <strong>direct</strong> is doing the work. Ingredients, raw materials, factory wages, freight in — costs that exist only because a unit was produced — belong here. Rent, head-office salaries and marketing do not; they are costs of being open, not costs of the unit."),
      p("Expressed as a percentage of revenue it becomes the <strong>gross margin</strong>, which is how the number is almost always discussed."),
      h2("Why does it matter?"),
      p("Gross margin tells you whether the business model works before any overheads are considered. A company with a 12% gross margin cannot pay for a large sales force out of it, no matter how well it is managed. A company with an 80% gross margin can absorb enormous overheads and still profit."),
      p("It is also the earliest place where trouble appears. Rising input costs or discounting show up in gross margin one or two periods before they reach net profit, because overheads mask the change further down."),
      h2("How does it work?"),
      h3("Step 1: Separate direct from indirect costs"),
      p("Ask of each cost: would this exist if we produced one unit fewer? If yes, it is direct and belongs in cost of goods sold."),
      h3("Step 2: Subtract"),
      p("Gross profit = Revenue − Cost of goods sold."),
      h3("Step 3: Convert to a margin"),
      p("Gross margin = Gross profit ÷ Revenue. Percentages compare across periods and companies; rupees do not."),
      h3("Step 4: Ask what moved it"),
      p("A margin change comes from price, input cost, or mix — selling more of a cheaper product lowers the blended margin even when nothing else changed."),
      { t: "formula", title: "Gross profit and gross margin", lines: [
        "<b>Gross profit = Revenue − COGS</b>",
        "<b>Gross margin = Gross profit ÷ Revenue</b>",
        "Revenue = value of goods delivered in the period",
        "COGS = direct cost of exactly those goods",
      ] },
      caseStudy("Real-Life Case Study: a garment exporter",
        ["An exporter sells 40,000 shirts at ₹450 each. Fabric, trims and factory labour cost ₹290 per shirt. Office rent and salaries are ₹28,00,000 for the year."],
        [["Revenue", "₹1,80,00,000"], ["Cost of goods sold", "₹1,16,00,000"], ["Gross profit", "₹64,00,000"], ["Gross margin", "35.6%"], ["Operating costs", "₹28,00,000"], ["Operating profit", "₹36,00,000"]],
        ["Every shirt contributes ₹160 towards overheads. The ₹28 lakh of office costs needs 17,500 shirts before the business breaks even; the remaining 22,500 shirts are profit.",
         "If fabric prices rise ₹30 a shirt, gross margin falls to 28.9% and operating profit drops to ₹24,00,000 — a third of the profit gone from a 10% move in one input."]),
      h2("Key terms"),
      def("Cost of goods sold (COGS)", "The direct cost of producing the specific goods sold in the period — not everything bought in the period."),
      def("Gross margin", "Gross profit as a percentage of revenue. The comparable form of the number."),
      def("Mix", "The blend of products sold. Shifting towards lower-margin products lowers the average margin with no change in any single price."),
      def("Contribution", "Selling price minus variable cost per unit — what each sale contributes towards fixed costs."),
      h2("Practice"),
      practice([
        { q: "Revenue is ₹90,00,000 and COGS is ₹58,50,000. Compute gross profit and gross margin.", a: "Gross profit = 90,00,000 − 58,50,000 = ₹31,50,000. Gross margin = 31,50,000 ÷ 90,00,000 = 35%." },
        { q: "A company's gross margin falls from 40% to 34% while revenue grows 20%. Name three possible causes and say how you would tell them apart.", a: "(1) Input costs rose — check COGS per unit. (2) Prices were discounted to win volume — check average selling price. (3) Mix shifted to cheaper products — check revenue by product line. Per-unit price and cost data separates them; the totals alone cannot." },
        { q: "A firm moves its factory rent from operating expenses into COGS. What happens to gross profit, operating profit and net profit?", a: "Gross profit falls (COGS is larger), operating profit and net profit are unchanged — the cost simply moved between lines. This is why gross margin comparisons between companies require checking what each puts in COGS." },
      ]),
      h2("Sandbox"),
      sandbox("sell-through", "Gross profit sandbox",
        "Lower the markup and watch gross profit fall faster than revenue. Then reduce the share sold and see cash sit in unsold stock while profit holds.", [
        { key: "stockBought", label: "Stock purchased", value: 1160000, unit: "₹" },
        { key: "percentSold", label: "Sold in the period", value: 100, unit: "%" },
        { key: "markup", label: "Markup on cost", value: 55, unit: "%" },
      ]),
      h2("What to remember"),
      note([
        "Gross profit = revenue − direct costs. It tests the product, not the company.",
        "The margin, not the rupee amount, is the comparable figure.",
        "Margin moves come from price, input cost or mix — always identify which.",
        "What counts as COGS varies between companies, so check before comparing.",
      ]),
      h2("Common mistakes"),
      list([
        "<strong>Treating gross profit as profit.</strong> Overheads, interest and tax all still have to be paid out of it.",
        "<strong>Comparing margins across industries.</strong> A 20% margin is excellent in distribution and alarming in software.",
        "<strong>Ignoring mix.</strong> A falling blended margin can happen with every single product's margin unchanged.",
        "<strong>Assuming COGS means cash spent this period.</strong> It is the cost of goods <em>sold</em>; goods bought and unsold sit in inventory.",
      ]),
      mcq("Revenue is ₹50,00,000, COGS ₹32,00,000, operating expenses ₹10,00,000. What is gross profit?",
        ["₹8,00,000", "₹18,00,000", "₹40,00,000", "₹22,00,000"], 1,
        ["That is operating profit — it also subtracts operating expenses.", "Correct. 50,00,000 − 32,00,000 = ₹18,00,000. Operating expenses come after gross profit.", WRONG, WRONG]),
      mcq("A company's gross margin rises while its prices are unchanged. The most likely cause is:",
        ["Higher interest costs", "Lower input costs or a shift to higher-margin products", "A larger tax bill", "More borrowing"], 1,
        [WRONG, "Correct. With price fixed, margin can only improve through cheaper inputs or a mix shift towards higher-margin products.", WRONG, WRONG]),
      mcq("Why is gross margin often the earliest warning of trouble?",
        ["It is audited more often", "It reacts to pricing and input costs before overheads dilute the signal", "It includes interest", "It is always positive"], 1,
        [WRONG, "Correct. Discounting and cost inflation hit gross margin immediately, while further down the statement fixed overheads mask the change.", WRONG, WRONG]),
    ]);

  lesson("c-ebitda", "EBITDA",
    "EBITDA strips out financing, tax and past investment to show what the operations earned.",
    [
      h2("What is this?"),
      p("EBITDA is <strong>Earnings Before Interest, Tax, Depreciation and Amortisation</strong>. Start from operating profit and add back depreciation and amortisation — the two large costs that reflect assets bought in earlier years rather than cash spent now."),
      p("The idea is to describe the operating business alone: what it earns before the effects of how it was financed (interest), where it is taxed (tax), and what it bought in the past (depreciation)."),
      p("Indian statutory income statements do not print a line called EBITDA. Analysts compute it, which is exactly why two people can quote different EBITDA figures for the same company."),
      h2("Why does it matter?"),
      p("It makes two businesses comparable when one is heavily indebted and the other is not, or when one owns its factories and the other leases them. It is also the base for the most common valuation multiple, EV/EBITDA, and for most debt covenants — lenders size loans as a multiple of EBITDA."),
      p("That popularity is also its danger. EBITDA excludes the cost of replacing the machines that generate it, so for capital-heavy businesses it flatters reality substantially."),
      h2("How does it work?"),
      h3("Step 1: Start from operating profit"),
      p("Revenue − COGS − operating expenses = operating profit (EBIT)."),
      h3("Step 2: Add back the non-cash charges"),
      p("Add depreciation and amortisation, both of which reduced operating profit without any cash leaving this period."),
      h3("Step 3: Sanity-check against capex"),
      p("Compare EBITDA with the capital spending needed to keep the asset base intact. If capex persistently equals depreciation, the add-back was not free money."),
      { t: "formula", title: "EBITDA", lines: [
        "<b>EBITDA = Operating profit + Depreciation + Amortisation</b>",
        "Operating profit = revenue − COGS − operating expenses",
        "Depreciation = periodic charge for tangible assets",
        "Amortisation = the same for intangible assets",
      ] },
      caseStudy("Real-Life Case Study: two logistics firms",
        ["Both earn ₹100 crore of revenue and ₹18 crore of operating profit. Fleet Owner Ltd owns its trucks; Asset Light Ltd hires them."],
        [["Fleet Owner — operating profit", "₹18 crore"], ["Fleet Owner — depreciation", "₹12 crore"], ["Fleet Owner — EBITDA", "₹30 crore"], ["Asset Light — operating profit", "₹18 crore"], ["Asset Light — depreciation", "₹1 crore"], ["Asset Light — EBITDA", "₹19 crore"]],
        ["On EBITDA, Fleet Owner looks 58% more profitable. On operating profit they are identical.",
         "Fleet Owner must spend roughly ₹12 crore a year replacing trucks to stay in business. That obligation is real but invisible in EBITDA — which is precisely the criticism of the measure."]),
      h2("Key terms"),
      def("EBITDA", "Earnings before interest, tax, depreciation and amortisation. A measure of operating performance before financing and past investment."),
      def("EBITDA margin", "EBITDA ÷ revenue. The comparable form."),
      def("Non-cash charge", "An expense that reduces profit without cash leaving in that period — depreciation is the main example."),
      def("EV/EBITDA", "Enterprise value divided by EBITDA — the most common valuation multiple, used because both terms ignore capital structure."),
      h2("Practice"),
      practice([
        { q: "Revenue ₹60 crore, COGS ₹34 crore, operating expenses ₹14 crore, depreciation ₹5 crore (included in operating expenses). Compute operating profit and EBITDA.", a: "Operating profit = 60 − 34 − 14 = ₹12 crore. EBITDA = 12 + 5 = ₹17 crore. EBITDA margin = 17 ÷ 60 = 28.3%." },
        { q: "A company reports EBITDA of ₹40 crore and annual capex of ₹38 crore just to maintain its fleet. Why should you be cautious about the ₹40 crore?", a: "Almost all of it is consumed keeping the existing asset base running. Only about ₹2 crore is genuinely available to pay interest, tax and shareholders — EBITDA here overstates economic earnings dramatically." },
        { q: "Why do lenders write covenants as 'Net debt / EBITDA below 3.0x' rather than using net profit?", a: "EBITDA approximates cash available to service debt before financing and tax effects, and it is comparable across borrowers with different debt loads and tax positions. Net profit is already reduced by the interest the covenant is trying to test." },
      ]),
      h2("Sandbox"),
      sandbox("profit-bridge", "Operating profit sandbox",
        "Set interest to zero and note that EBITDA and operating profit do not move — financing sits below them. Then change direct costs and watch every level shift.", [
        { key: "revenue", label: "Revenue", value: 600000000, unit: "₹" },
        { key: "cogs", label: "Direct costs", value: 340000000, unit: "₹" },
        { key: "opex", label: "Operating costs", value: 140000000, unit: "₹" },
        { key: "interest", label: "Interest", value: 20000000, unit: "₹" },
        { key: "taxRate", label: "Tax rate", value: 25, unit: "%" },
      ]),
      h2("What to remember"),
      note([
        "EBITDA = operating profit + depreciation + amortisation.",
        "It compares operating performance across different financing and ownership choices.",
        "It is not cash flow: it ignores capex, working capital, interest and tax.",
        "For asset-heavy businesses, always read it next to capital expenditure.",
      ]),
      h2("Common mistakes"),
      list([
        "<strong>Calling EBITDA cash flow.</strong> It excludes the working capital and capex that consume most of it.",
        "<strong>Comparing EBITDA across asset-light and asset-heavy firms.</strong> The add-back is far larger for one of them.",
        "<strong>Accepting an 'adjusted EBITDA' unquestioned.</strong> Adjustments are chosen by management; read what was excluded.",
        "<strong>Forgetting it is not a statutory line.</strong> Two analysts can compute it differently for the same company.",
      ]),
      mcq("Operating profit is ₹25 crore, depreciation ₹8 crore, interest ₹4 crore. What is EBITDA?",
        ["₹21 crore", "₹33 crore", "₹29 crore", "₹37 crore"], 1,
        [WRONG, "Correct. EBITDA = 25 + 8 = ₹33 crore. Interest sits below operating profit and is not added back here.", WRONG, WRONG]),
      mcq("EBITDA is most misleading for which kind of business?",
        ["A consultancy with few assets", "A steel plant that must constantly replace heavy machinery", "A firm with no debt", "A company with a single product"], 1,
        [WRONG, "Correct. The depreciation added back corresponds to real, recurring replacement spending, so EBITDA overstates what the owners can actually keep.", WRONG, WRONG]),
      mcq("Two firms have identical operations, but one is financed with debt. Compared with net profit, EBITDA will:",
        ["Differ more between them", "Be the same for both, because interest sits below it", "Be negative for the borrower", "Include the interest cost"], 1,
        [WRONG, "Correct. EBITDA is measured before interest, so capital structure does not affect it — which is exactly why it is used for comparison.", WRONG, WRONG]),
    ]);

  lesson("c-ebit", "EBIT",
    "EBIT is the profit the business itself produced, before lenders and the tax office take their share.",
    [
      h2("What is this?"),
      p("EBIT is <strong>Earnings Before Interest and Tax</strong> — also called operating profit. It is revenue minus every operating cost, including depreciation and amortisation, but before financing costs and tax."),
      p("Unlike EBITDA, EBIT accepts that assets wear out and charges for it. That makes it a stricter and, for most businesses, more honest measure of operating performance."),
      h2("Why does it matter?"),
      p("EBIT is the number that answers 'is the business itself profitable?' independently of how it was funded. Two identical factories, one bought with debt and one with equity, produce the same EBIT and very different net profits."),
      p("It is also the numerator of interest coverage (EBIT ÷ interest), the standard test of whether a company can service its debt, and the base of ROIC, which measures return on all invested capital."),
      h2("How does it work?"),
      h3("Step 1: Take gross profit"),
      p("Revenue − COGS."),
      h3("Step 2: Subtract operating expenses"),
      p("Salaries, rent, marketing, administration — the costs of running the business rather than making the unit."),
      h3("Step 3: Subtract depreciation and amortisation"),
      p("The periodic cost of assets already bought. What remains is EBIT."),
      h3("Step 4: Test it against interest"),
      p("Interest coverage = EBIT ÷ interest expense. Below roughly 2x, a bad year starts to threaten the ability to pay lenders."),
      { t: "formula", title: "EBIT and interest coverage", lines: [
        "<b>EBIT = Revenue − COGS − Operating expenses − D&amp;A</b>",
        "<b>Interest coverage = EBIT ÷ Interest expense</b>",
        "D&amp;A = depreciation and amortisation for the period",
      ] },
      caseStudy("Real-Life Case Study: a mid-size manufacturer",
        ["A components maker reports the following for the year."],
        [["Revenue", "₹240 crore"], ["Cost of goods sold", "₹150 crore"], ["Operating expenses", "₹48 crore"], ["Depreciation", "₹18 crore"], ["EBIT", "₹24 crore"], ["Interest expense", "₹9 crore"], ["Interest coverage", "2.7x"]],
        ["The business earns ₹24 crore before financing. Lenders take ₹9 crore of that, leaving ₹15 crore before tax.",
         "Coverage of 2.7x means EBIT could fall by roughly 63% before interest became unpayable. If EBIT dropped to ₹9 crore, everything the operations earned would go to the lenders and nothing would remain for owners."]),
      h2("Key terms"),
      def("EBIT", "Earnings before interest and tax; operating profit. Revenue less all operating costs including depreciation."),
      def("Operating margin", "EBIT ÷ revenue. The comparable form of operating profitability."),
      def("Interest coverage", "EBIT ÷ interest expense. How many times over the operating profit covers the interest bill."),
      def("ROIC", "Return on invested capital — after-tax EBIT divided by the debt and equity invested in the business."),
      h2("Practice"),
      practice([
        { q: "Revenue ₹120 crore, COGS ₹70 crore, operating expenses ₹28 crore, depreciation ₹9 crore. Compute EBIT and the operating margin.", a: "EBIT = 120 − 70 − 28 − 9 = ₹13 crore. Operating margin = 13 ÷ 120 = 10.8%." },
        { q: "The same company pays ₹6.5 crore of interest. Compute interest coverage and say what it implies.", a: "Coverage = 13 ÷ 6.5 = 2.0x. Operating profit could halve before interest was exactly covered, leaving nothing for owners or tax. That is a thin cushion for a cyclical manufacturer." },
        { q: "Why can EBIT be identical for two firms whose net profits differ by a wide margin?", a: "EBIT is measured before interest and tax. Different debt loads produce different interest charges, and different tax positions do the rest — neither touches EBIT." },
      ]),
      h2("Sandbox"),
      sandbox("profit-bridge", "EBIT sandbox",
        "Raise operating costs until operating profit no longer covers interest, and watch profit before tax turn negative.", [
        { key: "revenue", label: "Revenue", value: 2400000000, unit: "₹" },
        { key: "cogs", label: "Direct costs", value: 1500000000, unit: "₹" },
        { key: "opex", label: "Operating costs incl. depreciation", value: 660000000, unit: "₹" },
        { key: "interest", label: "Interest", value: 90000000, unit: "₹" },
        { key: "taxRate", label: "Tax rate", value: 25, unit: "%" },
      ]),
      h2("What to remember"),
      note([
        "EBIT = operating profit: after depreciation, before interest and tax.",
        "It isolates operating performance from financing choices.",
        "Interest coverage (EBIT ÷ interest) is the first test of debt safety.",
        "EBIT is stricter than EBITDA because it charges for assets wearing out.",
      ]),
      h2("Common mistakes"),
      list([
        "<strong>Confusing EBIT with EBITDA.</strong> The difference is depreciation and amortisation, which for asset-heavy firms is very large.",
        "<strong>Reading EBIT as cash.</strong> Working capital movements and capex are nowhere in it.",
        "<strong>Judging debt safety by interest rate alone.</strong> What matters is EBIT relative to the interest bill.",
        "<strong>Comparing operating margins across industries</strong> without allowing for their different cost structures.",
      ]),
      mcq("Which costs are subtracted before arriving at EBIT?",
        ["Interest and tax only", "All operating costs including depreciation, but not interest or tax", "Only direct costs", "Everything including dividends"], 1,
        [WRONG, "Correct. EBIT is after every operating cost including depreciation, and before financing and tax.", WRONG, WRONG]),
      mcq("EBIT is ₹18 crore and interest expense ₹6 crore. Interest coverage is:",
        ["0.33x", "3.0x", "12x", "24x"], 1,
        [WRONG, "Correct. 18 ÷ 6 = 3.0x — operating profit covers the interest bill three times over.", WRONG, WRONG]),
      mcq("A company takes on a large loan. Everything else unchanged, what happens to EBIT?",
        ["It falls by the interest amount", "It is unchanged, because interest sits below EBIT", "It rises", "It becomes negative"], 1,
        [WRONG, "Correct. EBIT is measured before interest, so borrowing changes net profit but not EBIT.", WRONG, WRONG]),
    ]);

  lesson("c-ebt", "EBT",
    "EBT is what is left after lenders are paid but before the tax office takes its share.",
    [
      h2("What is this?"),
      p("EBT — <strong>Earnings Before Tax</strong>, also written PBT (profit before tax) — is operating profit minus interest, plus or minus any non-operating items such as interest income or a one-off gain on selling an asset."),
      p("It is the last subtotal that belongs entirely to the company's own decisions. Everything below it is determined by tax law."),
      h2("Why does it matter?"),
      p("EBT is the figure tax is actually charged on (after adjustments), so it drives the tax bill. It is also where the effect of debt finally shows up: two firms with identical EBIT but different borrowings diverge here for the first time."),
      p("Comparing EBT with EBIT shows how much of the operating profit the lenders are taking. If that share is large and rising, financing is eating the business."),
      h2("How does it work?"),
      h3("Step 1: Start at EBIT"),
      p("The profit the operations produced."),
      h3("Step 2: Subtract interest expense"),
      p("What is owed to lenders for the period, whether or not it has been paid in cash."),
      h3("Step 3: Add non-operating income"),
      p("Interest earned on deposits, dividends received, gains on asset sales. These are real but usually not repeatable."),
      h3("Step 4: Separate the one-offs"),
      p("Before drawing conclusions, strip out non-recurring items — otherwise this year's asset sale looks like operating improvement."),
      { t: "formula", title: "Earnings before tax", lines: [
        "<b>EBT = EBIT − Interest expense + Non-operating income</b>",
        "EBIT = operating profit",
        "Non-operating income = interest earned, gains on sales and similar items",
      ] },
      caseStudy("Real-Life Case Study: the same firm, two balance sheets",
        ["Two companies each generate ₹30 crore of EBIT. One is unlevered; the other carries ₹150 crore of debt at 11%."],
        [["Unlevered — EBIT", "₹30 crore"], ["Unlevered — interest", "₹0"], ["Unlevered — EBT", "₹30 crore"], ["Levered — EBIT", "₹30 crore"], ["Levered — interest", "₹16.5 crore"], ["Levered — EBT", "₹13.5 crore"]],
        ["The operations are identical; the owners' pre-tax profit differs by ₹16.5 crore purely because of financing.",
         "If EBIT fell 40% to ₹18 crore, the unlevered firm would still show ₹18 crore of EBT while the levered one would fall to ₹1.5 crore — the same operating decline, magnified into near-breakeven by the fixed interest bill."]),
      h2("Key terms"),
      def("EBT / PBT", "Earnings before tax — profit after interest and non-operating items, before the tax charge."),
      def("Non-operating income", "Income not produced by the core business: interest earned, dividends received, gains on disposals."),
      def("One-off item", "A gain or loss that is not expected to repeat. Must be separated before judging performance."),
      def("Effective tax rate", "Tax expense ÷ EBT. Usually differs from the statutory rate because of allowances and past losses."),
      h2("Practice"),
      practice([
        { q: "EBIT is ₹45 crore, interest expense ₹12 crore, and the company earned ₹2 crore of interest on deposits. Compute EBT.", a: "EBT = 45 − 12 + 2 = ₹35 crore." },
        { q: "A company's EBT rose 40% while EBIT rose 5%. Give the two most likely explanations.", a: "Either interest expense fell sharply (debt repaid or refinanced cheaper), or a large non-operating gain — such as selling land or a subsidiary — was included. Both should be checked, since only the first is repeatable and neither reflects better operations." },
        { q: "Why is EBT a poor basis for comparing two companies' operating quality?", a: "It embeds financing decisions and one-off items. A well-run but indebted company can show lower EBT than a mediocre debt-free one. Compare EBIT or operating margin for operations." },
      ]),
      h2("Sandbox"),
      sandbox("profit-bridge", "Interest bite sandbox",
        "Increase interest and watch the gap open between operating profit and profit before tax — that gap is the lenders' share.", [
        { key: "revenue", label: "Revenue", value: 3000000000, unit: "₹" },
        { key: "cogs", label: "Direct costs", value: 1800000000, unit: "₹" },
        { key: "opex", label: "Operating costs", value: 900000000, unit: "₹" },
        { key: "interest", label: "Interest", value: 165000000, unit: "₹" },
        { key: "taxRate", label: "Tax rate", value: 25, unit: "%" },
      ]),
      h2("What to remember"),
      note([
        "EBT = EBIT − interest + non-operating income.",
        "It is the first line where financing choices change the answer.",
        "Tax is charged on it, so it drives the tax expense.",
        "Strip out one-off items before treating a change in EBT as progress.",
      ]),
      h2("Common mistakes"),
      list([
        "<strong>Reading a jump in EBT as operating improvement</strong> when it came from an asset sale.",
        "<strong>Comparing EBT across companies with different debt levels</strong> and concluding one operates better.",
        "<strong>Forgetting interest is owed whatever the year looked like.</strong> A fixed charge against a variable profit is what makes leverage risky.",
        "<strong>Assuming tax = statutory rate × EBT.</strong> Allowances and carried-forward losses usually make the effective rate different.",
      ]),
      mcq("EBIT is ₹80 crore, interest ₹22 crore, non-operating income ₹3 crore. EBT is:",
        ["₹58 crore", "₹61 crore", "₹105 crore", "₹55 crore"], 1,
        [WRONG, "Correct. 80 − 22 + 3 = ₹61 crore.", WRONG, WRONG]),
      mcq("Two firms have the same EBIT but very different EBT. The difference is explained mainly by:",
        ["Their tax rates", "Their interest costs and non-operating items", "Their revenue", "Their gross margins"], 1,
        [WRONG, "Correct. Everything between EBIT and EBT is financing and non-operating activity; tax comes after EBT.", WRONG, WRONG]),
      mcq("A one-off gain on selling a factory appears in EBT. When judging next year's prospects you should:",
        ["Include it, since it was real cash", "Exclude it, because it will not repeat", "Double it", "Treat it as revenue"], 1,
        [WRONG, "Correct. It happened, but it says nothing about future operating performance, so it is stripped out when forecasting.", WRONG, WRONG]),
    ]);

  lesson("c-taxes", "Taxes",
    "Tax is a real cash cost, and the rate a company actually pays is rarely the rate in the statute.",
    [
      h2("What is this?"),
      p("The tax line is the charge on the company's profits for the period. It has two parts: <strong>current tax</strong>, payable to the government for this year, and <strong>deferred tax</strong>, which records timing differences between accounting profit and taxable profit."),
      p("The rate a company actually bears — the <strong>effective tax rate</strong>, tax expense ÷ profit before tax — is usually different from the headline statutory rate, because tax law and accounting rules measure profit differently."),
      p("Rates and reliefs are set by law and change; treat any specific rate as current fact rather than a permanent truth."),
      h2("Why does it matter?"),
      p("Tax is often one of the largest single costs a profitable company has, and unlike most costs it is unavoidable if profits are earned. It converts pre-tax profit into what owners can actually keep."),
      p("The effective rate also carries information. A rate far below statutory may mean past losses being used up — a benefit that will end — or incentives that expire. A rate above statutory may signal disallowed expenses or foreign taxes."),
      h2("How does it work?"),
      h3("Step 1: Start from accounting profit"),
      p("Profit before tax, as reported."),
      h3("Step 2: Adjust to taxable profit"),
      p("Add back expenses the law disallows, apply the depreciation rates the tax code specifies rather than the accounting ones, deduct brought-forward losses."),
      h3("Step 3: Apply the statutory rate"),
      p("The result is current tax — the actual liability for the year."),
      h3("Step 4: Record deferred tax"),
      p("Where a difference is timing rather than permanent — such as depreciation charged faster for tax than for accounts — a deferred tax asset or liability records that the difference reverses later."),
      { t: "formula", title: "Effective tax rate", lines: [
        "<b>Effective tax rate = Total tax expense ÷ Profit before tax</b>",
        "<b>Net profit = EBT − Tax expense</b>",
        "Total tax expense = current tax + deferred tax",
      ] },
      caseStudy("Real-Life Case Study: a company using past losses",
        ["A firm reports ₹50 crore of profit before tax. It carries ₹20 crore of losses from earlier years that tax law lets it set against this year's profit. The statutory rate is 25%."],
        [["Profit before tax", "₹50 crore"], ["Brought-forward losses used", "₹20 crore"], ["Taxable profit", "₹30 crore"], ["Current tax at 25%", "₹7.5 crore"], ["Effective rate this year", "15%"], ["Net profit", "₹42.5 crore"]],
        ["The company pays 15% rather than 25% because the past losses shelter part of the profit.",
         "Those losses are now used up. On the same ₹50 crore next year the tax would be ₹12.5 crore and net profit ₹37.5 crore — a 12% fall in reported profit with no change whatsoever in the business."]),
      h2("Key terms"),
      def("Current tax", "Tax payable to the government on this period's taxable profit."),
      def("Deferred tax", "An accounting entry recording timing differences between accounting and taxable profit that will reverse in future periods."),
      def("Effective tax rate", "Total tax expense divided by profit before tax — what the company actually bore."),
      def("Carried-forward loss", "A past loss that tax law permits to be set against future taxable profits, within limits set by statute."),
      h2("Practice"),
      practice([
        { q: "Profit before tax is ₹80 crore and the tax expense is ₹17.6 crore. Compute the effective tax rate and net profit.", a: "Effective rate = 17.6 ÷ 80 = 22%. Net profit = 80 − 17.6 = ₹62.4 crore." },
        { q: "A company's effective rate was 12% last year and 26% this year, with no change in tax law. Give the most likely explanation.", a: "Brought-forward losses or a tax incentive sheltered last year's profit and have now been exhausted or expired. Reported profit falls even though the underlying business is unchanged — a common surprise for investors reading only net profit." },
        { q: "Why does depreciation create deferred tax?", a: "Tax law usually allows a different depreciation schedule from the accounting one. The total deducted over the asset's life is the same, but the timing differs, so a liability or asset is recorded for the difference that will reverse in later years." },
      ]),
      h2("Sandbox"),
      sandbox("profit-bridge", "Tax sandbox",
        "Change the tax rate and watch only the final line move — tax touches nothing above profit before tax.", [
        { key: "revenue", label: "Revenue", value: 1000000000, unit: "₹" },
        { key: "cogs", label: "Direct costs", value: 520000000, unit: "₹" },
        { key: "opex", label: "Operating costs", value: 280000000, unit: "₹" },
        { key: "interest", label: "Interest", value: 40000000, unit: "₹" },
        { key: "taxRate", label: "Effective tax rate", value: 25, unit: "%" },
      ]),
      h2("What to remember"),
      note([
        "Tax expense = current tax + deferred tax.",
        "The effective rate is usually not the statutory rate — always compute it.",
        "An unusually low rate often reflects something temporary that will end.",
        "Tax rules are set by law and change; verify current rates rather than assuming.",
      ]),
      h2("Common mistakes"),
      list([
        "<strong>Assuming tax = statutory rate × profit before tax.</strong> Allowances, disallowances and past losses all intervene.",
        "<strong>Treating a low effective rate as skill.</strong> It is frequently a timing benefit that reverses.",
        "<strong>Confusing deferred tax with cash owed now.</strong> Deferred tax is a timing record, not a current payment.",
        "<strong>Forecasting net profit without forecasting the tax rate</strong> — the two move independently.",
      ]),
      mcq("Profit before tax is ₹40 crore and tax expense is ₹6 crore. The effective tax rate is:",
        ["6%", "15%", "25%", "40%"], 1,
        [WRONG, "Correct. 6 ÷ 40 = 15%. That is well below a 25% statutory rate, so something — often past losses — is sheltering profit.", WRONG, WRONG]),
      mcq("Deferred tax arises because:",
        ["Companies delay paying tax illegally", "Accounting profit and taxable profit are measured on different timing", "Tax rates change every year", "Auditors require it"], 1,
        [WRONG, "Correct. The same total is taxed over time, but the periods differ; deferred tax records the difference until it reverses.", WRONG, WRONG]),
      mcq("A company's effective rate jumps from 10% to 25% with no change in the law. The most likely cause is:",
        ["Higher revenue", "Carried-forward losses have been fully used", "Lower interest costs", "A share buyback"], 1,
        [WRONG, "Correct. Once the shelter from past losses is exhausted, the company pays close to the statutory rate and reported profit falls without any operating change.", WRONG, WRONG]),
    ]);

  /* ====================== BALANCE SHEET ====================== */

  lesson("c-intangibles", "Intangibles",
    "Intangibles are assets you cannot touch — and the most valuable ones are often missing from the balance sheet entirely.",
    [
      h2("What is this?"),
      p("An intangible asset has no physical form but is expected to produce future benefit: patents, licences, software, trademarks, customer contracts."),
      p("The critical rule is how they arrive. An intangible <strong>purchased</strong> — in an acquisition or bought outright — is recorded at cost. An intangible <strong>built internally</strong>, such as a brand created through decades of advertising, is generally expensed as incurred and never appears as an asset."),
      p("So two companies with economically identical brands can show completely different balance sheets depending only on whether the brand was bought or built."),
      h2("Why does it matter?"),
      p("For modern businesses — software, pharmaceuticals, consumer brands, media — the assets that actually generate profit are largely intangible, and largely unrecognised. Book value therefore understates them badly, which makes price-to-book comparisons against an asset-heavy manufacturer close to meaningless."),
      p("Intangibles also carry judgement. Useful lives are estimates, and an intangible with an indefinite life is not amortised at all — it is tested for impairment, which relies on management forecasts."),
      h2("How does it work?"),
      h3("Step 1: Decide whether it can be recognised"),
      p("Purchased: yes, at cost. Internally generated: research is expensed; development may be capitalised only when strict criteria are demonstrably met."),
      h3("Step 2: Determine the useful life"),
      p("A patent with 12 years remaining has a defined life. A trademark that can be renewed indefinitely may not."),
      h3("Step 3: Amortise or test"),
      p("Finite life: amortise over that life. Indefinite life: no amortisation, but test for impairment periodically."),
      h3("Step 4: Write down when the benefit disappears"),
      p("If a drug fails trials or a licence loses value, the carrying amount is reduced through the income statement."),
      caseStudy("Real-Life Case Study: two identical brands",
        ["Brand A was built over 40 years by its owner. Brand B, economically identical, was acquired last year for ₹1,000 crore."],
        [["Brand A on the balance sheet", "₹0"], ["Brand A advertising spend, cumulative", "expensed"], ["Brand B on the balance sheet", "₹1,000 crore"], ["Brand B annual amortisation (20-yr life)", "₹50 crore"], ["Effect on Brand B's profit", "−₹50 crore/yr"]],
        ["Brand A shows no asset and no amortisation, so its reported profit is higher and its book value lower.",
         "Brand B looks more asset-rich and less profitable — for the identical economic position. Any ratio built on book value or reported profit will rank these two companies wrongly unless the difference is understood."]),
      h2("Key terms"),
      def("Intangible asset", "A non-physical asset expected to generate future economic benefit — patents, software, licences, trademarks."),
      def("Amortisation", "The periodic charge spreading a finite-life intangible's cost over the years it benefits."),
      def("Indefinite life", "No foreseeable limit to the asset's usefulness. Not amortised; tested for impairment instead."),
      def("Impairment", "A write-down when an asset's recoverable amount falls below its carrying value."),
      h2("Practice"),
      practice([
        { q: "A company buys a 10-year software licence for ₹40 crore. What is the annual amortisation, and the carrying value after 4 years?", a: "Annual = 40 ÷ 10 = ₹4 crore. Carrying value after 4 years = 40 − 16 = ₹24 crore." },
        { q: "A pharmaceutical firm spends ₹200 crore on research and ₹150 crore on development that meets the capitalisation criteria. How is each treated?", a: "The ₹200 crore of research is expensed as incurred, reducing this year's profit. The ₹150 crore of qualifying development is capitalised as an intangible and amortised once the product is in use." },
        { q: "Why might a software company trade at eight times book value while a steel plant trades at one times?", a: "The software company's main assets — code, brand, customer relationships — are largely internally generated and therefore not on the balance sheet, so book value captures little of its worth. The steel plant's assets are physical and recorded. The multiple difference reflects measurement, not necessarily better value." },
      ]),
      h2("Sandbox"),
      sandbox("depreciation", "Amortisation sandbox",
        "Set residual to zero, as most licences have none, and stretch the useful life to see how the annual charge — and reported profit — changes.", [
        { key: "cost", label: "Intangible cost", value: 400000000, unit: "₹" },
        { key: "residual", label: "Residual value", value: 0, unit: "₹" },
        { key: "usefulLife", label: "Useful life (years)", value: 10 },
        { key: "yearsElapsed", label: "Years elapsed", value: 4 },
      ]),
      h2("What to remember"),
      note([
        "Purchased intangibles are recognised; internally built ones generally are not.",
        "Finite lives are amortised; indefinite lives are impairment-tested.",
        "Book value systematically understates intangible-heavy businesses.",
        "Useful life is an estimate, and estimates move reported profit.",
      ]),
      h2("Common mistakes"),
      list([
        "<strong>Assuming a missing brand means no brand.</strong> Absence from the balance sheet reflects accounting rules, not economics.",
        "<strong>Comparing price-to-book across intangible-heavy and asset-heavy firms.</strong> They measure different fractions of reality.",
        "<strong>Treating amortisation as cash.</strong> The cash left when the intangible was bought.",
        "<strong>Ignoring impairment risk</strong> on large acquired intangibles — the write-down is where an overpayment finally surfaces.",
      ]),
      mcq("Which of these appears as an intangible asset on the balance sheet?",
        ["A brand built by the company's own advertising over 30 years", "A patent portfolio acquired in a takeover", "Employee skill", "Customer goodwill built through good service"], 1,
        [WRONG, "Correct. Acquisition creates a measurable cost that can be recognised; internally generated intangibles generally cannot be.", WRONG, WRONG]),
      mcq("An intangible with an indefinite useful life is:",
        ["Amortised over 10 years", "Not amortised, but tested for impairment", "Expensed immediately", "Revalued upward each year"], 1,
        [WRONG, "Correct. With no foreseeable end to its usefulness there is no sensible period to spread the cost over, so impairment testing polices its value instead.", WRONG, WRONG]),
      mcq("A ₹60 crore licence with a 12-year life has been held for 5 years. Its carrying value is:",
        ["₹60 crore", "₹35 crore", "₹25 crore", "₹5 crore"], 1,
        [WRONG, "Correct. Annual amortisation = 60 ÷ 12 = ₹5 crore; after 5 years, 60 − 25 = ₹35 crore.", WRONG, WRONG]),
    ]);

  lesson("c-other-liabilities", "Other liabilities",
    "The obligations that are not debt — and are easy to miss precisely because they carry no interest.",
    [
      h2("What is this?"),
      p("'Other liabilities' collects the obligations that are neither borrowings nor ordinary trade payables: provisions, employee benefit obligations, deferred revenue, lease liabilities, tax payable, warranty obligations."),
      p("They share one feature: a past event has already created a present obligation, so the company will have to give up resources later even though no lender is involved."),
      h2("Why does it matter?"),
      p("Analysts focus on debt because it carries interest and a repayment date. Other liabilities carry neither, so they attract less attention — yet they consume cash just as surely. A large warranty provision or pension obligation is a genuine future outflow."),
      p("Some of them are also informative. Rising deferred revenue means customers are paying in advance, which is a strength. A rising warranty provision may mean product quality is deteriorating."),
      h2("How does it work?"),
      h3("Step 1: Identify the obligating event"),
      p("The goods were sold with a warranty; the employee earned a year of service; the customer paid in advance. The obligation exists from that moment."),
      h3("Step 2: Estimate the amount"),
      p("Many of these require judgement — how many products will be returned, what future salaries will be. Provisions are estimates, and estimates can be adjusted."),
      h3("Step 3: Recognise the liability and the cost"),
      p("The obligation goes on the balance sheet and the matching expense reduces profit in the period the obligation arose, not when cash is eventually paid."),
      h3("Step 4: Release or settle it"),
      p("When the warranty claim is paid or the service delivered, the liability falls. If the estimate proves too high, the excess is released back to profit — which flatters that period's results."),
      caseStudy("Real-Life Case Study: an appliance maker",
        ["A manufacturer sells ₹300 crore of appliances with a two-year warranty and expects claims of 2% of sales. It also holds customer advances for undelivered orders."],
        [["Revenue", "₹300 crore"], ["Warranty provision created", "₹6 crore"], ["Effect on this year's profit", "−₹6 crore"], ["Customer advances (deferred revenue)", "₹22 crore"], ["Total 'other liabilities'", "₹28 crore"], ["Interest payable on them", "₹0"]],
        ["The ₹6 crore reduces profit now even though no claim has yet been made — the obligation was created by the sale, not by the repair.",
         "None of the ₹28 crore appears in the debt figure, so a 'debt-free' description would be misleading: the company still owes ₹28 crore of value, ₹22 crore of it in services it has been paid for but not yet delivered."]),
      h2("Key terms"),
      def("Provision", "A liability of uncertain timing or amount, recognised when a present obligation exists and can be estimated reliably."),
      def("Deferred revenue", "Cash collected before delivery. A liability until the goods or services are provided."),
      def("Lease liability", "The obligation to make future lease payments, recognised on the balance sheet under current standards."),
      def("Employee benefit obligation", "Amounts owed to staff for service already rendered, such as gratuity or pension entitlements."),
      h2("Practice"),
      practice([
        { q: "A company sells ₹500 crore of goods and expects warranty claims of 1.5%. What is recorded, and what is the effect on profit and cash this year?", a: "A provision of ₹7.5 crore is recognised as a liability, with a matching ₹7.5 crore expense reducing profit. No cash moves this year — cash leaves only when claims are actually paid." },
        { q: "A firm describes itself as debt-free but carries ₹40 crore of deferred revenue and ₹15 crore of employee benefit obligations. Is 'debt-free' a fair description of its obligations?", a: "It is accurate about borrowings but incomplete about obligations. ₹55 crore of value is still owed — ₹40 crore of it in services already paid for. No interest is charged, but the resources must still be given up." },
        { q: "A company releases ₹10 crore of an unused warranty provision back to profit. Why should this be treated differently from operating profit?", a: "It is a reversal of a past estimate, not value created by trading this year. It raises reported profit without any operating improvement, so it should be stripped out when assessing performance or forecasting." },
      ]),
      h2("Sandbox"),
      sandbox("deferred-revenue", "Advance collections sandbox",
        "Move months delivered from 0 to full term and watch a liability convert into earned revenue.", [
        { key: "contractValue", label: "Customer advances collected", value: 220000000, unit: "₹" },
        { key: "monthsTotal", label: "Delivery period (months)", value: 12 },
        { key: "monthsDelivered", label: "Months delivered", value: 4 },
      ]),
      h2("What to remember"),
      note([
        "Other liabilities are obligations without interest — provisions, deferred revenue, leases, employee benefits.",
        "They are recognised when the obligating event happens, not when cash is paid.",
        "'Debt-free' describes borrowings only, not total obligations.",
        "Many are estimates, so they can be adjusted — and releases flatter profit.",
      ]),
      h2("Common mistakes"),
      list([
        "<strong>Equating liabilities with debt.</strong> Debt is one type of liability; these are another, and they still consume cash.",
        "<strong>Ignoring provisions because they carry no interest.</strong> The future outflow is real.",
        "<strong>Reading a provision release as operating performance.</strong> It is an estimate being corrected.",
        "<strong>Treating deferred revenue as a problem.</strong> It usually signals customers committing early — a strength.",
      ]),
      mcq("Which of these is a liability but not debt?",
        ["A five-year bank term loan", "A warranty provision for goods already sold", "A bond issued to the public", "An overdraft facility drawn down"], 1,
        [WRONG, "Correct. The obligation arose from selling the goods, not from borrowing, and it carries no interest or repayment schedule.", WRONG, WRONG]),
      mcq("When a warranty provision is created, the immediate effect is:",
        ["Cash falls", "Profit falls and a liability is recognised, with no cash movement", "Revenue rises", "Debt rises"], 1,
        [WRONG, "Correct. The expense is matched to the period of the sale; cash only leaves later, when claims are settled.", WRONG, WRONG]),
      mcq("A growing deferred revenue balance usually indicates:",
        ["Customers are refusing to pay", "Customers are paying in advance of delivery", "The company is in default", "Revenue was overstated"], 1,
        [WRONG, "Correct. It is cash received ahead of performance — interest-free funding and a sign of customer commitment, though the service must still be delivered.", WRONG, WRONG]),
    ]);

  /* ====================== CASH FLOW STATEMENT ====================== */

  lesson("c-capex", "Capex",
    "Capital expenditure is cash spent on long-lived assets — invisible to profit in the year it is spent.",
    [
      h2("What is this?"),
      p("Capital expenditure — capex — is cash spent buying or improving assets that will be used for more than one year: machinery, buildings, vehicles, IT systems."),
      p("It is not an expense when it happens. The cash leaves immediately and appears in investing activities on the cash flow statement, while the income statement sees only the depreciation of that asset, spread over its useful life."),
      p("This is the largest single reason profit and cash diverge for asset-heavy companies."),
      h2("Why does it matter?"),
      p("Capex determines both future capacity and current cash. A company can report healthy profit while consuming every rupee of it on new plants — which is fine if the plants earn a return, and ruinous if they do not."),
      p("Analysts separate <strong>maintenance capex</strong>, the spending needed just to keep the existing business running, from <strong>growth capex</strong>, which expands capacity. Only the second should be expected to raise future profits."),
      h2("How does it work?"),
      h3("Step 1: Cash leaves, an asset arrives"),
      p("The balance sheet swaps cash for property, plant and equipment. Profit is untouched."),
      h3("Step 2: The asset is depreciated"),
      p("Each year a portion of the cost becomes an expense, reducing profit without any cash leaving."),
      h3("Step 3: Compare capex with depreciation"),
      p("Capex above depreciation means the asset base is growing. Persistently below means it is being run down."),
      h3("Step 4: Deduct it from operating cash flow"),
      p("Free cash flow = operating cash flow − capex. This is what is genuinely available for lenders and owners."),
      { t: "formula", title: "Free cash flow", lines: [
        "<b>Free cash flow = Cash flow from operations − Capital expenditure</b>",
        "Capex = cash paid for property, plant, equipment and other long-lived assets",
      ] },
      caseStudy("Real-Life Case Study: a cement producer",
        ["The company reports strong profit but its cash balance barely moves."],
        [["Net profit", "₹120 crore"], ["Depreciation added back", "₹95 crore"], ["Cash flow from operations", "₹210 crore"], ["Capital expenditure", "₹185 crore"], ["Free cash flow", "₹25 crore"], ["Capex ÷ depreciation", "1.95x"]],
        ["Operations generated ₹210 crore, but ₹185 crore went straight back into kilns and plant, leaving only ₹25 crore.",
         "Capex at nearly twice depreciation means this is expansion, not just maintenance — acceptable if the new capacity earns a good return, but until it does, the ₹120 crore of profit is not money the owners can touch."]),
      h2("Key terms"),
      def("Capital expenditure", "Cash spent acquiring or improving long-lived assets. Capitalised on the balance sheet rather than expensed."),
      def("Maintenance capex", "Spending required to keep existing operations running at current capacity."),
      def("Growth capex", "Spending that adds new capacity or capability."),
      def("Free cash flow", "Operating cash flow less capital expenditure — what is left for lenders and owners."),
      h2("Practice"),
      practice([
        { q: "Operating cash flow is ₹80 crore and capex is ₹95 crore. Compute free cash flow and say what it implies.", a: "Free cash flow = 80 − 95 = −₹15 crore. The company must fund the gap from cash reserves, new borrowing or share issuance. Sustainable briefly during expansion; a serious problem if it persists." },
        { q: "A company spends ₹50 crore on a machine with a 10-year life. Show the effect on year 1 profit and year 1 cash.", a: "Cash: −₹50 crore in year 1 (investing activities). Profit: reduced by depreciation of ₹5 crore only. The remaining ₹45 crore of cash outflow never appears on the income statement in year 1." },
        { q: "Depreciation is ₹40 crore a year and capex has been ₹22 crore for four consecutive years. What is happening, and what should you expect?", a: "The asset base is shrinking — the company is spending far less than assets are wearing out. Reported profit is flattered in the short run, but expect either a large catch-up spend or declining capacity and output." },
      ]),
      h2("Sandbox"),
      sandbox("ppe-rollforward", "Capex sandbox",
        "Set capex below depreciation and watch the asset base shrink — the warning appears in the note.", [
        { key: "opening", label: "Opening PP&E", value: 9500000000, unit: "₹" },
        { key: "capex", label: "Capital expenditure", value: 1850000000, unit: "₹" },
        { key: "depreciationCharge", label: "Depreciation", value: 950000000, unit: "₹" },
      ]),
      h2("What to remember"),
      note([
        "Capex is cash out now; depreciation is the expense spread over later years.",
        "Free cash flow = operating cash flow − capex.",
        "Capex above depreciation means growth; persistently below means decline.",
        "Profit can look strong while capex consumes all of the cash.",
      ]),
      h2("Common mistakes"),
      list([
        "<strong>Reading profit as available cash</strong> in a business that must reinvest heavily every year.",
        "<strong>Treating all capex as growth.</strong> Much of it merely replaces what wore out.",
        "<strong>Cheering falling capex.</strong> It raises free cash flow this year and can starve the business.",
        "<strong>Expecting capex on the income statement.</strong> Only its depreciation appears there.",
      ]),
      mcq("A company spends ₹30 crore on equipment with a 6-year life. The effect on this year's profit is:",
        ["A ₹30 crore expense", "A ₹5 crore depreciation charge", "No effect ever", "A ₹30 crore liability"], 1,
        [WRONG, "Correct. The cost is capitalised and depreciated: 30 ÷ 6 = ₹5 crore this year. The full ₹30 crore left as cash.", WRONG, WRONG]),
      mcq("Operating cash flow ₹150 crore, capex ₹110 crore. Free cash flow is:",
        ["₹260 crore", "₹40 crore", "₹150 crore", "−₹110 crore"], 1,
        [WRONG, "Correct. 150 − 110 = ₹40 crore is what remains for lenders and owners.", WRONG, WRONG]),
      mcq("Capex persistently running well below depreciation most likely means:",
        ["The company is highly efficient", "The productive asset base is being run down", "Assets are appreciating", "Profits are understated"], 1,
        [WRONG, "Correct. Assets are wearing out faster than they are replaced — tolerable briefly, corrosive if sustained.", WRONG, WRONG]),
    ]);

  lesson("c-change-in-working-capital", "Change in working capital",
    "The line that explains why a profitable, growing company can still run out of cash.",
    [
      h2("What is this?"),
      p("Working capital is the cash tied up in day-to-day operations: inventory plus receivables minus payables. The <strong>change</strong> in it between two balance sheet dates is an adjustment on the cash flow statement, converting profit into cash actually generated."),
      p("The direction confuses almost everyone at first. An <strong>increase</strong> in working capital <em>consumes</em> cash; a decrease releases it."),
      h2("Why does it matter?"),
      p("This single line explains most of the gap between profit and cash for a growing business. Growth means buying more stock and extending more credit before the profit is collected — so the faster a company grows, the more cash it needs, even while every sale is profitable."),
      p("It also reverses. A company that stops growing releases working capital and produces a burst of cash that looks like improvement but is a one-off unwinding."),
      h2("How does it work?"),
      h3("Step 1: Compute working capital at both dates"),
      p("Inventory + receivables − payables, at the start and at the end of the period."),
      h3("Step 2: Take the difference"),
      p("Closing minus opening. A positive number means more cash is now locked inside operations."),
      h3("Step 3: Apply it with the correct sign"),
      p("On the cash flow statement, an increase is subtracted from profit; a decrease is added."),
      h3("Step 4: Ask which component moved"),
      p("Slower collections, stock building up and faster supplier payments all consume cash — but they mean very different things about the business."),
      { t: "formula", title: "Working capital and its cash effect", lines: [
        "<b>Working capital = Inventory + Receivables − Payables</b>",
        "<b>Cash effect = −(Closing working capital − Opening working capital)</b>",
        "An increase consumes cash; a decrease releases it",
      ] },
      caseStudy("Real-Life Case Study: a distributor growing 40%",
        ["Revenue grew from ₹100 crore to ₹140 crore and the business earned ₹9 crore of profit. Working capital scaled with sales."],
        [["Opening working capital", "₹25 crore"], ["Closing working capital", "₹36 crore"], ["Increase", "₹11 crore"], ["Net profit", "₹9 crore"], ["Approximate operating cash", "−₹2 crore"], ["Growth in revenue", "40%"]],
        ["Every sale was profitable, yet operations consumed ₹2 crore of cash, because ₹11 crore went into extra stock and unpaid customer invoices.",
         "The company must fund that ₹11 crore from reserves or borrowing. This is the classic growth squeeze — and the reason fast-growing firms fail while still profitable."]),
      h2("Key terms"),
      def("Working capital", "Inventory plus receivables minus payables — the cash locked into operations."),
      def("Cash conversion cycle", "Days inventory + days receivable − days payable. How long cash is tied up before returning."),
      def("Source of cash", "A decrease in working capital, which releases cash back to the business."),
      def("Use of cash", "An increase in working capital, which absorbs cash."),
      h2("Practice"),
      practice([
        { q: "Opening working capital ₹18 crore, closing ₹27 crore, net profit ₹14 crore. Estimate the cash generated by operations.", a: "Working capital rose ₹9 crore, consuming cash. Approximate operating cash = 14 − 9 = ₹5 crore. Two-thirds of the profit never became cash." },
        { q: "A company's revenue is flat but its working capital falls ₹12 crore. What happened to cash, and should you be pleased?", a: "Cash rose ₹12 crore. But with flat revenue this is an unwinding — collecting faster, holding less stock, or paying suppliers later. It is a genuine one-off benefit, not a repeatable source of cash, and stretching suppliers can signal strain." },
        { q: "Why does a company growing 50% a year usually need external funding even when profitable?", a: "Working capital scales with sales, so it absorbs cash roughly in proportion to growth, while profit is collected later. The gap between cash consumed and profit realised must be funded from reserves, debt or equity until growth slows." },
      ]),
      h2("Sandbox"),
      sandbox("working-capital", "Working capital sandbox",
        "Raise inventory and receivables by 40%, as if revenue grew, and read the increase as cash the growth demands.", [
        { key: "inventory", label: "Inventory", value: 220000000, unit: "₹" },
        { key: "receivables", label: "Receivables", value: 260000000, unit: "₹" },
        { key: "payables", label: "Payables", value: 120000000, unit: "₹" },
      ]),
      h2("What to remember"),
      note([
        "Working capital = inventory + receivables − payables.",
        "An increase consumes cash; a decrease releases it.",
        "Growth consumes working capital, which is why profitable firms run short of cash.",
        "A large release with flat sales is a one-off, not an improvement in earnings.",
      ]),
      h2("Common mistakes"),
      list([
        "<strong>Getting the sign backwards.</strong> More working capital means less cash, not more.",
        "<strong>Treating a working capital release as recurring.</strong> You can only collect the same invoices once.",
        "<strong>Ignoring which component moved.</strong> Stretching suppliers and collecting faster look identical in the total.",
        "<strong>Forecasting revenue growth without funding the working capital it requires.</strong>",
      ]),
      mcq("Working capital rises from ₹20 crore to ₹28 crore. The effect on cash is:",
        ["+₹8 crore", "−₹8 crore", "No effect", "+₹28 crore"], 1,
        [WRONG, "Correct. An increase in working capital consumes ₹8 crore of cash — it is now locked in stock and unpaid invoices.", WRONG, WRONG]),
      mcq("Which combination consumes the most cash?",
        ["Inventory falls, receivables fall, payables rise", "Inventory rises, receivables rise, payables fall", "All three unchanged", "Payables rise sharply"], 1,
        [WRONG, "Correct. More stock and more unpaid customer invoices absorb cash, while paying suppliers faster removes a source of funding.", WRONG, WRONG]),
      mcq("A profitable company growing 45% a year reports negative operating cash flow. The most likely explanation is:",
        ["The profit figure is fraudulent", "Working capital is absorbing cash faster than profit is collected", "Depreciation is too high", "Interest costs rose"], 1,
        [WRONG, "Correct. Growth requires stock and credit ahead of collection, so working capital consumes the profit and more. Common and usually fundable, but it must be planned for.", WRONG, WRONG]),
    ]);

  lesson("c-debt-issuance", "Debt issuance",
    "Raising borrowed money: cash in today, a fixed obligation from that moment on.",
    [
      h2("What is this?"),
      p("Debt issuance is the act of raising money by borrowing — drawing a bank term loan, issuing bonds or debentures, or taking a working capital facility. It appears as a cash inflow in <strong>financing activities</strong> on the cash flow statement."),
      p("Crucially, borrowing is not income. Cash rises and a liability of the same size appears; the income statement sees nothing at all in that moment. Only the interest, in later periods, becomes an expense."),
      h2("Why does it matter?"),
      p("Debt is the cheapest external capital because lenders take the least risk — they are paid before owners and their return is fixed. Used on projects that earn more than the interest rate, it lifts owner returns. Used on projects that do not, it magnifies losses just as efficiently."),
      p("It also matters where the cash came from. A company whose operating cash flow is negative and whose cash balance is only rising because of new borrowing is in a very different position from one generating cash internally — a distinction visible only by reading the three sections of the cash flow statement separately."),
      h2("How does it work?"),
      h3("Step 1: Cash and liability rise together"),
      p("Assets increase by the amount received; liabilities increase by the amount owed. Equity is untouched."),
      h3("Step 2: Interest begins to accrue"),
      p("From then on, each period's interest is an expense on the income statement, reducing profit before tax."),
      h3("Step 3: The repayment schedule starts running"),
      p("Principal repayments are financing outflows later — not expenses, since they simply extinguish the liability."),
      h3("Step 4: Judge it against what the money buys"),
      p("Borrowing to fund an asset earning 16% at an 11% rate creates value. The same loan funding losses only postpones a problem."),
      caseStudy("Real-Life Case Study: funding a new plant",
        ["A manufacturer raises ₹200 crore of 5-year debt at 11% to build a plant expected to add ₹38 crore a year of operating profit."],
        [["Debt raised (financing inflow)", "₹200 crore"], ["Effect on this year's profit", "₹0"], ["Annual interest from next year", "₹22 crore"], ["Expected extra operating profit", "₹38 crore"], ["Net annual gain to owners", "₹16 crore"], ["Return on the borrowed money", "19%"]],
        ["The ₹200 crore inflow is not profit — it is cash matched by an equal obligation.",
         "The arithmetic works while the plant delivers ₹38 crore. If it delivers only ₹15 crore, the ₹22 crore of interest still falls due in full and the borrowing destroys ₹7 crore a year. The loan did not change; the return on what it bought did."]),
      h2("Key terms"),
      def("Financing activities", "The section of the cash flow statement covering money raised from or returned to lenders and shareholders."),
      def("Principal", "The amount borrowed, repayable at or before maturity. Its repayment is not an expense."),
      def("Covenant", "A condition in a loan agreement — often a leverage or coverage ratio — that the borrower must keep meeting."),
      def("Maturity", "The date by which the borrowing must be repaid or refinanced."),
      h2("Practice"),
      practice([
        { q: "A company borrows ₹80 crore at 10%. Show the effect on this year's cash, profit and balance sheet.", a: "Cash: +₹80 crore in financing activities. Profit: unchanged in the moment of borrowing. Balance sheet: assets +₹80 crore (cash), liabilities +₹80 crore (debt), equity unchanged. From next period, ₹8 crore a year of interest reduces profit before tax." },
        { q: "A firm's cash balance rose ₹50 crore. Operating cash flow was −₹30 crore and it raised ₹90 crore of debt. What should you conclude?", a: "The cash increase is entirely borrowed; the business consumed ₹30 crore. Cash is up while the underlying position deteriorated, and ₹90 crore now has to be serviced and repaid. Reading only the cash balance would badly mislead." },
        { q: "Why does borrowing at 11% to fund a project returning 9% still increase reported profit in absolute terms, yet destroy value?", a: "Absolute profit may rise because the project adds some earnings, but each rupee borrowed costs 11 and earns 9, so owners lose 2 per rupee. Value depends on the spread between return and cost of capital, not on whether profit went up." },
      ]),
      h2("Sandbox"),
      sandbox("leverage-returns", "Borrowing sandbox",
        "Cut operating profit by half and compare the levered and all-equity returns — interest does not flex with a bad year.", [
        { key: "operatingProfit", label: "Profit before interest", value: 380000000, unit: "₹" },
        { key: "debt", label: "Debt raised", value: 2000000000, unit: "₹" },
        { key: "interestRate", label: "Interest rate", value: 11, unit: "%" },
        { key: "equity", label: "Owner capital", value: 2000000000, unit: "₹" },
      ]),
      h2("What to remember"),
      note([
        "Borrowing is a financing inflow, never income.",
        "Cash and liabilities rise together; equity is unchanged.",
        "Only interest hits the income statement; principal repayment does not.",
        "Debt adds value only when what it funds earns more than it costs.",
      ]),
      h2("Common mistakes"),
      list([
        "<strong>Treating borrowed cash as performance.</strong> A rising cash balance funded by debt is not cash generation.",
        "<strong>Ignoring maturity.</strong> The same amount is routine over eight years and existential over four months.",
        "<strong>Judging debt by the interest rate alone</strong> rather than by the cash flow available to service it.",
        "<strong>Forgetting covenants.</strong> Breaching one can make long-term debt repayable immediately.",
      ]),
      mcq("A company raises ₹100 crore of debt. The immediate effect on the income statement is:",
        ["₹100 crore of income", "Nothing — borrowing is not income", "A ₹100 crore expense", "Revenue rises"], 1,
        [WRONG, "Correct. Cash and liabilities both rise; only the later interest becomes an expense.", WRONG, WRONG]),
      mcq("Debt issuance appears in which section of the cash flow statement?",
        ["Operating", "Financing", "Investing", "It does not appear"], 1,
        [WRONG, "Correct. Money raised from lenders or shareholders is a financing activity.", WRONG, WRONG]),
      mcq("Borrowing at 12% to fund a project earning 18% will:",
        ["Reduce owner returns", "Raise owner returns, while also raising risk", "Have no effect", "Eliminate risk"], 1,
        [WRONG, "Correct. The 6-point spread accrues to owners — but the interest is owed in full even if the project underperforms, so risk rises too.", WRONG, WRONG]),
    ]);

  lesson("c-debt-repayment", "Debt repayment",
    "Paying back principal reduces cash and debt together — and never touches profit.",
    [
      h2("What is this?"),
      p("Debt repayment is the return of borrowed principal to lenders. It appears as a cash outflow in financing activities."),
      p("The distinction that trips up beginners: <strong>interest is an expense; principal repayment is not</strong>. Interest is the cost of using the money and reduces profit. Repaying principal simply extinguishes a liability — cash falls, debt falls, and the income statement records nothing."),
      h2("Why does it matter?"),
      p("A company must generate enough cash for both interest and principal, but only one of them appears on the income statement. A firm can look comfortably profitable and still fail because a large repayment falls due in a year when the cash is not there."),
      p("This is why the maturity schedule matters as much as the total. ₹500 crore repayable over ten years and ₹500 crore repayable in six months are entirely different risks."),
      h2("How does it work?"),
      h3("Step 1: Split the payment"),
      p("A loan instalment usually contains both interest and principal. Only the interest portion is an expense."),
      h3("Step 2: Record each part correctly"),
      p("Interest: income statement, and operating (or financing) cash flow depending on presentation. Principal: financing outflow only."),
      h3("Step 3: Reduce the liability"),
      p("Cash falls and debt falls by the principal amount. Equity is unchanged — repaying debt does not create profit."),
      h3("Step 4: Check refinancing risk"),
      p("Many companies never truly repay; they refinance. That works until credit conditions tighten, which is exactly when they need it most."),
      caseStudy("Real-Life Case Study: an instalment year",
        ["A company with ₹300 crore of debt at 10% must repay ₹60 crore of principal this year."],
        [["Interest paid", "₹30 crore"], ["Principal repaid", "₹60 crore"], ["Total cash to lenders", "₹90 crore"], ["Charged to the income statement", "₹30 crore"], ["Operating cash flow", "₹75 crore"], ["Shortfall after debt service", "−₹15 crore"]],
        ["The income statement shows only the ₹30 crore of interest, so profit may look adequate.",
         "But ₹90 crore of cash has to leave against ₹75 crore generated. The ₹15 crore gap must come from reserves, asset sales or refinancing — a cash problem entirely invisible in the profit figure."]),
      h2("Key terms"),
      def("Principal repayment", "Returning the borrowed amount. A financing cash outflow, not an expense."),
      def("Debt service", "Interest plus principal — the total cash a borrower must find in a period."),
      def("Refinancing", "Replacing maturing debt with new borrowing rather than repaying it from cash."),
      def("Maturity schedule", "The timetable of when each borrowing falls due — as important as the total amount."),
      h2("Practice"),
      practice([
        { q: "A company pays a ₹14 crore instalment made up of ₹9 crore principal and ₹5 crore interest. What appears on the income statement and what appears in financing cash flow?", a: "Income statement: ₹5 crore of interest expense only. Financing cash flow: ₹9 crore principal outflow. Total cash out is ₹14 crore, but only ₹5 crore reduces profit." },
        { q: "Operating cash flow is ₹40 crore, interest is ₹12 crore and principal due is ₹35 crore. Assess the position.", a: "Debt service totals ₹47 crore against ₹40 crore generated — a ₹7 crore shortfall. The company must draw on cash reserves, sell something, or refinance. Profitability is not the issue; the repayment timetable is." },
        { q: "Why can a company that has always been profitable still default?", a: "Default is a cash event. Principal repayment never appears in profit, so a large maturity can arrive in a year when cash generation, reserves and refinancing markets do not cover it — regardless of the profit history." },
      ]),
      h2("Sandbox"),
      sandbox("leverage-returns", "Debt service sandbox",
        "Reduce debt and watch the interest burden fall — then note that principal repayment never appears in these profit figures at all.", [
        { key: "operatingProfit", label: "Profit before interest", value: 750000000, unit: "₹" },
        { key: "debt", label: "Debt outstanding", value: 3000000000, unit: "₹" },
        { key: "interestRate", label: "Interest rate", value: 10, unit: "%" },
        { key: "equity", label: "Owner capital", value: 2500000000, unit: "₹" },
      ]),
      h2("What to remember"),
      note([
        "Interest is an expense; principal repayment is not.",
        "Principal repayment reduces cash and debt, leaving profit untouched.",
        "Debt service = interest + principal, and only part of it is visible in profit.",
        "The maturity schedule matters as much as the amount borrowed.",
      ]),
      h2("Common mistakes"),
      list([
        "<strong>Expecting principal repayment to reduce profit.</strong> It settles a liability; it is not a cost of the period.",
        "<strong>Assessing debt safety from the income statement alone.</strong> The repayment timetable is not there.",
        "<strong>Assuming refinancing is always available.</strong> It is least available exactly when it is most needed.",
        "<strong>Treating repayment as value destruction.</strong> Net worth is unchanged; only the balance sheet composition moves.",
      ]),
      mcq("Repaying ₹50 crore of loan principal has what effect on profit?",
        ["Profit falls ₹50 crore", "No effect — it is not an expense", "Profit rises ₹50 crore", "It depends on the interest rate"], 1,
        [WRONG, "Correct. Cash and debt both fall by ₹50 crore; the income statement records nothing.", WRONG, WRONG]),
      mcq("A ₹20 crore instalment contains ₹6 crore of interest. How much reduces profit?",
        ["₹20 crore", "₹6 crore", "₹14 crore", "Nothing"], 1,
        [WRONG, "Correct. Only the ₹6 crore of interest is an expense; the ₹14 crore of principal is a financing outflow.", WRONG, WRONG]),
      mcq("A profitable company defaults on its debt. The most likely reason is:",
        ["Its margins fell slightly", "A large principal repayment fell due when cash and refinancing were unavailable", "Depreciation was too high", "It paid too much tax"], 1,
        [WRONG, "Correct. Solvency is about cash on a date. Principal repayments never appear in profit, so profitability offers no protection against a maturity wall.", WRONG, WRONG]),
    ]);

  lesson("c-dividends", "Dividends",
    "A dividend distributes profit to owners — it is not a cost of earning that profit.",
    [
      h2("What is this?"),
      p("A dividend is a payment of profit to shareholders. It is a <strong>distribution</strong>, not an expense: it does not appear on the income statement at all. It reduces retained earnings within equity, and appears as a cash outflow in financing activities."),
      p("Paying one is a choice. Unlike interest, a dividend can be reduced or skipped without legal consequence — which is exactly what makes equity less risky for the company and more risky for the investor."),
      h2("Why does it matter?"),
      p("The decision to pay or retain is one of the three core corporate finance decisions. Cash paid out cannot fund growth; cash retained must earn a decent return or it would have been better in shareholders' hands."),
      p("Dividend policy also signals. Companies are reluctant to cut dividends because the market reads a cut as distress, so a raised dividend is usually a statement of confidence in sustainable future cash — and a dividend maintained by borrowing is a warning."),
      h2("How does it work?"),
      h3("Step 1: The board decides"),
      p("Directors recommend an amount out of available profits, subject to law and any loan covenants restricting distributions."),
      h3("Step 2: Retained earnings fall"),
      p("The equity section reduces by the dividend. No expense is recorded anywhere."),
      h3("Step 3: Cash leaves"),
      p("A financing outflow when it is actually paid, which may be in a later period than when it was declared."),
      h3("Step 4: Test whether it was affordable"),
      p("Compare the dividend with free cash flow. Paid out of free cash flow it is sustainable; paid out of borrowing it is not."),
      { t: "formula", title: "Payout and retained earnings", lines: [
        "<b>Payout ratio = Dividends ÷ Net profit</b>",
        "<b>Closing retained earnings = Opening + Net profit − Dividends</b>",
      ] },
      caseStudy("Real-Life Case Study: two dividend decisions",
        ["A company earns ₹100 crore of net profit and generates ₹70 crore of free cash flow. It is considering a ₹60 crore dividend."],
        [["Net profit", "₹100 crore"], ["Free cash flow", "₹70 crore"], ["Proposed dividend", "₹60 crore"], ["Payout ratio (of profit)", "60%"], ["Covered by free cash flow", "1.17x"], ["Retained for growth", "₹10 crore"]],
        ["The dividend is affordable: free cash flow covers it 1.17 times, so it does not require borrowing.",
         "But only ₹10 crore remains for reinvestment. If the company has projects earning 20%, retaining more would create more value for the same shareholders than the cash they received. Payout is a genuine trade-off, not simply generosity."]),
      h2("Key terms"),
      def("Dividend", "A distribution of profit to shareholders. Reduces retained earnings; never an expense."),
      def("Payout ratio", "Dividends as a percentage of net profit."),
      def("Dividend yield", "Dividend per share divided by the share price — the income return to an investor at that price."),
      def("Retained earnings", "Cumulative profit kept in the business rather than distributed."),
      h2("Practice"),
      practice([
        { q: "Opening retained earnings ₹180 crore, net profit ₹45 crore, dividend ₹18 crore. Compute closing retained earnings and the payout ratio.", a: "Closing = 180 + 45 − 18 = ₹207 crore. Payout ratio = 18 ÷ 45 = 40%." },
        { q: "A company pays a ₹50 crore dividend while free cash flow is ₹20 crore and it raises ₹40 crore of debt. Assess this.", a: "The dividend is not covered by cash generation; ₹30 crore of it is effectively funded by borrowing. That converts equity into debt on the balance sheet and is unsustainable — the dividend is being maintained for signalling reasons rather than affordability." },
        { q: "Why is a dividend not an expense, when interest is?", a: "Interest is the contractual cost of using lenders' money, incurred to earn the profit. A dividend is the distribution of profit already earned, to the owners of that profit. One is a cost of doing business; the other is what is done with the result." },
      ]),
      h2("Sandbox"),
      sandbox("retained", "Payout sandbox",
        "Pay out more than the year's profit and watch retained earnings fall — a company can distribute past profits, but not indefinitely.", [
        { key: "opening", label: "Opening retained earnings", value: 1800000000, unit: "₹" },
        { key: "netProfit", label: "Profit for the year", value: 450000000, unit: "₹" },
        { key: "dividends", label: "Dividends paid", value: 180000000, unit: "₹" },
      ]),
      h2("What to remember"),
      note([
        "A dividend is a distribution, not an expense — it never touches the income statement.",
        "It reduces retained earnings and appears as a financing cash outflow.",
        "Test affordability against free cash flow, not against profit.",
        "Retaining is better than paying out only if the retained cash earns a good return.",
      ]),
      h2("Common mistakes"),
      list([
        "<strong>Expecting dividends on the income statement.</strong> They reduce equity, not profit.",
        "<strong>Judging a dividend against profit rather than free cash flow.</strong> Profit is not cash.",
        "<strong>Reading a high yield as a bargain.</strong> A yield rises when the price falls, which often precedes a cut.",
        "<strong>Assuming retention is always better.</strong> Cash retained and invested poorly destroys value.",
      ]),
      mcq("A ₹30 crore dividend is paid. The effect on net profit is:",
        ["Net profit falls ₹30 crore", "No effect — dividends are a distribution of profit, not an expense", "Net profit rises", "It depends on the tax rate"], 1,
        [WRONG, "Correct. The dividend reduces retained earnings within equity and cash; the income statement is untouched.", WRONG, WRONG]),
      mcq("Net profit ₹80 crore, dividend ₹24 crore. The payout ratio is:",
        ["24%", "30%", "56%", "333%"], 1,
        [WRONG, "Correct. 24 ÷ 80 = 30% — the rest is retained in the business.", WRONG, WRONG]),
      mcq("A company maintains its dividend by borrowing. This is best described as:",
        ["Prudent capital management", "Unsustainable — equity is being converted into debt", "Tax efficient", "A sign of strong cash generation"], 1,
        [WRONG, "Correct. Distributions should come from cash the business generates. Funding them with debt raises leverage while returning capital, and cannot continue.", WRONG, WRONG]),
    ]);

  lesson("c-stock-issuance", "Stock issuance",
    "Selling new shares raises cash without repayment — and divides ownership among more hands.",
    [
      h2("What is this?"),
      p("Stock issuance is raising money by selling new shares: an IPO, a follow-on offering, a rights issue, a private placement. Cash comes in as a financing inflow and equity rises by the same amount."),
      p("Unlike debt, there is no repayment date and no interest. What the company gives up instead is a permanent share of all future profits, and some control."),
      h2("Why does it matter?"),
      p("Equity is the most patient capital there is. It does not have to be repaid, so it is what businesses use when cash flows are uncertain — startups, or companies funding long projects with distant payoffs."),
      p("It is also the most expensive, precisely because shareholders bear the most risk and demand the highest return. And it <strong>dilutes</strong>: existing owners' proportional stake, and their claim on each rupee of future profit, shrinks."),
      h2("How does it work?"),
      h3("Step 1: Cash and equity rise"),
      p("Assets increase by the amount raised; share capital and share premium increase within equity. Liabilities are unchanged."),
      h3("Step 2: The share count rises"),
      p("More shares now divide the same future profits, so earnings per share falls unless the new money earns a return."),
      h3("Step 3: No fixed obligation is created"),
      p("Nothing is owed on a schedule. In a bad year the company simply pays no dividend — an option debt never offers."),
      h3("Step 4: Judge dilution against what the money buys"),
      p("Issuing 20% more shares is worthwhile if the cash raises future profits by more than 20%. Otherwise existing owners are worse off."),
      { t: "formula", title: "Dilution", lines: [
        "<b>EPS = Net profit ÷ Number of shares</b>",
        "<b>New ownership % = Old shares ÷ (Old shares + New shares)</b>",
      ] },
      caseStudy("Real-Life Case Study: a rights issue",
        ["A company with 10 crore shares and ₹60 crore of net profit issues 2 crore new shares at ₹150 to fund expansion."],
        [["Shares before", "10 crore"], ["EPS before", "₹6.00"], ["New shares issued", "2 crore"], ["Cash raised", "₹300 crore"], ["Shares after", "12 crore"], ["EPS if profit unchanged", "₹5.00"]],
        ["Ownership for an existing holder who does not participate falls from 100% of 10 crore shares to 10/12 — about 83% of the company.",
         "EPS drops from ₹6.00 to ₹5.00 immediately. The issue only benefits existing owners if the ₹300 crore lifts net profit above ₹72 crore, restoring EPS to ₹6. Below that, they own a smaller slice of a business that did not grow enough to compensate."]),
      h2("Key terms"),
      def("Dilution", "The reduction in existing shareholders' proportional ownership and per-share claim when new shares are issued."),
      def("Rights issue", "New shares offered first to existing shareholders, usually at a discount, so they can avoid dilution."),
      def("Share premium", "The amount received above the nominal value of the shares, recorded within equity."),
      def("EPS", "Earnings per share — net profit divided by the number of shares outstanding."),
      h2("Practice"),
      practice([
        { q: "A company with 50 lakh shares and ₹4 crore of profit issues 10 lakh new shares. What happens to EPS if profit is unchanged?", a: "EPS before = 4,00,00,000 ÷ 50,00,000 = ₹8.00. After: 4,00,00,000 ÷ 60,00,000 = ₹6.67. A 20% increase in shares cut EPS by about 17%." },
        { q: "Following on: how much must profit rise for EPS to return to ₹8?", a: "Profit needed = ₹8 × 60,00,000 = ₹4.8 crore — a 20% increase. The new money must earn enough to lift profit in proportion to the dilution before existing owners are no worse off." },
        { q: "Why might a loss-making company with volatile cash flows prefer equity to debt, despite equity being more expensive?", a: "Debt demands fixed interest and repayment regardless of results, which a volatile, loss-making business may be unable to meet — risking default. Equity has no fixed obligation, so it survives bad years. The higher cost buys survivability." },
      ]),
      h2("Sandbox"),
      sandbox("balance", "Equity raise sandbox",
        "Add the cash raised to assets while leaving liabilities alone, and watch the owners' stake grow by exactly that amount.", [
        { key: "assets", label: "Total assets after raise", value: 1800000000, unit: "₹" },
        { key: "liabilities", label: "Total liabilities", value: 700000000, unit: "₹" },
      ]),
      h2("What to remember"),
      note([
        "Issuing shares raises cash and equity together; no liability is created.",
        "There is no repayment date and no interest — but ownership is permanently shared.",
        "Dilution is only justified if the money raised grows profit by more than the increase in shares.",
        "Equity is the most expensive capital because shareholders bear the most risk.",
      ]),
      h2("Common mistakes"),
      list([
        "<strong>Calling equity free because there is no interest.</strong> Shareholders demand higher returns than lenders.",
        "<strong>Treating money raised as profit.</strong> It is capital contributed, not earnings.",
        "<strong>Ignoring dilution</strong> when the headline profit figure rises but EPS falls.",
        "<strong>Issuing shares when they are cheap.</strong> Selling ownership at a low price transfers value from existing owners to new ones.",
      ]),
      mcq("A company issues new shares for ₹200 crore. The effect on liabilities is:",
        ["Liabilities rise ₹200 crore", "Liabilities are unchanged; equity rises ₹200 crore", "Liabilities fall", "Profit rises ₹200 crore"], 1,
        [WRONG, "Correct. Cash and equity both rise. No obligation to repay is created, which is what distinguishes equity from debt.", WRONG, WRONG]),
      mcq("A firm with 20 crore shares earning ₹100 crore issues 5 crore new shares. If profit is unchanged, EPS moves from:",
        ["₹5.00 to ₹5.00", "₹5.00 to ₹4.00", "₹5.00 to ₹6.25", "₹4.00 to ₹5.00"], 1,
        [WRONG, "Correct. 100 ÷ 20 = ₹5.00 before; 100 ÷ 25 = ₹4.00 after. Profit must rise 25% just to hold EPS steady.", WRONG, WRONG]),
      mcq("Why is equity described as more expensive than debt?",
        ["It carries a higher interest rate", "Shareholders bear the most risk and therefore demand the highest return", "It must be repaid faster", "Regulators require it"], 1,
        [WRONG, "Correct. Owners are paid last and have no guarantee, so they require a higher expected return than lenders — which makes equity costly despite having no interest.", WRONG, WRONG]),
    ]);

  /* ====================== THREE-STATEMENT CONNECTION ====================== */

  lesson("c-revenue-cascade-through-the-three-statements", "Revenue cascade through the three statements",
    "Follow one sale as it moves through the income statement, balance sheet and cash flow statement.",
    [
      h2("What is this?"),
      p("The three statements are not three separate reports. They are three views of the same events. A single sale touches all three, and tracing one transaction end to end is the fastest way to understand how they lock together."),
      p("The cascade: revenue is recognised on the income statement when delivery happens; the balance sheet records what that created — a receivable, then cash; the cash flow statement explains the difference between the profit reported and the cash actually collected."),
      h2("Why does it matter?"),
      p("Almost every confusion in financial analysis comes from reading one statement in isolation. Profit without cash flow hides collection problems. Cash without profit hides whether the business is actually viable. The balance sheet without either hides how it got there."),
      p("Anyone who can trace a transaction through all three can also spot when the three do not agree — which is where accounting problems usually first show."),
      h2("How does it work?"),
      h3("Step 1: Delivery creates revenue"),
      p("The income statement recognises the sale when goods or services are handed over, regardless of payment."),
      h3("Step 2: The balance sheet records the claim"),
      p("If the customer has not paid, a receivable appears. Inventory falls by the cost of what was sold."),
      h3("Step 3: Profit lands in equity"),
      p("Net profit flows into retained earnings, which is why the balance sheet balances after the income statement is prepared."),
      h3("Step 4: Cash flow reconciles the difference"),
      p("Start from profit, add back non-cash charges, adjust for the working capital movement. The result is the cash the sale really produced — this period."),
      caseStudy("Real-Life Case Study: one ₹10 lakh order",
        ["A furniture maker delivers a ₹10,00,000 order in March that cost ₹6,00,000 to build. The customer pays in May."],
        [["March revenue", "₹10,00,000"], ["March cost of goods sold", "₹6,00,000"], ["March gross profit", "₹4,00,000"], ["Receivable created (March)", "₹10,00,000"], ["Cash received in March", "₹0"], ["Working capital adjustment (March)", "−₹10,00,000"]],
        ["March shows ₹4,00,000 of profit and zero cash from this order. The income statement and the bank balance disagree, and both are correct.",
         "In May the receivable converts: cash rises ₹10,00,000, the receivable disappears, and no new revenue is recorded — May's cash flow statement shows a positive working capital movement with no matching profit. Over the two months the statements reconcile exactly."]),
      h2("Key terms"),
      def("Accrual", "Recording revenue and costs when earned or incurred, not when cash moves. The reason the three statements differ."),
      def("Retained earnings link", "Net profit flows from the income statement into equity — the join that keeps the balance sheet balancing."),
      def("Working capital adjustment", "The cash flow line converting accrual profit into cash by allowing for receivables, inventory and payables."),
      def("Reconciliation", "Checking that profit, balance sheet movements and cash flow tell one consistent story."),
      h2("Practice"),
      practice([
        { q: "A company delivers ₹25 lakh of goods costing ₹15 lakh in June and collects in August. State the June effect on all three statements.", a: "Income statement: revenue ₹25 lakh, COGS ₹15 lakh, gross profit ₹10 lakh. Balance sheet: receivables +₹25 lakh, inventory −₹15 lakh, retained earnings +₹10 lakh. Cash flow: profit ₹10 lakh less a ₹25 lakh receivable increase, plus ₹15 lakh inventory release = −₹0 cash… more precisely, operating cash is profit ₹10L − receivable ₹25L + inventory reduction ₹15L = ₹0." },
        { q: "Net profit is ₹30 crore, depreciation ₹12 crore, and working capital rose ₹20 crore. Compute approximate operating cash flow.", a: "30 + 12 − 20 = ₹22 crore. The depreciation add-back raises it because no cash left; the working capital increase reduces it because cash is locked in operations." },
        { q: "Why must net profit appear in the equity section of the balance sheet?", a: "Profit belongs to the owners, so it increases their residual claim through retained earnings. Without that link the balance sheet would not balance after recognising the assets and liabilities the period's trading created." },
      ]),
      h2("Sandbox"),
      sandbox("profit-to-cash", "Profit-to-cash sandbox",
        "Raise receivables and inventory and watch cash fall away from profit; then increase payables and see some of it return.", [
        { key: "profit", label: "Reported profit", value: 30000000, unit: "₹" },
        { key: "receivablesIncrease", label: "Increase in receivables", value: 20000000, unit: "₹" },
        { key: "inventoryIncrease", label: "Increase in inventory", value: 8000000, unit: "₹" },
        { key: "payablesIncrease", label: "Increase in payables", value: 5000000, unit: "₹" },
      ]),
      h2("What to remember"),
      note([
        "One transaction touches all three statements; they are views, not separate reports.",
        "Revenue follows delivery; the balance sheet records the resulting claim; cash flow explains the timing gap.",
        "Net profit flows into retained earnings — the link that keeps the balance sheet balanced.",
        "Profit and cash disagreeing is normal. Persistent, widening divergence is the warning.",
      ]),
      h2("Common mistakes"),
      list([
        "<strong>Reading one statement alone</strong> and drawing conclusions the other two would contradict.",
        "<strong>Assuming revenue means cash received.</strong> It means value delivered.",
        "<strong>Forgetting inventory falls when a sale happens.</strong> The cost moves from the balance sheet to COGS.",
        "<strong>Treating a profit–cash gap as fraud.</strong> It is usually timing; the question is whether it keeps widening.",
      ]),
      mcq("A sale is delivered in March and paid in May. March's income statement and cash flow show:",
        ["Revenue and cash in March", "Revenue in March, no cash from the sale until May", "Cash in March, revenue in May", "Nothing until May"], 1,
        [WRONG, "Correct. Revenue follows delivery; the cash arrives later, and a receivable bridges the two on the balance sheet.", WRONG, WRONG]),
      mcq("Net profit ₹50 crore, depreciation ₹10 crore, working capital increase ₹30 crore. Approximate operating cash flow is:",
        ["₹90 crore", "₹30 crore", "₹50 crore", "₹70 crore"], 1,
        [WRONG, "Correct. 50 + 10 − 30 = ₹30 crore. Depreciation is added back; the working capital increase consumes cash.", WRONG, WRONG]),
      mcq("Which link makes the balance sheet balance after the income statement is prepared?",
        ["Revenue flows into receivables", "Net profit flows into retained earnings", "Cash flows into equity", "Depreciation flows into liabilities"], 1,
        [WRONG, "Correct. Profit belongs to owners, so it increases retained earnings within equity — the joint between the two statements.", WRONG, WRONG]),
    ]);
})();
