/* Level 6 — Investment Banking. 14 lessons.
   Same schema and loop as Levels 4-5. One deal runs through the M&A module:
   Northline Foods acquiring Kesar Spices, so the numbers accumulate. */
(function () {
  "use strict";
  var LS = (window.LS = window.LS || {});
  LS.lessons = LS.lessons || {};

  function h2(t) { return { t: "h2", text: t }; }
  function p(h) { return { t: "p", h: h }; }
  function list(i) { return { t: "list", items: i }; }
  function def(term, h) { return { t: "def", term: term, h: h }; }
  function note(i) { return { t: "note", h: "<ul>" + i.map(function (x) { return "<li>" + x + "</li>"; }).join("") + "</ul>" }; }
  function practice(i) { return { t: "practice", items: i }; }
  function sandbox(kind, title, prompt, fields) { return { t: "sandbox", kind: kind, title: title, prompt: prompt, fields: fields }; }
  function formula(title, lines) { return { t: "formula", title: title, lines: lines }; }
  function mcq(q, o, c, w) { return { t: "mcq", q: q, opts: o, correct: c, why: w }; }
  function fig(title, intro, rows, meaning) {
    var h = '<p class="case-title"><strong>' + title + "</strong></p>";
    intro.forEach(function (x) { h += "<p>" + x + "</p>"; });
    h += '<div class="case-figures">';
    rows.forEach(function (r) { h += '<div class="case-row"><span class="case-label">' + r[0] + '</span><span class="case-value">' + r[1] + "</span></div>"; });
    h += '</div><p class="case-meaning"><strong>What it means.</strong></p>';
    meaning.forEach(function (x) { h += "<p>" + x + "</p>"; });
    return { t: "example", h: h };
  }
  function L(id, title, lede, body) {
    LS.lessons[id] = { id: id, title: title, short: title, desc: lede, lede: lede, minutes: 7, body: body };
  }
  var W = "Not quite — re-read the explanation above.";

  /* ============ TRANSACTION VALUATION ============ */

  L("c-comparable-companies", "Comparable companies",
    "Value a business by what similar listed businesses trade at today.",
    [
      h2("What is this?"),
      p("Comparable company analysis — 'comps' — values a company by applying the multiples at which similar listed companies trade. If five peers trade at 8-10× EBITDA, that range becomes the starting point for the company you are valuing."),
      p("It is a relative valuation: it tells you what the market pays for businesses like this one, not what the business is intrinsically worth."),
      h2("Why does it matter?"),
      p("It is fast, grounded in observable prices, and it is how most deal conversations actually start. A DCF says what you think; comps say what the market currently pays."),
      p("Its weakness follows directly: if the whole sector is overpriced, comps will value your company at that overpriced level and look perfectly reasonable doing it."),
      h2("How does it work?"),
      list([
        "<strong>Select the peer set.</strong> Same industry, similar size, similar growth and margins. Four to eight genuine comparables beat twenty loose ones.",
        "<strong>Compute each peer's multiples</strong> — EV/EBITDA, EV/Revenue, P/E — from current prices and latest reported figures.",
        "<strong>Take the median</strong>, not the mean; one outlier distorts an average badly.",
        "<strong>Apply the range</strong> to the target's own metric, and state where in the range it belongs and why.",
      ]),
      fig("Real-Life Case Study: a peer set",
        ["Valuing Kesar Spices, EBITDA ₹80 crore, using five listed food companies."],
        [["Peer A", "9.2x"], ["Peer B", "7.8x"], ["Peer C", "11.4x"], ["Peer D", "8.6x"], ["Peer E", "8.1x"],
         ["Median", "8.6x"], ["Implied EV for Kesar", "₹688 crore"]],
        ["The median of 8.6× gives ₹688 crore; the mean of 9.0× would give ₹720 crore, pulled up by Peer C.",
         "Before using either, ask why Peer C trades at 11.4×. If it grows faster or earns better margins, it is not comparable and the median is the honest anchor."]),
      h2("Key terms"),
      def("Comparable companies", "Listed businesses similar enough that their trading multiples inform the target's value."),
      def("Peer set", "The specific companies chosen for comparison — the most consequential judgement in the analysis."),
      def("Median multiple", "The middle value of the peer multiples, preferred over the mean because outliers distort averages."),
      h2("Practice"),
      practice([
        { q: "Peers trade at 6.2×, 7.0×, 7.4×, 12.8× and 7.8× EBITDA. Compute the median and mean, and say which to use.", a: "Sorted: 6.2, 7.0, 7.4, 7.8, 12.8. Median = 7.4×. Mean = 8.24×. Use the median — the 12.8× outlier lifts the mean by 0.84 turns and probably reflects a company that is not truly comparable." },
        { q: "Your target grows 4% a year; the peer median grows 12%. How should you apply the peer multiple?", a: "At a discount to the median. Slower growth justifies a lower multiple, so applying the median unadjusted would overvalue the target. State the discount and the reason explicitly rather than quietly using the median." },
      ]),
      h2("Connection"),
      p("Comps give the multiple that EV/EBITDA from Level 5 applies, and the exit multiple used in LBO returns at Level 7."),
      mcq("Why use the median rather than the mean peer multiple?",
        ["It is easier", "A single outlier distorts the mean but not the median", "The median is always higher", "Regulators require it"], 1,
        [W, "Correct. One unusually priced peer can move a mean by a full turn; the median is unaffected.", W, W]),
    ]);

  L("c-precedent-transactions", "Precedent transactions",
    "Value a business by what acquirers actually paid for similar ones.",
    [
      h2("What is this?"),
      p("Precedent transaction analysis uses the multiples paid in past acquisitions of similar companies. Where comps show trading prices, precedents show what a buyer paid to own the whole thing."),
      h2("Why does it matter?"),
      p("Acquisition prices are almost always higher than trading prices, because a buyer pays a <strong>control premium</strong> — the right to direct the business, and the synergies they expect to extract. If you are advising on a sale, precedents are the more relevant benchmark."),
      p("They are also stale. A deal done two years ago was priced in different conditions, so a precedent set spanning a cycle mixes markets that no longer exist."),
      h2("How does it work?"),
      list([
        "Gather completed deals in the same sector, ideally within the last two to three years.",
        "Compute EV paid ÷ target's EBITDA at the time of the deal.",
        "Note the control premium implied over the target's pre-announcement trading price.",
        "Weight recent deals more heavily, and discard those done in obviously different conditions.",
      ]),
      fig("Real-Life Case Study: trading versus transaction",
        ["Food-sector deals over three years, against where the sector trades."],
        [["Deal 1 (last year)", "10.5x"], ["Deal 2 (18 months ago)", "9.8x"], ["Deal 3 (3 years ago)", "12.6x"],
         ["Median transaction multiple", "10.5x"], ["Median trading multiple", "8.6x"], ["Implied control premium", "≈22%"]],
        ["Buyers paid about 22% more than the market was paying for minority stakes in the same companies.",
         "For Kesar Spices at ₹80 crore of EBITDA, that is the difference between ₹688 crore and ₹840 crore — ₹152 crore of value that depends entirely on which benchmark you cite."]),
      h2("Key terms"),
      def("Precedent transaction", "A completed acquisition whose price informs the valuation of a similar company."),
      def("Control premium", "The extra paid to own and direct a business rather than hold a minority stake."),
      h2("Practice"),
      practice([
        { q: "Trading median 8.6×, transaction median 10.5×, target EBITDA ₹80 crore. Compute both implied EVs and the premium.", a: "Trading: 8.6 × 80 = ₹688 crore. Transaction: 10.5 × 80 = ₹840 crore. Premium = 840 ÷ 688 − 1 = 22%." },
        { q: "Why do precedent transactions usually show higher multiples than trading comps?", a: "A buyer acquires control and expects synergies, so pays above the price of a passive minority stake. The premium compensates existing shareholders for giving up the asset." },
      ]),
      h2("Connection"),
      p("Precedents set the price expectation the purchase price lesson works from, and the premium is what synergies must justify."),
      mcq("A control premium exists because the buyer:",
        ["Pays in cash", "Gains the right to direct the business and capture synergies", "Is a larger company", "Is overpaying by definition"], 1,
        [W, "Correct. Control and expected synergies are worth something a minority stake does not confer.", W, W]),
    ]);

  L("c-trading-multiples", "Trading multiples",
    "What the public market pays, per unit of earnings, for a minority stake.",
    [
      h2("What is this?"),
      p("Trading multiples are the ratios derived from a listed company's current share price: EV/EBITDA, EV/Revenue, P/E. They price a small, passive stake bought on an exchange."),
      h2("Why does it matter?"),
      p("They are observable, updated daily, and require no assumptions about the future. That makes them the fastest sanity check on any valuation — including a DCF, whose output should be compared against them before it is trusted."),
      p("What they price is important: a minority stake with no control. That is why they sit below transaction multiples."),
      h2("How does it work?"),
      formula("Trading multiples", [
        "<b>EV/EBITDA = (Market cap + Net debt) ÷ EBITDA</b>",
        "<b>P/E = Share price ÷ EPS</b>",
        "Use current market prices with the latest reported or forward earnings",
      ]),
      p("Be consistent about the period: a multiple on trailing earnings and one on forward earnings are different numbers and must not be mixed within a peer set."),
      fig("Real-Life Case Study: trailing versus forward",
        ["A peer growing EBITDA 20% a year, priced at an EV of ₹960 crore."],
        [["Trailing EBITDA", "₹100 crore"], ["Trailing EV/EBITDA", "9.6x"], ["Forward EBITDA", "₹120 crore"],
         ["Forward EV/EBITDA", "8.0x"], ["Difference", "1.6 turns"]],
        ["The same company looks 9.6× or 8.0× depending purely on which year's earnings you divide by.",
         "Mixing trailing multiples for some peers and forward for others is one of the commonest errors in a comps table, and it silently moves the median."]),
      h2("Key terms"),
      def("Trailing multiple", "Based on the last twelve months of reported earnings."),
      def("Forward multiple", "Based on forecast earnings for the coming year."),
      h2("Practice"),
      practice([
        { q: "Market cap ₹700 crore, net debt ₹180 crore, trailing EBITDA ₹95 crore, forward ₹115 crore. Compute both multiples.", a: "EV = ₹880 crore. Trailing = 880 ÷ 95 = 9.3×. Forward = 880 ÷ 115 = 7.7×." },
        { q: "Why must a comps table use the same basis for every peer?", a: "Trailing and forward multiples differ by a turn or more for growing companies. Mixing them makes the median meaningless, because it averages numbers computed on different years." },
      ]),
      h2("Connection"),
      p("These are the multiples the comparable companies lesson collects, and the cross-check on any DCF from Level 5."),
      mcq("Trading multiples price:",
        ["Full control of a business", "A minority stake bought on the exchange", "Only private companies", "The book value of assets"], 1,
        [W, "Correct. That is why acquisition multiples sit above them — control and synergies are extra.", W, W]),
    ]);

  L("c-transaction-multiples", "Transaction multiples",
    "The price paid for control, and what it tells you about a sale.",
    [
      h2("What is this?"),
      p("Transaction multiples are calculated from completed acquisitions: enterprise value paid divided by the target's EBITDA or revenue at the time."),
      h2("Why does it matter?"),
      p("If you are selling a business or advising a board, these are the numbers that matter. They embed the control premium and whatever synergies the buyer believed in."),
      p("They are also negotiating anchors. A seller cites the highest defensible precedent; a buyer cites the median and argues the outliers were strategic exceptions."),
      h2("How does it work?"),
      list([
        "Use enterprise value paid, not equity value — the buyer assumed the debt too.",
        "Use the target's EBITDA for the twelve months before announcement, not after.",
        "Record whether the buyer was strategic or financial: strategic buyers pay more, because they can extract synergies a financial buyer cannot.",
        "Note the deal conditions — a competitive auction produces a higher multiple than a bilateral negotiation.",
      ]),
      fig("Real-Life Case Study: who bought matters",
        ["Six food-sector deals, split by buyer type."],
        [["Strategic buyer — median", "11.2x"], ["Financial buyer — median", "9.0x"], ["Auction processes — median", "11.0x"],
         ["Bilateral deals — median", "9.3x"], ["Overall median", "10.5x"]],
        ["Strategic buyers paid 2.2 turns more than financial buyers, because they could fold the target into an existing business and remove duplicate costs.",
         "For Kesar Spices at ₹80 crore of EBITDA, that gap is ₹176 crore. Knowing who is likely to buy is therefore part of estimating what it will fetch."]),
      h2("Key terms"),
      def("Strategic buyer", "An operating company that can extract synergies from the target."),
      def("Financial buyer", "A private equity fund or similar, valuing the target on its standalone cash flows and returns."),
      h2("Practice"),
      practice([
        { q: "A target with ₹60 crore EBITDA attracts a strategic buyer at 11.2× and a financial buyer at 9.0×. Compute both prices and the gap.", a: "Strategic: ₹672 crore. Financial: ₹540 crore. Gap = ₹132 crore, or 24% — the value of the synergies the strategic buyer expects to capture." },
        { q: "Why does an auction typically produce a higher multiple than a bilateral negotiation?", a: "Competition. Multiple bidders force each to bid closer to their true maximum, whereas a single buyer in a private negotiation can hold nearer the seller's minimum." },
      ]),
      h2("Connection"),
      p("These multiples set the purchase price in the merger model, and the synergies lesson tests whether the premium is justified."),
      mcq("Strategic buyers typically pay more than financial buyers because they:",
        ["Have more cash", "Can extract synergies a standalone owner cannot", "Are less careful", "Pay in shares"], 1,
        [W, "Correct. Synergies raise the value of the target in their hands specifically, so they can pay more and still earn a return.", W, W]),
    ]);

  /* ============ M&A MODELING ============ */

  L("c-purchase-price", "Purchase price",
    "What the buyer actually pays, and how the offer is constructed.",
    [
      h2("What is this?"),
      p("The purchase price is what the acquirer pays for the target. It is usually expressed as an <strong>offer per share</strong> for a listed company, or an enterprise value for a private one — and the two are connected by net debt."),
      h2("Why does it matter?"),
      p("Everything in a merger model flows from it: the funding required, the goodwill created, the interest cost, and whether the deal adds to or dilutes the buyer's earnings."),
      p("It is also the number the premium is measured against. Offering ₹120 for a share trading at ₹100 is a 20% premium — the amount the buyer must justify with synergies or a better plan for the assets."),
      h2("How does it work?"),
      formula("Purchase price", [
        "<b>Offer premium = (Offer price ÷ Unaffected price) − 1</b>",
        "<b>Equity purchase price = Offer per share × Diluted shares</b>",
        "<b>Enterprise value paid = Equity purchase price + Net debt assumed</b>",
      ]),
      p("Use the <em>unaffected</em> share price — the price before rumours moved it. Measuring a premium against an already-inflated price understates what is being paid."),
      fig("Real-Life Case Study: Northline offers for Kesar",
        ["Kesar Spices traded at ₹96 before rumours; Northline offers ₹120 per share."],
        [["Unaffected price", "₹96"], ["Offer price", "₹120"], ["Premium", "25%"],
         ["Diluted shares", "5 crore"], ["Equity purchase price", "₹600 crore"],
         ["Net debt assumed", "₹240 crore"], ["Enterprise value paid", "₹840 crore"], ["Implied EV/EBITDA on ₹80 cr", "10.5x"]],
        ["Northline pays ₹600 crore for the shares and takes on ₹240 crore of debt, so the business costs ₹840 crore.",
         "At 10.5× EBITDA that matches the transaction median — the price is defensible, but only if the synergies justify the 25% premium over where the shares actually traded."]),
      h2("Key terms"),
      def("Unaffected price", "The target's share price before deal speculation moved it."),
      def("Offer premium", "The percentage above the unaffected price that the buyer is paying."),
      def("Equity purchase price", "Offer per share times diluted shares — what shareholders receive."),
      h2("Practice"),
      practice([
        { q: "Unaffected price ₹80, offer ₹100, 8 crore diluted shares, net debt ₹150 crore. Compute the premium, equity price and EV paid.", a: "Premium = 25%. Equity price = 100 × 8 = ₹800 crore. EV paid = 800 + 150 = ₹950 crore." },
        { q: "Why measure the premium against the unaffected price rather than yesterday's close?", a: "Once a deal leaks, the target's price rises towards the expected offer. Measuring against that inflated price understates the true premium and makes the deal look cheaper than it is." },
      ]),
      h2("Connection"),
      p("The purchase price drives sources and uses, goodwill, and the accretion/dilution test that follows."),
      mcq("Enterprise value paid equals equity purchase price plus:",
        ["Synergies", "Net debt assumed", "The control premium", "Advisory fees only"], 1,
        [W, "Correct. The buyer inherits the target's debt, so the true cost of the business is the equity price plus that net debt.", W, W]),
    ]);

  L("c-sources-and-uses", "Sources & Uses",
    "The table that proves a deal is fully funded: every rupee needed, and where it comes from.",
    [
      h2("What is this?"),
      p("A sources and uses table lists what the transaction costs (uses) and where the money comes from (sources). The two totals must be equal — a deal that does not balance is not funded."),
      h2("Why does it matter?"),
      p("It is the first check any banker or lender performs. It exposes how much debt the buyer is taking on, how much equity it is contributing, and whether fees and refinancing have been forgotten — all before any modelling of the combined company."),
      h2("How does it work?"),
      list([
        "<strong>Uses:</strong> equity purchase price, refinancing the target's existing debt, transaction fees, financing fees.",
        "<strong>Sources:</strong> new debt raised, cash on hand, new equity issued, and rollover equity if management reinvests.",
        "Total sources must equal total uses exactly.",
      ]),
      fig("Real-Life Case Study: funding the Kesar deal",
        ["Northline acquires Kesar Spices, refinancing the target's debt."],
        [["Use — equity purchase price", "₹600 crore"], ["Use — refinance target debt", "₹240 crore"],
         ["Use — transaction fees", "₹25 crore"], ["Total uses", "₹865 crore"],
         ["Source — new debt", "₹500 crore"], ["Source — cash on hand", "₹115 crore"],
         ["Source — new equity issued", "₹250 crore"], ["Total sources", "₹865 crore"]],
        ["The table balances, so the deal is funded — and it immediately shows the structure: 58% debt-funded.",
         "Fees of ₹25 crore are real cash that buys nothing. Beginners routinely omit them, which understates the funding needed and overstates the returns."]),
      h2("Key terms"),
      def("Uses of funds", "Everything the transaction must pay for, including fees and refinancing."),
      def("Sources of funds", "Where the money comes from: debt, cash, new equity, rollover."),
      def("Rollover equity", "Target management reinvesting their proceeds into the new structure rather than cashing out."),
      h2("Practice"),
      practice([
        { q: "Equity price ₹400 crore, refinance ₹120 crore, fees ₹18 crore. The buyer raises ₹350 crore of debt and uses ₹40 crore of cash. How much new equity is needed?", a: "Uses = 400 + 120 + 18 = ₹538 crore. Sources so far = ₹390 crore. New equity required = ₹148 crore." },
        { q: "Why does the target's existing debt usually appear as a use of funds?", a: "Loan agreements often contain change-of-control clauses requiring repayment on acquisition, so the buyer must refinance it. It is a real cash requirement on day one, not an inherited liability that quietly continues." },
      ]),
      h2("Connection"),
      p("The financing mix chosen here determines the interest cost in the pro forma statements and the accretion/dilution outcome."),
      mcq("In a sources and uses table, total sources must:",
        ["Exceed uses", "Equal uses exactly", "Be less than uses", "Include synergies"], 1,
        [W, "Correct. Every rupee spent must be funded from somewhere; an imbalance means the deal is not fully financed.", W, W]),
    ]);

  L("c-financing-mix", "Financing mix",
    "How much of the deal is debt, how much is equity, and what each choice costs.",
    [
      h2("What is this?"),
      p("The financing mix is the split between debt, cash and new equity used to fund an acquisition. It is one of the few genuinely strategic choices in a deal, because it changes both the risk and the returns."),
      h2("Why does it matter?"),
      p("Debt is cheaper after tax and does not dilute existing shareholders, but it must be serviced whatever happens. New equity is safe but hands part of the combined company's future to new shareholders."),
      p("The mix usually decides whether a deal is accretive or dilutive, which is why boards argue about it far more than about the price."),
      h2("How does it work?"),
      list([
        "<strong>Cash on hand</strong> is cheapest — it earns little on deposit — but drains liquidity.",
        "<strong>Debt</strong> costs interest after tax and is constrained by leverage covenants and lender appetite.",
        "<strong>New equity</strong> costs the buyer's cost of equity and dilutes existing holders immediately.",
        "Test the resulting leverage: if pro forma net debt / EBITDA breaches what lenders accept, the mix is not available.",
      ]),
      fig("Real-Life Case Study: two ways to fund ₹865 crore",
        ["Northline's alternatives, with a pre-tax debt cost of 10% and a 25% tax rate."],
        [["Mix A — debt ₹700 cr / equity ₹165 cr", "after-tax interest ₹52.5 cr"], ["Mix A — pro forma leverage", "3.4x"],
         ["Mix B — debt ₹500 cr / equity ₹365 cr", "after-tax interest ₹37.5 cr"], ["Mix B — pro forma leverage", "2.6x"],
         ["Shares issued: Mix A vs B", "1.1 cr vs 2.4 cr"]],
        ["Mix A costs ₹15 crore more in after-tax interest but issues less than half the shares.",
         "Mix A will usually look more accretive per share and leaves far less room if earnings disappoint. That trade — earnings per share against survivability — is the real financing decision."]),
      h2("Key terms"),
      def("Financing mix", "The proportions of debt, cash and equity used to fund a transaction."),
      def("Pro forma leverage", "The combined company's net debt to EBITDA immediately after the deal."),
      h2("Practice"),
      practice([
        { q: "A ₹600 crore deal funded with ₹400 crore debt at 9% pre-tax, 25% tax. Compute the annual after-tax interest cost.", a: "Interest = 400 × 9% = ₹36 crore. After tax = 36 × 0.75 = ₹27 crore." },
        { q: "Why might a board choose more equity even though it dilutes shareholders?", a: "To keep pro forma leverage within covenant limits and preserve the ability to survive a downturn. Debt maximises earnings per share in good years and is what destroys the combined company in bad ones." },
      ]),
      h2("Connection"),
      p("The mix feeds directly into the pro forma interest expense and therefore the accretion/dilution result."),
      sandbox("leverage-returns", "Financing mix sandbox",
        "Shift the debt and equity split and watch the interest burden and owner return move in opposite directions.", [
        { key: "operatingProfit", label: "Combined operating profit", value: 2200000000, unit: "₹" },
        { key: "debt", label: "Acquisition debt", value: 5000000000, unit: "₹" },
        { key: "interestRate", label: "Interest rate", value: 10, unit: "%" },
        { key: "equity", label: "Equity funding", value: 3650000000, unit: "₹" },
      ]),
      mcq("Funding a deal with more debt rather than equity generally:",
        ["Reduces earnings per share", "Improves earnings per share but raises financial risk", "Has no effect on EPS", "Eliminates goodwill"], 1,
        [W, "Correct. Fewer new shares are issued, so earnings are split fewer ways — at the cost of a fixed interest obligation.", W, W]),
    ]);

  L("c-goodwill-acquisition", "Goodwill",
    "The premium over identifiable net assets, created the moment a deal closes.",
    [
      h2("What is this?"),
      p("In an acquisition, goodwill is the amount paid above the fair value of the target's identifiable net assets. It represents what the buyer paid for things that cannot be separately valued: brand, customer relationships, workforce, expected synergies."),
      h2("Why does it matter?"),
      p("It is usually one of the largest items created by a deal, and it sits on the balance sheet as a permanent record of the price paid. If the acquisition disappoints, goodwill is written down — a large non-cash loss that publicly marks the overpayment."),
      h2("How does it work?"),
      formula("Goodwill on acquisition", [
        "<b>Goodwill = Purchase price − Fair value of identifiable net assets</b>",
        "Identifiable net assets = fair value of assets − liabilities assumed",
        "Some of the premium may be allocated to identifiable intangibles first",
      ]),
      p("Before goodwill is struck, the target's assets are revalued to fair value and separable intangibles — brands, customer contracts — are recognised. Only the residual becomes goodwill."),
      fig("Real-Life Case Study: goodwill on the Kesar deal",
        ["Northline pays ₹600 crore of equity value for Kesar Spices."],
        [["Purchase price (equity)", "₹600 crore"], ["Book value of net assets", "₹180 crore"],
         ["Fair value uplift on property", "₹60 crore"], ["Brand recognised separately", "₹90 crore"],
         ["Identifiable net assets", "₹330 crore"], ["Goodwill", "₹270 crore"]],
        ["₹270 crore of the price rests on expectations rather than anything you can point at.",
         "That is not automatically bad — brand, customers and synergies are real. It does mean 45% of what Northline paid must be justified by performance, and will be written off publicly if it is not."]),
      h2("Key terms"),
      def("Identifiable net assets", "Assets and liabilities that can be separately valued, at fair value."),
      def("Purchase price allocation", "The exercise of assigning the price across assets, intangibles and goodwill."),
      def("Impairment", "A write-down when the acquired business is worth less than its carrying value."),
      h2("Practice"),
      practice([
        { q: "Purchase price ₹500 crore, assets at fair value ₹420 crore, liabilities assumed ₹180 crore. Compute goodwill.", a: "Identifiable net assets = 420 − 180 = ₹240 crore. Goodwill = 500 − 240 = ₹260 crore." },
        { q: "Two years later the acquired business is worth ₹350 crore against a carrying value of ₹500 crore. What happens, and does cash move?", a: "Goodwill is impaired by about ₹150 crore, recorded as a non-cash loss. No cash moves — it left at closing. The write-down is the accounting system admitting the price was too high." },
      ]),
      h2("Connection"),
      p("Goodwill appears on the pro forma balance sheet, and the synergies lesson tests whether the premium behind it was ever achievable."),
      sandbox("goodwill", "Goodwill sandbox",
        "Raise the price paid and watch how much of it rests on expectations rather than identifiable assets.", [
        { key: "purchasePrice", label: "Purchase price", value: 6000000000, unit: "₹" },
        { key: "assetsAcquired", label: "Assets at fair value", value: 5100000000, unit: "₹" },
        { key: "liabilitiesAcquired", label: "Liabilities assumed", value: 1800000000, unit: "₹" },
      ]),
      mcq("Goodwill impairment is:",
        ["A cash outflow in the year of write-down", "A non-cash charge admitting the acquisition price was too high", "A tax refund", "Routine amortisation"], 1,
        [W, "Correct. The cash left at closing; the impairment is the later recognition that it bought less than expected.", W, W]),
    ]);

  L("c-synergies", "Synergies",
    "The benefits that justify a premium — and the reason most deals disappoint.",
    [
      h2("What is this?"),
      p("Synergies are the value created by combining two businesses that neither could produce alone. <strong>Cost synergies</strong> remove duplicated overheads, plants or systems. <strong>Revenue synergies</strong> come from cross-selling or wider distribution."),
      h2("Why does it matter?"),
      p("A buyer paying a 25% premium is asserting the combined business is worth more than the two standalone. Synergies are that assertion, quantified. Without them, the premium is a transfer from the buyer's shareholders to the seller's."),
      p("Cost synergies are credible: you can name the duplicate function and the salaries removed. Revenue synergies are far softer, arrive later, and are where deal cases are usually inflated."),
      h2("How does it work?"),
      list([
        "Quantify each synergy separately with a named source — 'close one warehouse, save ₹12 crore'.",
        "Subtract the cost to achieve them: severance, integration, systems. These are real and immediate.",
        "Phase them realistically — most take 12 to 36 months.",
        "Value them as a stream: the recurring saving, capitalised at a multiple or discounted, less the one-off cost.",
      ]),
      fig("Real-Life Case Study: do the synergies cover the premium?",
        ["Northline paid a ₹120 crore premium over Kesar's unaffected market value."],
        [["Cost synergies — annual", "₹22 crore"], ["Revenue synergies — annual", "₹8 crore"],
         ["One-off cost to achieve", "₹35 crore"], ["Value of ₹22 cr at 8.6x", "₹189 crore"],
         ["Less cost to achieve", "−₹35 crore"], ["Net value of cost synergies", "₹154 crore"], ["Premium paid", "₹120 crore"]],
        ["Cost synergies alone cover the premium with ₹34 crore to spare — the deal can be justified without the revenue synergies at all.",
         "That is the test worth applying. If a deal only works when soft revenue synergies are counted, the buyer is paying today for something that may never arrive."]),
      h2("Key terms"),
      def("Cost synergy", "A recurring saving from removing duplication — usually the credible kind."),
      def("Revenue synergy", "Additional sales from combining the businesses — usually slower and less certain."),
      def("Cost to achieve", "The one-off cash cost of realising synergies: severance, integration, systems."),
      h2("Practice"),
      practice([
        { q: "Annual cost synergies ₹15 crore, valued at 9× with a ₹30 crore cost to achieve. Compute the net value and compare with a ₹90 crore premium.", a: "Value = 15 × 9 = ₹135 crore, less ₹30 crore = ₹105 crore net. That exceeds the ₹90 crore premium, so the deal creates about ₹15 crore of value on cost synergies alone." },
        { q: "Why should a board be sceptical of a deal case that depends on revenue synergies?", a: "Cross-selling requires customers to change behaviour, which is outside the buyer's control and historically the least reliably delivered part of any deal case. Cost synergies depend only on decisions the buyer can make itself." },
      ]),
      h2("Connection"),
      p("Synergies are added to the pro forma income statement and are what makes an otherwise dilutive deal accretive."),
      mcq("Which type of synergy is generally more credible?",
        ["Revenue synergies, because they grow", "Cost synergies, because the duplication can be named and removed", "Both equally", "Neither is credible"], 1,
        [W, "Correct. Removing a warehouse or a duplicate finance team is within the buyer's control; persuading customers to buy more is not.", W, W]),
    ]);

  L("c-merger-models", "Merger models",
    "Combine two companies on paper and see what the result actually earns.",
    [
      h2("What is this?"),
      p("A merger model combines the acquirer's and target's financials, adjusts for the deal — new interest, new shares, synergies, amortisation of acquired intangibles — and produces the pro forma combined company."),
      h2("Why does it matter?"),
      p("It answers the question a board asks first: after paying this price and funding it this way, are our shareholders better or worse off per share? A deal can raise total profit and still leave each existing shareholder worse off."),
      h2("How does it work?"),
      list([
        "Add the two income statements line by line.",
        "Add synergies, net of the cost to achieve in the early years.",
        "Subtract new interest on acquisition debt, and add back interest lost on cash used.",
        "Add amortisation of newly recognised intangibles.",
        "Tax the result, then divide by the new, larger share count.",
      ]),
      fig("Real-Life Case Study: the pro forma income statement",
        ["Northline and Kesar combined, first full year."],
        [["Northline standalone net profit", "₹180 crore"], ["Kesar standalone net profit", "₹42 crore"],
         ["Add: cost synergies after tax", "₹16.5 crore"], ["Less: new interest after tax", "−₹37.5 crore"],
         ["Less: intangible amortisation after tax", "−₹6.8 crore"], ["Pro forma net profit", "₹194.2 crore"],
         ["Shares before / after", "20 cr / 22.4 cr"], ["EPS before / after", "₹9.00 / ₹8.67"]],
        ["Combined profit rose from ₹180 crore to ₹194.2 crore, and earnings per share fell from ₹9.00 to ₹8.67.",
         "The deal made the company bigger and each existing shareholder slightly worse off — because the shares issued and interest incurred cost more than the acquired earnings and synergies delivered."]),
      h2("Key terms"),
      def("Pro forma", "The combined company as if the deal had already happened."),
      def("Merger model", "The financial model producing the combined company's statements and per-share outcomes."),
      h2("Practice"),
      practice([
        { q: "Acquirer profit ₹100 crore on 10 crore shares. It acquires a target earning ₹20 crore, issuing 3 crore shares, with ₹4 crore after-tax interest. Compute EPS before and after.", a: "Before = 100 ÷ 10 = ₹10.00. After: profit = 100 + 20 − 4 = ₹116 crore over 13 crore shares = ₹8.92. The deal is dilutive by about 11%." },
        { q: "Why can a deal increase total profit and still hurt shareholders?", a: "Because the shares issued to fund it grow the denominator faster than the acquired earnings grow the numerator. Shareholders own a smaller share of a bigger company, and end up with less profit each." },
      ]),
      h2("Connection"),
      p("The merger model produces the accretion/dilution answer, which is the next lesson and the standard first test of any deal."),
      mcq("A merger model's headline output for a listed acquirer is usually:",
        ["Total revenue", "Pro forma earnings per share versus standalone", "Goodwill", "The tax rate"], 1,
        [W, "Correct. Boards judge deals on what happens to earnings per share, because that is what existing shareholders actually experience.", W, W]),
    ]);

  L("c-accretion-dilution", "Accretion/dilution",
    "Does the deal raise or lower the acquirer's earnings per share?",
    [
      h2("What is this?"),
      p("A deal is <strong>accretive</strong> if pro forma earnings per share exceed the acquirer's standalone EPS, and <strong>dilutive</strong> if they fall. It is the single most quoted test in M&A."),
      h2("Why does it matter?"),
      p("It is the fastest read on whether the price and funding structure work for existing shareholders. Boards and markets react to it immediately."),
      p("It is also a poor measure of value creation. A deal can be accretive because it was funded with cheap debt and still destroy value if the return on the price paid is below the cost of capital. Accretion measures earnings, not value."),
      h2("How does it work?"),
      formula("The accretion test", [
        "<b>Pro forma EPS = (Combined net profit + synergies − new interest − amortisation) ÷ New share count</b>",
        "<b>Accretion = (Pro forma EPS ÷ Standalone EPS) − 1</b>",
      ]),
      p("A rough shortcut for a share-funded deal: it is accretive if the acquirer's P/E is higher than the effective P/E paid for the target. A high-multiple company buying a low-multiple one usually shows accretion automatically."),
      fig("Real-Life Case Study: making a dilutive deal accretive",
        ["The Northline deal was dilutive at ₹8.67 against ₹9.00. The board tests more debt funding."],
        [["Original mix — new shares", "2.4 crore"], ["Original — pro forma EPS", "₹8.67 (−3.7%)"],
         ["More debt — new shares", "1.1 crore"], ["More debt — extra after-tax interest", "−₹15 crore"],
         ["More debt — pro forma EPS", "₹8.49"], ["Leverage after", "3.4x vs 2.6x"]],
        ["Shifting to debt reduced the share count but the extra interest cost more than it saved — EPS fell further.",
         "This is why accretion is a test, not a lever. When both structures dilute, the honest conclusion is that the price is too high, not that a cleverer funding mix is needed."]),
      h2("Key terms"),
      def("Accretive", "The deal increases the acquirer's earnings per share."),
      def("Dilutive", "The deal decreases earnings per share."),
      def("Effective P/E paid", "Purchase price divided by the target's earnings — the multiple the buyer paid."),
      h2("Practice"),
      practice([
        { q: "Standalone EPS ₹9.00, pro forma EPS ₹9.63. Compute the accretion and say what it does and does not prove.", a: "Accretion = 9.63 ÷ 9.00 − 1 = 7%. It proves earnings per share rise. It does not prove value was created — that requires the return on the price paid to exceed the cost of capital." },
        { q: "An acquirer trades at 25× earnings and buys a target at an effective 14× P/E, funded in shares. Accretive or dilutive, and why?", a: "Accretive. It issues shares valued at 25× earnings to buy earnings priced at 14×, so each new share brings in more earnings than it dilutes. The mechanism is the multiple gap, not any operational improvement." },
      ]),
      h2("Connection"),
      p("Accretion is the merger model's headline output; ROIC on the price paid, from Level 3, is the value test it does not replace."),
      mcq("An accretive deal:",
        ["Always creates shareholder value", "Raises EPS, which is not the same as creating value", "Requires all-cash funding", "Eliminates goodwill"], 1,
        [W, "Correct. Cheap debt can lift EPS while the return on the price paid still falls short of the cost of capital.", W, W]),
    ]);

  L("c-pro-forma-financials", "Pro forma financials",
    "The combined company's statements, adjusted for everything the deal changes.",
    [
      h2("What is this?"),
      p("Pro forma financials show the merged business as if the transaction had already happened: the two sets of statements added together and adjusted for the purchase, the funding and the accounting consequences."),
      h2("Why does it matter?"),
      p("Simply adding two balance sheets gives the wrong answer. The target's equity disappears, goodwill appears, debt changes, and assets are revalued. Getting these adjustments right is what separates a real merger model from arithmetic."),
      h2("How does it work?"),
      list([
        "<strong>Eliminate the target's equity.</strong> It is replaced by the purchase consideration.",
        "<strong>Add goodwill and revalued intangibles</strong> from the purchase price allocation.",
        "<strong>Adjust debt and cash</strong> for the funding used and the debt refinanced.",
        "<strong>Remove intercompany transactions</strong> if the two traded with each other.",
        "<strong>Check it balances</strong> — the same discipline as any balance sheet.",
      ]),
      fig("Real-Life Case Study: the pro forma balance sheet",
        ["Northline plus Kesar, at closing."],
        [["Combined assets before adjustments", "₹2,450 crore"], ["Add: goodwill", "₹270 crore"],
         ["Add: brand intangible", "₹90 crore"], ["Less: cash used in the deal", "−₹115 crore"],
         ["Pro forma total assets", "₹2,695 crore"], ["Add: new acquisition debt", "₹500 crore"],
         ["Eliminate: Kesar's equity", "−₹180 crore"], ["Add: new equity issued", "₹250 crore"]],
        ["Total assets rose by more than the cash spent, because goodwill and the brand intangible were created by the transaction itself.",
         "The target's ₹180 crore of equity vanishes — it was bought, not inherited. Forgetting that elimination is the most common reason a pro forma balance sheet fails to balance."]),
      h2("Key terms"),
      def("Pro forma adjustment", "A change made to combined figures to reflect the transaction."),
      def("Equity elimination", "Removing the target's pre-deal equity, which the purchase consideration replaces."),
      h2("Practice"),
      practice([
        { q: "Acquirer assets ₹1,800 crore, target assets ₹650 crore, goodwill created ₹270 crore, cash used ₹115 crore. Compute pro forma assets.", a: "1,800 + 650 + 270 − 115 = ₹2,605 crore." },
        { q: "Why is the target's equity removed rather than added to the acquirer's?", a: "The acquirer bought that equity; it did not inherit it as a separate claim. The consideration paid replaces it, so leaving it in would double-count the target's ownership." },
      ]),
      h2("Connection"),
      p("These statements are what the debt schedules and covenant tests in the next lesson are run against."),
      mcq("When two balance sheets are combined in an acquisition:",
        ["The target's equity is added to the acquirer's", "The target's equity is eliminated and replaced by the consideration paid", "Goodwill is ignored", "Debt disappears"], 1,
        [W, "Correct. The buyer purchased that equity, so it is replaced by what was paid for it plus any goodwill created.", W, W]),
    ]);

  L("c-debt-schedules", "Debt schedules",
    "Track the acquisition debt: what is drawn, what is repaid, and whether covenants hold.",
    [
      h2("What is this?"),
      p("In a merger model the debt schedule tracks each tranche of acquisition financing separately — term loans, revolving facilities, bonds — rolling each forward and computing its interest."),
      h2("Why does it matter?"),
      p("Acquisition debt is usually large and layered, with different rates, maturities and repayment terms. Modelling it as one blended balance hides the covenant tests and the repayment cliffs that decide whether the deal is financeable."),
      h2("How does it work?"),
      list([
        "One roll-forward per tranche: opening + drawdowns − repayments = closing.",
        "Interest on the average balance at each tranche's own rate.",
        "A revolver to absorb cash shortfalls, drawn and repaid automatically as cash allows.",
        "A covenant test each year — usually net debt / EBITDA and interest coverage — against the agreed limits.",
      ]),
      fig("Real-Life Case Study: the first three years",
        ["₹500 crore of acquisition debt at 10%, with mandatory repayments and a 3.5× leverage covenant."],
        [["Year 1 opening", "₹500 crore"], ["Year 1 repayment", "₹60 crore"], ["Year 1 closing", "₹440 crore"],
         ["Year 1 leverage", "3.1x"], ["Year 2 closing", "₹370 crore"], ["Year 2 leverage", "2.5x"],
         ["Year 3 closing", "₹290 crore"], ["Year 3 leverage", "1.9x"]],
        ["Leverage falls steadily as debt is repaid and combined EBITDA grows — the deal deleverages, which is what lenders want to see.",
         "Year 1 at 3.1× leaves only 0.4 turns of covenant headroom. If synergies arrive late or EBITDA disappoints by 12%, the covenant breaks in the first year — before the integration is even finished."]),
      h2("Key terms"),
      def("Tranche", "A distinct layer of debt with its own rate, maturity and terms."),
      def("Revolver", "A flexible facility drawn to cover shortfalls and repaid when cash allows."),
      def("Covenant headroom", "The gap between the current ratio and the level at which the covenant breaks."),
      h2("Practice"),
      practice([
        { q: "Opening debt ₹500 crore, repayment ₹60 crore, rate 10%. Compute closing debt and interest on the average balance.", a: "Closing = ₹440 crore. Average = ₹470 crore. Interest = ₹47 crore." },
        { q: "Year 1 leverage is 3.1× against a 3.5× covenant. By how much can EBITDA fall before breach?", a: "Net debt ₹440 crore ÷ 3.5 = ₹125.7 crore of EBITDA needed. Current EBITDA = 440 ÷ 3.1 = ₹142 crore. It can fall about 11.5% — thin headroom in an integration year." },
      ]),
      h2("Connection"),
      p("The same roll-forward drives the debt paydown that generates sponsor returns in Level 7."),
      sandbox("leverage-returns", "Covenant sandbox",
        "Cut operating profit and watch the interest burden stay fixed — the mechanism behind a covenant breach.", [
        { key: "operatingProfit", label: "Combined operating profit", value: 1420000000, unit: "₹" },
        { key: "debt", label: "Acquisition debt", value: 4400000000, unit: "₹" },
        { key: "interestRate", label: "Interest rate", value: 10, unit: "%" },
        { key: "equity", label: "Equity funding", value: 2500000000, unit: "₹" },
      ]),
      mcq("Why model each debt tranche separately rather than as one balance?",
        ["It looks more professional", "Tranches have different rates, maturities and repayment terms that drive covenants and cash", "Lenders require it", "It reduces interest"], 1,
        [W, "Correct. A blended balance hides repayment cliffs and mis-states interest, which is exactly what the covenant tests depend on.", W, W]),
    ]);

  L("c-lbo-basics", "LBO basics",
    "Buy a company mostly with borrowed money, repay the debt from its cash, and sell it later.",
    [
      h2("What is this?"),
      p("A leveraged buyout is an acquisition funded largely with debt, secured against the target's own assets and cash flows. A private equity fund contributes a slice of equity; lenders provide the rest."),
      p("The returns come from three sources: repaying debt with the company's cash, improving its earnings, and selling at a higher multiple than was paid — in roughly that order of reliability."),
      h2("Why does it matter?"),
      p("It is the clearest demonstration of leverage in practice. The same business, bought with 30% equity instead of 100%, produces dramatically higher returns to that equity if things go well, and wipes it out if they do not."),
      h2("How does it work?"),
      list([
        "<strong>Entry:</strong> buy at an entry multiple, funded perhaps 60-70% with debt.",
        "<strong>Hold:</strong> use the company's free cash flow to repay debt over four to six years.",
        "<strong>Exit:</strong> sell at an exit multiple. Equity value at exit is enterprise value less the remaining, much smaller debt.",
        "<strong>Return:</strong> exit equity divided by entry equity gives the multiple of money; annualising it gives the IRR.",
      ]),
      fig("Real-Life Case Study: the arithmetic of an LBO",
        ["A sponsor buys a business with ₹100 crore of EBITDA at 8×, funded 65% with debt, and exits after five years at 8×."],
        [["Entry EV", "₹800 crore"], ["Debt", "₹520 crore"], ["Sponsor equity", "₹280 crore"],
         ["EBITDA at exit (3% growth)", "₹116 crore"], ["Exit EV at 8x", "₹928 crore"],
         ["Debt repaid over 5 years", "₹250 crore"], ["Debt at exit", "₹270 crore"], ["Exit equity", "₹658 crore"], ["Multiple of money", "2.35x"]],
        ["The sponsor turned ₹280 crore into ₹658 crore without the multiple improving at all.",
         "Most of that came from repaying ₹250 crore of debt with the company's own cash — value transferred from lenders to owners. That is the core LBO mechanic, and why cash generation matters more than growth to a buyout fund."]),
      h2("Key terms"),
      def("Leveraged buyout", "An acquisition funded predominantly with debt secured on the target."),
      def("Sponsor", "The private equity fund providing the equity and controlling the company."),
      def("Multiple of money", "Exit equity divided by entry equity — how many times the investment returned."),
      h2("Practice"),
      practice([
        { q: "Entry EV ₹600 crore with ₹400 crore debt. Exit EV ₹720 crore with ₹230 crore debt remaining. Compute entry and exit equity and the multiple of money.", a: "Entry equity = ₹200 crore. Exit equity = 720 − 230 = ₹490 crore. Multiple of money = 490 ÷ 200 = 2.45×." },
        { q: "Why do sponsors prefer businesses with stable, predictable cash flows?", a: "Debt repayment is the main engine of returns and interest is owed regardless of performance. A volatile business risks breaching covenants and cannot be levered as heavily, which caps both the debt and the return." },
      ]),
      h2("Connection"),
      p("Level 7 builds this out step by step — entry valuation, financing, operating case, paydown, exit and returns."),
      sandbox("leverage-returns", "LBO leverage sandbox",
        "Raise the debt share and watch the owner return climb — then halve operating profit and see the same mechanism reverse.", [
        { key: "operatingProfit", label: "Operating profit", value: 1000000000, unit: "₹" },
        { key: "debt", label: "Acquisition debt", value: 5200000000, unit: "₹" },
        { key: "interestRate", label: "Interest rate", value: 11, unit: "%" },
        { key: "equity", label: "Sponsor equity", value: 2800000000, unit: "₹" },
      ]),
      mcq("The most reliable source of return in a typical LBO is:",
        ["Multiple expansion at exit", "Repaying debt with the company's own cash flow", "Issuing more equity", "Goodwill"], 1,
        [W, "Correct. Debt paydown is within the sponsor's control; exit multiples depend on the market at the moment of sale.", W, W]),
    ]);
})();
