/* Level 8 — Equity Research & Investing. 17 lessons.
   One company runs through the whole level: Aarna Retail, a listed Indian
   footwear chain. Each lesson advances the same investment case, ending with
   a written thesis and three scenarios.
   Teaches analysis, not recommendations — no lesson tells anyone what to buy. */
(function () {
  "use strict";
  var LS = (window.LS = window.LS || {});
  LS.lessons = LS.lessons || {};

  function h2(t) { return { t: "h2", text: t }; }
  function p(h) { return { t: "p", h: h }; }
  function list(i) { return { t: "list", items: i }; }
  function def(term, h) { return { t: "def", term: term, h: h }; }
  function note(i) { return { t: "note", h: "<ul>" + i.map(function (x) { return "<li>" + x + "</li>"; }).join("") + "</ul>" }; }
  function practice(i) { return { t: "practice", items: i }; }
  function sandbox(kind, title, prompt, fields) { return { t: "sandbox", kind: kind, title: title, prompt: prompt, fields: fields }; }
  function formula(title, lines) { return { t: "formula", title: title, lines: lines }; }
  function mcq(q, o, c, w) { return { t: "mcq", q: q, opts: o, correct: c, why: w }; }
  function fig(title, intro, rows, meaning) {
    var h = '<p class="case-title"><strong>' + title + "</strong></p>";
    intro.forEach(function (x) { h += "<p>" + x + "</p>"; });
    h += '<div class="case-figures">';
    rows.forEach(function (r) { h += '<div class="case-row"><span class="case-label">' + r[0] + '</span><span class="case-value">' + r[1] + "</span></div>"; });
    h += '</div><p class="case-meaning"><strong>What it means.</strong></p>';
    meaning.forEach(function (x) { h += "<p>" + x + "</p>"; });
    return { t: "example", h: h };
  }
  function L(id, title, lede, body) {
    LS.lessons[id] = { id: id, title: title, short: title, desc: lede, lede: lede, minutes: 7, body: body };
  }
  var W = "Not quite — re-read the explanation above.";

  /* ============ BUSINESS ANALYSIS ============ */

  L("c-business-analysis", "Business analysis",
    "Before any number matters, understand how the company actually makes money.",
    [
      h2("What is this?"),
      p("Business analysis is working out what a company sells, to whom, at what price, against whom, and why customers keep coming back. It comes before valuation, not after."),
      p("The test is whether you can explain the business in three sentences without using its own marketing language."),
      h2("Why does it matter?"),
      p("A model built on a business you do not understand is arithmetic, not analysis. The assumptions that drive value — growth, margin, capital intensity — come from how the business works, and you cannot forecast what you cannot describe."),
      p("Most investment mistakes are not modelling errors. They are cases where the analyst understood the spreadsheet and not the company."),
      h2("How does it work?"),
      list([
        "<strong>What is sold, and to whom?</strong> Products, customers, channels, geographies.",
        "<strong>How is it priced?</strong> Premium, value, subscription, one-off.",
        "<strong>What does it cost to serve one customer?</strong> This becomes unit economics.",
        "<strong>Who else can do this?</strong> Barriers, substitutes, switching costs.",
        "<strong>What has to keep being true</strong> for the business to work in five years?",
      ]),
      fig("Real-Life Case Study: Aarna Retail in three sentences",
        ["A listed footwear chain, 320 stores across tier-2 and tier-3 India."],
        [["Revenue", "₹1,240 crore"], ["Stores", "320"], ["Revenue per store", "₹3.9 crore"],
         ["Gross margin", "48%"], ["EBITDA margin", "14%"], ["Own-brand share of sales", "62%"]],
        ["Aarna sells mid-priced footwear through its own stores in smaller cities, where rents are low and organised competition is thin. Nearly two-thirds of sales are own-brand, which is why gross margin is 48% rather than the 30% a pure reseller earns.",
         "That single fact — own-brand share — explains the margin, the growth plan and the main risk. Everything modelled later depends on whether it holds."]),
      h2("Key terms"),
      def("Business model", "How a company creates, delivers and captures value."),
      def("Channel", "The route to the customer: own stores, distributors, online, franchise."),
      h2("Practice"),
      practice([
        { q: "Describe Aarna in three sentences without using the words 'leading', 'innovative' or 'growing'.", a: "Aarna sells mid-priced footwear through 320 owned stores in smaller Indian cities. It designs and brands 62% of what it sells, which lifts gross margin to 48%. It grows mainly by opening stores in towns where organised retail has not yet arrived." },
        { q: "Why does understanding the business have to come before building a model?", a: "The model's assumptions — growth, margin, capital needs — are claims about how the business behaves. Without understanding the mechanism, you are picking numbers that look reasonable rather than forecasting anything." },
      ]),
      h2("Connection"),
      p("Everything in this level builds on this description: revenue drivers, unit economics and competitive advantage all elaborate it."),
      mcq("The best first test of whether you understand a business is:",
        ["Knowing its share price history", "Being able to explain how it makes money in a few plain sentences", "Memorising its ratios", "Knowing the CEO's name"], 1,
        [W, "Correct. If the explanation needs the company's own marketing language, the mechanism is not yet understood.", W, W]),
    ]);

  L("c-revenue-drivers", "Revenue drivers",
    "Break the top line into the two or three physical things that actually move it.",
    [
      h2("What is this?"),
      p("Revenue drivers are the underlying quantities whose product is revenue: stores × sales per store, customers × spend, volume × price. Identifying them turns a forecast from a guess into a set of testable claims."),
      h2("Why does it matter?"),
      p("Saying revenue grows 18% invites no scrutiny. Saying the company opens 40 stores and same-store sales rise 6% invites several useful questions: can it fund 40 fit-outs, are the sites available, has same-store growth ever been 6%?"),
      h2("How does it work?"),
      list([
        "Find the driver pair the company itself reports — most disclose stores, customers or volumes.",
        "Split growth into <strong>capacity</strong> (more stores, more customers) and <strong>intensity</strong> (more spend per unit of capacity).",
        "Check each against history separately; they often move in opposite directions.",
        "Watch for capacity growth masking intensity decline — the most common way a growth story hides deterioration.",
      ]),
      fig("Real-Life Case Study: two kinds of growth",
        ["Aarna's last three years, split into store count and same-store sales."],
        [["FY23 — stores / revenue", "248 / ₹930 cr"], ["FY24 — stores / revenue", "285 / ₹1,082 cr"],
         ["FY25 — stores / revenue", "320 / ₹1,240 cr"], ["Store growth FY25", "+12.3%"],
         ["Same-store growth FY25", "+2.0%"], ["Revenue per store trend", "₹3.75 → ₹3.80 → ₹3.88 cr"]],
        ["Revenue grew 14.6%, but only 2 points came from existing stores selling more. The rest was new stores.",
         "That distinction matters enormously. Store-led growth requires continuous capital and eventually runs out of towns; same-store growth is nearly free. A model assuming 14% forever must say which half continues."]),
      h2("Key terms"),
      def("Same-store sales", "Growth from stores open in both periods, isolating underlying demand."),
      def("Capacity growth", "Revenue growth from adding units — stores, customers, plants."),
      h2("Practice"),
      practice([
        { q: "320 stores at ₹3.88 crore each. The company adds 35 stores and same-store sales rise 3%. Compute next year's revenue and total growth.", a: "355 stores × ₹3.996 crore = ₹1,418.6 crore, against ₹1,241.6 crore. Growth = 14.3%." },
        { q: "Same-store sales fall 1% while total revenue grows 12%. What is happening, and why does it matter?", a: "New stores are carrying all the growth while existing ones sell slightly less. It matters because store-led growth needs capital and available towns, and declining same-store sales suggest either cannibalisation or weakening demand — a problem that becomes visible only when expansion slows." },
      ]),
      h2("Connection"),
      p("These drivers are exactly the revenue build from Level 4, applied to a company you are analysing rather than one you are modelling."),
      sandbox("revenue-growth", "Driver sandbox",
        "Set store growth and same-store growth separately, and see why the combined figure exceeds their sum.", [
        { key: "price", label: "Revenue per store", value: 38800000, unit: "₹" },
        { key: "volume", label: "Stores", value: 320 },
        { key: "priceGrowth", label: "Same-store growth", value: 3, unit: "%" },
        { key: "volumeGrowth", label: "Store count growth", value: 11, unit: "%" },
      ]),
      mcq("Total revenue grows 14% while same-store sales grow 2%. This means:",
        ["The business is improving rapidly", "Most growth comes from new capacity, which needs capital and eventually runs out", "Prices rose sharply", "Margins are expanding"], 1,
        [W, "Correct. Capacity-led growth is real but capital-hungry and finite; underlying demand grew only 2%.", W, W]),
    ]);

  L("c-unit-economics", "Unit economics",
    "Does one store, one customer, one unit make money — before head office is counted?",
    [
      h2("What is this?"),
      p("Unit economics is the profitability of a single repeatable unit of the business: one store, one customer, one subscription. Strip out head office and ask whether the thing being replicated actually earns."),
      h2("Why does it matter?"),
      p("A company can grow revenue rapidly by replicating a unit that loses money, and the losses grow with it. Conversely, healthy unit economics with poor headline profit usually means the business is simply small relative to its overheads — a far better problem."),
      p("For a store-based retailer, the key figures are the cost to open a store and how long it takes to pay that back."),
      h2("How does it work?"),
      formula("Store-level unit economics", [
        "<b>Store contribution = Store revenue × gross margin − store operating costs</b>",
        "<b>Payback period = Capex per store ÷ annual store contribution</b>",
        "Head office costs are excluded — they are not part of the unit",
      ]),
      fig("Real-Life Case Study: one Aarna store",
        ["The economics of a single average store, before head office."],
        [["Revenue per store", "₹3.88 crore"], ["Gross profit at 48%", "₹1.86 crore"],
         ["Rent, staff, utilities", "₹1.28 crore"], ["Store contribution", "₹0.58 crore"],
         ["Capex to open a store", "₹1.15 crore"], ["Payback period", "2.0 years"], ["Contribution margin", "15%"]],
        ["Each store returns its build cost in two years and contributes ₹58 lakh a year thereafter. That is genuinely good retail economics.",
         "It also tells you what to watch: if rents rise or same-store sales fall, payback stretches. At a four-year payback the expansion stops creating value, and the whole growth story changes without any headline number looking alarming yet."]),
      h2("Key terms"),
      def("Unit contribution", "Profit from one unit after its own direct costs, before central overheads."),
      def("Payback period", "How long a unit takes to return the capital spent opening it."),
      def("Cohort", "A group of units opened in the same period, tracked to see if newer ones perform worse."),
      h2("Practice"),
      practice([
        { q: "Store revenue ₹3.2 crore, gross margin 45%, store costs ₹1.15 crore, capex ₹1.0 crore. Compute contribution and payback.", a: "Gross profit = ₹1.44 crore. Contribution = 1.44 − 1.15 = ₹0.29 crore. Payback = 1.0 ÷ 0.29 = 3.4 years." },
        { q: "Newer store cohorts show a 3.5-year payback against 2.0 for older ones. What does that suggest?", a: "The best locations were taken first, and expansion is now reaching weaker towns or more expensive sites. Growth continues but creates less value per rupee invested — an early signal that the expansion runway is narrowing." },
      ]),
      h2("Connection"),
      p("Unit economics explains whether the revenue drivers above can keep growing profitably, and it feeds the margin assumption in valuation."),
      sandbox("operating-leverage", "Store economics sandbox",
        "Raise store costs or cut volume and watch contribution collapse — a store is a small business with its own operating leverage.", [
        { key: "price", label: "Revenue per store", value: 38800000, unit: "₹" },
        { key: "variableCost", label: "Cost of goods per store", value: 20176000, unit: "₹" },
        { key: "units", label: "Stores", value: 1 },
        { key: "fixedCosts", label: "Store operating costs", value: 12800000, unit: "₹" },
        { key: "volumeChange", label: "Volume change", value: -10, unit: "%" },
      ]),
      mcq("A company grows fast while each unit loses money. The likely outcome is:",
        ["Profits improve with scale automatically", "Losses grow with the business unless unit economics change", "Revenue is overstated", "Margins expand"], 1,
        [W, "Correct. Replicating an unprofitable unit multiplies the loss. Scale helps only when the unit itself contributes.", W, W]),
    ]);

  L("c-competitive-advantage", "Competitive advantage",
    "Why can this company keep earning good returns when others would compete them away?",
    [
      h2("What is this?"),
      p("A competitive advantage is a structural reason a business can sustain returns above its cost of capital. Without one, high returns attract competition and fade."),
      p("The common sources: cost advantage, switching costs, network effects, intangible assets like brands or licences, and efficient scale in a market too small for two players."),
      h2("Why does it matter?"),
      p("Valuation assumes returns persist. A DCF with 15% ROIC for ten years is asserting that competitors cannot take that away for a decade — a claim that needs a reason, not an assumption."),
      h2("How does it work?"),
      list([
        "<strong>Test with returns.</strong> Sustained ROIC above the cost of capital is the evidence; the advantage is the explanation.",
        "<strong>Name the mechanism.</strong> 'Great brand' is not a mechanism; 'customers pay 20% more for our brand and repurchase every 14 months' is.",
        "<strong>Ask what would break it.</strong> An advantage you cannot imagine losing is usually one you have not examined.",
        "<strong>Check the trend.</strong> Advantages erode; the question is how fast.",
      ]),
      fig("Real-Life Case Study: is Aarna's advantage real?",
        ["Testing the claim that small-city presence protects returns."],
        [["ROIC", "16.2%"], ["Estimated cost of capital", "12.5%"], ["Spread", "+3.7 points"],
         ["Years of ROIC above 12.5%", "6 of last 7"], ["Own-brand gross margin premium", "18 points"],
         ["Nearest organised competitor in core towns", "few"]],
        ["Seven years of returns above the cost of capital is evidence of something real, and the mechanism is plausible: own-brand economics plus towns too small to attract national chains.",
         "The honest counter: that second advantage disappears as those towns grow. The question for the model is not whether the advantage exists today, but how many years it survives — and that number drives most of the valuation."]),
      h2("Key terms"),
      def("Economic moat", "A structural barrier allowing returns above the cost of capital to persist."),
      def("Switching cost", "What a customer gives up by moving to a competitor."),
      def("Fade", "The gradual decline of excess returns towards the cost of capital as competition arrives."),
      h2("Practice"),
      practice([
        { q: "A company earns 22% ROIC against an 11% cost of capital and has no identifiable advantage. What should you forecast?", a: "Fading returns. Without a mechanism protecting them, competition should compete the spread away over several years. Modelling 22% in perpetuity assumes a barrier you cannot name — which usually means it is not there." },
        { q: "Why is 'strong brand' insufficient as a stated competitive advantage?", a: "It describes the outcome, not the mechanism. The useful version specifies what the brand lets the company do — charge a price premium, achieve higher repeat purchase, get better shelf placement — because only that can be tested against the numbers." },
      ]),
      h2("Connection"),
      p("The durability of the advantage decides how long ROIC stays above the cost of capital, which drives the terminal value from Level 5."),
      mcq("The evidence of a competitive advantage is:",
        ["A well-known brand name", "Returns on capital sustained above the cost of capital over years", "High revenue growth", "A large marketing budget"], 1,
        [W, "Correct. Sustained excess returns are the evidence; the named mechanism is the explanation for why they persist.", W, W]),
    ]);

  L("c-tam-sam-som", "TAM / SAM / SOM",
    "How big could this get — and how much of that is honestly reachable?",
    [
      h2("What is this?"),
      p("Three nested market sizes. <strong>TAM</strong> is the total addressable market — everyone who could conceivably buy the category. <strong>SAM</strong> is the serviceable addressable market — the part this company's model can actually reach. <strong>SOM</strong> is the serviceable obtainable market — the share it can realistically win."),
      h2("Why does it matter?"),
      p("It bounds the growth forecast. A company cannot grow 25% a year for a decade into a market that is only three times its current size, and a model implying an impossible market share is wrong regardless of how carefully the rows were built."),
      p("TAM is also the most abused number in investing, routinely inflated by defining the market as broadly as possible."),
      h2("How does it work?"),
      list([
        "<strong>TAM:</strong> total category spend in the geography — usually from industry data.",
        "<strong>SAM:</strong> the slice the business model can serve. A small-city store chain cannot address metro online demand.",
        "<strong>SOM:</strong> realistic share given competition, capital and execution — typically single digits.",
        "<strong>Sanity-check the forecast:</strong> what market share does the model's final year imply?",
      ]),
      fig("Real-Life Case Study: sizing Aarna's runway",
        ["Indian footwear, narrowed to what Aarna can actually serve."],
        [["TAM — Indian footwear retail", "₹95,000 crore"], ["SAM — organised, tier-2/3 towns", "₹18,000 crore"],
         ["Aarna revenue", "₹1,240 crore"], ["Current share of SAM", "6.9%"],
         ["Revenue if growth held 15% for 8 years", "₹3,795 crore"], ["Implied share of SAM", "21%"]],
        ["Fifteen percent growth for eight years implies Aarna takes over a fifth of organised footwear retail in its towns.",
         "Not impossible, but a strong claim requiring a specific reason. Against the ₹95,000 crore TAM the same forecast looks like 4% share and entirely unremarkable — which is exactly why the TAM figure is the one companies prefer to quote."]),
      h2("Key terms"),
      def("TAM", "Total addressable market — the whole category."),
      def("SAM", "Serviceable addressable market — what this business model can reach."),
      def("SOM", "Serviceable obtainable market — the share realistically winnable."),
      h2("Practice"),
      practice([
        { q: "SAM ₹18,000 crore, company revenue ₹1,240 crore growing 15% for 8 years. Compute the implied share.", a: "1,240 × 1.15⁸ = ₹3,795 crore. Implied share = 3,795 ÷ 18,000 = 21% — up from 6.9%, roughly tripling market share." },
        { q: "Why do companies prefer to quote TAM rather than SAM?", a: "TAM is far larger, so any growth forecast looks modest against it. SAM reflects what the business can actually serve, which makes an aggressive forecast look aggressive — which is precisely why the analyst should use it." },
      ]),
      h2("Connection"),
      p("The implied market share is a hard constraint on the revenue growth assumption used in valuation."),
      mcq("A forecast implying a company reaches 40% of its serviceable market should be:",
        ["Accepted — growth is good", "Challenged with a specific reason why that share is achievable", "Doubled", "Ignored"], 1,
        [W, "Correct. Large share gains happen, but they need a named mechanism. Unexamined, they are usually arithmetic that nobody checked against the market.", W, W]),
    ]);

  L("c-management-analysis", "Management analysis",
    "Judge the people running the business by what they did with capital, not what they say.",
    [
      h2("What is this?"),
      p("Management analysis assesses how competently and honestly a company's leadership allocates capital and communicates. It relies on their record, not their presentations."),
      h2("Why does it matter?"),
      p("Over a decade, capital allocation is most of what determines shareholder returns. A management team that reinvests at 18% compounds value; one that reinvests the same cash at 8% while the cost of capital is 12% destroys it, while reporting growth throughout."),
      h2("How does it work?"),
      list([
        "<strong>Where did the cash go?</strong> Reinvestment, acquisitions, dividends, buybacks — and what did each earn?",
        "<strong>Did past promises happen?</strong> Compare guidance given three years ago with what was delivered.",
        "<strong>How do they discuss failure?</strong> Specific and early is a good sign; vague and late is not.",
        "<strong>Is incentive pay linked to returns</strong> or just to size?",
        "<strong>Related-party transactions</strong> and unusual arrangements deserve reading closely.",
      ]),
      fig("Real-Life Case Study: Aarna's capital allocation record",
        ["Where ₹640 crore of operating cash went over five years."],
        [["New stores", "₹410 crore at ~2.2 yr payback"], ["Acquisition of a regional chain", "₹90 crore"],
         ["Return on that acquisition", "≈6%"], ["Dividends", "₹85 crore"],
         ["Debt repayment", "₹55 crore"], ["Blended return on reinvested capital", "≈15%"]],
        ["Store expansion — the thing they understand — earned well. The one acquisition earned 6% against a 12.5% cost of capital and destroyed value.",
         "That is a useful, specific finding: this team compounds capital effectively inside their own model and should be watched carefully whenever they buy something. It is far more informative than any assessment of their strategy slides."]),
      h2("Key terms"),
      def("Capital allocation", "How management deploys the cash the business generates."),
      def("Guidance credibility", "Whether past forecasts by this team proved accurate."),
      h2("Practice"),
      practice([
        { q: "Management reinvests ₹200 crore at 9% while the cost of capital is 12.5%. What is the annual value effect?", a: "A negative spread of 3.5 points on ₹200 crore destroys about ₹7 crore of value a year — while reported profit rises, because 9% is still positive." },
        { q: "How would you test a management team's credibility without meeting them?", a: "Pull their guidance and strategy statements from three to five years ago and compare with what actually happened. Consistent delivery, and candid early disclosure when things went wrong, are observable in the record." },
      ]),
      h2("Connection"),
      p("Capital allocation quality determines whether reinvested cash earns above the cost of capital — the ROIC test from Level 3."),
      mcq("The most informative evidence about a management team is:",
        ["Their strategy presentation", "What past capital deployment actually earned", "Their industry experience", "Media coverage"], 1,
        [W, "Correct. Returns on past decisions are observable and hard to spin; intentions are neither.", W, W]),
    ]);

  L("c-earnings", "Earnings",
    "Reported profit is a starting point — the analyst's job is working out what is repeatable.",
    [
      h2("What is this?"),
      p("Earnings analysis separates the profit a company reported from the profit its ongoing operations actually generate. One-offs, accounting changes and unusual items sit between the two."),
      h2("Why does it matter?"),
      p("Valuation multiplies earnings. If the base includes a one-off gain, every multiple and every forecast built on it is overstated — often materially, and in a way that looks perfectly normal on the face of the statement."),
      h2("How does it work?"),
      list([
        "Start from reported net profit.",
        "Strip out non-recurring items: asset sales, restructuring charges, insurance receipts, one-time tax benefits.",
        "Check the tax rate: an unusually low effective rate often means a benefit that will not repeat.",
        "Compare earnings with cash flow. Persistent profit without cash deserves investigation.",
        "The result is <strong>normalised earnings</strong> — the base for forecasting.",
      ]),
      fig("Real-Life Case Study: normalising Aarna",
        ["Reported FY25 results, adjusted."],
        [["Reported net profit", "₹96 crore"], ["Less: gain on sale of a warehouse", "−₹18 crore"],
         ["Add back: one-off store closure costs", "+₹7 crore"], ["Adjust: tax benefit that will not repeat", "−₹5 crore"],
         ["Normalised net profit", "₹80 crore"], ["Reported vs normalised P/E at ₹1,440 cr market cap", "15.0x vs 18.0x"]],
        ["The stock looks 15× earnings on reported figures and 18× on what the business actually earns — a 20% difference in apparent cheapness.",
         "Neither number is wrong; they answer different questions. Only the normalised figure should be forecast forward, because only it describes something repeatable."]),
      h2("Key terms"),
      def("Normalised earnings", "Reported profit adjusted for non-recurring items — the repeatable base."),
      def("Quality of earnings", "How closely reported profit tracks cash and repeatable operations."),
      h2("Practice"),
      practice([
        { q: "Reported profit ₹120 crore including a ₹25 crore asset sale gain and ₹8 crore of one-off restructuring costs. Compute normalised profit.", a: "120 − 25 + 8 = ₹103 crore." },
        { q: "A company reports rising profit while operating cash flow falls for three consecutive years. What does this warrant?", a: "Investigation of working capital and revenue recognition. Sustained divergence usually means receivables or inventory are building — either the company is selling to weaker customers, stuffing the channel, or recognising revenue too early." },
      ]),
      h2("Connection"),
      p("Normalised earnings are the base for the P/E from Level 5 and for every forecast in the investment case."),
      mcq("A one-off gain from selling a building should be:",
        ["Included in the earnings base for valuation", "Excluded, because it will not repeat", "Doubled", "Treated as revenue"], 1,
        [W, "Correct. Valuation multiplies repeatable earnings; including a one-off inflates every number built on it.", W, W]),
    ]);

  L("c-guidance", "Guidance",
    "What management says about the future — useful, and never neutral.",
    [
      h2("What is this?"),
      p("Guidance is management's own forecast of future results, given publicly. It ranges from precise revenue and margin targets to vague directional statements."),
      h2("Why does it matter?"),
      p("It is the single best source of information about near-term expectations, because management sees the order book. It is also produced by people whose pay and reputation depend on how the shares perform, which shapes both the number and the language."),
      p("Guidance sets the bar the market measures against. A company beating lowered guidance may be performing worse than one missing ambitious guidance."),
      h2("How does it work?"),
      list([
        "Record the guidance and the date, then check it against the outcome later. A track record is more informative than any single forecast.",
        "Watch for quiet resets: guidance lowered gradually so each 'beat' looks like success.",
        "Note what is guided and what is not. Companies stop guiding on metrics that are about to deteriorate.",
        "Separate the controllable from the hopeful: cost targets are within management's control, demand forecasts are not.",
      ]),
      fig("Real-Life Case Study: reading a track record",
        ["Aarna's revenue growth guidance against delivery."],
        [["FY22 guided / actual", "14% / 15.1%"], ["FY23 guided / actual", "16% / 16.4%"],
         ["FY24 guided / actual", "15% / 16.3%"], ["FY25 guided / actual", "14% / 14.6%"],
         ["FY26 guidance", "11-13%"], ["Store additions guided", "30-35, down from 35"]],
        ["Four years of small, consistent beats suggests a team that guides conservatively and delivers — a genuinely useful signal.",
         "The FY26 guidance is the news: growth and store additions both stepping down. That deceleration, disclosed by the people who can see the pipeline, matters more than the beat history."]),
      h2("Key terms"),
      def("Guidance", "Management's public forecast of future performance."),
      def("Beat and raise", "Exceeding guidance and increasing it — the pattern markets reward."),
      def("Sandbagging", "Guiding deliberately low so results reliably exceed it."),
      h2("Practice"),
      practice([
        { q: "A company has beaten guidance every quarter for three years by 1-2%. What does that tell you?", a: "That guidance is set conservatively, not that performance is exceptional. The useful information is the guidance level itself, adjusted upward slightly — and that a miss would be genuinely significant from a team that sandbags." },
        { q: "A company stops guiding on same-store sales after five years of doing so. How should you read it?", a: "As a signal worth investigating. Disclosure is usually withdrawn when the metric is about to become unflattering. It does not prove deterioration, but it moves the burden of proof." },
      ]),
      h2("Connection"),
      p("Guidance anchors the near-term revenue and margin assumptions that feed the valuation and the three scenarios."),
      mcq("A company that consistently beats guidance by small margins is most likely:",
        ["Outperforming dramatically", "Guiding conservatively", "In financial distress", "Misreporting"], 1,
        [W, "Correct. Consistent small beats indicate the guidance is set low; the pattern says more about the forecast than the performance.", W, W]),
    ]);

  /* ============ INVESTMENT CASE ============ */

  L("c-free-cash-flow-investment-case", "Free cash flow",
    "The cash an owner could actually take out — the number an investment case rests on.",
    [
      h2("What is this?"),
      p("Free cash flow is operating cash flow less capital expenditure: what remains after the business has paid its costs, funded its working capital and maintained its assets."),
      p("For an investor it is the most important single figure, because it is the only cash that can fund dividends, buybacks, debt repayment or acquisitions."),
      h2("Why does it matter?"),
      p("Profit can be strong while free cash flow is negative for years, particularly in expanding businesses. Neither is wrong, but only one of them can be paid to you."),
      p("Distinguishing <strong>maintenance</strong> from <strong>growth</strong> capex is what makes this usable: a company spending heavily to expand may have poor free cash flow and excellent economics."),
      h2("How does it work?"),
      formula("Free cash flow", [
        "<b>FCF = Operating cash flow − Capital expenditure</b>",
        "<b>Owner earnings ≈ Operating cash flow − Maintenance capex</b>",
        "<b>FCF yield = Free cash flow ÷ Market capitalisation</b>",
      ]),
      fig("Real-Life Case Study: Aarna's cash, two ways",
        ["FY25, splitting capex into maintenance and expansion."],
        [["Operating cash flow", "₹152 crore"], ["Total capex", "₹128 crore"], ["Reported free cash flow", "₹24 crore"],
         ["Of which: new store capex", "₹98 crore"], ["Maintenance capex", "₹30 crore"],
         ["Owner earnings", "₹122 crore"], ["FCF yield vs owner-earnings yield", "1.7% vs 8.5%"]],
        ["On reported free cash flow the company looks cash-poor at a 1.7% yield. Strip out the growth spending it chooses to make and it generates ₹122 crore.",
         "That is the distinction that matters: Aarna is not struggling for cash, it is investing it at a two-year payback. If expansion stopped tomorrow, ₹122 crore would be available to shareholders."]),
      h2("Key terms"),
      def("Free cash flow", "Operating cash flow less all capital expenditure."),
      def("Owner earnings", "Operating cash flow less maintenance capex — cash available if growth stopped."),
      def("FCF yield", "Free cash flow divided by market capitalisation."),
      h2("Practice"),
      practice([
        { q: "Operating cash flow ₹152 crore, maintenance capex ₹30 crore, growth capex ₹98 crore, market cap ₹1,440 crore. Compute both yields.", a: "FCF = 152 − 128 = ₹24 crore, yield 1.7%. Owner earnings = 152 − 30 = ₹122 crore, yield 8.5%." },
        { q: "Why can a company with negative free cash flow still be an attractive business?", a: "If the shortfall is growth capex earning well above the cost of capital, the company is choosing to invest rather than distribute. The test is the return on that spending — negative FCF from a two-year payback expansion is very different from negative FCF from a business that cannot fund itself." },
      ]),
      h2("Connection"),
      p("This is the cash the DCF from Level 5 discounts, and the figure the bull, base and bear cases each forecast differently."),
      sandbox("profit-to-cash", "Cash conversion sandbox",
        "Raise the working capital increase and watch how much of reported profit actually becomes cash.", [
        { key: "profit", label: "Net profit", value: 960000000, unit: "₹" },
        { key: "receivablesIncrease", label: "Increase in receivables", value: 40000000, unit: "₹" },
        { key: "inventoryIncrease", label: "Increase in inventory", value: 120000000, unit: "₹" },
        { key: "payablesIncrease", label: "Increase in payables", value: 60000000, unit: "₹" },
      ]),
      mcq("Separating maintenance from growth capex matters because:",
        ["Tax treatment differs", "Growth capex is discretionary, so owner earnings can far exceed reported free cash flow", "Maintenance capex is not real", "It changes EBITDA"], 1,
        [W, "Correct. A company investing heavily by choice is very different from one whose assets consume all its cash.", W, W]),
    ]);

  L("c-valuation", "Valuation",
    "Put a number on the business, then compare it with the price.",
    [
      h2("What is this?"),
      p("Valuation in an investment case means triangulating: a multiple based on comparable companies, a DCF based on forecast cash flows, and a cross-check such as free cash flow yield. Where they agree, confidence rises; where they disagree, you have found the question worth working on."),
      h2("Why does it matter?"),
      p("A good business is not automatically a good investment. Price decides that. The whole purpose of the analysis in this level is to reach a defensible view of value that can be held against the market's price."),
      h2("How does it work?"),
      list([
        "<strong>Multiple:</strong> apply a peer multiple to normalised earnings or EBITDA.",
        "<strong>DCF:</strong> discount forecast free cash flow, as built in Level 5.",
        "<strong>Yield check:</strong> compare owner-earnings yield with the risk-free rate — the extra is what you are paid for equity risk.",
        "<strong>Reconcile:</strong> when the methods disagree materially, find out which assumption drives the gap.",
      ]),
      fig("Real-Life Case Study: triangulating Aarna",
        ["Market cap ₹1,440 crore, 8 crore shares, price ₹180."],
        [["Peer P/E 17x on ₹80 cr normalised", "₹1,360 crore (₹170/share)"],
         ["DCF at 12.5% WACC, 4% terminal", "₹1,520 crore (₹190/share)"],
         ["Owner-earnings yield check", "8.5% vs 7% risk-free"],
         ["Range", "₹170 - ₹190"], ["Market price", "₹180"], ["Midpoint upside", "0%"]],
        ["Three methods bracket the market price almost exactly. The stock is fairly priced on current assumptions.",
         "That is a genuine and common conclusion. The interesting work now is not refining the arithmetic but asking which assumption you would disagree with — the store payback, the growth runway, or the terminal fade."]),
      h2("Key terms"),
      def("Triangulation", "Using several valuation methods and examining where they disagree."),
      def("Fair value range", "The band the methods support, rather than a single figure."),
      h2("Practice"),
      practice([
        { q: "Normalised earnings ₹80 crore, peer P/E 17×, 8 crore shares. Compute value per share.", a: "Equity value = 80 × 17 = ₹1,360 crore. Per share = 1,360 ÷ 8 = ₹170." },
        { q: "Your multiple gives ₹170 and your DCF gives ₹250. What should you do?", a: "Find the assumption causing the gap rather than averaging them. Usually the DCF assumes growth or margins the peer multiple does not, and the question becomes whether that assumption is defensible. Averaging hides the disagreement, which is the most informative part." },
      ]),
      h2("Connection"),
      p("This range is what the thesis, catalysts and three scenarios in the rest of this level are built around."),
      mcq("When a multiple and a DCF disagree substantially, the right response is:",
        ["Average them", "Identify which assumption causes the gap", "Use the higher one", "Discard the DCF"], 1,
        [W, "Correct. The disagreement points at the assumption doing the work, which is where the analysis actually is.", W, W]),
    ]);

  L("c-investment-thesis", "Investment thesis",
    "One paragraph stating what you believe, why, and what would prove you wrong.",
    [
      h2("What is this?"),
      p("An investment thesis is a short written statement of the case: what the business is, what the market is missing or mispricing, what has to happen, and what would falsify it."),
      p("Writing it down is the point. A thesis you cannot state in a paragraph is one you have not finished forming."),
      h2("Why does it matter?"),
      p("It protects against drift. Positions held without a written thesis get justified after the fact — the reason for owning quietly changes as the facts change, which is how a growth investment becomes a value investment and then a mistake."),
      p("It also makes you specify falsification in advance, when you are calm, rather than during a decline when you are not."),
      h2("How does it work?"),
      list([
        "<strong>What the business is</strong> — in a sentence.",
        "<strong>What you believe that the price does not reflect</strong> — the actual thesis.",
        "<strong>Why you might be right</strong> — the mechanism and evidence.",
        "<strong>What must happen</strong> — specific, observable milestones.",
        "<strong>What would prove you wrong</strong> — written before you need it.",
      ]),
      fig("Real-Life Case Study: a thesis for Aarna",
        ["Written at ₹180 per share against a ₹170-190 fair value range."],
        [["Belief", "Store payback stays near 2 years for 3+ more years"],
         ["Market view implied by price", "Payback stretches and growth fades soon"],
         ["Evidence", "6.9% share of a ₹18,000 cr serviceable market"],
         ["Must happen", "30+ store additions/yr at stable contribution"],
         ["Falsified by", "Payback beyond 3 years, or same-store sales negative for 2 quarters"],
         ["Position sizing implication", "small — no valuation margin of safety"]],
        ["The thesis is specific enough to be wrong, which is what makes it useful.",
         "Note the last line. With the price inside the fair value range, the case rests entirely on the operating belief and not on the valuation, so the position should be sized accordingly."]),
      h2("Key terms"),
      def("Investment thesis", "A written statement of what you believe, why, and what would disprove it."),
      def("Falsification criteria", "The specific observations that would end the thesis."),
      def("Variant perception", "A view that differs from what the market price implies."),
      h2("Practice"),
      practice([
        { q: "Write a falsification criterion for a thesis that a retailer's expansion is value-creating.", a: "Store payback lengthening beyond three years for two consecutive cohorts, or store contribution margin falling below 10%. Both are observable from disclosure and would mean expansion no longer creates value at the cost of capital." },
        { q: "Why must falsification criteria be written before you buy?", a: "Afterwards, the mind reinterprets bad news as noise and finds reasons to hold. Criteria specified in advance are a commitment made while you are still capable of judging the evidence dispassionately." },
      ]),
      h2("Connection"),
      p("The thesis is what catalysts confirm, risks threaten, and the three scenarios quantify."),
      mcq("A thesis without falsification criteria is dangerous because:",
        ["It is illegal", "There is nothing that can prove it wrong, so the position never gets re-examined", "It reduces returns", "It cannot be shared"], 1,
        [W, "Correct. Without a defined way to be wrong, disconfirming evidence gets reinterpreted rather than acted on.", W, W]),
    ]);

  L("c-catalysts", "Catalysts",
    "The events that could make the market recognise what you think it is missing.",
    [
      h2("What is this?"),
      p("A catalyst is a specific, identifiable event that could cause the gap between price and value to close: results, a capacity expansion completing, a margin inflection, an index inclusion, a change in disclosure."),
      h2("Why does it matter?"),
      p("Being right about value is not enough if nothing ever causes the market to agree. A cheap stock with no catalyst can stay cheap for years, and time is a real cost — money tied up compounds nowhere."),
      p("Catalysts also give you dates. A thesis with a milestone calendar can be checked; one without becomes an indefinite hold."),
      h2("How does it work?"),
      list([
        "<strong>Operational:</strong> a new plant reaching capacity, a cohort of stores maturing, a cost programme completing.",
        "<strong>Financial:</strong> debt repaid to a level that changes the risk profile, a first dividend, a buyback.",
        "<strong>Disclosure:</strong> segment reporting that reveals a hidden business.",
        "<strong>Structural:</strong> index inclusion, a demerger, a change of control.",
        "Attach an approximate date to each so the thesis can be reviewed against them.",
      ]),
      fig("Real-Life Case Study: Aarna's catalyst calendar",
        ["Events that could move the price towards the analyst's view."],
        [["Q2 results — same-store sales", "in 3 months"], ["FY26 store cohort maturing", "6-12 months"],
         ["Own-brand share crossing 70%", "12-18 months"], ["Warehouse automation completing", "9 months"],
         ["Possible first dividend", "12 months"]],
        ["Each item is dated and observable, so the thesis has review points rather than running indefinitely.",
         "If same-store sales disappoint at Q2 and the FY26 cohort matures below expectation, two of the five catalysts have failed within a year — a clear signal to re-examine rather than to wait longer."]),
      h2("Key terms"),
      def("Catalyst", "An identifiable event that could cause the market to reprice."),
      def("Value trap", "A cheap asset that stays cheap because nothing forces recognition."),
      h2("Practice"),
      practice([
        { q: "You believe a stock is 40% undervalued but can identify no catalyst for three years. What is the risk?", a: "A value trap. The capital is committed while returning nothing, and the annualised return falls with every year of waiting even if you are eventually proved right. A 40% gain realised in year five is under 7% a year." },
        { q: "Give one operational and one financial catalyst for a retailer.", a: "Operational: a cohort of new stores reaching maturity, lifting group margin as they move past their loss-making first year. Financial: net debt falling to a level that permits a first dividend, which changes the shareholder base." },
      ]),
      h2("Connection"),
      p("Catalysts give the thesis its timetable; risks are the events that would work against it."),
      mcq("A cheap stock with no identifiable catalyst risks becoming:",
        ["A growth stock", "A value trap — cheap indefinitely", "Overvalued", "Delisted"], 1,
        [W, "Correct. Without something to force recognition, the discount can persist for years while your capital earns nothing.", W, W]),
    ]);

  L("c-risks", "Risks",
    "Write down what could go wrong before you own it, not after.",
    [
      h2("What is this?"),
      p("Risk analysis identifies what could damage the thesis: competitive, operational, financial, regulatory and valuation risks. Each is stated specifically enough to be monitored."),
      h2("Why does it matter?"),
      p("The biggest losses come from risks that were visible and unexamined. Listing them in advance forces you to consider whether you are being paid for them and to size the position accordingly."),
      p("It also separates risks you can monitor from those you cannot. A concentrated supplier is observable; a regulatory change may not be."),
      h2("How does it work?"),
      list([
        "<strong>Competitive:</strong> who could take this market, and what would it cost them to try?",
        "<strong>Operational:</strong> concentration in customers, suppliers, geographies or key people.",
        "<strong>Financial:</strong> leverage, refinancing dates, covenant headroom.",
        "<strong>Regulatory:</strong> rules that could change the economics.",
        "<strong>Valuation:</strong> how much of the price depends on assumptions rather than current performance.",
        "For each: how likely, how damaging, and how would you notice early?",
      ]),
      fig("Real-Life Case Study: Aarna's risk register",
        ["Each risk with a monitoring signal."],
        [["National chains entering tier-2 towns", "watch: competitor store openings"],
         ["Online footwear taking share", "watch: same-store sales trend"],
         ["Store payback lengthening", "watch: new cohort disclosure"],
         ["Own-brand quality failure", "watch: return rates, if disclosed"],
         ["Lease commitments ₹340 crore", "watch: fixed cost if sales fall"],
         ["Valuation risk", "price already inside fair value range"]],
        ["The two structural risks — national entrants and online — are the ones that would break the thesis rather than dent it.",
         "The lease commitment is the one most people miss: ₹340 crore of fixed obligations behaves like debt if sales decline, and it does not appear in the headline borrowing figure."]),
      h2("Key terms"),
      def("Concentration risk", "Dependence on a small number of customers, suppliers or locations."),
      def("Monitoring signal", "The observable indicator that a risk is materialising."),
      h2("Practice"),
      practice([
        { q: "A retailer has ₹340 crore of lease commitments and ₹120 crore of reported debt. Why does the lease figure matter?", a: "Leases are fixed obligations that must be paid whatever sales do, so they behave like debt. Effective leverage is far higher than the reported ₹120 crore suggests, and in a downturn the leases are what create the distress." },
        { q: "Why attach a monitoring signal to each risk rather than just listing it?", a: "A listed risk is forgotten; a signal turns it into something you check. It also lets you act on early evidence rather than after the damage appears in results." },
      ]),
      h2("Connection"),
      p("The most damaging risks become the bear case, quantified in the scenarios that follow."),
      mcq("Operating lease commitments matter to an equity analyst because they:",
        ["Are tax deductible", "Are fixed obligations that behave like debt in a downturn", "Increase revenue", "Reduce the share count"], 1,
        [W, "Correct. They must be paid regardless of sales, so they raise effective leverage without appearing in reported borrowings.", W, W]),
    ]);

  L("c-bear-case", "Bear case",
    "What the investment is worth if the things you are worried about actually happen.",
    [
      h2("What is this?"),
      p("The bear case is a coherent scenario in which the main risks materialise, valued through to a price. It is not the worst imaginable outcome — it is a plausible bad one, modelled properly."),
      h2("Why does it matter?"),
      p("It tells you what you can lose, which is what determines position size. An investment with 30% upside and 45% downside is a poor bet regardless of how likely the upside feels."),
      p("Building it also forces the risks to be quantified rather than acknowledged. 'Competition could increase' becomes 'gross margin falls 4 points and same-store sales turn negative'."),
      h2("How does it work?"),
      list([
        "Take the two or three risks that would genuinely damage the business.",
        "Let them move together — competition compresses margin and slows growth simultaneously.",
        "Apply a lower exit multiple: a weaker business deserves one, and multiples compress exactly when fundamentals do.",
        "Value it through to a price per share.",
      ]),
      fig("Real-Life Case Study: Aarna's bear case",
        ["National chains enter the core towns; online share grows."],
        [["Same-store sales", "−2% a year"], ["Store additions", "15 a year, from 35"],
         ["Gross margin", "48% → 44%"], ["FY29 normalised earnings", "₹58 crore"],
         ["Exit P/E", "12x (from 17x)"], ["Value per share", "₹87"], ["Downside from ₹180", "−52%"]],
        ["The bear case is a 52% loss — the multiple compressing at the same time as earnings fall is what makes it severe.",
         "That double effect is the point most beginners miss. Earnings fell 28% and the price fell 52%, because a deteriorating business is valued on a lower multiple as well as lower earnings."]),
      h2("Key terms"),
      def("Bear case", "A coherent adverse scenario, valued through to a price."),
      def("Multiple compression", "The market applying a lower multiple as fundamentals weaken, amplifying the fall."),
      h2("Practice"),
      practice([
        { q: "Earnings fall from ₹80 crore to ₹58 crore and the multiple from 17× to 12×. Compute the change in value.", a: "Before: 80 × 17 = ₹1,360 crore. After: 58 × 12 = ₹696 crore — a 49% fall from a 28% earnings decline." },
        { q: "Why does multiple compression usually accompany falling earnings?", a: "A multiple prices expected future growth and quality. When results deteriorate, the market lowers both expectations, so the denominator falls and the multiple applied to it falls too — the effects multiply rather than offset." },
      ]),
      h2("Connection"),
      p("The bear case, base case and bull case together define the risk-reward that decides whether and how much to invest."),
      mcq("In a bear case, earnings fall 28% and the price falls 52%. The extra decline comes from:",
        ["Currency movements", "The multiple compressing alongside the earnings fall", "Higher dividends", "Share issuance"], 1,
        [W, "Correct. A weaker business is valued on a lower multiple, so the two effects compound.", W, W]),
    ]);

  L("c-base-case", "Base case",
    "The outcome you actually expect, stated precisely enough to be checked.",
    [
      h2("What is this?"),
      p("The base case is the scenario you consider most likely: the assumptions you would defend, valued through to a price. It is the anchor the other two scenarios are measured against."),
      h2("Why does it matter?"),
      p("It is where the discipline lives. A base case should be a genuine expectation, not a mildly optimistic one — most analysts' 'base' cases sit closer to their bull case than they realise, because the assumptions were each chosen at the favourable end of a reasonable range."),
      h2("How does it work?"),
      list([
        "Anchor each assumption to history and to guidance, adjusted for what you know is changing.",
        "Let growth fade towards something sustainable — few businesses grow at today's rate for a decade.",
        "Use a multiple in line with the peer median, not the top of the range.",
        "Check the base case implies a market share and a margin the company has plausibly achieved.",
      ]),
      fig("Real-Life Case Study: Aarna's base case",
        ["Growth decelerating as guided, margin stable, multiple at the peer median."],
        [["Same-store sales", "+2.5% a year"], ["Store additions", "30 a year, fading to 20"],
         ["Gross margin", "48%, stable"], ["FY29 normalised earnings", "₹118 crore"],
         ["Exit P/E", "16x"], ["Value per share", "₹236"], ["Upside from ₹180", "+31% over 4 years"]],
        ["A 31% gain over four years is about 7% a year — before dividends, and below what an investor would require for equity risk.",
         "That is a genuinely useful finding. The base case does not clear the hurdle, which means the investment depends on the bull case happening. Most people discover this only after owning the stock."]),
      h2("Key terms"),
      def("Base case", "The most likely scenario, with assumptions you would defend individually."),
      def("Annualised return", "The compound annual rate implied by a scenario over its horizon."),
      h2("Practice"),
      practice([
        { q: "Base case value ₹236 in four years against a ₹180 price. Compute the annualised return.", a: "(236 ÷ 180)^(1/4) − 1 = 1.311^0.25 − 1 = 7.0% a year." },
        { q: "Why do most analysts' base cases drift towards optimism?", a: "Each assumption is chosen individually at the favourable end of a defensible range, and the effects compound. Growth slightly high, margin slightly high, multiple slightly high — each defensible alone, collectively producing a case closer to the bull scenario than to expectation." },
      ]),
      h2("Connection"),
      p("Compare the base case return with what you require for equity risk — the cost of equity from Level 5."),
      mcq("A base case implying a 7% annual return against a 13% cost of equity means:",
        ["The investment is attractive", "The expected outcome does not compensate for equity risk", "The model is wrong", "The stock is cheap"], 1,
        [W, "Correct. If the most likely scenario returns less than the risk requires, the case depends on the optimistic scenario occurring.", W, W]),
    ]);

  L("c-bull-case", "Bull case",
    "What it is worth if things go right — and what specifically must happen.",
    [
      h2("What is this?"),
      p("The bull case is a coherent favourable scenario: the growth runway proves longer, margins improve, and the market applies a higher multiple to a business that has demonstrated durability."),
      h2("Why does it matter?"),
      p("It quantifies the upside so risk and reward can be compared directly. It also disciplines optimism: writing down exactly what must happen makes it obvious whether the bull case is a plan or a wish."),
      h2("How does it work?"),
      list([
        "Extend the favourable conditions, but keep them internally consistent — faster growth usually costs capital.",
        "Apply a higher multiple only where the business has become demonstrably better, not just because the price is higher.",
        "State the preconditions: what specific, observable events must occur.",
        "Sanity-check against market size — a bull case implying an impossible share is not a case.",
      ]),
      fig("Real-Life Case Study: Aarna's bull case and the full picture",
        ["Own-brand share rises, payback stays near 2 years, expansion continues."],
        [["Same-store sales", "+5% a year"], ["Store additions", "35 a year sustained"],
         ["Gross margin", "48% → 51%"], ["FY29 normalised earnings", "₹168 crore"],
         ["Exit P/E", "19x"], ["Bull value per share", "₹399"],
         ["Bear / Base / Bull", "₹87 / ₹236 / ₹399"], ["From ₹180", "−52% / +31% / +122%"]],
        ["The spread is wide: roughly half your money in the bear case, more than double in the bull.",
         "Weighting them 25/50/25 gives an expected value of about ₹240 — a 33% gain over four years, or 7.4% a year. The upside is real, and it is not being handed to you cheaply at ₹180."]),
      h2("Key terms"),
      def("Bull case", "A coherent favourable scenario with stated preconditions."),
      def("Probability weighting", "Assigning likelihoods to scenarios to compute an expected value."),
      def("Risk-reward", "The relationship between upside in the bull case and downside in the bear case."),
      h2("Practice"),
      practice([
        { q: "Bear ₹87, base ₹236, bull ₹399, weighted 25/50/25. Compute expected value and the return from ₹180 over four years.", a: "EV = 0.25(87) + 0.5(236) + 0.25(399) = 21.75 + 118 + 99.75 = ₹239.5. Return = (239.5 ÷ 180)^(1/4) − 1 = 7.4% a year." },
        { q: "Bull case +122%, bear case −52%. What does this imply for position sizing?", a: "The upside is larger than the downside, but a 52% loss is severe enough that the position must be small enough to survive it without forcing a sale. Attractive asymmetry does not justify a size that makes the bear case unbearable." },
      ]),
      h2("Connection"),
      p("The three scenarios together are the output of the whole level: business analysis, valuation, thesis, catalysts and risks, expressed as a range."),
      mcq("Three scenarios are most useful because they:",
        ["Guarantee accuracy", "Show the range of outcomes and let risk and reward be compared", "Replace the need for a thesis", "Predict the share price"], 1,
        [W, "Correct. A single target price hides the distribution; three cases make the asymmetry explicit and inform how much to risk.", W, W]),
    ]);

  L("c-build-interactive-investment-cases", "Build interactive investment cases",
    "Assemble everything in this level into one case you could actually defend.",
    [
      h2("What is this?"),
      p("This lesson puts the level together. An investment case is a short document combining the business description, the drivers, the valuation, the thesis, the catalysts, the risks and the three scenarios — with the assumptions exposed so anyone can change them and see the effect."),
      h2("Why does it matter?"),
      p("Analysis that only exists in your head cannot be checked, criticised or revisited. Writing the case makes the assumptions visible, which is what allows someone — including you, later — to find the mistake."),
      p("Making it interactive matters too: a case with hard-coded conclusions gets defended, while one where anyone can change growth or the multiple gets tested."),
      h2("How does it work?"),
      list([
        "<strong>One page of business</strong> — what it sells, to whom, why it wins.",
        "<strong>Drivers and unit economics</strong> — the numbers underneath the revenue line.",
        "<strong>Normalised earnings and cash</strong> — what is repeatable.",
        "<strong>Valuation range</strong> from at least two methods.",
        "<strong>Thesis, catalysts, risks</strong> — including falsification criteria.",
        "<strong>Three scenarios</strong> with probabilities and an expected value.",
        "<strong>Exposed assumptions</strong> — every input changeable, so the case can be stress-tested.",
      ]),
      fig("Real-Life Case Study: the Aarna case on one page",
        ["Everything from this level, assembled."],
        [["Business", "320 stores, tier-2/3, 62% own-brand"],
         ["Drivers", "store count + 2.5% same-store"],
         ["Unit economics", "₹58 lakh contribution, 2.0 yr payback"],
         ["Normalised earnings", "₹80 crore (₹96 cr reported)"],
         ["Fair value range", "₹170 - ₹190; price ₹180"],
         ["Scenarios", "₹87 / ₹236 / ₹399"],
         ["Expected value", "₹240 — 7.4% a year"],
         ["Falsified by", "payback > 3 yrs or 2 quarters of negative SSS"]],
        ["The case concludes that Aarna is a good business at a fair price, with an expected return below what equity risk requires — so the answer is to watch it, with defined triggers.",
         "That is a legitimate and common conclusion, and reaching it explicitly is the entire value of the process. Most people never write the case and so never notice that their expected return does not clear their hurdle."]),
      h2("Key terms"),
      def("Investment case", "The assembled written analysis supporting a decision, with assumptions exposed."),
      def("Watchlist trigger", "A predefined price or event that would make you revisit a case you declined."),
      h2("Practice"),
      practice([
        { q: "Expected value ₹240 over four years from ₹180, against a 13% required return. At what price would the case clear the hurdle?", a: "Required: price × 1.13⁴ = 240, so price = 240 ÷ 1.630 = ₹147. Roughly 18% below the current ₹180 — which becomes the watchlist trigger." },
        { q: "Why expose every assumption rather than presenting conclusions?", a: "Hidden assumptions get defended; visible ones get tested. Someone who can change the growth rate and see the price move will find the assumption carrying the case — which is exactly the criticism the analysis needs." },
      ]),
      h2("Connection"),
      p("This is the equity-research counterpart of the capstone: the same discipline applied to a listed company at a market price."),
      sandbox("future-value", "Required price sandbox",
        "Set your required return and the horizon to find the price at which an expected value clears your hurdle.", [
        { key: "principal", label: "Price today", value: 180, unit: "₹" },
        { key: "rate", label: "Required return", value: 13, unit: "%" },
        { key: "years", label: "Holding period", value: 4 },
      ]),
      mcq("An investment case concluding 'good business, fair price, below my hurdle' is:",
        ["A failed analysis", "A legitimate conclusion, with a watchlist trigger as the output", "A reason to buy anyway", "Impossible"], 1,
        [W, "Correct. Deciding not to act, at a specified price you would act at, is one of the most valuable outputs the process produces.", W, W]),
    ]);
})();
