/* Level 10 — Advanced Finance. 16 lessons.
   Options pricing, portfolio theory, risk and simulation, and the corporate
   finance decisions that close the curriculum. Same schema and loop throughout.
   Educational only: nothing here recommends a security or a strategy. */
(function () {
  "use strict";
  var LS = (window.LS = window.LS || {});
  LS.lessons = LS.lessons || {};

  function h2(t) { return { t: "h2", text: t }; }
  function p(h) { return { t: "p", h: h }; }
  function list(i) { return { t: "list", items: i }; }
  function def(term, h) { return { t: "def", term: term, h: h }; }
  function note(i) { return { t: "note", h: "<ul>" + i.map(function (x) { return "<li>" + x + "</li>"; }).join("") + "</ul>" }; }
  function practice(i) { return { t: "practice", items: i }; }
  function sandbox(kind, title, prompt, fields) { return { t: "sandbox", kind: kind, title: title, prompt: prompt, fields: fields }; }
  function formula(title, lines) { return { t: "formula", title: title, lines: lines }; }
  function mcq(q, o, c, w) { return { t: "mcq", q: q, opts: o, correct: c, why: w }; }
  function fig(title, intro, rows, meaning) {
    var h = '<p class="case-title"><strong>' + title + "</strong></p>";
    intro.forEach(function (x) { h += "<p>" + x + "</p>"; });
    h += '<div class="case-figures">';
    rows.forEach(function (r) { h += '<div class="case-row"><span class="case-label">' + r[0] + '</span><span class="case-value">' + r[1] + "</span></div>"; });
    h += '</div><p class="case-meaning"><strong>What it means.</strong></p>';
    meaning.forEach(function (x) { h += "<p>" + x + "</p>"; });
    return { t: "example", h: h };
  }
  function L(id, title, lede, body) {
    LS.lessons[id] = { id: id, title: title, short: title, desc: lede, lede: lede, minutes: 8, body: body };
  }
  var W = "Not quite — re-read the explanation above.";

  /* ============ OPTIONS & PORTFOLIO THEORY ============ */

  L("c-options-pricing", "Options pricing",
    "What an option is worth before expiry: what it would pay now, plus what it might become.",
    [
      h2("What is this?"),
      p("An option's value has two parts. <strong>Intrinsic value</strong> is what it would pay if exercised immediately. <strong>Time value</strong> is the extra someone pays for the chance it becomes more valuable before expiry."),
      p("A call with a ₹200 strike on a ₹210 share has ₹10 of intrinsic value. If it trades at ₹17, the other ₹7 is time value."),
      h2("Why does it matter?"),
      p("It explains why an option can lose money while the share moves the right way — time value decays every day, and a small favourable move may not offset it."),
      p("It also identifies what actually drives the price: five variables, of which only one is unobservable."),
      h2("How does it work?"),
      formula("Option value", [
        "<b>Option value = Intrinsic value + Time value</b>",
        "<b>Call intrinsic = max(Spot − Strike, 0)</b>",
        "<b>Put intrinsic = max(Strike − Spot, 0)</b>",
      ]),
      list([
        "<strong>Spot price</strong> — higher helps calls, hurts puts.",
        "<strong>Strike</strong> — fixed at the outset.",
        "<strong>Time to expiry</strong> — more time means more chance, so more value.",
        "<strong>Volatility</strong> — more movement means more chance of a large favourable move.",
        "<strong>Interest rates</strong> — a smaller effect, through the present value of the strike.",
      ]),
      fig("Real-Life Case Study: decomposing a call",
        ["Share at ₹210, call struck at ₹200, three months to expiry, trading at ₹17."],
        [["Intrinsic value", "₹10"], ["Time value", "₹7"],
         ["Same option, one month left", "≈₹13 (time value ₹3)"],
         ["Same option, at expiry", "₹10 (time value ₹0)"],
         ["If volatility rises sharply", "time value increases"]],
        ["Holding the option for two months while the share does nothing loses ₹4 — the time value decaying.",
         "That is the trap in buying options: you need the underlying to move enough, and soon enough, to beat the decay. Being right about direction but late is the same as being wrong."]),
      h2("Key terms"),
      def("Intrinsic value", "What the option would pay if exercised now."),
      def("Time value", "The premium above intrinsic value, reflecting the chance of future gains."),
      def("In the money", "An option with positive intrinsic value."),
      h2("Practice"),
      practice([
        { q: "A put struck at ₹300 trades at ₹22 while the share is at ₹285. Split the value.", a: "Intrinsic = 300 − 285 = ₹15. Time value = 22 − 15 = ₹7." },
        { q: "The share rises 3% over a month and your call loses value. How?", a: "Time value decayed by more than the intrinsic value gained. With a month less to expiry, the chance of a further large move fell, and that loss exceeded the small gain from the share's rise." },
      ]),
      h2("Connection"),
      p("Black-Scholes next formalises how these five inputs combine into a single price."),
      mcq("An option's time value at expiry is:",
        ["At its maximum", "Zero", "Equal to the premium", "Negative"], 1,
        [W, "Correct. With no time remaining there is no chance of further movement, so only intrinsic value is left.", W, W]),
    ]);

  L("c-black-scholes-intuition", "Black-Scholes intuition",
    "The idea behind the formula, without the mathematics.",
    [
      h2("What is this?"),
      p("The Black-Scholes model prices an option by asking a specific question: what portfolio of the underlying share and cash would exactly replicate the option's payoff? If such a portfolio exists, the option must cost what that portfolio costs — otherwise there would be a riskless profit."),
      h2("Why does it matter?"),
      p("It is the foundation of modern derivatives markets, and its logic — price by replication, not by forecasting — appears throughout finance."),
      p("Its key insight is counter-intuitive: the option's price does not depend on the expected return of the share. Two people who disagree completely about whether a stock will rise should still agree on the option's price, provided they agree on its volatility."),
      h2("How does it work?"),
      list([
        "<strong>Replication:</strong> a continuously adjusted mix of shares and borrowing reproduces the option's payoff.",
        "<strong>No arbitrage:</strong> if the option cost more or less than that portfolio, a riskless profit would exist.",
        "<strong>Volatility is the key input</strong> — the only one not directly observable.",
        "<strong>Expected return is absent</strong>, because the replicating portfolio hedges away directional exposure.",
      ]),
      p("The model assumes constant volatility, continuous trading, no transaction costs and normally distributed returns. Real markets satisfy none of these exactly, which is why practitioners adjust its outputs rather than trusting them blindly."),
      fig("Real-Life Case Study: what moves the price",
        ["A three-month call, ₹200 strike, share at ₹210."],
        [["Volatility 20% — value", "≈₹14"], ["Volatility 35% — value", "≈₹19"], ["Volatility 50% — value", "≈₹25"],
         ["One month to expiry, 35% vol", "≈₹14"], ["Expected share return", "no effect on price"]],
        ["Volatility nearly doubles the option's value between 20% and 50%, while a view on the share's expected return changes nothing.",
         "This is why option traders talk about volatility rather than direction. Buying an option is largely a position on how much the share moves, not on which way."]),
      h2("Key terms"),
      def("Replication", "Building a portfolio that reproduces a derivative's payoff."),
      def("No-arbitrage pricing", "Pricing so that no riskless profit is available."),
      def("Implied volatility", "The volatility that makes the model's price equal the market price."),
      h2("Practice"),
      practice([
        { q: "Two analysts disagree about whether a share will rise. Should they disagree about its option prices?", a: "Not necessarily. Black-Scholes prices via replication, so expected return does not enter. If they agree on volatility, time and rates, they should agree on the option price despite opposite directional views." },
        { q: "Name two assumptions of Black-Scholes that real markets violate, and the consequence.", a: "Constant volatility — real volatility clusters and spikes — and normally distributed returns, which understate extreme moves. Both mean the model underprices far out-of-the-money options, which is why observed implied volatility varies by strike rather than being flat." },
      ]),
      h2("Connection"),
      p("The Greeks next describe how a Black-Scholes price responds to each of its inputs."),
      mcq("Black-Scholes does not require an estimate of:",
        ["Volatility", "The share's expected return", "Time to expiry", "The strike price"], 1,
        [W, "Correct. Replication hedges away directional exposure, so the expected return drops out of the pricing entirely.", W, W]),
    ]);

  L("c-greeks", "Greeks",
    "The sensitivities: how an option's price responds to each thing that can change.",
    [
      h2("What is this?"),
      p("The Greeks are the partial sensitivities of an option's price. Each isolates one variable: delta for the underlying price, gamma for how delta itself changes, theta for time, vega for volatility, rho for interest rates."),
      h2("Why does it matter?"),
      p("An option position has several risks at once, and they behave differently. A trader can be right about direction and lose on volatility, or right on both and lose to time decay. The Greeks separate these so each can be measured and managed."),
      h2("How does it work?"),
      list([
        "<strong>Delta</strong> — price change per ₹1 move in the underlying. A 0.6 delta call gains ₹0.60 per ₹1 rise. Also roughly the probability of finishing in the money.",
        "<strong>Gamma</strong> — how fast delta changes. High gamma means the position's directional exposure shifts quickly.",
        "<strong>Theta</strong> — daily loss from time passing. Negative for buyers, positive for sellers.",
        "<strong>Vega</strong> — price change per 1 point of volatility. Positive for buyers of options.",
        "<strong>Rho</strong> — sensitivity to interest rates, usually the smallest effect.",
      ]),
      fig("Real-Life Case Study: right on direction, still losing",
        ["A ₹200 call bought at ₹17. Over two weeks the share rises ₹4 and volatility falls 8 points."],
        [["Delta 0.58 — gain from ₹4 move", "+₹2.32"], ["Vega 0.28 — loss from −8 vol points", "−₹2.24"],
         ["Theta −0.09/day — loss over 14 days", "−₹1.26"], ["Net change", "−₹1.18"],
         ["Share direction", "correct"]],
        ["The share moved the right way and the option still lost money, because volatility fell and time passed.",
         "This is the most common experience of a first-time option buyer: a correct directional view producing a loss. The Greeks show exactly where the money went."]),
      h2("Key terms"),
      def("Delta", "Sensitivity to the underlying price."),
      def("Theta", "Daily time decay."),
      def("Vega", "Sensitivity to volatility."),
      def("Gamma", "The rate of change of delta."),
      h2("Practice"),
      practice([
        { q: "Delta 0.45, theta −0.11 per day. The share rises ₹3 over 5 days, volatility unchanged. Estimate the option's price change.", a: "Delta gain = 0.45 × 3 = +₹1.35. Theta loss = 0.11 × 5 = −₹0.55. Net ≈ +₹0.80." },
        { q: "Why does a seller of options have positive theta and negative vega?", a: "Time decay works in their favour — every day the option they sold is worth less, which is their gain. Rising volatility works against them, because it increases the value of the option they must eventually settle." },
      ]),
      h2("Connection"),
      p("Delta and gamma are how the replicating portfolio behind Black-Scholes is actually maintained in practice."),
      mcq("An option buyer's theta is negative because:",
        ["Volatility falls", "Time passing reduces the option's value", "Interest rates rise", "Delta is positive"], 1,
        [W, "Correct. Every day removes some chance of a favourable move, so time value decays against the buyer.", W, W]),
    ]);

  L("c-portfolio-theory", "Portfolio theory",
    "Combining assets that do not move together reduces risk without giving up return.",
    [
      h2("What is this?"),
      p("Modern portfolio theory shows that a portfolio's risk depends not only on the riskiness of its holdings but on how they move relative to each other. Assets whose returns are imperfectly correlated partly offset, so the combination is less volatile than the average of its parts."),
      h2("Why does it matter?"),
      p("It is the reason diversification is described as the only free lunch in finance. Combining two assets with the same expected return and the same volatility, but low correlation, produces the same expected return at lower risk."),
      h2("How does it work?"),
      formula("Two-asset portfolio", [
        "<b>Expected return = w₁R₁ + w₂R₂</b>",
        "<b>Variance = w₁²σ₁² + w₂²σ₂² + 2w₁w₂ρσ₁σ₂</b>",
        "ρ = correlation. Lower ρ means lower portfolio risk",
      ]),
      p("The return of a portfolio is simply the weighted average. Its risk is not — the correlation term is what makes diversification work, and it is why the maths is worth following."),
      fig("Real-Life Case Study: correlation does the work",
        ["Two assets, each with 12% expected return and 20% volatility, held 50/50."],
        [["Correlation +1.0 — portfolio volatility", "20.0%"], ["Correlation +0.5 — volatility", "17.3%"],
         ["Correlation 0.0 — volatility", "14.1%"], ["Correlation −0.5 — volatility", "10.0%"],
         ["Expected return in every case", "12.0%"]],
        ["The expected return never changes; the risk falls by half as correlation drops from +1 to −0.5.",
         "That is diversification precisely stated. It is not about owning many things — it is about owning things that do not fall together. Twenty stocks in one sector are barely diversified at all."]),
      h2("Key terms"),
      def("Correlation", "How closely two assets' returns move together, from −1 to +1."),
      def("Diversification", "Combining imperfectly correlated assets to reduce risk at a given return."),
      def("Systematic risk", "Market-wide risk that diversification cannot remove."),
      h2("Practice"),
      practice([
        { q: "Two assets, 20% volatility each, held 50/50 with zero correlation. Compute portfolio volatility.", a: "Variance = 0.25(0.04) + 0.25(0.04) + 0 = 0.02. Volatility = √0.02 = 14.1%, down from 20% with no loss of expected return." },
        { q: "Why does owning twenty stocks in one industry provide little diversification?", a: "They share the same drivers, so their correlation is high — close to 1. The correlation term barely reduces portfolio variance, and a sector-wide shock hits all twenty at once." },
      ]),
      h2("Connection"),
      p("This is the theoretical basis for CAPM and for the efficient frontier that follows."),
      mcq("Diversification reduces risk most when assets have:",
        ["High positive correlation", "Low or negative correlation", "Identical returns", "The same issuer"], 1,
        [W, "Correct. The benefit comes entirely from assets not moving together; correlated holdings offer little.", W, W]),
    ]);

  L("c-capm-portfolio-theory", "CAPM",
    "If company-specific risk can be diversified away, only market risk deserves a reward.",
    [
      h2("What is this?"),
      p("The Capital Asset Pricing Model follows from portfolio theory. If investors can eliminate company-specific risk for free by diversifying, then the market should not pay them for bearing it. Only <strong>systematic</strong> risk — exposure to the market as a whole — earns a premium."),
      p("The required return is therefore the risk-free rate plus beta times the equity risk premium."),
      h2("Why does it matter?"),
      p("It is the standard method for turning risk into a required return, and it produces the cost of equity used in every WACC and every DCF."),
      p("Placed here, after portfolio theory, its logic is visible: the reason beta is the risk measure is that everything else can be diversified away at no cost."),
      h2("How does it work?"),
      formula("CAPM", [
        "<b>Required return = Rf + β × (Rm − Rf)</b>",
        "Total risk = systematic (priced) + specific (diversifiable, unpriced)",
        "β measures exposure to systematic risk alone",
      ]),
      p("The model's assumptions — costless diversification, one shared view of risk, frictionless trading — are strong. Empirical evidence for beta explaining returns is mixed, which is what motivated factor investing later in this module."),
      fig("Real-Life Case Study: two risky companies, one premium",
        ["Risk-free 7%, equity risk premium 5.5%."],
        [["Company A — total volatility", "45%"], ["Company A — beta", "0.7"], ["Company A — required return", "10.85%"],
         ["Company B — total volatility", "28%"], ["Company B — beta", "1.4"], ["Company B — required return", "14.7%"]],
        ["Company A is far more volatile in total, and CAPM requires a lower return from it than from Company B.",
         "The reason is that most of A's volatility is company-specific and disappears in a diversified portfolio, while B moves with the market and cannot be diversified away. Whether you accept that depends on whether you are diversified — a concentrated holder is not."]),
      h2("Key terms"),
      def("Systematic risk", "Market-wide risk, measured by beta, which cannot be diversified away."),
      def("Specific risk", "Company-level risk, diversifiable and therefore unpriced by CAPM."),
      h2("Practice"),
      practice([
        { q: "Risk-free 7%, ERP 5.5%, beta 1.25. Compute the required return.", a: "7 + 1.25 × 5.5 = 7 + 6.875 = 13.875%." },
        { q: "Why does CAPM give a lower required return to a highly volatile stock with a low beta?", a: "Most of its volatility is company-specific and vanishes in a diversified portfolio, so no premium is required for it. Only market-correlated risk is compensated. This holds only for a diversified investor — a concentrated one bears the specific risk fully and uncompensated." },
      ]),
      h2("Connection"),
      p("This is the same CAPM from Level 5, now with the portfolio-theory reasoning that justifies it."),
      mcq("CAPM prices only systematic risk because:",
        ["Specific risk does not exist", "Specific risk can be diversified away at no cost, so it earns no premium", "Beta is easy to calculate", "Regulators require it"], 1,
        [W, "Correct. Markets do not pay for risk that can be removed for free — only for exposure that cannot be avoided.", W, W]),
    ]);

  L("c-efficient-frontier", "Efficient frontier",
    "The set of portfolios giving the most return available for each level of risk.",
    [
      h2("What is this?"),
      p("Plot every possible portfolio with risk on one axis and expected return on the other. The upper-left boundary of the resulting cloud is the efficient frontier: portfolios where no more return is available without accepting more risk."),
      p("Any portfolio below the frontier is inefficient — another combination offers more return for the same risk, or the same return for less."),
      h2("Why does it matter?"),
      p("It reframes the investment problem. The question is not 'which asset is best' but 'which combination sits on the frontier, and where on it do I belong?'"),
      p("It also shows that a single asset is almost never efficient. Combinations dominate individual holdings, because correlation reduces risk without reducing expected return."),
      h2("How does it work?"),
      list([
        "Compute expected return, volatility and correlations for the available assets.",
        "Find, for each level of risk, the combination with the highest expected return.",
        "That set of combinations is the frontier.",
        "Adding a risk-free asset extends it into a straight line from the risk-free rate through the best risk-adjusted portfolio.",
      ]),
      p("In practice the frontier is unstable: it is built from estimated returns, volatilities and correlations, and small estimation errors move it substantially. It is a way of thinking more than a portfolio construction recipe."),
      fig("Real-Life Case Study: three portfolios",
        ["Built from the same assets, with different weights."],
        [["Portfolio X — risk 12%", "return 9.0%"], ["Portfolio Y — risk 12%", "return 11.5%"],
         ["Portfolio Z — risk 18%", "return 13.0%"], ["Efficient at 12% risk", "Y, not X"],
         ["X's shortfall", "2.5 points of return, free"]],
        ["Portfolio X takes exactly the same risk as Y and earns 2.5 points less. It is simply inefficient.",
         "Choosing between Y and Z is a genuine preference about risk. Holding X is not a preference — it is a mistake, and the frontier is what makes it visible."]),
      h2("Key terms"),
      def("Efficient frontier", "Portfolios offering maximum return for each level of risk."),
      def("Inefficient portfolio", "One that could be improved without taking more risk."),
      def("Estimation error", "The instability caused by building the frontier from estimated inputs."),
      h2("Practice"),
      practice([
        { q: "Portfolio A: 12% risk, 9% return. Portfolio B: 12% risk, 11.5% return. What can you conclude?", a: "A is inefficient. For identical risk, B delivers 2.5 points more return, so no investor with the choice should hold A." },
        { q: "Why is the efficient frontier unstable in practice?", a: "It is computed from estimated expected returns, volatilities and correlations. Expected returns especially are hard to estimate, and small changes shift the optimal weights dramatically — which is why optimisers often produce concentrated, unusable portfolios." },
      ]),
      h2("Connection"),
      p("The Sharpe ratio next measures how efficient a single portfolio is, without needing the whole frontier."),
      mcq("A portfolio below the efficient frontier is one where:",
        ["Returns are guaranteed", "More return is available at the same risk", "Risk is zero", "Correlation is 1"], 1,
        [W, "Correct. Being below the frontier means an alternative combination dominates it — the same risk for more return.", W, W]),
    ]);

  L("c-sharpe-ratio", "Sharpe ratio",
    "Return earned per unit of risk taken — the standard way to compare portfolios.",
    [
      h2("What is this?"),
      p("The Sharpe ratio is excess return over the risk-free rate, divided by volatility. It answers how much return a portfolio produced for each unit of risk it took."),
      h2("Why does it matter?"),
      p("Raw returns are not comparable. A 25% return earned with 40% volatility is worse, risk-adjusted, than 15% earned with 12%. The Sharpe ratio makes that comparison explicit."),
      p("It is also how leverage is exposed: doubling a portfolio's leverage roughly doubles both excess return and volatility, leaving the Sharpe ratio unchanged. Leverage manufactures returns, not skill."),
      h2("How does it work?"),
      formula("Sharpe ratio", [
        "<b>Sharpe = (Portfolio return − Risk-free rate) ÷ Portfolio volatility</b>",
        "Higher is better; use the same period for all inputs",
      ]),
      p("Limitations worth knowing: it treats upside and downside volatility identically, assumes returns are roughly normally distributed, and can be flattered by strategies that produce steady small gains and rare large losses."),
      fig("Real-Life Case Study: comparing three managers",
        ["Risk-free rate 7%."],
        [["Manager A — return 25%, volatility 40%", "Sharpe 0.45"],
         ["Manager B — return 15%, volatility 12%", "Sharpe 0.67"],
         ["Manager C — return 11%, volatility 5%", "Sharpe 0.80"],
         ["Highest raw return", "A"], ["Best risk-adjusted", "C"]],
        ["Manager A returned more than twice Manager C and delivered the worst risk-adjusted outcome.",
         "A investor could have levered C's portfolio to reach A's volatility and earned considerably more. That is the practical meaning of a higher Sharpe ratio."]),
      h2("Key terms"),
      def("Sharpe ratio", "Excess return per unit of volatility."),
      def("Risk-adjusted return", "Return measured relative to the risk taken to earn it."),
      h2("Practice"),
      practice([
        { q: "Return 18%, risk-free 7%, volatility 16%. Compute the Sharpe ratio.", a: "(18 − 7) ÷ 16 = 0.69." },
        { q: "A portfolio returns 12% with 10% volatility. The manager doubles leverage, funding the extra exposure at the 7% risk-free rate. Compute the Sharpe ratio before and after.", a: "Before: (12 − 7) ÷ 10 = 0.50. Doubling the position doubles the excess return over the funding cost, so the return becomes 7 + 2 × 5 = 17%, and volatility doubles to 20%. After: (17 − 7) ÷ 20 = 0.50 — unchanged. Leverage scales excess return and risk together, so it cannot manufacture skill." },
      ]),
      h2("Connection"),
      p("The Sharpe ratio measures efficiency for a single portfolio; the frontier describes the whole set of efficient ones."),
      mcq("Adding leverage to a portfolio typically:",
        ["Raises the Sharpe ratio", "Leaves the Sharpe ratio roughly unchanged while raising both return and risk", "Eliminates risk", "Lowers volatility"], 1,
        [W, "Correct. Leverage scales excess return and volatility together, so the ratio between them is unchanged — which is why it cannot substitute for skill.", W, W]),
    ]);

  L("c-beta-portfolio-theory", "Beta",
    "The measure of how much of the market's movement an asset inherits.",
    [
      h2("What is this?"),
      p("Beta is an asset's sensitivity to market movements: the slope of its returns regressed against the market's. A beta of 1.3 means it has historically moved about 30% more than the market in both directions."),
      h2("Why does it matter?"),
      p("Within portfolio theory, beta is the risk that survives diversification. It sets the required return in CAPM and determines how much market exposure a portfolio carries."),
      p("Its limitations are important. Beta is estimated from history and is unstable; it captures only linear co-movement; and it says nothing about a company's own risks."),
      h2("How does it work?"),
      list([
        "<strong>Estimated by regression</strong> of asset returns against index returns over a chosen window.",
        "<strong>Portfolio beta</strong> is the weighted average of the components' betas.",
        "<strong>Levered beta</strong> includes financial leverage; unlevering allows business-risk comparison across firms.",
        "<strong>Window matters:</strong> the same stock can show 0.9 or 1.4 depending on the period chosen.",
      ]),
      fig("Real-Life Case Study: portfolio beta",
        ["A three-holding portfolio and its market exposure."],
        [["Holding 1 — 40% at beta 1.4", "0.56"], ["Holding 2 — 35% at beta 0.9", "0.315"],
         ["Holding 3 — 25% at beta 0.6", "0.15"], ["Portfolio beta", "1.025"],
         ["Expected move if market falls 10%", "≈−10.3%"]],
        ["Despite holding two defensive names, the portfolio carries essentially full market exposure.",
         "That is worth knowing before a downturn rather than during one. Diversifying across stocks with similar betas reduces specific risk but leaves market exposure almost untouched."]),
      h2("Key terms"),
      def("Beta", "Sensitivity of an asset's returns to market returns."),
      def("Portfolio beta", "The weighted average beta of the holdings."),
      def("Unlevered beta", "Beta with the effect of financial leverage removed."),
      h2("Practice"),
      practice([
        { q: "50% at beta 1.6, 30% at beta 1.0, 20% at beta 0.4. Compute the portfolio beta and the expected move if the market rises 8%.", a: "Beta = 0.8 + 0.3 + 0.08 = 1.18. Expected move ≈ 1.18 × 8 = 9.4%." },
        { q: "Why is beta an incomplete description of a stock's risk?", a: "It is estimated from past returns over an arbitrary window, captures only linear co-movement with the index, and ignores company-specific risks entirely. A firm facing a decisive lawsuit can have a low beta and enormous risk." },
      ]),
      h2("Connection"),
      p("Beta links portfolio theory to CAPM, and it is the same input used for the cost of equity in Level 5."),
      mcq("A portfolio of ten stocks all with beta near 1.2 has:",
        ["No market risk", "Reduced specific risk but roughly full market exposure", "Zero volatility", "Guaranteed returns"], 1,
        [W, "Correct. Diversification removes company-specific risk; market exposure remains and is what beta measures.", W, W]),
    ]);

  L("c-alpha", "Alpha",
    "Return above what the risk taken should have produced — and why it is rare.",
    [
      h2("What is this?"),
      p("Alpha is the return a portfolio earned beyond what its risk exposure would predict. If beta is 1.2 and the market returned 10% over a 7% risk-free rate, CAPM predicts 10.6%; earning 14% means 3.4 points of alpha."),
      h2("Why does it matter?"),
      p("It separates skill from exposure. A manager who beat the market by taking more market risk has not added value — a cheaper leveraged index fund would have done the same. Alpha is what is left after that adjustment."),
      p("It is genuinely hard to earn. Every active manager's alpha comes from another participant's negative alpha, and after fees the average must be below zero. Persistent alpha is uncommon and difficult to distinguish from luck over short periods."),
      h2("How does it work?"),
      formula("Alpha", [
        "<b>Expected return = Rf + β × (Rm − Rf)</b>",
        "<b>Alpha = Actual return − Expected return</b>",
        "Positive alpha = return beyond what the risk taken justifies",
      ]),
      fig("Real-Life Case Study: two managers who both beat the market",
        ["Market returned 10%, risk-free 7%."],
        [["Manager D — return 14%, beta 1.5", "expected 11.5% → alpha +2.5%"],
         ["Manager E — return 12%, beta 0.8", "expected 9.4% → alpha +2.6%"],
         ["Higher raw return", "D"], ["More skill demonstrated", "E, marginally"],
         ["Manager F — return 13%, beta 2.0", "expected 13.0% → alpha 0.0%"]],
        ["Manager F beat the market by 3 points and produced no alpha at all — the excess came entirely from taking double the market risk.",
         "That is the value of the adjustment. Without it, leverage looks exactly like skill, which is how a great many track records are built."]),
      h2("Key terms"),
      def("Alpha", "Return in excess of what the risk exposure predicts."),
      def("Zero-sum", "The property that active returns before costs must sum to the market return."),
      h2("Practice"),
      practice([
        { q: "Beta 1.3, market 11%, risk-free 7%, actual return 15%. Compute alpha.", a: "Expected = 7 + 1.3 × 4 = 12.2%. Alpha = 15 − 12.2 = +2.8%." },
        { q: "Why must the average active manager underperform after fees?", a: "Active positions are collectively the market, so before costs the average active return equals the market return. Fees and trading costs are subtracted from that, so the average must fall below the index by roughly the cost." },
      ]),
      h2("Connection"),
      p("Alpha is the return that factor investing next tries to explain away as exposure rather than skill."),
      mcq("The market returns 10% and the risk-free rate is 7%. A manager with a beta of 2.0 returns 13%. Their alpha is:",
        ["+3%", "0%", "+6%", "−3%"], 1,
        [W, "Correct. Expected return = 7 + 2.0 × (10 − 7) = 13%. The manager returned exactly 13%, so alpha is zero — the 3 points of outperformance came entirely from taking double the market risk.", W, W]),
    ]);

  L("c-factor-investing", "Factor investing",
    "Much of what looked like skill turns out to be systematic exposure with a name.",
    [
      h2("What is this?"),
      p("Factor investing identifies characteristics — value, size, momentum, quality, low volatility — that have historically been associated with different average returns. Portfolios can be built to target them deliberately."),
      h2("Why does it matter?"),
      p("It reframes performance measurement. A manager beating the market while consistently holding cheap, small companies may be earning a value and size premium available systematically at low cost, rather than demonstrating stock-picking skill."),
      p("It also gives investors a middle path between a single index and expensive active management."),
      h2("How does it work?"),
      list([
        "<strong>Value:</strong> cheaper stocks on measures like price-to-book have historically outperformed expensive ones over long periods.",
        "<strong>Size:</strong> smaller companies have shown higher average returns, with higher risk and lower liquidity.",
        "<strong>Momentum:</strong> recent winners have tended to keep outperforming over medium horizons.",
        "<strong>Quality:</strong> profitable, low-debt companies have delivered better risk-adjusted returns.",
        "<strong>Low volatility:</strong> less volatile stocks have historically produced returns not much lower than volatile ones.",
      ]),
      p("Two cautions. These are historical patterns, not laws — several have underperformed for a decade at a time. And a factor that becomes widely traded may see its premium compress, since it depended partly on few people pursuing it."),
      fig("Real-Life Case Study: decomposing a track record",
        ["A manager returning 14.5% against an 11% market over a decade."],
        [["Raw outperformance", "+3.5 points"], ["Explained by value exposure", "1.6 points"],
         ["Explained by size exposure", "1.1 points"], ["Explained by momentum", "0.4 points"],
         ["Unexplained (true alpha)", "0.4 points"], ["Cost of replicating factors via funds", "≈0.3%"]],
        ["Nearly all the outperformance came from systematic exposures an investor could buy cheaply.",
         "That does not make the manager bad. It does mean the fee should be compared with the cost of obtaining the same exposures directly, which is precisely what factor analysis is for."]),
      h2("Key terms"),
      def("Factor", "A characteristic historically associated with a return premium."),
      def("Factor decomposition", "Attributing a track record to systematic exposures versus true alpha."),
      def("Premium compression", "The decline in a factor's return as more capital pursues it."),
      h2("Practice"),
      practice([
        { q: "A manager outperforms by 3.5 points, of which 3.1 is explained by value and size exposure. What is the true alpha, and what should an investor ask?", a: "0.4 points of alpha. The investor should ask whether the fee exceeds the cost of buying value and size exposure directly through low-cost funds — if so, they are paying active fees for systematic exposure." },
        { q: "Why might a well-documented factor stop working?", a: "Publication attracts capital. If enough investors buy the same characteristic, prices rise and the future premium falls. A premium that existed because few pursued it can be competed away once many do." },
      ]),
      h2("Connection"),
      p("Factors extend CAPM's single market factor into several, and explain much of what alpha appeared to capture."),
      mcq("Factor analysis of a track record is useful because it:",
        ["Guarantees future returns", "Separates systematic exposures from genuine skill", "Eliminates risk", "Predicts the market"], 1,
        [W, "Correct. It shows how much of the outperformance could have been obtained cheaply through systematic exposure.", W, W]),
    ]);

  /* ============ RISK & SIMULATION ============ */

  L("c-risk-management", "Risk management",
    "Identify what can go wrong, size it, and decide what to do about it — before it happens.",
    [
      h2("What is this?"),
      p("Risk management is the discipline of identifying exposures, measuring them, and deciding for each whether to accept, reduce, transfer or avoid it. It is a process, not a number."),
      h2("Why does it matter?"),
      p("Most serious losses are not caused by unknown risks. They are caused by known risks that were not sized, or that were assumed to be independent when they were not — everything failing together in the same week."),
      p("Good risk management is also unglamorous: it costs money in normal conditions and pays only in bad ones, which is why it is cut first."),
      h2("How does it work?"),
      list([
        "<strong>Identify:</strong> market, credit, liquidity, operational and concentration exposures.",
        "<strong>Measure:</strong> how much could be lost, and how likely.",
        "<strong>Decide:</strong> accept it, reduce it, transfer it via hedging or insurance, or avoid it.",
        "<strong>Monitor:</strong> with limits and triggers set in advance, not during the event.",
        "<strong>Stress test:</strong> assume several risks materialise together, because they usually do.",
      ]),
      fig("Real-Life Case Study: correlated failure",
        ["A business assesses four risks individually and then together."],
        [["Currency loss (individually)", "₹8 crore"], ["Commodity spike (individually)", "₹14 crore"],
         ["Customer default (individually)", "₹6 crore"], ["Refinancing at higher spread", "₹5 crore"],
         ["Sum of individual risks", "₹33 crore"], ["Combined in one downturn", "₹52 crore"]],
        ["Assessed one at a time the total is ₹33 crore; occurring together in a single downturn it is ₹52 crore.",
         "The excess comes from interaction — a weaker currency raises commodity costs, distressed customers default, and credit spreads widen simultaneously. Risks assessed in isolation systematically understate the real exposure."]),
      h2("Key terms"),
      def("Risk transfer", "Moving an exposure to another party via hedging or insurance."),
      def("Correlation of risks", "The tendency for multiple exposures to materialise together in stress."),
      def("Risk limit", "A predefined maximum exposure, set before conditions deteriorate."),
      h2("Practice"),
      practice([
        { q: "Four risks are individually ₹8, ₹14, ₹6 and ₹5 crore. Why might a stress test show more than ₹33 crore?", a: "Because they are correlated. In a downturn several materialise together and amplify each other — a weak currency raises input costs while customers default and credit becomes dearer. Independence is the assumption that fails." },
        { q: "Why is risk management usually cut in good times?", a: "It costs money continuously and delivers nothing visible while conditions are benign. The benefit appears only in the event it was protecting against, so the cost is felt constantly and the value rarely." },
      ]),
      h2("Connection"),
      p("VaR, scenario analysis and Monte Carlo simulation are the measurement tools this process uses."),
      mcq("Assessing risks individually rather than jointly usually:",
        ["Overstates total risk", "Understates total risk, because risks correlate in stress", "Has no effect", "Eliminates risk"], 1,
        [W, "Correct. Exposures that seem independent in calm conditions tend to materialise together in a downturn.", W, W]),
    ]);

  L("c-var", "VaR",
    "A single number for potential loss — useful, and famously insufficient.",
    [
      h2("What is this?"),
      p("Value at Risk states the maximum loss expected over a period at a chosen confidence level. A one-day 95% VaR of ₹4 crore means that on 95% of days losses should be under ₹4 crore."),
      h2("Why does it matter?"),
      p("It compresses a complex risk profile into one comparable figure, which is why regulators and boards use it."),
      p("It is also dangerous, and the danger is specific: <strong>VaR says nothing about what happens in the remaining 5%.</strong> Two portfolios with identical VaR can have completely different losses on the bad days — one loses ₹5 crore, the other ₹90 crore."),
      h2("How does it work?"),
      formula("Parametric VaR", [
        "<b>VaR ≈ Portfolio value × volatility × z-score × √time</b>",
        "z = 1.65 for 95% confidence, 2.33 for 99%",
        "<b>Expected shortfall</b> = the average loss in the tail beyond VaR",
      ]),
      p("Expected shortfall — the average loss given that VaR is breached — addresses the main weakness and is increasingly preferred for exactly that reason."),
      fig("Real-Life Case Study: identical VaR, different portfolios",
        ["Both portfolios show a one-day 95% VaR of ₹4 crore."],
        [["Portfolio P — average loss beyond VaR", "₹5.2 crore"],
         ["Portfolio Q — average loss beyond VaR", "₹31 crore"],
         ["Portfolio Q holding", "sold far out-of-the-money options"],
         ["Days VaR breached per year (expected)", "≈13"], ["Same VaR figure", "₹4 crore"]],
        ["The VaR number is identical and the risk is not remotely comparable.",
         "Portfolio Q collects small premiums almost every day and loses enormously on rare ones. VaR at 95% never sees that, which is exactly how option-selling strategies pass risk limits until they do not."]),
      h2("Key terms"),
      def("Value at Risk", "The loss threshold not expected to be exceeded at a given confidence level."),
      def("Expected shortfall", "The average loss in the tail beyond VaR — what VaR omits."),
      def("Tail risk", "The risk of extreme losses in the low-probability region."),
      h2("Practice"),
      practice([
        { q: "A ₹200 crore portfolio has 1.4% daily volatility. Compute the one-day 95% VaR.", a: "200 × 0.014 × 1.65 = ₹4.62 crore." },
        { q: "Why can two portfolios with the same VaR have very different real risk?", a: "VaR describes only the threshold, not the shape of the tail beyond it. A portfolio with rare but enormous losses shows the same VaR as one with mild tail losses. Expected shortfall distinguishes them; VaR cannot." },
      ]),
      h2("Connection"),
      p("VaR is one measurement within the risk management process; scenario analysis and simulation cover what it cannot see."),
      mcq("A 95% one-day VaR of ₹4 crore means:",
        ["Losses can never exceed ₹4 crore", "On about 5% of days, losses exceed ₹4 crore by an unspecified amount", "Expected loss is ₹4 crore", "The portfolio is safe"], 1,
        [W, "Correct. VaR sets the threshold and says nothing about the magnitude of losses beyond it.", W, W]),
    ]);

  L("c-scenario-analysis-risk", "Scenario analysis",
    "Ask what happens in a specific, named bad world — not a statistical one.",
    [
      h2("What is this?"),
      p("Scenario analysis in risk management constructs concrete adverse situations — a sharp rate rise, a currency collapse, the loss of the largest customer — and works out the effect on the portfolio or business."),
      h2("Why does it matter?"),
      p("Statistical measures like VaR are built from historical distributions and assume the future resembles the past. Scenarios can include events that have never happened, which is where the largest losses tend to come from."),
      p("Scenarios are also easier for decision-makers to act on. 'A 15% loss at 99% confidence' invites debate about methodology; 'if our largest customer leaves we breach the covenant in month four' invites action."),
      h2("How does it work?"),
      list([
        "<strong>Historical scenarios:</strong> replay a past crisis against today's positions.",
        "<strong>Hypothetical scenarios:</strong> construct a plausible event that has not occurred.",
        "<strong>Reverse stress testing:</strong> start from failure and ask what would have to happen to cause it.",
        "Move all affected variables together — a real crisis is never a single-variable event.",
      ]),
      p("Reverse stress testing is the most useful and least used. Asking 'what would break us?' produces a specific list, which can then be monitored."),
      fig("Real-Life Case Study: reverse stress test",
        ["A leveraged company asks what combination would breach its covenant."],
        [["Covenant limit", "net debt / EBITDA 3.5x"], ["Current", "2.6x"],
         ["EBITDA fall needed alone", "−26%"], ["With a 1-point spread widening", "−21% suffices"],
         ["With one major customer lost", "−13% suffices"], ["All three together", "breach in 2 quarters"]],
        ["Individually the company looks resilient — EBITDA would have to fall over a quarter. Together, a 13% decline is enough.",
         "That specific finding — 13%, two quarters, three named causes — is far more actionable than any confidence interval, and it gives management something to monitor directly."]),
      h2("Key terms"),
      def("Reverse stress test", "Starting from failure and identifying what would cause it."),
      def("Historical scenario", "Replaying a past crisis against current positions."),
      h2("Practice"),
      practice([
        { q: "Leverage is 2.6× against a 3.5× covenant. By how much can EBITDA fall before breach, all else equal?", a: "EBITDA can fall to 2.6 ÷ 3.5 = 74.3% of current — a decline of 25.7%." },
        { q: "Why is reverse stress testing more useful than a standard adverse scenario?", a: "It works backwards from the outcome that matters — failure — and identifies the specific combination that produces it. A forward scenario tests a situation you imagined; reverse testing finds the ones you did not." },
      ]),
      h2("Connection"),
      p("This is the risk-management counterpart of the scenario analysis from Level 4, applied to survival rather than valuation."),
      mcq("Reverse stress testing starts by:",
        ["Assuming markets rise", "Assuming failure and asking what would cause it", "Calculating VaR", "Modelling the base case"], 1,
        [W, "Correct. Working backwards from failure identifies the specific combinations that would break the business, including ones nobody thought to test forwards.", W, W]),
    ]);

  L("c-monte-carlo-simulation", "Monte Carlo simulation",
    "Run the future thousands of times and look at the distribution of outcomes.",
    [
      h2("What is this?"),
      p("Monte Carlo simulation replaces single-point assumptions with probability distributions, then runs the model thousands of times drawing randomly from each. The result is a distribution of outcomes rather than one answer."),
      h2("Why does it matter?"),
      p("A standard model gives one number from one set of assumptions, and a sensitivity table gives a grid. A simulation shows the whole distribution — including how often the outcome is catastrophic, which neither of the others reveals."),
      p("It is particularly useful when several uncertain variables interact, because the combined effect is rarely intuitive."),
      h2("How does it work?"),
      list([
        "Specify a distribution for each uncertain input — growth, margin, rates — rather than a single value.",
        "Specify correlations between them; ignoring these is the most common error and understates risk badly.",
        "Draw a random value for each input and run the model. Repeat thousands of times.",
        "Read the distribution: median, percentiles, and the probability of outcomes below a threshold.",
      ]),
      p("The output looks precise and is entirely dependent on the distributions chosen. Garbage distributions produce a beautifully detailed histogram of nonsense."),
      fig("Real-Life Case Study: a valuation distribution",
        ["10,000 runs of a DCF with distributions on growth, margin and WACC."],
        [["Median value per share", "₹182"], ["10th percentile", "₹118"], ["90th percentile", "₹264"],
         ["Probability below ₹150", "23%"], ["Probability above ₹250", "14%"],
         ["Single-point model output", "₹184"]],
        ["The single-point model said ₹184; the simulation says ₹182 median with a 23% chance of being below ₹150.",
         "The point estimate was nearly right and told you almost nothing. The useful output is the 23% — the probability of a materially worse outcome, which is what determines whether the position size is sensible."]),
      h2("Key terms"),
      def("Monte Carlo simulation", "Repeated random sampling from input distributions to produce an output distribution."),
      def("Percentile", "The value below which a given share of simulated outcomes falls."),
      def("Input distribution", "The probability distribution assumed for each uncertain variable."),
      h2("Practice"),
      practice([
        { q: "A simulation gives a median of ₹182 with a 10th percentile of ₹118 against a ₹180 price. What does this tell you?", a: "The price is close to the median outcome, so there is no obvious mispricing, but there is roughly a 10% chance of a value below ₹118 — a 35% loss. The distribution informs position sizing far better than the median alone." },
        { q: "Why does ignoring correlations between inputs understate risk?", a: "Independent draws let bad outcomes offset each other, producing a narrow distribution. In reality weak growth, compressed margins and higher discount rates arrive together, so the true tail is fatter than an uncorrelated simulation shows." },
      ]),
      h2("Connection"),
      p("Simulation generalises the scenario and sensitivity analysis from Levels 4 and 5 into a full distribution."),
      sandbox("risk-outcomes", "Distribution sandbox",
        "Hold the expected return fixed and widen the gap between good and bad outcomes — the average stays put while the risk changes completely.", [
        { key: "amount", label: "Amount invested", value: 1000000, unit: "₹" },
        { key: "goodChance", label: "Chance of the good outcome", value: 60, unit: "%" },
        { key: "goodReturn", label: "Good-case return", value: 35, unit: "%" },
        { key: "badReturn", label: "Bad-case return", value: -25, unit: "%" },
      ]),
      mcq("The main output of a Monte Carlo simulation is:",
        ["A single precise valuation", "A distribution of outcomes, including the probability of bad ones", "A guaranteed forecast", "The correct discount rate"], 1,
        [W, "Correct. Its value lies in the shape of the distribution, particularly the tail — not in the median, which a point estimate already gives you.", W, W]),
    ]);

  /* ============ CORPORATE FINANCE ============ */

  L("c-capital-structure", "Capital structure",
    "How much debt a company should use — and why the answer is not zero or maximum.",
    [
      h2("What is this?"),
      p("Capital structure is the mix of debt and equity funding a business. The question is whether that mix changes the value of the company, and if so, what mix is best."),
      h2("Why does it matter?"),
      p("It is one of the three core corporate finance decisions, alongside which projects to fund and how much to return to shareholders. Get it wrong in either direction and value is lost: too little debt forgoes a real tax benefit, too much invites distress."),
      h2("How does it work?"),
      p("The classical result — Modigliani and Miller — is that in a world with no taxes, no bankruptcy costs and no information gaps, capital structure does not affect firm value. Rearranging the claims does not change the cash the business produces."),
      p("Real value comes from where those assumptions fail:"),
      list([
        "<strong>Tax shield:</strong> interest is deductible, so debt genuinely lowers the total tax bill.",
        "<strong>Distress costs:</strong> beyond some level, debt brings lost customers, forced asset sales and constrained investment.",
        "<strong>Financial flexibility:</strong> unused borrowing capacity has value — it lets a company act when opportunities appear.",
        "<strong>Signalling:</strong> financing choices convey information about management's own view.",
      ]),
      p("The practical answer is the <strong>trade-off theory</strong>: increase debt while the tax benefit exceeds the expected cost of distress, and stop before it does not. Where that point sits depends on cash flow stability, not on a universal ratio."),
      fig("Real-Life Case Study: the trade-off in numbers",
        ["A stable business with ₹100 crore of EBITDA, considering leverage levels."],
        [["No debt — WACC", "13.0%"], ["Net debt 1.5x — WACC", "11.9%"],
         ["Net debt 3.0x — WACC", "11.4%"], ["Net debt 4.5x — WACC", "12.1%"],
         ["Net debt 6.0x — WACC", "14.2%"], ["Approximate optimum", "≈3x"]],
        ["WACC falls as cheap after-tax debt replaces expensive equity, then rises as lenders and shareholders both demand more for distress risk.",
         "The curve is shallow near the bottom, which is the practical lesson: the difference between 2× and 3.5× is small, while 6× is expensive. Precision is not needed — avoiding the extremes is."]),
      h2("Key terms"),
      def("Trade-off theory", "Optimal leverage balances the tax shield against expected distress costs."),
      def("Financial flexibility", "The value of unused borrowing capacity."),
      def("Distress costs", "The real economic costs of being perceived as financially fragile."),
      h2("Practice"),
      practice([
        { q: "Why does WACC fall and then rise as leverage increases?", a: "Initially, cheap after-tax debt replaces expensive equity, lowering the blend. Beyond a point, distress risk makes both lenders and shareholders demand higher returns, so both components rise and the blend increases." },
        { q: "Two companies have identical assets; one is cyclical. Should they carry the same leverage?", a: "No. The cyclical company's EBITDA can halve, doubling leverage and breaching covenants without any new borrowing. Its optimal leverage is materially lower, because the expected cost of distress is higher at every level of debt." },
      ]),
      h2("Connection"),
      p("This determines the weights in WACC from Level 5, and it is the decision the LBO structures in Level 7 push to its limit."),
      sandbox("leverage-returns", "Capital structure sandbox",
        "Shift the debt-equity mix and watch owner returns rise — then cut operating profit and see why the optimum is not maximum debt.", [
        { key: "operatingProfit", label: "Operating profit", value: 1000000000, unit: "₹" },
        { key: "debt", label: "Debt", value: 3000000000, unit: "₹" },
        { key: "interestRate", label: "Interest rate", value: 10, unit: "%" },
        { key: "equity", label: "Equity", value: 4000000000, unit: "₹" },
      ]),
      mcq("Under the trade-off theory, a company should add debt until:",
        ["Lenders refuse to provide more", "The marginal tax benefit is offset by the expected cost of distress", "Equity is eliminated", "WACC reaches zero"], 1,
        [W, "Correct. The optimum balances a real tax saving against a real, rising risk cost — which sits at different levels for different businesses.", W, W]),
    ]);

  L("c-cost-of-capital", "Cost of capital",
    "The return a business must earn to justify existing — and the last idea in the curriculum.",
    [
      h2("What is this?"),
      p("The cost of capital is the blended return that a company's funders — lenders and shareholders — require. It is WACC, viewed as a hurdle rather than as a discount rate."),
      h2("Why does it matter?"),
      p("It is the line between creating and destroying value. A business earning above it makes its owners richer; one earning below it makes them poorer while still reporting a profit, and can do so for years."),
      p("It is the single idea this curriculum has been building towards. Almost every concept covered — margins, working capital, ROIC, DCF, leverage, portfolio theory — is either a way of measuring the return earned or a way of estimating what it must clear."),
      h2("How does it work?"),
      formula("Cost of capital as a hurdle", [
        "<b>WACC = (E/V) × Re + (D/V) × Rd × (1 − t)</b>",
        "<b>Value created = (ROIC − WACC) × Invested capital</b>",
        "Growth adds value only when ROIC > WACC",
      ]),
      list([
        "<strong>Investment decisions:</strong> fund projects expected to return above it.",
        "<strong>Valuation:</strong> discount future cash flows at it.",
        "<strong>Performance:</strong> compare ROIC against it to judge whether value was created.",
        "<strong>Capital structure:</strong> choose the mix that minimises it, within safe leverage.",
      ]),
      fig("Real-Life Case Study: two decades, two companies",
        ["Both grew revenue 11% a year for twenty years."],
        [["Company A — average ROIC", "17%"], ["Company A — WACC", "11%"], ["Company A — spread", "+6 points"],
         ["Company B — average ROIC", "8%"], ["Company B — WACC", "11%"], ["Company B — spread", "−3 points"],
         ["Value created per ₹100 reinvested/yr", "+₹6 vs −₹3"]],
        ["Identical growth, opposite outcomes. Company B reported rising profit throughout and destroyed value every single year.",
         "This is the idea worth carrying out of the curriculum. Growth is not the objective, profit is not the objective, and neither tells you whether value was created. The comparison of return against the cost of capital does."]),
      h2("Key terms"),
      def("Cost of capital", "The blended return required by all providers of finance."),
      def("Hurdle rate", "The minimum return a project must earn to be worth undertaking."),
      def("Value creation", "Earning a return above the cost of the capital employed."),
      h2("Practice"),
      practice([
        { q: "ROIC 14.5%, WACC 11.2%, invested capital ₹800 crore. Compute annual value created.", a: "Spread = 3.3 points. Value created ≈ 3.3% × 800 = ₹26.4 crore a year above what funders required." },
        { q: "A company reports growing profit every year for a decade while earning 8% on capital costing 12%. What happened to shareholders?", a: "They lost about 4% a year on all capital reinvested, despite a decade of rising reported profit. The company grew and destroyed value simultaneously — which is invisible on the income statement and obvious the moment ROIC is compared with the cost of capital." },
      ]),
      h2("Connection"),
      p("This closes the curriculum. Everything from Level 0's time value of money to Level 9's market prices exists to estimate two numbers: what a business earns on its capital, and what that capital costs."),
      mcq("A company growing rapidly while earning below its cost of capital is:",
        ["Creating value through scale", "Destroying value with every rupee reinvested", "Risk-free", "Guaranteed to succeed"], 1,
        [W, "Correct. Growth multiplies whatever the underlying spread is. A negative spread means faster growth destroys value faster.", W, W]),
    ]);
})();
