/* Generated by scripts/build-legacy-lessons.ts — do not edit by hand.
   All 11 levels, 35 modules and 227 topics, for the left curriculum pane.
   "written: false" means the concept lesson is not authored yet; the pane
   shows the topic but does not link it, so no route can 404. */
(function () {
  "use strict";
  var LS = (window.LS = window.LS || {});

  /* ---- sandbox calculators (compiled from sandboxEngine.ts) ---- */
var FinStudioSandbox = (() => {
  var __defProp = Object.defineProperty;
  var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
  var __getOwnPropNames = Object.getOwnPropertyNames;
  var __hasOwnProp = Object.prototype.hasOwnProperty;
  var __export = (target, all) => {
    for (var name in all)
      __defProp(target, name, { get: all[name], enumerable: true });
  };
  var __copyProps = (to, from, except, desc) => {
    if (from && typeof from === "object" || typeof from === "function") {
      for (let key of __getOwnPropNames(from))
        if (!__hasOwnProp.call(to, key) && key !== except)
          __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
    }
    return to;
  };
  var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

  // src/data/lessons/sandboxEngine.ts
  var sandboxEngine_exports = {};
  __export(sandboxEngine_exports, {
    computeSandbox: () => computeSandbox,
    sandboxKinds: () => sandboxKinds
  });
  var inr = (n) => "\u20B9" + Math.round(n).toLocaleString("en-IN");
  var pct = (n, dp = 1) => `${n.toFixed(dp)}%`;
  var sandboxKinds = {
    /** FV = P × (1+r)^n */
    "future-value": ({ principal = 0, rate = 0, years = 0 }) => {
      const fv = principal * Math.pow(1 + rate / 100, years);
      return [
        { label: "Future value", value: inr(fv) },
        { label: "Total growth", value: inr(fv - principal), note: `${inr(principal)} growing at ${pct(rate)} a year for ${years} year(s).` }
      ];
    },
    /** PV = CF ÷ (1+r)^t */
    "present-value": ({ amount = 0, rate = 0, years = 0 }) => {
      const pv = amount / Math.pow(1 + rate / 100, years);
      return [
        { label: "Present value", value: inr(pv) },
        { label: "Discount applied", value: inr(amount - pv), note: `What ${inr(amount)} arriving in ${years} year(s) is worth today at ${pct(rate)}.` }
      ];
    },
    /** Simple P(1+rn) vs compound P(1+r)^n, and the gap between them. */
    "simple-vs-compound": ({ principal = 0, rate = 0, years = 0 }) => {
      const simple = principal * (1 + rate / 100 * years);
      const compound = principal * Math.pow(1 + rate / 100, years);
      return [
        { label: "Simple interest total", value: inr(simple) },
        { label: "Compound interest total", value: inr(compound) },
        { label: "Extra from compounding", value: inr(compound - simple), note: "The gap is interest earned on interest. Stretch the years and watch it widen." }
      ];
    },
    /** Nominal growth vs purchasing power after inflation. */
    "inflation-real": ({ amount = 0, nominalRate = 0, inflation = 0, years = 0 }) => {
      const nominal = amount * Math.pow(1 + nominalRate / 100, years);
      const real = amount * Math.pow((1 + nominalRate / 100) / (1 + inflation / 100), years);
      const realRate = ((1 + nominalRate / 100) / (1 + inflation / 100) - 1) * 100;
      return [
        { label: "Balance in rupees", value: inr(nominal) },
        { label: "In today's purchasing power", value: inr(real) },
        { label: "Real return per year", value: pct(realRate, 2), note: realRate < 0 ? "Your balance grows while your buying power falls." : "Growth after inflation \u2014 the figure that says whether you are better off." }
      ];
    },
    /** Revenue = price × volume, this year and next. */
    "revenue-growth": ({ price = 0, volume = 0, priceGrowth = 0, volumeGrowth = 0 }) => {
      const now = price * volume;
      const next = price * (1 + priceGrowth / 100) * volume * (1 + volumeGrowth / 100);
      return [
        { label: "Revenue this year", value: inr(now) },
        { label: "Revenue next year", value: inr(next) },
        { label: "Growth", value: pct(now ? (next / now - 1) * 100 : 0), note: "Price and volume growth multiply \u2014 the total is more than their sum." }
      ];
    },
    /** Fixed costs amplify profit swings relative to revenue swings. */
    "operating-leverage": ({ price = 0, variableCost = 0, units = 0, fixedCosts = 0, volumeChange = 0 }) => {
      const profitAt = (u) => (price - variableCost) * u - fixedCosts;
      const before = profitAt(units);
      const after = profitAt(units * (1 + volumeChange / 100));
      const profitSwing = before !== 0 ? (after - before) / Math.abs(before) * 100 : 0;
      return [
        { label: "Profit now", value: inr(before) },
        { label: `Profit after ${pct(volumeChange, 0)} volume change`, value: inr(after) },
        { label: "Profit swing", value: pct(profitSwing, 0), note: "Compare this with the volume change \u2014 fixed costs amplify it in both directions." }
      ];
    },
    /** Revenue down to net profit, one subtraction at a time. */
    "profit-bridge": ({ revenue = 0, cogs = 0, opex = 0, interest = 0, taxRate = 0 }) => {
      const gross = revenue - cogs;
      const operating = gross - opex;
      const pbt = operating - interest;
      const tax = Math.max(pbt, 0) * (taxRate / 100);
      const net = pbt - tax;
      return [
        { label: "Gross profit", value: inr(gross) },
        { label: "Operating profit", value: inr(operating) },
        { label: "Profit before tax", value: inr(pbt) },
        { label: "Net profit", value: inr(net), note: revenue ? `Net margin ${pct(net / revenue * 100)}.` : void 0 }
      ];
    },
    /** Profit adjusted for cash trapped in receivables and inventory. */
    "profit-to-cash": ({ profit = 0, receivablesIncrease = 0, inventoryIncrease = 0, payablesIncrease = 0 }) => {
      const cash = profit - receivablesIncrease - inventoryIncrease + payablesIncrease;
      return [
        { label: "Reported profit", value: inr(profit) },
        { label: "Cash effect", value: inr(cash), note: "Unpaid invoices and unsold stock absorb cash; supplier credit releases it." },
        { label: "Gap", value: inr(profit - cash) }
      ];
    },
    /** Total return = (sell − buy + income) ÷ buy. */
    "holding-return": ({ buyPrice = 0, sellPrice = 0, income = 0 }) => {
      const gain = sellPrice - buyPrice + income;
      return [
        { label: "Total gain", value: inr(gain) },
        { label: "Total return", value: pct(buyPrice ? gain / buyPrice * 100 : 0), note: "Income counts. Leaving it out understates the result." }
      ];
    },
    /** Compare a chosen option against the best alternative. */
    "opportunity": ({ amount = 0, chosenReturn = 0, alternativeReturn = 0 }) => {
      const chosen = amount * (chosenReturn / 100);
      const alt = amount * (alternativeReturn / 100);
      return [
        { label: "Chosen option earns", value: inr(chosen) },
        { label: "Best alternative earns", value: inr(alt) },
        { label: "Opportunity cost of choosing", value: inr(alt - chosen), note: alt > chosen ? "Positive means the alternative was better \u2014 the choice has a hidden cost." : "Zero or negative means the chosen option beats the alternative." }
      ];
    },
    /** Probability-weighted outcome of a risky bet. */
    "risk-outcomes": ({ amount = 0, goodChance = 0, goodReturn = 0, badReturn = 0 }) => {
      const p = Math.min(Math.max(goodChance, 0), 100) / 100;
      const expected = p * (goodReturn / 100) + (1 - p) * (badReturn / 100);
      return [
        { label: "Good year ends at", value: inr(amount * (1 + goodReturn / 100)) },
        { label: "Bad year ends at", value: inr(amount * (1 + badReturn / 100)) },
        { label: "Expected return", value: pct(expected * 100), note: "An average of outcomes, not a promise \u2014 you never actually receive the average." }
      ];
    },
    /** Owner return with and without borrowing. */
    "leverage-returns": ({ operatingProfit = 0, debt = 0, interestRate = 0, equity = 0 }) => {
      const interest = debt * (interestRate / 100);
      const ownerProfit = operatingProfit - interest;
      const totalCapital = debt + equity;
      const unlevered = totalCapital ? operatingProfit / totalCapital * 100 : 0;
      const levered = equity ? ownerProfit / equity * 100 : 0;
      return [
        { label: "Interest owed", value: inr(interest), note: "Owed in full whatever the year looks like." },
        { label: "Left for owners", value: inr(ownerProfit) },
        { label: "Owner return with debt", value: pct(levered) },
        { label: "Return if all-equity", value: pct(unlevered), note: "Cut operating profit and watch the levered return fall much faster." }
      ];
    },
    /** Equity as the residual: A − L. */
    "balance": ({ assets = 0, liabilities = 0 }) => [
      { label: "Equity", value: inr(assets - liabilities), note: "Found by subtraction \u2014 the owners keep whatever is left." }
    ],
    /** Operating working capital from its three main parts. */
    "working-capital": ({ inventory = 0, receivables = 0, payables = 0 }) => [
      { label: "Operating working capital", value: inr(inventory + receivables - payables), note: "Cash locked into running the business. Grow the first two and it rises \u2014 consuming cash." }
    ],
    /** Cash tied up in receivables at different collection speeds. */
    "receivables-cash": ({ revenue = 0, dsoNow = 0, dsoNew = 0 }) => {
      const now = dsoNow / 365 * revenue;
      const later = dsoNew / 365 * revenue;
      return [
        { label: `Cash tied up at ${dsoNow} days`, value: inr(now) },
        { label: `Cash tied up at ${dsoNew} days`, value: inr(later) },
        { label: later > now ? "Extra cash consumed" : "Cash released", value: inr(Math.abs(later - now)), note: "Every extra day of collection time is your money financing customers." }
      ];
    },
    /** Cash released or consumed by paying suppliers slower or faster. */
    "payables-cash": ({ cogs = 0, dpoNow = 0, dpoNew = 0 }) => {
      const now = dpoNow / 365 * cogs;
      const later = dpoNew / 365 * cogs;
      return [
        { label: `Supplier credit at ${dpoNow} days`, value: inr(now) },
        { label: `Supplier credit at ${dpoNew} days`, value: inr(later) },
        { label: later > now ? "One-off cash released" : "Cash given up", value: inr(Math.abs(later - now)), note: "A real benefit, but it happens once \u2014 it is not recurring cash flow." }
      ];
    },
    /** Buy stock, sell part of it at a markup. */
    "sell-through": ({ stockBought = 0, percentSold = 0, markup = 0 }) => {
      const share = Math.min(Math.max(percentSold, 0), 100) / 100;
      const cogs = stockBought * share;
      const revenue = cogs * (1 + markup / 100);
      return [
        { label: "Revenue", value: inr(revenue) },
        { label: "Cost of goods sold", value: inr(cogs) },
        { label: "Gross profit", value: inr(revenue - cogs) },
        { label: "Stock still on the shelf", value: inr(stockBought - cogs), note: "Cash already spent, profit untouched \u2014 and at risk if it must be discounted." }
      ];
    },
    /** A cost paid once, spread over the months it covers. */
    "spread-cost": ({ totalCost = 0, monthsCovered = 0, monthsElapsed = 0 }) => {
      const months = Math.max(monthsCovered, 1);
      const elapsed = Math.min(Math.max(monthsElapsed, 0), months);
      const monthly = totalCost / months;
      return [
        { label: "Expense per month", value: inr(monthly) },
        { label: "Expensed so far", value: inr(monthly * elapsed) },
        { label: "Still a prepaid asset", value: inr(totalCost - monthly * elapsed), note: "Cash left once; the expense arrives month by month." }
      ];
    },
    /** Advance collections earned only as delivery happens. */
    "deferred-revenue": ({ contractValue = 0, monthsTotal = 0, monthsDelivered = 0 }) => {
      const months = Math.max(monthsTotal, 1);
      const delivered = Math.min(Math.max(monthsDelivered, 0), months);
      const recognised = contractValue / months * delivered;
      return [
        { label: "Revenue earned so far", value: inr(recognised) },
        { label: "Still owed to the customer", value: inr(contractValue - recognised), note: "Cash in the bank, but a liability until the service is delivered." }
      ];
    },
    /** Revenue recognised when delivered, not when collected. */
    "accrual-timing": ({ workDelivered = 0, cashCollected = 0 }) => {
      const receivable = Math.max(workDelivered - cashCollected, 0);
      const deferred = Math.max(cashCollected - workDelivered, 0);
      return [
        { label: "Revenue recognised", value: inr(workDelivered), note: "Follows delivery, not payment." },
        { label: "Receivable created", value: inr(receivable) },
        { label: "Deferred revenue created", value: inr(deferred), note: deferred > 0 ? "Collected ahead of delivery \u2014 a liability until earned." : void 0 }
      ];
    },
    /** Straight-line depreciation and the value still on the books. */
    "depreciation": ({ cost = 0, residual = 0, usefulLife = 0, yearsElapsed = 0 }) => {
      const life = Math.max(usefulLife, 1);
      const annual = (cost - residual) / life;
      const elapsed = Math.min(Math.max(yearsElapsed, 0), life);
      return [
        { label: "Annual charge", value: inr(annual) },
        { label: `Accumulated after ${elapsed} year(s)`, value: inr(annual * elapsed) },
        { label: "Net book value", value: inr(cost - annual * elapsed), note: "Original cost minus everything charged so far \u2014 not a market price." }
      ];
    },
    /** Opening + capex − depreciation, with a shrinking-base warning. */
    "ppe-rollforward": ({ opening = 0, capex = 0, depreciationCharge = 0 }) => {
      const closing = opening + capex - depreciationCharge;
      return [
        { label: "Closing PP&E", value: inr(closing) },
        { label: "Change in asset base", value: inr(closing - opening), note: closing < opening ? "Spending below depreciation \u2014 the asset base is being run down." : "The asset base grew this period." }
      ];
    },
    /** Purchase premium over identifiable net assets. */
    "goodwill": ({ purchasePrice = 0, assetsAcquired = 0, liabilitiesAcquired = 0 }) => {
      const identifiable = assetsAcquired - liabilitiesAcquired;
      return [
        { label: "Identifiable net assets", value: inr(identifiable) },
        { label: "Goodwill", value: inr(purchasePrice - identifiable), note: "The premium paid for expectations \u2014 reputation, relationships, synergies." }
      ];
    },
    /** Opening + profit − dividends. */
    "retained": ({ opening = 0, netProfit = 0, dividends = 0 }) => [
      { label: "Closing retained earnings", value: inr(opening + netProfit - dividends), note: "Accumulated profit kept in the business \u2014 not a cash balance." }
    ]
  };
  function computeSandbox(kind, values) {
    const fn = sandboxKinds[kind];
    return fn ? fn(values) : [];
  }
  return __toCommonJS(sandboxEngine_exports);
})();

  LS.sandbox = FinStudioSandbox;

  LS.curriculumMap = [
    { level: 0, title: "Finance Foundations", modules: [
      { title: "Finance basics", topics: [
        { title: "What is finance?", id: "c-what-is-finance", cid: "c-what-is-finance", written: true },
        { title: "Personal finance vs corporate finance vs investing", id: "c-personal-corporate-investing", cid: "c-personal-corporate-investing", written: true },
        { title: "Financial markets", id: "c-financial-markets", cid: "c-financial-markets", written: true },
        { title: "Companies and capital", id: "c-companies-and-capital", cid: "c-companies-and-capital", written: true },
        { title: "Revenue", id: "c-revenue", cid: "c-revenue", written: true },
        { title: "Costs", id: "c-costs", cid: "c-costs", written: true },
        { title: "Profit", id: "c-profit", cid: "c-profit", written: true },
        { title: "Cash", id: "c-cash", cid: "c-cash", written: true },
        { title: "Assets", id: "c-assets", cid: "c-assets", written: true },
        { title: "Liabilities", id: "c-liabilities", cid: "c-liabilities", written: true },
        { title: "Equity", id: "c-equity", cid: "c-equity", written: true },
        { title: "Debt", id: "c-debt", cid: "c-debt", written: true },
        { title: "Interest", id: "c-interest", cid: "c-interest", written: true },
        { title: "Risk", id: "c-risk", cid: "c-risk", written: true },
        { title: "Return", id: "c-return", cid: "c-return", written: true }
      ] },
      { title: "Time value & decision making", topics: [
        { title: "Time value of money", id: "c-time-value-of-money", cid: "c-time-value-of-money", written: true },
        { title: "Compounding", id: "c-compounding", cid: "c-compounding", written: true },
        { title: "Inflation", id: "c-inflation", cid: "c-inflation", written: true },
        { title: "Present value", id: "c-present-value", cid: "c-present-value", written: true },
        { title: "Future value", id: "c-future-value", cid: "c-future-value", written: true },
        { title: "Opportunity cost", id: "c-opportunity-cost", cid: "c-opportunity-cost", written: true },
        { title: "Risk vs reward", id: "c-risk-vs-reward", cid: "c-risk-vs-reward", written: true }
      ] }
    ] },
    { level: 1, title: "Accounting Foundations", modules: [
      { title: "Accounting mechanics", topics: [
        { title: "Accounting equation", id: "c-accounting-equation", cid: "c-accounting-equation", written: true },
        { title: "Double-entry accounting", id: "c-double-entry-accounting", cid: "c-double-entry-accounting", written: true },
        { title: "Debits and credits", id: "c-debits-and-credits", cid: "c-debits-and-credits", written: true },
        { title: "Chart of accounts", id: "c-chart-of-accounts", cid: "c-chart-of-accounts", written: true },
        { title: "Accrual accounting", id: "c-accrual-accounting", cid: "c-accrual-accounting", written: true },
        { title: "Cash accounting", id: "c-cash-accounting", cid: "c-cash-accounting", written: true },
        { title: "Revenue recognition", id: "c-revenue-recognition", cid: "c-revenue-recognition", written: true },
        { title: "Expenses", id: "c-expenses", cid: "c-expenses", written: true }
      ] },
      { title: "Working capital & operating assets", topics: [
        { title: "Accounts receivable", id: "c-accounts-receivable", cid: "c-accounts-receivable", written: true },
        { title: "Accounts payable", id: "c-accounts-payable", cid: "c-accounts-payable", written: true },
        { title: "Inventory", id: "c-inventory", cid: "c-inventory", written: true },
        { title: "Prepaid expenses", id: "c-prepaid-expenses", cid: "c-prepaid-expenses", written: true },
        { title: "Deferred revenue", id: "c-deferred-revenue", cid: "c-deferred-revenue", written: true },
        { title: "Accrued expenses", id: "c-accrued-expenses", cid: "c-accrued-expenses", written: true },
        { title: "Working capital", id: "c-working-capital", cid: "c-working-capital", written: true }
      ] },
      { title: "Long-lived assets & equity", topics: [
        { title: "Depreciation", id: "c-depreciation", cid: "c-depreciation", written: true },
        { title: "Amortization", id: "c-amortization", cid: "c-amortization", written: true },
        { title: "PP&E", id: "c-ppe", cid: "c-ppe", written: true },
        { title: "Goodwill", id: "c-goodwill", cid: "c-goodwill", written: true },
        { title: "Intangible assets", id: "c-intangible-assets", cid: "c-intangible-assets", written: true },
        { title: "Retained earnings", id: "c-retained-earnings", cid: "c-retained-earnings", written: true }
      ] }
    ] },
    { level: 2, title: "Financial Statements", modules: [
      { title: "Income statement", topics: [
        { title: "Revenue", id: "1410-revenue", cid: "1410-revenue", written: true },
        { title: "COGS", id: "1420-cogs", cid: "1420-cogs", written: true },
        { title: "Gross profit", id: "c-gross-profit", cid: "c-gross-profit", written: true },
        { title: "Operating expenses", id: "1430-opex-ebitda", cid: "1430-opex-ebitda", written: true },
        { title: "EBITDA", id: "c-ebitda", cid: "c-ebitda", written: true },
        { title: "D&A", id: "1440-depreciation-pl", cid: "1440-depreciation-pl", written: true },
        { title: "EBIT", id: "c-ebit", cid: "c-ebit", written: true },
        { title: "Interest", id: "1450-interest-tax", cid: "1450-interest-tax", written: true },
        { title: "EBT", id: "c-ebt", cid: "c-ebt", written: true },
        { title: "Taxes", id: "c-taxes", cid: "c-taxes", written: true },
        { title: "Net income", id: "1460-pl-capstone", cid: "1460-pl-capstone", written: true }
      ] },
      { title: "Balance sheet", topics: [
        { title: "Cash", id: "1150-cash-deposit", cid: "1150-cash-deposit", written: true },
        { title: "Receivables", id: "1140-receivables", cid: "1140-receivables", written: true },
        { title: "Inventory", id: "1130-inventory", cid: "1130-inventory", written: true },
        { title: "PP&E", id: "1110-ppe", cid: "1110-ppe", written: true },
        { title: "Intangibles", id: "c-intangibles", cid: "c-intangibles", written: true },
        { title: "Debt", id: "1220-borrowings", cid: "1220-borrowings", written: true },
        { title: "Payables", id: "1210-payables", cid: "1210-payables", written: true },
        { title: "Other liabilities", id: "c-other-liabilities", cid: "c-other-liabilities", written: true },
        { title: "Equity", id: "1310-share-capital", cid: "1310-share-capital", written: true }
      ] },
      { title: "Cash flow statement", topics: [
        { title: "CFO", id: "1520-cfo", cid: "1520-cfo", written: true },
        { title: "CFI", id: "1530-cfi", cid: "1530-cfi", written: true },
        { title: "CFF", id: "1540-cff", cid: "1540-cff", written: true },
        { title: "Capex", id: "c-capex", cid: "c-capex", written: true },
        { title: "Change in working capital", id: "c-change-in-working-capital", cid: "c-change-in-working-capital", written: true },
        { title: "Debt issuance", id: "c-debt-issuance", cid: "c-debt-issuance", written: true },
        { title: "Debt repayment", id: "c-debt-repayment", cid: "c-debt-repayment", written: true },
        { title: "Dividends", id: "c-dividends", cid: "c-dividends", written: true },
        { title: "Stock issuance", id: "c-stock-issuance", cid: "c-stock-issuance", written: true }
      ] },
      { title: "Three-statement connection", topics: [
        { title: "Three-statement connection", id: "2110-three-bridges", cid: "2110-three-bridges", written: true },
        { title: "Revenue cascade through the three statements", id: "c-revenue-cascade-through-the-three-statements", cid: "c-revenue-cascade-through-the-three-statements", written: true },
        { title: "Profit to cash", id: "1510-profit-not-cash", cid: "1510-profit-not-cash", written: true },
        { title: "Balance sheet check", id: "1330-balance-sheet", cid: "1330-balance-sheet", written: true }
      ] }
    ] },
    { level: 3, title: "Financial Analysis", modules: [
      { title: "Profitability & returns", topics: [
        { title: "Gross margin", id: "1610-margins", cid: "1610-margins", written: true },
        { title: "EBITDA margin", id: "c-ebitda-margin", cid: "c-ebitda-margin", written: true },
        { title: "EBIT margin", id: "c-ebit-margin", cid: "c-ebit-margin", written: true },
        { title: "Net margin", id: "c-net-margin", cid: "c-net-margin", written: true },
        { title: "ROE", id: "1640-returns", cid: "1640-returns", written: true },
        { title: "ROA", id: "c-roa", cid: "c-roa", written: true },
        { title: "ROIC", id: "c-roic", cid: "c-roic", written: true },
        { title: "Asset turnover", id: "c-asset-turnover", cid: "c-asset-turnover", written: true }
      ] },
      { title: "Liquidity & leverage", topics: [
        { title: "Current ratio", id: "1620-liquidity", cid: "1620-liquidity", written: true },
        { title: "Quick ratio", id: "c-quick-ratio", cid: "c-quick-ratio", written: true },
        { title: "Debt/equity", id: "1630-leverage", cid: "1630-leverage", written: true },
        { title: "Net debt/EBITDA", id: "c-net-debt-ebitda", cid: "c-net-debt-ebitda", written: true },
        { title: "Interest coverage", id: "c-interest-coverage", cid: "c-interest-coverage", written: true }
      ] },
      { title: "Cash & operating analysis", topics: [
        { title: "Free cash flow", id: "2230-fcff", cid: "2230-fcff", written: true },
        { title: "Working capital analysis", id: "c-working-capital-analysis", cid: "c-working-capital-analysis", written: true },
        { title: "Cash conversion cycle", id: "c-cash-conversion-cycle", cid: "c-cash-conversion-cycle", written: true },
        { title: "Operating leverage", id: "c-operating-leverage", cid: "c-operating-leverage", written: true },
        { title: "Financial leverage", id: "c-financial-leverage", cid: "c-financial-leverage", written: true }
      ] }
    ] },
    { level: 4, title: "Financial Modeling", modules: [
      { title: "Model architecture", topics: [
        { title: "Model architecture", id: "c-model-architecture", cid: "c-model-architecture", written: true },
        { title: "Assumptions", id: "c-assumptions", cid: "c-assumptions", written: true },
        { title: "Historical periods", id: "c-historical-periods", cid: "c-historical-periods", written: true },
        { title: "Forecast periods", id: "2220-project-pl", cid: "2220-project-pl", written: true },
        { title: "Drivers", id: "2210-drivers", cid: "2210-drivers", written: true },
        { title: "Model formatting", id: "c-model-formatting", cid: "c-model-formatting", written: true },
        { title: "Model best practices", id: "c-model-best-practices", cid: "c-model-best-practices", written: true }
      ] },
      { title: "Operating schedules", topics: [
        { title: "Revenue build", id: "c-revenue-build", cid: "c-revenue-build", written: true },
        { title: "Cost build", id: "c-cost-build", cid: "c-cost-build", written: true },
        { title: "Headcount model", id: "c-headcount-model", cid: "c-headcount-model", written: true },
        { title: "Working capital model", id: "c-working-capital-model", cid: "c-working-capital-model", written: true },
        { title: "Capex model", id: "c-capex-model", cid: "c-capex-model", written: true },
        { title: "Depreciation schedule", id: "c-depreciation-schedule", cid: "c-depreciation-schedule", written: true },
        { title: "Debt schedule", id: "c-debt-schedule", cid: "c-debt-schedule", written: true },
        { title: "Interest schedule", id: "c-interest-schedule", cid: "c-interest-schedule", written: true },
        { title: "Tax schedule", id: "c-tax-schedule", cid: "c-tax-schedule", written: true },
        { title: "Retained earnings", id: "c-retained-earnings-schedule", cid: "c-retained-earnings-schedule", written: true }
      ] },
      { title: "Integrated modeling", topics: [
        { title: "Three-statement model", id: "2120-linked-model", cid: "2120-linked-model", written: true },
        { title: "Scenario analysis", id: "c-scenario-analysis", cid: "c-scenario-analysis", written: true },
        { title: "Sensitivity analysis", id: "c-sensitivity-analysis", cid: "c-sensitivity-analysis", written: true },
        { title: "Model checks", id: "2130-broken-link", cid: "2130-broken-link", written: true },
        { title: "Circularity", id: "c-circularity", cid: "c-circularity", written: true }
      ] },
      { title: "Build a real model", topics: [
        { title: "Revenue", id: "c-revenue-forecast", cid: "c-revenue-forecast", written: true },
        { title: "Gross Profit", id: "c-gross-profit-model", cid: "c-gross-profit-model", written: true },
        { title: "EBITDA", id: "c-ebitda-model", cid: "c-ebitda-model", written: true },
        { title: "EBIT", id: "c-ebit-model", cid: "c-ebit-model", written: true },
        { title: "Net Income", id: "c-net-income-model", cid: "c-net-income-model", written: true },
        { title: "Cash Flow", id: "c-cash-flow", cid: "c-cash-flow", written: true },
        { title: "Balance Sheet", id: "c-balance-sheet", cid: "c-balance-sheet", written: true }
      ] }
    ] },
    { level: 5, title: "Valuation", modules: [
      { title: "Valuation building blocks", topics: [
        { title: "Enterprise value", id: "c-enterprise-value", cid: "c-enterprise-value", written: false },
        { title: "Equity value", id: "c-equity-value", cid: "c-equity-value", written: false },
        { title: "Market capitalization", id: "c-market-capitalization", cid: "c-market-capitalization", written: false },
        { title: "Net debt", id: "c-net-debt", cid: "c-net-debt", written: false },
        { title: "EV/Revenue", id: "c-ev-revenue", cid: "c-ev-revenue", written: false },
        { title: "EV/EBITDA", id: "c-ev-ebitda", cid: "c-ev-ebitda", written: false },
        { title: "P/E", id: "c-p-e", cid: "c-p-e", written: false },
        { title: "PEG", id: "c-peg", cid: "c-peg", written: false }
      ] },
      { title: "DCF", topics: [
        { title: "DCF", id: "2240-dcf", cid: "2240-dcf", written: true },
        { title: "WACC", id: "c-wacc", cid: "c-wacc", written: false },
        { title: "Cost of equity", id: "c-cost-of-equity", cid: "c-cost-of-equity", written: false },
        { title: "Cost of debt", id: "c-cost-of-debt", cid: "c-cost-of-debt", written: false },
        { title: "CAPM", id: "c-capm", cid: "c-capm", written: false },
        { title: "Beta", id: "c-beta", cid: "c-beta", written: false },
        { title: "Risk-free rate", id: "c-risk-free-rate", cid: "c-risk-free-rate", written: false },
        { title: "Equity risk premium", id: "c-equity-risk-premium", cid: "c-equity-risk-premium", written: false },
        { title: "Terminal value", id: "c-terminal-value", cid: "c-terminal-value", written: false },
        { title: "Perpetuity growth", id: "c-perpetuity-growth", cid: "c-perpetuity-growth", written: false },
        { title: "Exit multiple", id: "c-exit-multiple", cid: "c-exit-multiple", written: false },
        { title: "Discount factors", id: "c-discount-factors", cid: "c-discount-factors", written: false },
        { title: "Sensitivity analysis", id: "c-sensitivity-analysis-dcf", cid: "c-sensitivity-analysis-dcf", written: false }
      ] },
      { title: "Live DCF", topics: [
        { title: "Revenue growth", id: "c-revenue-growth", cid: "c-revenue-growth", written: false },
        { title: "Margin", id: "c-margin", cid: "c-margin", written: false },
        { title: "WACC", id: "c-wacc-dcf-input", cid: "c-wacc-dcf-input", written: false },
        { title: "Terminal growth", id: "c-terminal-growth", cid: "c-terminal-growth", written: false },
        { title: "Enterprise Value", id: "c-enterprise-value-dcf-output", cid: "c-enterprise-value-dcf-output", written: false },
        { title: "Equity Value", id: "c-equity-value-dcf-output", cid: "c-equity-value-dcf-output", written: false },
        { title: "Share Price", id: "c-share-price", cid: "c-share-price", written: false }
      ] }
    ] },
    { level: 6, title: "Investment Banking", modules: [
      { title: "Transaction valuation", topics: [
        { title: "Comparable companies", id: "c-comparable-companies", cid: "c-comparable-companies", written: false },
        { title: "Precedent transactions", id: "c-precedent-transactions", cid: "c-precedent-transactions", written: false },
        { title: "Trading multiples", id: "c-trading-multiples", cid: "c-trading-multiples", written: false },
        { title: "Transaction multiples", id: "c-transaction-multiples", cid: "c-transaction-multiples", written: false }
      ] },
      { title: "M&A modeling", topics: [
        { title: "Accretion/dilution", id: "c-accretion-dilution", cid: "c-accretion-dilution", written: false },
        { title: "Merger models", id: "c-merger-models", cid: "c-merger-models", written: false },
        { title: "Sources & Uses", id: "c-sources-and-uses", cid: "c-sources-and-uses", written: false },
        { title: "Purchase price", id: "c-purchase-price", cid: "c-purchase-price", written: false },
        { title: "Financing mix", id: "c-financing-mix", cid: "c-financing-mix", written: false },
        { title: "Goodwill", id: "c-goodwill-acquisition", cid: "c-goodwill-acquisition", written: false },
        { title: "Synergies", id: "c-synergies", cid: "c-synergies", written: false },
        { title: "Pro forma financials", id: "c-pro-forma-financials", cid: "c-pro-forma-financials", written: false },
        { title: "Debt schedules", id: "c-debt-schedules", cid: "c-debt-schedules", written: false }
      ] },
      { title: "LBO basics", topics: [
        { title: "LBO basics", id: "c-lbo-basics", cid: "c-lbo-basics", written: false }
      ] }
    ] },
    { level: 7, title: "Private Equity / LBO", modules: [
      { title: "LBO construction", topics: [
        { title: "Entry valuation", id: "c-entry-valuation", cid: "c-entry-valuation", written: false },
        { title: "Debt financing", id: "c-debt-financing", cid: "c-debt-financing", written: false },
        { title: "Sources & Uses", id: "c-sources-and-uses-lbo", cid: "c-sources-and-uses-lbo", written: false },
        { title: "Operating case", id: "c-operating-case", cid: "c-operating-case", written: false },
        { title: "Debt paydown", id: "c-debt-paydown", cid: "c-debt-paydown", written: false },
        { title: "Exit valuation", id: "c-exit-valuation", cid: "c-exit-valuation", written: false },
        { title: "Exit multiple", id: "c-exit-multiple-lbo", cid: "c-exit-multiple-lbo", written: false },
        { title: "Sponsor equity", id: "c-sponsor-equity", cid: "c-sponsor-equity", written: false }
      ] },
      { title: "Sponsor returns", topics: [
        { title: "MOIC", id: "c-moic", cid: "c-moic", written: false },
        { title: "IRR", id: "c-irr", cid: "c-irr", written: false },
        { title: "Management options", id: "c-management-options", cid: "c-management-options", written: false },
        { title: "Sensitivity analysis", id: "c-sensitivity-analysis-lbo", cid: "c-sensitivity-analysis-lbo", written: false }
      ] }
    ] },
    { level: 8, title: "Equity Research & Investing", modules: [
      { title: "Business analysis", topics: [
        { title: "Business analysis", id: "c-business-analysis", cid: "c-business-analysis", written: false },
        { title: "Revenue drivers", id: "c-revenue-drivers", cid: "c-revenue-drivers", written: false },
        { title: "Unit economics", id: "c-unit-economics", cid: "c-unit-economics", written: false },
        { title: "Competitive advantage", id: "c-competitive-advantage", cid: "c-competitive-advantage", written: false },
        { title: "TAM / SAM / SOM", id: "c-tam-sam-som", cid: "c-tam-sam-som", written: false },
        { title: "Management analysis", id: "c-management-analysis", cid: "c-management-analysis", written: false },
        { title: "Earnings", id: "c-earnings", cid: "c-earnings", written: false },
        { title: "Guidance", id: "c-guidance", cid: "c-guidance", written: false }
      ] },
      { title: "Investment case", topics: [
        { title: "Free cash flow", id: "c-free-cash-flow-investment-case", cid: "c-free-cash-flow-investment-case", written: false },
        { title: "Valuation", id: "c-valuation", cid: "c-valuation", written: false },
        { title: "Investment thesis", id: "c-investment-thesis", cid: "c-investment-thesis", written: false },
        { title: "Catalysts", id: "c-catalysts", cid: "c-catalysts", written: false },
        { title: "Risks", id: "c-risks", cid: "c-risks", written: false },
        { title: "Bear case", id: "c-bear-case", cid: "c-bear-case", written: false },
        { title: "Base case", id: "c-base-case", cid: "c-base-case", written: false },
        { title: "Bull case", id: "c-bull-case", cid: "c-bull-case", written: false }
      ] },
      { title: "Interactive investment cases", topics: [
        { title: "Build interactive investment cases", id: "c-build-interactive-investment-cases", cid: "c-build-interactive-investment-cases", written: false }
      ] }
    ] },
    { level: 9, title: "Markets", modules: [
      { title: "Equities", topics: [
        { title: "Stocks", id: "c-stocks", cid: "c-stocks", written: false },
        { title: "Market capitalization", id: "c-market-capitalization-equities", cid: "c-market-capitalization-equities", written: false }
      ] },
      { title: "Fixed income", topics: [
        { title: "Bonds", id: "c-bonds", cid: "c-bonds", written: false },
        { title: "Yield", id: "c-yield", cid: "c-yield", written: false },
        { title: "Yield curves", id: "c-yield-curves", cid: "c-yield-curves", written: false },
        { title: "Duration", id: "c-duration", cid: "c-duration", written: false },
        { title: "Convexity", id: "c-convexity", cid: "c-convexity", written: false },
        { title: "Credit", id: "c-credit", cid: "c-credit", written: false }
      ] },
      { title: "Macro & currencies", topics: [
        { title: "Interest rates", id: "c-interest-rates", cid: "c-interest-rates", written: false },
        { title: "Central banks", id: "c-central-banks", cid: "c-central-banks", written: false },
        { title: "FX", id: "c-fx", cid: "c-fx", written: false },
        { title: "Commodities", id: "c-commodities", cid: "c-commodities", written: false }
      ] },
      { title: "Derivatives", topics: [
        { title: "Derivatives", id: "c-derivatives", cid: "c-derivatives", written: false },
        { title: "Options", id: "c-options", cid: "c-options", written: false },
        { title: "Futures", id: "c-futures", cid: "c-futures", written: false }
      ] },
      { title: "Market mechanics", topics: [
        { title: "Liquidity", id: "c-liquidity", cid: "c-liquidity", written: false },
        { title: "Volatility", id: "c-volatility", cid: "c-volatility", written: false }
      ] }
    ] },
    { level: 10, title: "Advanced Finance", modules: [
      { title: "Options & portfolio theory", topics: [
        { title: "Options pricing", id: "c-options-pricing", cid: "c-options-pricing", written: false },
        { title: "Black-Scholes intuition", id: "c-black-scholes-intuition", cid: "c-black-scholes-intuition", written: false },
        { title: "Greeks", id: "c-greeks", cid: "c-greeks", written: false },
        { title: "Portfolio theory", id: "c-portfolio-theory", cid: "c-portfolio-theory", written: false },
        { title: "CAPM", id: "c-capm-portfolio-theory", cid: "c-capm-portfolio-theory", written: false },
        { title: "Efficient frontier", id: "c-efficient-frontier", cid: "c-efficient-frontier", written: false },
        { title: "Sharpe ratio", id: "c-sharpe-ratio", cid: "c-sharpe-ratio", written: false },
        { title: "Beta", id: "c-beta-portfolio-theory", cid: "c-beta-portfolio-theory", written: false },
        { title: "Alpha", id: "c-alpha", cid: "c-alpha", written: false },
        { title: "Factor investing", id: "c-factor-investing", cid: "c-factor-investing", written: false }
      ] },
      { title: "Risk & simulation", topics: [
        { title: "Risk management", id: "c-risk-management", cid: "c-risk-management", written: false },
        { title: "VaR", id: "c-var", cid: "c-var", written: false },
        { title: "Scenario analysis", id: "c-scenario-analysis-risk", cid: "c-scenario-analysis-risk", written: false },
        { title: "Monte Carlo simulation", id: "c-monte-carlo-simulation", cid: "c-monte-carlo-simulation", written: false }
      ] },
      { title: "Corporate finance", topics: [
        { title: "Capital structure", id: "c-capital-structure", cid: "c-capital-structure", written: false },
        { title: "Cost of capital", id: "c-cost-of-capital", cid: "c-cost-of-capital", written: false }
      ] }
    ] }
  ];
})();
