/* Generated by scripts/build-legacy-lessons.ts — do not edit by hand.
   All 11 levels, 35 modules and 227 topics, for the left curriculum pane.
   "written: false" means the concept lesson is not authored yet; the pane
   shows the topic but does not link it, so no route can 404. */
(function () {
  "use strict";
  var LS = (window.LS = window.LS || {});
  LS.curriculumMap = [
    { level: 0, title: "Finance Foundations", modules: [
      { title: "Finance basics", topics: [
        { title: "What is finance?", id: "c-what-is-finance", written: true },
        { title: "Personal finance vs corporate finance vs investing", id: "c-personal-corporate-investing", written: true },
        { title: "Financial markets", id: "c-financial-markets", written: true },
        { title: "Companies and capital", id: "c-companies-and-capital", written: true },
        { title: "Revenue", id: "c-revenue", written: true },
        { title: "Costs", id: "c-costs", written: true },
        { title: "Profit", id: "c-profit", written: true },
        { title: "Cash", id: "c-cash", written: true },
        { title: "Assets", id: "c-assets", written: true },
        { title: "Liabilities", id: "c-liabilities", written: true },
        { title: "Equity", id: "c-equity", written: true },
        { title: "Debt", id: "c-debt", written: true },
        { title: "Interest", id: "c-interest", written: true },
        { title: "Risk", id: "c-risk", written: true },
        { title: "Return", id: "c-return", written: true }
      ] },
      { title: "Time value & decision making", topics: [
        { title: "Time value of money", id: "c-time-value-of-money", written: true },
        { title: "Compounding", id: "c-compounding", written: true },
        { title: "Inflation", id: "c-inflation", written: true },
        { title: "Present value", id: "c-present-value", written: true },
        { title: "Future value", id: "c-future-value", written: true },
        { title: "Opportunity cost", id: "c-opportunity-cost", written: true },
        { title: "Risk vs reward", id: "c-risk-vs-reward", written: true }
      ] }
    ] },
    { level: 1, title: "Accounting Foundations", modules: [
      { title: "Accounting mechanics", topics: [
        { title: "Accounting equation", id: "c-accounting-equation", written: true },
        { title: "Double-entry accounting", id: "c-double-entry-accounting", written: true },
        { title: "Debits and credits", id: "c-debits-and-credits", written: true },
        { title: "Chart of accounts", id: "c-chart-of-accounts", written: true },
        { title: "Accrual accounting", id: "c-accrual-accounting", written: true },
        { title: "Cash accounting", id: "c-cash-accounting", written: true },
        { title: "Revenue recognition", id: "c-revenue-recognition", written: true },
        { title: "Expenses", id: "c-expenses", written: true }
      ] },
      { title: "Working capital & operating assets", topics: [
        { title: "Accounts receivable", id: "c-accounts-receivable", written: true },
        { title: "Accounts payable", id: "c-accounts-payable", written: true },
        { title: "Inventory", id: "c-inventory", written: true },
        { title: "Prepaid expenses", id: "c-prepaid-expenses", written: true },
        { title: "Deferred revenue", id: "c-deferred-revenue", written: true },
        { title: "Accrued expenses", id: "c-accrued-expenses", written: true },
        { title: "Working capital", id: "c-working-capital", written: true }
      ] },
      { title: "Long-lived assets & equity", topics: [
        { title: "Depreciation", id: "c-depreciation", written: true },
        { title: "Amortization", id: "c-amortization", written: true },
        { title: "PP&E", id: "c-ppe", written: true },
        { title: "Goodwill", id: "c-goodwill", written: true },
        { title: "Intangible assets", id: "c-intangible-assets", written: true },
        { title: "Retained earnings", id: "c-retained-earnings", written: true }
      ] }
    ] },
    { level: 2, title: "Financial Statements", modules: [
      { title: "Income statement", topics: [
        { title: "Revenue", id: "c-revenue-line-item", written: false },
        { title: "COGS", id: "c-cogs", written: false },
        { title: "Gross profit", id: "c-gross-profit", written: false },
        { title: "Operating expenses", id: "c-operating-expenses", written: false },
        { title: "EBITDA", id: "c-ebitda", written: false },
        { title: "D&A", id: "c-d-a", written: false },
        { title: "EBIT", id: "c-ebit", written: false },
        { title: "Interest", id: "c-interest-expense", written: false },
        { title: "EBT", id: "c-ebt", written: false },
        { title: "Taxes", id: "c-taxes", written: false },
        { title: "Net income", id: "c-net-income", written: false }
      ] },
      { title: "Balance sheet", topics: [
        { title: "Cash", id: "c-cash-balance-sheet", written: false },
        { title: "Receivables", id: "c-receivables", written: false },
        { title: "Inventory", id: "c-inventory-balance-sheet", written: false },
        { title: "PP&E", id: "c-ppe-balance-sheet", written: false },
        { title: "Intangibles", id: "c-intangibles", written: false },
        { title: "Debt", id: "c-debt-balance-sheet", written: false },
        { title: "Payables", id: "c-payables", written: false },
        { title: "Other liabilities", id: "c-other-liabilities", written: false },
        { title: "Equity", id: "c-equity-balance-sheet", written: false }
      ] },
      { title: "Cash flow statement", topics: [
        { title: "CFO", id: "c-cfo", written: false },
        { title: "CFI", id: "c-cfi", written: false },
        { title: "CFF", id: "c-cff", written: false },
        { title: "Capex", id: "c-capex", written: false },
        { title: "Change in working capital", id: "c-change-in-working-capital", written: false },
        { title: "Debt issuance", id: "c-debt-issuance", written: false },
        { title: "Debt repayment", id: "c-debt-repayment", written: false },
        { title: "Dividends", id: "c-dividends", written: false },
        { title: "Stock issuance", id: "c-stock-issuance", written: false }
      ] },
      { title: "Three-statement connection", topics: [
        { title: "Three-statement connection", id: "c-three-statement-connection", written: false },
        { title: "Revenue cascade through the three statements", id: "c-revenue-cascade-through-the-three-statements", written: false },
        { title: "Profit to cash", id: "c-profit-to-cash", written: false },
        { title: "Balance sheet check", id: "c-balance-sheet-check", written: false }
      ] }
    ] },
    { level: 3, title: "Financial Analysis", modules: [
      { title: "Profitability & returns", topics: [
        { title: "Gross margin", id: "c-gross-margin", written: false },
        { title: "EBITDA margin", id: "c-ebitda-margin", written: false },
        { title: "EBIT margin", id: "c-ebit-margin", written: false },
        { title: "Net margin", id: "c-net-margin", written: false },
        { title: "ROE", id: "c-roe", written: false },
        { title: "ROA", id: "c-roa", written: false },
        { title: "ROIC", id: "c-roic", written: false },
        { title: "Asset turnover", id: "c-asset-turnover", written: false }
      ] },
      { title: "Liquidity & leverage", topics: [
        { title: "Current ratio", id: "c-current-ratio", written: false },
        { title: "Quick ratio", id: "c-quick-ratio", written: false },
        { title: "Debt/equity", id: "c-debt-equity", written: false },
        { title: "Net debt/EBITDA", id: "c-net-debt-ebitda", written: false },
        { title: "Interest coverage", id: "c-interest-coverage", written: false }
      ] },
      { title: "Cash & operating analysis", topics: [
        { title: "Free cash flow", id: "c-free-cash-flow", written: false },
        { title: "Working capital analysis", id: "c-working-capital-analysis", written: false },
        { title: "Cash conversion cycle", id: "c-cash-conversion-cycle", written: false },
        { title: "Operating leverage", id: "c-operating-leverage", written: false },
        { title: "Financial leverage", id: "c-financial-leverage", written: false }
      ] }
    ] },
    { level: 4, title: "Financial Modeling", modules: [
      { title: "Model architecture", topics: [
        { title: "Model architecture", id: "c-model-architecture", written: false },
        { title: "Assumptions", id: "c-assumptions", written: false },
        { title: "Historical periods", id: "c-historical-periods", written: false },
        { title: "Forecast periods", id: "c-forecast-periods", written: false },
        { title: "Drivers", id: "c-drivers", written: false },
        { title: "Model formatting", id: "c-model-formatting", written: false },
        { title: "Model best practices", id: "c-model-best-practices", written: false }
      ] },
      { title: "Operating schedules", topics: [
        { title: "Revenue build", id: "c-revenue-build", written: false },
        { title: "Cost build", id: "c-cost-build", written: false },
        { title: "Headcount model", id: "c-headcount-model", written: false },
        { title: "Working capital model", id: "c-working-capital-model", written: false },
        { title: "Capex model", id: "c-capex-model", written: false },
        { title: "Depreciation schedule", id: "c-depreciation-schedule", written: false },
        { title: "Debt schedule", id: "c-debt-schedule", written: false },
        { title: "Interest schedule", id: "c-interest-schedule", written: false },
        { title: "Tax schedule", id: "c-tax-schedule", written: false },
        { title: "Retained earnings", id: "c-retained-earnings-schedule", written: false }
      ] },
      { title: "Integrated modeling", topics: [
        { title: "Three-statement model", id: "c-three-statement-model", written: false },
        { title: "Scenario analysis", id: "c-scenario-analysis", written: false },
        { title: "Sensitivity analysis", id: "c-sensitivity-analysis", written: false },
        { title: "Model checks", id: "c-model-checks", written: false },
        { title: "Circularity", id: "c-circularity", written: false }
      ] },
      { title: "Build a real model", topics: [
        { title: "Revenue", id: "c-revenue-forecast", written: false },
        { title: "Gross Profit", id: "c-gross-profit-model", written: false },
        { title: "EBITDA", id: "c-ebitda-model", written: false },
        { title: "EBIT", id: "c-ebit-model", written: false },
        { title: "Net Income", id: "c-net-income-model", written: false },
        { title: "Cash Flow", id: "c-cash-flow", written: false },
        { title: "Balance Sheet", id: "c-balance-sheet", written: false }
      ] }
    ] },
    { level: 5, title: "Valuation", modules: [
      { title: "Valuation building blocks", topics: [
        { title: "Enterprise value", id: "c-enterprise-value", written: false },
        { title: "Equity value", id: "c-equity-value", written: false },
        { title: "Market capitalization", id: "c-market-capitalization", written: false },
        { title: "Net debt", id: "c-net-debt", written: false },
        { title: "EV/Revenue", id: "c-ev-revenue", written: false },
        { title: "EV/EBITDA", id: "c-ev-ebitda", written: false },
        { title: "P/E", id: "c-p-e", written: false },
        { title: "PEG", id: "c-peg", written: false }
      ] },
      { title: "DCF", topics: [
        { title: "DCF", id: "c-dcf", written: false },
        { title: "WACC", id: "c-wacc", written: false },
        { title: "Cost of equity", id: "c-cost-of-equity", written: false },
        { title: "Cost of debt", id: "c-cost-of-debt", written: false },
        { title: "CAPM", id: "c-capm", written: false },
        { title: "Beta", id: "c-beta", written: false },
        { title: "Risk-free rate", id: "c-risk-free-rate", written: false },
        { title: "Equity risk premium", id: "c-equity-risk-premium", written: false },
        { title: "Terminal value", id: "c-terminal-value", written: false },
        { title: "Perpetuity growth", id: "c-perpetuity-growth", written: false },
        { title: "Exit multiple", id: "c-exit-multiple", written: false },
        { title: "Discount factors", id: "c-discount-factors", written: false },
        { title: "Sensitivity analysis", id: "c-sensitivity-analysis-dcf", written: false }
      ] },
      { title: "Live DCF", topics: [
        { title: "Revenue growth", id: "c-revenue-growth", written: false },
        { title: "Margin", id: "c-margin", written: false },
        { title: "WACC", id: "c-wacc-dcf-input", written: false },
        { title: "Terminal growth", id: "c-terminal-growth", written: false },
        { title: "Enterprise Value", id: "c-enterprise-value-dcf-output", written: false },
        { title: "Equity Value", id: "c-equity-value-dcf-output", written: false },
        { title: "Share Price", id: "c-share-price", written: false }
      ] }
    ] },
    { level: 6, title: "Investment Banking", modules: [
      { title: "Transaction valuation", topics: [
        { title: "Comparable companies", id: "c-comparable-companies", written: false },
        { title: "Precedent transactions", id: "c-precedent-transactions", written: false },
        { title: "Trading multiples", id: "c-trading-multiples", written: false },
        { title: "Transaction multiples", id: "c-transaction-multiples", written: false }
      ] },
      { title: "M&A modeling", topics: [
        { title: "Accretion/dilution", id: "c-accretion-dilution", written: false },
        { title: "Merger models", id: "c-merger-models", written: false },
        { title: "Sources & Uses", id: "c-sources-and-uses", written: false },
        { title: "Purchase price", id: "c-purchase-price", written: false },
        { title: "Financing mix", id: "c-financing-mix", written: false },
        { title: "Goodwill", id: "c-goodwill-acquisition", written: false },
        { title: "Synergies", id: "c-synergies", written: false },
        { title: "Pro forma financials", id: "c-pro-forma-financials", written: false },
        { title: "Debt schedules", id: "c-debt-schedules", written: false }
      ] },
      { title: "LBO basics", topics: [
        { title: "LBO basics", id: "c-lbo-basics", written: false }
      ] }
    ] },
    { level: 7, title: "Private Equity / LBO", modules: [
      { title: "LBO construction", topics: [
        { title: "Entry valuation", id: "c-entry-valuation", written: false },
        { title: "Debt financing", id: "c-debt-financing", written: false },
        { title: "Sources & Uses", id: "c-sources-and-uses-lbo", written: false },
        { title: "Operating case", id: "c-operating-case", written: false },
        { title: "Debt paydown", id: "c-debt-paydown", written: false },
        { title: "Exit valuation", id: "c-exit-valuation", written: false },
        { title: "Exit multiple", id: "c-exit-multiple-lbo", written: false },
        { title: "Sponsor equity", id: "c-sponsor-equity", written: false }
      ] },
      { title: "Sponsor returns", topics: [
        { title: "MOIC", id: "c-moic", written: false },
        { title: "IRR", id: "c-irr", written: false },
        { title: "Management options", id: "c-management-options", written: false },
        { title: "Sensitivity analysis", id: "c-sensitivity-analysis-lbo", written: false }
      ] }
    ] },
    { level: 8, title: "Equity Research & Investing", modules: [
      { title: "Business analysis", topics: [
        { title: "Business analysis", id: "c-business-analysis", written: false },
        { title: "Revenue drivers", id: "c-revenue-drivers", written: false },
        { title: "Unit economics", id: "c-unit-economics", written: false },
        { title: "Competitive advantage", id: "c-competitive-advantage", written: false },
        { title: "TAM / SAM / SOM", id: "c-tam-sam-som", written: false },
        { title: "Management analysis", id: "c-management-analysis", written: false },
        { title: "Earnings", id: "c-earnings", written: false },
        { title: "Guidance", id: "c-guidance", written: false }
      ] },
      { title: "Investment case", topics: [
        { title: "Free cash flow", id: "c-free-cash-flow-investment-case", written: false },
        { title: "Valuation", id: "c-valuation", written: false },
        { title: "Investment thesis", id: "c-investment-thesis", written: false },
        { title: "Catalysts", id: "c-catalysts", written: false },
        { title: "Risks", id: "c-risks", written: false },
        { title: "Bear case", id: "c-bear-case", written: false },
        { title: "Base case", id: "c-base-case", written: false },
        { title: "Bull case", id: "c-bull-case", written: false }
      ] },
      { title: "Interactive investment cases", topics: [
        { title: "Build interactive investment cases", id: "c-build-interactive-investment-cases", written: false }
      ] }
    ] },
    { level: 9, title: "Markets", modules: [
      { title: "Equities", topics: [
        { title: "Stocks", id: "c-stocks", written: false },
        { title: "Market capitalization", id: "c-market-capitalization-equities", written: false }
      ] },
      { title: "Fixed income", topics: [
        { title: "Bonds", id: "c-bonds", written: false },
        { title: "Yield", id: "c-yield", written: false },
        { title: "Yield curves", id: "c-yield-curves", written: false },
        { title: "Duration", id: "c-duration", written: false },
        { title: "Convexity", id: "c-convexity", written: false },
        { title: "Credit", id: "c-credit", written: false }
      ] },
      { title: "Macro & currencies", topics: [
        { title: "Interest rates", id: "c-interest-rates", written: false },
        { title: "Central banks", id: "c-central-banks", written: false },
        { title: "FX", id: "c-fx", written: false },
        { title: "Commodities", id: "c-commodities", written: false }
      ] },
      { title: "Derivatives", topics: [
        { title: "Derivatives", id: "c-derivatives", written: false },
        { title: "Options", id: "c-options", written: false },
        { title: "Futures", id: "c-futures", written: false }
      ] },
      { title: "Market mechanics", topics: [
        { title: "Liquidity", id: "c-liquidity", written: false },
        { title: "Volatility", id: "c-volatility", written: false }
      ] }
    ] },
    { level: 10, title: "Advanced Finance", modules: [
      { title: "Options & portfolio theory", topics: [
        { title: "Options pricing", id: "c-options-pricing", written: false },
        { title: "Black-Scholes intuition", id: "c-black-scholes-intuition", written: false },
        { title: "Greeks", id: "c-greeks", written: false },
        { title: "Portfolio theory", id: "c-portfolio-theory", written: false },
        { title: "CAPM", id: "c-capm-portfolio-theory", written: false },
        { title: "Efficient frontier", id: "c-efficient-frontier", written: false },
        { title: "Sharpe ratio", id: "c-sharpe-ratio", written: false },
        { title: "Beta", id: "c-beta-portfolio-theory", written: false },
        { title: "Alpha", id: "c-alpha", written: false },
        { title: "Factor investing", id: "c-factor-investing", written: false }
      ] },
      { title: "Risk & simulation", topics: [
        { title: "Risk management", id: "c-risk-management", written: false },
        { title: "VaR", id: "c-var", written: false },
        { title: "Scenario analysis", id: "c-scenario-analysis-risk", written: false },
        { title: "Monte Carlo simulation", id: "c-monte-carlo-simulation", written: false }
      ] },
      { title: "Corporate finance", topics: [
        { title: "Capital structure", id: "c-capital-structure", written: false },
        { title: "Cost of capital", id: "c-cost-of-capital", written: false }
      ] }
    ] }
  ];
})();
