const terms = [
  ["EBITDA", "Earnings before interest, tax, depreciation and amortisation.", "EBIT + D&A"],
  ["Working capital", "The short-term operating capital tied up in the business.", "Current assets − current liabilities"],
  ["Enterprise value", "The value of the operating business available to all capital providers.", "Equity value + net debt"],
  ["Free cash flow", "Cash generated by operations after reinvestment required to run the business.", "NOPAT + D&A − CapEx − ΔNWC"],
  ["ROIC", "A measure of how efficiently a company generates operating returns on invested capital.", "NOPAT ÷ invested capital"],
  ["Terminal value", "The value assigned to cash flows beyond the explicit forecast period in a DCF.", "Usually calculated with a perpetuity-growth or exit-multiple method"],
];

export function GlossaryPage() {
  return <div className="mx-auto max-w-4xl px-5 py-12 sm:px-8"><header><p className="text-sm font-semibold uppercase tracking-widest text-green">Reference</p><h1 className="mt-3 font-display text-5xl font-semibold">Finance glossary</h1><p className="mt-4 text-lg text-ink-soft">Plain-English definitions for the terms that show up throughout FinStudio.</p></header><div className="mt-10 space-y-3">{terms.map(([term, definition, formula]) => <article key={term} className="rounded-lg border border-line bg-paper-2 p-5"><h2 className="font-display text-2xl font-semibold">{term}</h2><p className="mt-2 text-ink-soft">{definition}</p><p className="mt-3 rounded bg-paper-3 px-3 py-2 font-mono text-sm">{formula}</p></article>)}</div></div>;
}
