/* FinStudio investment cases: interactive, judgement-first practice. */
(function(){
  "use strict";
  var LS=window.LS=window.LS||{};
  var cases=[
    {id:"consumer-growth",title:"Consumer growth case",industry:"Consumer",thesis:"A fast-growing consumer business is reinvesting heavily today to build a durable distribution advantage.",base:{growth:15,margin:18,multiple:16},bull:{growth:22,margin:22,multiple:20},bear:{growth:7,margin:13,multiple:12},catalysts:["New distribution capacity","Gross-margin expansion","Faster store productivity"],risks:["Growth normalisation","Input-cost inflation","Execution risk"]},
    {id:"industrial-cycle",title:"Industrial cycle case",industry:"Industrials",thesis:"A cyclical industrial company is approaching a capacity and margin inflection, but the market is pricing a strong cycle already.",base:{growth:10,margin:16,multiple:12},bull:{growth:18,margin:20,multiple:15},bear:{growth:2,margin:10,multiple:9},catalysts:["Capacity ramp","Order-book conversion","Operating leverage"],risks:["Cycle reversal","Commodity costs","Customer concentration"]},
    {id:"saas-quality",title:"SaaS quality case",industry:"Technology",thesis:"A software company can trade at a premium if durable growth and improving margins compound into strong free cash flow.",base:{growth:18,margin:20,multiple:22},bull:{growth:25,margin:28,multiple:28},bear:{growth:10,margin:12,multiple:16},catalysts:["Net retention improvement","Sales efficiency","FCF inflection"],risks:["Growth deceleration","Competition","Customer churn"]}
  ];
  LS.investmentCases=cases;
  function esc(s){return String(s).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/\"/g,"&quot;");}
  function render(c){
    var main=document.getElementById("main");if(!main)return;
    main.innerHTML='<div class="page case-page"><p class="lesson-kicker">INVESTMENT CASE · '+esc(c.industry)+'</p><h1>'+esc(c.title)+'</h1><p class="lesson-lede">'+esc(c.thesis)+'</p><section class="case-grid"><article><h2>Investment thesis</h2><p>'+esc(c.thesis)+'</p><h2>Catalysts</h2><ul>'+c.catalysts.map(function(x){return '<li>'+esc(x)+'</li>';}).join('')+'</ul><h2>Risks</h2><ul>'+c.risks.map(function(x){return '<li>'+esc(x)+'</li>';}).join('')+'</ul></article><article class="case-sandbox"><p class="lesson-kicker">BUILD YOUR VIEW</p><h2>Bear · Base · Bull sandbox</h2><p>Change growth, margin and exit multiple. The goal is to defend a valuation range, not find one perfect answer.</p><div class="case-inputs">'+['bear','base','bull'].map(function(k){return '<div class="case-scenario"><h3>'+k.toUpperCase()+'</h3><label>Growth %<input data-case="'+k+'" data-key="growth" type="number" value="'+c[k].growth+'"></label><label>Margin %<input data-case="'+k+'" data-key="margin" type="number" value="'+c[k].margin+'"></label><label>Exit multiple<input data-case="'+k+'" data-key="multiple" type="number" value="'+c[k].multiple+'"></label><strong class="case-value" data-value="'+k+'"></strong></div>';}).join('')+'</div><div class="case-verdict"><span>Probability-weighted view</span><strong id="caseResult"></strong></div></article></section><section class="case-challenge"><h2>Your challenge</h2><p>Pick probabilities for bear, base and bull. State one catalyst that would make you raise your valuation and one risk that would make you cut it. A good investment thesis explains what would prove it wrong.</p></section></div>';
    function update(){var vals={};['bear','base','bull'].forEach(function(k){vals[k]={};main.querySelectorAll('[data-case="'+k+'"]').forEach(function(el){vals[k][el.dataset.key]=Number(el.value)||0;});var score=vals[k].growth*vals[k].margin*vals[k].multiple/100;main.querySelector('[data-value="'+k+'"]').textContent=score.toFixed(1)+' score';});var weighted=vals.bear.growth*vals.bear.margin*vals.bear.multiple*.25/100+vals.base.growth*vals.base.margin*vals.base.multiple*.5/100+vals.bull.growth*vals.bull.margin*vals.bull.multiple*.25/100;main.querySelector('#caseResult').textContent=weighted.toFixed(1);}
    main.querySelectorAll('input').forEach(function(el){el.addEventListener('input',update);});update();
  }
  function sync(){var h=location.hash.replace(/^#\/?/,"");if(h.indexOf('cases/')===0){var c=cases.find(function(x){return x.id===h.slice(6);});if(c)render(c);}}
  window.addEventListener('hashchange',sync);window.addEventListener('load',sync);sync();
})();
