import { Link } from "react-router-dom";
import { allTopics, curriculum, topicSlug } from "@/data/masterCurriculum";

export function CurriculumPage() {
  return <div className="mx-auto max-w-6xl px-5 py-12 sm:px-8">
    <header className="max-w-4xl"><p className="text-sm font-semibold uppercase tracking-widest text-green">Curriculum · Levels 0–10</p><h1 className="mt-3 font-display text-5xl font-semibold tracking-tight sm:text-6xl">Learn finance by building it.</h1><p className="mt-5 text-lg text-ink-soft">Every topic follows the practice-first loop: Learn → See → Try → Practice → Build → Check → Apply → Master.</p><div className="mt-5 flex flex-wrap gap-3 text-sm"><span className="rounded-full border border-line bg-paper-2 px-3 py-1">{curriculum.length} levels</span><span className="rounded-full border border-line bg-paper-2 px-3 py-1">{curriculum.reduce((n,l)=>n+l.modules.length,0)} modules</span><span className="rounded-full border border-line bg-paper-2 px-3 py-1">{allTopics.length} topics</span></div></header>
    <div className="mt-12 space-y-10">{curriculum.map(level=><section key={level.level} id={`level-${level.level}`} className="scroll-mt-24"><div className="flex items-end justify-between gap-4 border-b border-line pb-3"><div><p className="font-mono text-xs text-ink-faint">LEVEL {level.level}</p><h2 className="mt-1 font-display text-3xl font-semibold">{level.title}</h2></div><span className="hidden text-sm text-ink-soft sm:block">{level.modules.reduce((n,m)=>n+m.topics.length,0)} topics</span></div><p className="mt-3 max-w-3xl text-sm text-ink-soft">{level.blurb}</p><div className="mt-5 grid gap-4 md:grid-cols-2">{level.modules.map(m=><article key={m.title} className="rounded-lg border border-line bg-paper-2 p-5 shadow-sm"><div className="flex items-start justify-between gap-4"><h3 className="font-display text-xl font-semibold">{m.title}</h3><span className="font-mono text-xs text-ink-faint">{m.topics.length}</span></div><div className="mt-4 grid gap-1 sm:grid-cols-2">{m.topics.map(topic=><Link key={topic} to={`/topic/${topicSlug(topic)}`} className="rounded px-2 py-1.5 text-sm text-ink-soft no-underline hover:bg-paper-3 hover:text-green">{topic} <span aria-hidden="true">→</span></Link>)}</div></article>)}</div></section>)}</div>
  </div>;
}
