import { Link } from "react-router-dom";
import { curriculum } from "@/data/masterCurriculum";

type Track = { title: string; description: string; href: string };
const tracks: Track[] = [
  { title: "Accounting", description: "Build the statements from first principles.", href: "/level/1" },
  { title: "Financial Modeling", description: "Link assumptions, statements and forecasts.", href: "/level/4" },
  { title: "Valuation", description: "Turn operating forecasts into enterprise value.", href: "/level/5" },
  { title: "Markets", description: "Understand stocks, bonds, rates and derivatives.", href: "/level/9" },
];
const learningLoop = ["Learn", "See", "Try", "Practice", "Build", "Check", "Apply", "Master"];
export function HomePage() { return <>
  <section className="border-b border-line bg-paper-2"><div className="mx-auto grid max-w-7xl gap-12 px-5 py-16 sm:px-8 lg:grid-cols-[1.05fr_.95fr] lg:items-center lg:py-24"><div><p className="font-mono text-sm font-semibold uppercase tracking-[.18em] text-green">FINANCE, BUILT NOT WATCHED</p><h1 className="mt-5 max-w-3xl font-display text-5xl font-semibold leading-[1.04] tracking-tight sm:text-7xl">Learn finance by actually doing finance.</h1><p className="mt-6 max-w-2xl text-xl leading-relaxed text-ink-soft sm:text-2xl">Understand concepts. Practice the mechanics. Build financial models. Get immediate feedback on every number and formula.</p><div className="mt-8 flex flex-wrap gap-3"><Link className="btn-primary px-5 py-3 text-base" to="/curriculum">Start learning</Link><Link className="rounded-md border border-line bg-paper px-5 py-3 text-base font-semibold no-underline hover:bg-paper-3" to="/formulas">Explore formulas</Link></div><div className="mt-7 flex flex-wrap gap-x-6 gap-y-2 text-base text-ink-faint"><span>Levels 0–10</span><span>Interactive topics</span><span>Practice-first</span><span>No sign-up</span></div></div><div className="rounded-xl border border-line bg-paper p-6 shadow-sm sm:p-8"><p className="font-mono text-sm text-ink-faint">A TYPICAL LESSON</p><h2 className="mt-2 font-display text-3xl font-semibold">Concept → Sandbox → Practice</h2><div className="mt-6 space-y-3 text-lg"><div className="rounded-lg border border-line bg-paper-2 p-4"><strong>1. Learn</strong><p className="mt-1 text-base text-ink-soft">Understand what the number means and why it matters.</p></div><div className="rounded-lg border border-line bg-paper-2 p-4"><strong>2. See & Try</strong><p className="mt-1 text-base text-ink-soft">Change assumptions and watch the financial output move.</p></div><div className="rounded-lg border border-line bg-paper-2 p-4"><strong>3. Practice & Apply</strong><p className="mt-1 text-base text-ink-soft">Solve a problem, check your work and use it in a mini-case.</p></div></div></div></div></section>
  <section className="mx-auto max-w-7xl px-5 py-16 sm:px-8"><div className="grid gap-8 lg:grid-cols-[.8fr_1.2fr]"><div><p className="text-base font-semibold uppercase tracking-widest text-green">The FinStudio loop</p><h2 className="mt-3 font-display text-4xl font-semibold">Learn → See → Try → Practice → Build → Check → Apply → Master</h2><p className="mt-5 text-lg leading-8 text-ink-soft">Every topic follows the same learning architecture. You learn the concept, use it, test it and carry it into a real finance workflow.</p></div><div className="grid gap-3 sm:grid-cols-2">{learningLoop.map((title,i)=><div key={title} className="rounded-lg border border-line bg-paper-2 p-5"><span className="font-mono text-sm text-green">{String(i+1).padStart(2,"0")}</span><h3 className="mt-3 font-display text-2xl font-semibold">{title}</h3><p className="mt-1 text-base text-ink-soft">{i===0?"Build the mental model.":i===1?"Watch a worked example.":i===2?"Make the first decision.":i===3?"Reinforce with exercises.":i===4?"Use a live sandbox.":i===5?"Get immediate feedback.":i===6?"Solve a real-world case.":"Prove you can use it."}</p></div>)}</div></div></section>
  <section className="border-y border-line bg-paper-2"><div className="mx-auto max-w-7xl px-5 py-16 sm:px-8"><p className="text-base font-semibold uppercase tracking-widest text-green">Choose your starting point</p><p className="mt-2 text-lg text-ink-soft">Start at Level 0 if you are new. Move forward only when the mechanics feel natural.</p><div className="mt-6 grid gap-4 md:grid-cols-2 lg:grid-cols-4">{tracks.map(track=><Link key={track.title} to={track.href} className="group rounded-lg border border-line bg-paper p-6 no-underline hover:border-green"><h3 className="font-display text-2xl font-semibold group-hover:text-green">{track.title}</h3><p className="mt-2 text-base leading-7 text-ink-soft">{track.description}</p><span className="mt-5 block text-base font-semibold text-green">Explore →</span></Link>)}</div><div className="mt-10 rounded-xl border border-line bg-paper p-6"><p className="text-base font-semibold text-green">Complete path</p><div className="mt-4 flex flex-wrap gap-2">{curriculum.map(l=><Link key={l.level} to={`/level/${l.level}`} className="rounded-full border border-line px-4 py-2 text-base font-medium no-underline hover:border-green">L{l.level} · {l.title}</Link>)}</div></div></div></section>
</>; }
