import { Link, useParams } from "react-router-dom";
import { allTopics, topicBySlug, topicRouteSlug } from "@/data/masterCurriculum";
import { getLessonContent } from "@/data/lessonContent";
import { completeLessonContent } from "@/data/lessonCompletion";
import { getTopicLearning } from "@/data/topicLearning";
import { useMemo, useState } from "react";

export function TopicPage() {
  const { topicSlug } = useParams();
  const topic = topicBySlug(topicSlug ?? "");
  const [values, setValues] = useState([100, 10, 5]);
  const [selected, setSelected] = useState<Record<number, number>>({});
  const [submitted, setSubmitted] = useState(false);
  const index = topic ? allTopics.findIndex((x) => x.slug === topic.slug) : -1;
  const previous = index > 0 ? allTopics[index - 1] : undefined;
  const next = index >= 0 ? allTopics[index + 1] : undefined;
  const result = useMemo(() => (values[0] ?? 0) * (1 + (values[1] ?? 0) / 100 + (values[2] ?? 0) / 100), [values]);
  if (!topic) return <div className="mx-auto max-w-5xl px-5 py-20"><h1 className="font-display text-4xl font-semibold">Topic not found</h1><p className="mt-3 text-lg text-ink-soft">This topic is not in the FinStudio curriculum.</p><Link className="mt-6 inline-block text-lg font-semibold text-green" to="/curriculum">Back to curriculum →</Link></div>;
  const lesson = completeLessonContent(topic.topic, getLessonContent(topic.topic, topic.module, topic.level));
  const learning = getTopicLearning(topic.topic, topic.module, topic.level);
  const steps = ["Learn", "See", "Try", "Practice", "Build", "Check", "Apply", "Master"];
  const score = submitted ? learning.questions.reduce((n, q, i) => n + (selected[i] === q.answer ? 1 : 0), 0) : 0;
  return <article className="mx-auto max-w-5xl px-5 py-12 sm:px-8 sm:py-16">
    <div className="flex flex-wrap items-center gap-x-3 gap-y-1 text-base"><Link to="/curriculum" className="font-semibold text-green no-underline">Curriculum</Link><span aria-hidden="true">→</span><Link to={`/level/${topic.level}`} className="font-semibold text-green no-underline">Level {topic.level}</Link><span aria-hidden="true">→</span><span className="text-ink-soft">{topic.module}</span><span aria-hidden="true">→</span><strong>{topic.topic}</strong></div>
    <p className="mt-8 font-mono text-sm font-semibold uppercase tracking-widest text-green">LEVEL {topic.level} · {topic.module}</p>
    <div className="mt-4 flex flex-wrap gap-2" aria-label="Lesson stages">{steps.map((s, i) => <span key={s} className={`rounded-full border px-3.5 py-2 text-base ${i === 0 ? "border-green bg-green-soft text-green" : "border-line text-ink-faint"}`}>{String(i + 1).padStart(2,"0")} {s}</span>)}</div>
    <h1 className="mt-8 font-display text-5xl font-semibold leading-tight tracking-tight sm:text-7xl">{topic.topic}</h1>
    <p className="mt-6 max-w-4xl text-xl leading-9 text-ink-soft sm:text-2xl sm:leading-10">{lesson.concept}</p>
    <div className="mt-6 grid gap-4 sm:grid-cols-3"><div className="rounded-xl border border-line bg-paper-2 p-5"><p className="text-sm font-semibold uppercase tracking-wider text-ink-faint">Objectives</p><p className="mt-2 text-lg font-semibold">{learning.objectives.length} outcomes</p></div><div className="rounded-xl border border-line bg-paper-2 p-5"><p className="text-sm font-semibold uppercase tracking-wider text-ink-faint">Practice</p><p className="mt-2 text-lg font-semibold">{learning.practice.length} exercises</p></div><div className="rounded-xl border border-line bg-paper-2 p-5"><p className="text-sm font-semibold uppercase tracking-wider text-ink-faint">Check</p><p className="mt-2 text-lg font-semibold">{learning.questions.length} questions</p></div></div>

    <section className="mt-10 rounded-2xl border border-line bg-paper-2 p-7 sm:p-10"><p className="font-mono text-sm font-semibold tracking-widest text-green">LEARNING OBJECTIVES</p><ul className="mt-5 grid gap-3 sm:grid-cols-2">{learning.objectives.map(x=><li key={x} className="rounded-xl border border-line bg-paper p-4 text-lg leading-8">✓ {x}</li>)}</ul><p className="mt-7 text-lg text-ink-soft"><strong>Prerequisites:</strong> {learning.prerequisites.length ? learning.prerequisites.join(" · ") : "None — start here."}</p><p className="mt-3 text-lg text-ink-soft"><strong>Key terms:</strong> {learning.keyTerms.join(" · ")}</p></section>

    <section className="mt-6 rounded-2xl border border-line bg-paper p-7 sm:p-10"><p className="font-mono text-sm font-semibold tracking-widest text-green">01 · LEARN</p><h2 className="mt-2 font-display text-3xl font-semibold sm:text-4xl">The idea, from first principles</h2><p className="mt-5 text-lg leading-9 text-ink-soft sm:text-xl sm:leading-9">{lesson.why}</p><div className="mt-7 space-y-4">{learning.mechanics.map((m,i)=><div key={m} className="flex gap-4 rounded-xl border border-line bg-paper-2 p-5"><span className="font-mono text-sm font-semibold text-green">{String(i+1).padStart(2,"0")}</span><p className="text-lg leading-8">{m}</p></div>)}</div></section>

    <section className="mt-6 rounded-2xl border border-line bg-ink p-7 text-paper sm:p-10"><p className="font-mono text-sm font-semibold tracking-widest text-green">02 · FORMULA / MECHANICS</p><h2 className="mt-2 font-display text-3xl font-semibold sm:text-4xl">How the numbers connect</h2><pre className="mt-5 overflow-x-auto whitespace-pre-wrap rounded-xl border border-white/15 bg-white/5 px-5 py-5 font-mono text-lg leading-8 text-paper sm:text-xl">{learning.formula}</pre></section>

    <section className="mt-6 rounded-2xl border border-line bg-paper p-7 shadow-sm sm:p-10"><p className="font-mono text-sm font-semibold tracking-widest text-green">03 · SEE</p><h2 className="mt-2 font-display text-3xl font-semibold sm:text-4xl">Worked example</h2><p className="mt-5 text-lg leading-9 text-ink-soft sm:text-xl sm:leading-9">{learning.workedExample}</p></section>

    <section className="mt-6 rounded-2xl border border-line bg-paper-2 p-7 sm:p-10"><p className="font-mono text-sm font-semibold tracking-widest text-green">04 · TRY</p><h2 className="mt-2 font-display text-3xl font-semibold sm:text-4xl">Predict before you calculate</h2><p className="mt-4 text-lg leading-8 text-ink-soft">{learning.tryPrompt}</p><div className="mt-7 grid gap-5 sm:grid-cols-3">{["Starting value","Driver A (%)","Driver B (%)"].map((label,i)=><label key={label} className="block text-lg font-semibold">{label}<input aria-label={label} className="mt-2 w-full rounded-lg border border-line bg-paper px-4 py-3.5 text-xl font-mono focus:border-green" type="number" step="any" value={values[i] ?? 0} onChange={(e)=>setValues(v=>v.map((x,j)=>j===i?(Number.isFinite(e.target.valueAsNumber)?e.target.valueAsNumber:0):x))} /></label>)}</div><div className="mt-8 flex flex-wrap items-center justify-between gap-4 rounded-xl bg-paper p-6"><span className="text-lg text-ink-soft">Live illustrative result</span><strong className="font-mono text-4xl">{result.toFixed(2)}</strong></div></section>

    <section className="mt-6 rounded-2xl border border-line bg-paper p-7 sm:p-10"><p className="font-mono text-sm font-semibold tracking-widest text-green">05 · PRACTICE</p><h2 className="mt-2 font-display text-3xl font-semibold sm:text-4xl">Practice the idea</h2><div className="mt-6 space-y-4">{learning.practice.map((p,i)=><div key={p} className="rounded-xl border border-line bg-paper-2 p-5"><span className="font-mono text-sm font-semibold text-green">Exercise {i+1}</span><p className="mt-2 text-lg leading-8">{p}</p></div>)}</div></section>

    <section className="mt-6 rounded-2xl border border-line bg-paper p-7 sm:p-10"><p className="font-mono text-sm font-semibold tracking-widest text-green">06 · BUILD</p><h2 className="mt-2 font-display text-3xl font-semibold sm:text-4xl">Sandbox</h2><p className="mt-4 text-lg leading-8 text-ink-soft">{learning.sandbox.prompt}</p><div className="mt-6 rounded-xl border border-line bg-paper-2 p-5"><p className="text-sm font-semibold uppercase tracking-wider text-ink-faint">Sandbox type</p><p className="mt-1 text-xl font-semibold">{learning.sandbox.type}</p><p className="mt-2 text-lg text-ink-soft">Change the inputs above, make a prediction, then explain the result in words. This turns the formula into a decision model rather than a static answer.</p></div></section>

    <section className="mt-6 rounded-2xl border border-line bg-paper-2 p-7 sm:p-10"><p className="font-mono text-sm font-semibold tracking-widest text-green">07 · CHECK</p><h2 className="mt-2 font-display text-3xl font-semibold sm:text-4xl">Check your understanding</h2><div className="mt-7 space-y-6">{learning.questions.map((q,i)=><fieldset key={q.prompt} className="rounded-xl border border-line bg-paper p-5"><legend className="px-2 text-lg font-semibold leading-8">{i+1}. {q.prompt}</legend><div className="mt-3 grid gap-2">{q.choices.map((choice,j)=><label key={choice} className="flex cursor-pointer items-start gap-3 rounded-lg border border-line p-3 text-lg hover:bg-paper-2"><input type="radio" name={`q-${i}`} checked={selected[i]===j} onChange={()=>setSelected(s=>({...s,[i]:j}))} className="mt-1.5" />{choice}</label>)}</div>{submitted && <p className={`mt-4 text-lg leading-8 ${selected[i]===q.answer?"text-green":"text-red"}`}><strong>{selected[i]===q.answer?"Correct":"Review"}.</strong> {q.explanation}</p>}</fieldset>)}</div><button type="button" className="btn-primary mt-7 px-6 py-3.5 text-lg" onClick={()=>setSubmitted(true)}>Check answers</button>{submitted && <p className="mt-4 text-lg font-semibold">Score: {score} / {learning.questions.length}</p>}</section>

    <section className="mt-6 grid gap-6 md:grid-cols-2"><article className="rounded-2xl border border-line bg-paper p-7 sm:p-9"><p className="font-mono text-sm font-semibold tracking-widest text-green">08 · APPLY</p><h2 className="mt-2 font-display text-3xl font-semibold">Real-world case</h2><p className="mt-4 text-lg leading-8 text-ink-soft">{learning.caseStudy}</p><p className="mt-5 text-lg leading-8"><strong>Professional perspective:</strong> {learning.professional}</p></article><article className="rounded-2xl border border-line bg-paper p-7 sm:p-9"><p className="font-mono text-sm font-semibold tracking-widest text-red">COMMON MISTAKES</p><ul className="mt-5 space-y-3">{learning.mistakes.map(m=><li key={m} className="rounded-lg border border-line p-4 text-lg leading-8">{m}</li>)}</ul></article></section>

    <section className="mt-6 rounded-2xl border border-line bg-paper p-7 sm:p-10"><p className="font-mono text-sm font-semibold tracking-widest text-green">MASTER</p><h2 className="mt-2 font-display text-3xl font-semibold sm:text-4xl">Challenge & interview readiness</h2><p className="mt-4 text-lg leading-8">{learning.challenge}</p><div className="mt-6 grid gap-3">{learning.interview.map(q=><div key={q} className="rounded-xl border border-line bg-paper-2 p-4 text-lg">{q}</div>)}</div><div className="mt-6 border-t border-line pt-5"><h3 className="font-display text-2xl font-semibold">Key takeaways</h3><ul className="mt-4 space-y-2">{learning.summary.map(x=><li key={x} className="text-lg leading-8">• {x}</li>)}</ul></div></section>

    <section className="mt-8 flex flex-col gap-5 border-t border-line pt-7 sm:flex-row sm:items-center sm:justify-between"><div>{previous && <Link className="text-lg font-semibold text-green no-underline" to={`/topic/${topicRouteSlug(previous)}`}>← Previous: {previous.topic}</Link>}</div><div className="text-right">{next && <Link className="btn-primary inline-flex px-5 py-3.5 text-lg" to={`/topic/${topicRouteSlug(next)}`}>Next: {next.topic} →</Link>}</div></section>
  </article>;
}
