import { Link, useParams } from "react-router-dom";
import { allTopics, topicBySlug, topicRouteSlug } from "@/data/masterCurriculum";
import { getLessonContent } from "@/data/lessonContent";
import { completeLessonContent } from "@/data/lessonCompletion";
import { getTopicLearning } from "@/data/topicLearning";
import { markTopicComplete, topicIsComplete } from "@/data/progress";
import { useEffect, useMemo, useState } from "react";

const steps = ["Learn", "See", "Try", "Practice", "Build", "Check", "Apply", "Master"];
type PracticeState = { answer: string; revealed: boolean; checked: boolean };

export function TopicPage() {
  const { topicSlug } = useParams();
  const topic = topicBySlug(topicSlug ?? "");
  const [values, setValues] = useState([100, 10, 5]);
  const [selected, setSelected] = useState<Record<number, number>>({});
  const [answered, setAnswered] = useState<Record<number, boolean>>({});
  const [practice, setPractice] = useState<Record<number, PracticeState>>({});
  const [complete, setComplete] = useState(() => topic ? topicIsComplete(topic.slug) : false);
  useEffect(() => { setComplete(topic ? topicIsComplete(topic.slug) : false); }, [topic?.slug]);

  const index = topic ? allTopics.findIndex(x => x.slug === topic.slug) : -1;
  const previous = index > 0 ? allTopics[index - 1] : undefined;
  const next = index >= 0 ? allTopics[index + 1] : undefined;
  const lesson = topic ? completeLessonContent(topic.topic, getLessonContent(topic.topic, topic.module, topic.level)) : null;
  const learning = topic ? getTopicLearning(topic.topic, topic.module, topic.level) : null;
  const result = useMemo(() => (values[0] ?? 0) * (1 + (values[1] ?? 0) / 100 + (values[2] ?? 0) / 100), [values]);
  if (!topic || !lesson || !learning) return <div className="mx-auto max-w-5xl px-5 py-20"><h1 className="font-display text-4xl font-semibold">Topic not found</h1><p className="mt-3 text-lg text-ink-soft">This topic is not in the FinStudio curriculum.</p><Link className="mt-6 inline-block text-lg font-semibold text-green" to="/curriculum">Back to curriculum →</Link></div>;

  const score = Object.entries(answered).reduce((n,[i,isAnswered]) => n + (isAnswered && selected[Number(i)] === learning.questions[Number(i)]?.answer ? 1 : 0), 0);
  const answeredCount = Object.keys(answered).length;
  const updatePractice = (i:number, patch:Partial<PracticeState>) => setPractice(current => ({...current,[i]:{answer:current[i]?.answer??"",revealed:current[i]?.revealed??false,checked:current[i]?.checked??false,...patch}}));
  const completeNow = () => { markTopicComplete(topic.slug); setComplete(true); };

  return <article className="topic-page">
    <div className="topic-header-axis">
      <div className="flex flex-wrap items-center gap-x-3 gap-y-1 text-base" aria-label="Breadcrumb"><Link to="/curriculum" className="font-semibold text-green no-underline">Curriculum</Link><span aria-hidden="true">→</span><Link to={`/level/${topic.level}`} className="font-semibold text-green no-underline">Level {topic.level}</Link><span aria-hidden="true">→</span><span className="text-ink-soft">{topic.module}</span><span aria-hidden="true">→</span><strong>{topic.topic}</strong></div>
      <p className="mt-8 font-mono text-sm font-semibold uppercase tracking-widest text-green">LEVEL {topic.level} · {topic.module}</p>
      <div className="mt-4 flex flex-wrap gap-2" aria-label="Lesson stages">{steps.map((s,i)=><span key={s} className={`rounded-full border px-3.5 py-2 text-base ${i===0?"border-green bg-green-soft text-green":"border-line text-ink-faint"}`}>{String(i+1).padStart(2,"0")} {s}</span>)}</div>
      <h1 className="mt-8 font-display text-5xl font-semibold leading-tight tracking-tight sm:text-7xl">{topic.topic}</h1>
      <p className="topic-copy mt-6 text-xl leading-9 text-ink-soft sm:text-2xl sm:leading-10">{lesson.concept}</p>
      <div className="mt-6 grid gap-4 sm:grid-cols-4"><div className="rounded-xl border border-line bg-paper-2 p-5"><p className="text-sm font-semibold uppercase tracking-wider text-ink-faint">Objectives</p><p className="mt-2 text-lg font-semibold">{learning.objectives.length} outcomes</p></div><div className="rounded-xl border border-line bg-paper-2 p-5"><p className="text-sm font-semibold uppercase tracking-wider text-ink-faint">Practice</p><p className="mt-2 text-lg font-semibold">{learning.practice.length} exercises</p></div><div className="rounded-xl border border-line bg-paper-2 p-5"><p className="text-sm font-semibold uppercase tracking-wider text-ink-faint">Check</p><p className="mt-2 text-lg font-semibold">{learning.questions.length} questions</p></div><div className={`rounded-xl border p-5 ${complete?"border-green bg-green-soft":"border-line bg-paper-2"}`}><p className="text-sm font-semibold uppercase tracking-wider text-ink-faint">Progress</p><p className="mt-2 text-lg font-semibold">{complete?"✓ Complete":"In progress"}</p></div></div>
    </div>

    <section className="topic-section bg-paper-2"><p className="font-mono text-sm font-semibold tracking-widest text-green">LEARNING OBJECTIVES</p><ul className="mt-5 grid gap-3 sm:grid-cols-2">{learning.objectives.map(x=><li key={x} className="rounded-xl border border-line bg-paper p-4 text-lg leading-8">✓ {x}</li>)}</ul><p className="mt-7 text-lg text-ink-soft"><strong>Prerequisites:</strong> {learning.prerequisites.length?learning.prerequisites.join(" · "):"None — start here."}</p><p className="mt-3 text-lg text-ink-soft"><strong>Key terms:</strong> {learning.keyTerms.join(" · ")}</p></section>
    <section className="topic-section bg-paper"><p className="font-mono text-sm font-semibold tracking-widest text-green">01 · LEARN</p><h2 className="mt-2 font-display text-3xl font-semibold sm:text-4xl">The idea, from first principles</h2><p className="topic-copy mt-5 text-lg leading-9 text-ink-soft sm:text-xl">{lesson.why}</p><div className="mt-7 space-y-4">{learning.mechanics.map((m,i)=><div key={m} className="flex gap-4 rounded-xl border border-line bg-paper-2 p-5"><span className="font-mono text-sm font-semibold text-green">{String(i+1).padStart(2,"0")}</span><p className="text-lg leading-8">{m}</p></div>)}</div></section>
    <section className="topic-section bg-ink text-paper"><p className="font-mono text-sm font-semibold tracking-widest text-green">02 · FORMULA / MECHANICS</p><h2 className="mt-2 font-display text-3xl font-semibold sm:text-4xl">How the numbers connect</h2><pre className="mt-5 overflow-x-auto whitespace-pre-wrap rounded-xl border border-white/15 bg-white/5 px-5 py-5 font-mono text-lg leading-8 text-paper sm:text-xl">{learning.formula}</pre></section>
    <section className="topic-section bg-paper"><p className="font-mono text-sm font-semibold tracking-widest text-green">03 · SEE</p><h2 className="mt-2 font-display text-3xl font-semibold sm:text-4xl">Worked example</h2><p className="topic-copy mt-5 text-lg leading-9 text-ink-soft sm:text-xl">{learning.workedExample}</p></section>
    <section className="topic-section bg-paper-2"><p className="font-mono text-sm font-semibold tracking-widest text-green">04 · TRY</p><h2 className="mt-2 font-display text-3xl font-semibold sm:text-4xl">Predict before you calculate</h2><p className="mt-4 text-lg leading-8 text-ink-soft">{learning.tryPrompt}</p><div className="mt-7 grid gap-5 sm:grid-cols-3">{["Starting value","Driver A (%)","Driver B (%)"].map((label,i)=><label key={label} className="block text-lg font-semibold">{label}<input aria-label={label} className="mt-2 w-full rounded-lg border border-line bg-paper px-4 py-3.5 text-xl font-mono" type="number" step="any" value={values[i]??0} onChange={e=>setValues(v=>v.map((x,j)=>j===i?(Number.isFinite(e.target.valueAsNumber)?e.target.valueAsNumber:0):x))}/></label>)}</div><div className="mt-8 flex flex-wrap items-center justify-between gap-4 rounded-xl bg-paper p-6"><span className="text-lg text-ink-soft">Live illustrative result</span><strong className="font-mono text-4xl">{result.toFixed(2)}</strong></div></section>
    <section className="topic-section bg-paper"><p className="font-mono text-sm font-semibold tracking-widest text-green">05 · PRACTICE</p><h2 className="mt-2 font-display text-3xl font-semibold sm:text-4xl">Practice the idea</h2><p className="mt-3 text-lg leading-8 text-ink-soft">Show your calculation or reasoning. Use the hint/model approach only after attempting the problem.</p><div className="mt-7 space-y-5">{learning.practice.map((p,i)=>{const state=practice[i]??{answer:"",revealed:false,checked:false}; return <div key={p} className="practice-exercise"><span className="font-mono text-sm font-semibold text-green">Exercise {i+1}</span><p className="mt-2 text-lg leading-8">{p}</p><label className="mt-5 block text-lg font-semibold">Your answer<textarea className="practice-answer mt-2" value={state.answer} onChange={e=>updatePractice(i,{answer:e.target.value,checked:false})} placeholder="Show your calculation, reasoning, assumptions, or interpretation…"/></label><div className="mt-4 flex flex-wrap gap-3"><button type="button" className="btn-primary" onClick={()=>updatePractice(i,{checked:true})}>{state.answer.trim()?"Compare your answer":"Show model approach"}</button><button type="button" className="rounded-lg border border-line px-4 py-3 text-lg font-semibold" onClick={()=>updatePractice(i,{revealed:!state.revealed})}>{state.revealed?"Hide solution":"Hint / model"}</button></div>{state.checked&&<div className="practice-feedback compare" role="status"><strong>Compare your answer</strong><p className="mt-1">Check the definition, units, formula, calculation, interpretation and assumptions.</p></div>}{state.revealed&&<div className="practice-feedback"><strong>Model approach</strong><p className="mt-1">{learning.workedExample}</p><p className="mt-2"><strong>Hint:</strong> Identify the relevant inputs, calculate step by step, then interpret the result.</p></div>}</div>})}</div></section>
    <section className="topic-section bg-paper"><p className="font-mono text-sm font-semibold tracking-widest text-green">06 · BUILD</p><h2 className="mt-2 font-display text-3xl font-semibold sm:text-4xl">Sandbox</h2><p className="mt-4 text-lg leading-8 text-ink-soft">{learning.sandbox.prompt}</p><div className="mt-6 rounded-xl border border-line bg-paper-2 p-5"><p className="text-sm font-semibold uppercase tracking-wider text-ink-faint">Sandbox type</p><p className="mt-1 text-xl font-semibold">{learning.sandbox.type}</p><p className="mt-2 text-lg text-ink-soft">Change inputs, predict the direction first, then explain the output. The live model above makes the relationship tangible; substantial topics can layer a dedicated domain sandbox onto this architecture.</p></div></section>
    <section className="topic-section bg-paper-2"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="font-mono text-sm font-semibold tracking-widest text-green">07 · CHECK</p><h2 className="mt-2 font-display text-3xl font-semibold sm:text-4xl">Check your understanding</h2></div><p className="text-base font-semibold text-ink-soft" aria-live="polite">{answeredCount} / {learning.questions.length} answered · {score} correct</p></div><div className="mt-7 space-y-6">{learning.questions.map((q,i)=>{const isAnswered=answered[i]===true;const isCorrect=isAnswered&&selected[i]===q.answer;return <fieldset key={q.prompt} className="quiz-question rounded-xl border border-line bg-paper p-5 sm:p-6"><legend className="px-2 text-lg font-semibold leading-8 sm:text-xl">{i+1}. {q.prompt}</legend><div className="mt-4 grid gap-2">{q.choices.map((choice,j)=>{const correct=isAnswered&&j===q.answer;const incorrect=isAnswered&&j===selected[i]&&j!==q.answer;return <label key={choice} className={`quiz-option ${correct?"is-correct":""} ${incorrect?"is-incorrect":""}`}><input type="radio" name={`q-${i}`} checked={selected[i]===j} disabled={isAnswered} onChange={()=>{setSelected(s=>({...s,[i]:j}));setAnswered(a=>({...a,[i]:true}));}}/><span className="quiz-option-copy">{choice}</span>{correct&&<strong>✓ Correct</strong>}{incorrect&&<strong>✕ Incorrect</strong>}</label>})}</div>{isAnswered&&<div className={`quiz-feedback ${isCorrect?"correct":"incorrect"}`} role="status"><strong>{isCorrect?"✓ Correct":"✕ Incorrect"}</strong>{!isCorrect&&<p><strong>Correct answer:</strong> {q.choices[q.answer]}</p>}<p><strong>Why?</strong> {q.explanation}</p></div>}{isAnswered&&<button type="button" className="mt-4 rounded-lg border border-line px-4 py-2.5 text-base font-semibold" onClick={()=>{setAnswered(a=>{const c={...a};delete c[i];return c});setSelected(s=>{const c={...s};delete c[i];return c})}}>Try again</button>}</fieldset>})}</div></section>
    <section className="mt-6 grid gap-6 md:grid-cols-2"><article className="topic-section mt-0 bg-paper"><p className="font-mono text-sm font-semibold tracking-widest text-green">08 · APPLY</p><h2 className="mt-2 font-display text-3xl font-semibold">Real-world case</h2><p className="mt-4 text-lg leading-8 text-ink-soft">{learning.caseStudy}</p><p className="mt-5 text-lg leading-8"><strong>Professional perspective:</strong> {learning.professional}</p></article><article className="topic-section mt-0 bg-paper"><p className="font-mono text-sm font-semibold tracking-widest text-red">COMMON MISTAKES</p><ul className="mt-5 space-y-3">{learning.mistakes.map(m=><li key={m} className="rounded-lg border border-line p-4 text-lg leading-8">{m}</li>)}</ul></article></section>
    <section className="topic-section bg-paper"><p className="font-mono text-sm font-semibold tracking-widest text-green">MASTER</p><h2 className="mt-2 font-display text-3xl font-semibold sm:text-4xl">Challenge & interview readiness</h2><p className="mt-4 text-lg leading-8">{learning.challenge}</p><div className="mt-6 grid gap-3">{learning.interview.map(q=><div key={q} className="rounded-xl border border-line bg-paper-2 p-4 text-lg">{q}</div>)}</div><div className="mt-6 border-t border-line pt-5"><h3 className="font-display text-2xl font-semibold">Key takeaways</h3><ul className="mt-4 space-y-2">{learning.summary.map(x=><li key={x} className="text-lg leading-8">• {x}</li>)}</ul></div><button type="button" onClick={completeNow} className={`mt-7 rounded-lg px-5 py-3.5 text-lg font-semibold ${complete?"border border-green bg-green-soft text-green":"btn-primary"}`}>{complete?"✓ Lesson complete":"Mark lesson complete"}</button></section>
    <section className="topic-navigation mt-8 grid gap-4 border-t border-line pt-7 sm:grid-cols-2"><div className="topic-nav-card">{previous?<><p className="text-sm font-semibold uppercase tracking-wider text-ink-faint">Previous topic</p><Link className="mt-2 inline-block text-lg font-semibold text-green no-underline" to={`/topic/${topicRouteSlug(previous)}`}>← {previous.topic}</Link></>:<span className="text-ink-faint">Start of curriculum</span>}</div><div className="topic-nav-card text-left sm:text-right">{next?<><p className="text-sm font-semibold uppercase tracking-wider text-ink-faint">Next topic</p><Link className="mt-2 inline-block text-lg font-semibold text-green no-underline" to={`/topic/${topicRouteSlug(next)}`}>{next.topic} →</Link></>:<span className="text-ink-faint">End of curriculum</span>}</div></section>
  </article>;
}
